"""
Nepal PSC Service Groups (Branches) and their specializations/post levels (SubBranches).

Hierarchy:
  Branch (Sewa/Service) → SubBranch (Post Level or Technical Specialization)

Maps to: src.models.branch.Branch, src.models.branch.SubBranch
"""

BRANCHES = [
    {
        "name_en": "Administrative Service",
        "name_np": "प्रशासन सेवा",
        "slug": "administrative-service",
        "description_en": "Nepal Administrative Service (NAS) — General administration, management, and governance posts across all government offices.",
        "description_np": "नेपाल प्रशासन सेवा — सबै सरकारी कार्यालयमा सामान्य प्रशासन, व्यवस्थापन र शासन पदहरू।",
        "has_sub_branches": True,
        "display_order": 1,
        "sub_branches": [
            {
                "name_en": "Kharidar (Non-Gazetted 2nd Class)",
                "name_np": "खरिदार (राजपत्र अनंकित द्वितीय श्रेणी)",
                "slug": "kharidar",
                "description_en": "Entry-level administrative post. Requires 10+2 qualification. Handles clerical duties, record keeping, and basic office operations.",
                "description_np": "प्रवेश तहको प्रशासनिक पद। +२ योग्यता आवश्यक। लिपिक कार्य, अभिलेख व्यवस्थापन र आधारभूत कार्यालय सञ्चालन।",
                "display_order": 1,
            },
            {
                "name_en": "Nayab Subba (Non-Gazetted 1st Class)",
                "name_np": "नायब सुब्बा (राजपत्र अनंकित प्रथम श्रेणी)",
                "slug": "nayab-subba",
                "description_en": "Mid-level administrative post. Requires 10+2 or Bachelor's degree. Supervisory role over Kharidars and office sections.",
                "description_np": "मध्य तहको प्रशासनिक पद। +२ वा स्नातक योग्यता आवश्यक। खरिदार र कार्यालय शाखाको सुपरिवेक्षण।",
                "display_order": 2,
            },
            {
                "name_en": "Section Officer (Gazetted 3rd Class)",
                "name_np": "शाखा अधिकृत (राजपत्रांकित तृतीय श्रेणी)",
                "slug": "section-officer",
                "description_en": "Officer-level gazetted post. Requires Bachelor's degree. Leads office sections, policy implementation, and administrative oversight.",
                "description_np": "अधिकृत तहको राजपत्रांकित पद। स्नातक योग्यता आवश्यक। शाखा नेतृत्व, नीति कार्यान्वयन र प्रशासनिक निगरानी।",
                "display_order": 3,
            },
        ],
    },
    {
        "name_en": "Engineering Service",
        "name_np": "ईन्जिनियरिङ सेवा",
        "slug": "engineering-service",
        "description_en": "Nepal Engineering Service — Technical posts for infrastructure, development, and engineering projects across government.",
        "description_np": "नेपाल ईन्जिनियरिङ सेवा — पूर्वाधार, विकास र सरकारी ईन्जिनियरिङ परियोजनाका प्राविधिक पदहरू।",
        "has_sub_branches": True,
        "display_order": 2,
        "sub_branches": [
            {
                "name_en": "Civil Engineering",
                "name_np": "सिभिल इन्जिनियरिङ",
                "slug": "civil-engineering",
                "description_en": "Roads, bridges, buildings, water supply, and infrastructure development projects.",
                "description_np": "सडक, पुल, भवन, खानेपानी र पूर्वाधार विकास परियोजनाहरू।",
                "display_order": 1,
            },
            {
                "name_en": "Computer Engineering",
                "name_np": "कम्प्युटर इन्जिनियरिङ",
                "slug": "computer-engineering",
                "description_en": "IT systems, e-governance, software development, and digital infrastructure.",
                "description_np": "सूचना प्रविधि प्रणाली, ई-गभर्नेन्स, सफ्टवेयर विकास र डिजिटल पूर्वाधार।",
                "display_order": 2,
            },
            {
                "name_en": "Electrical Engineering",
                "name_np": "विद्युत इन्जिनियरिङ",
                "slug": "electrical-engineering",
                "description_en": "Power generation, transmission, distribution, and electrical systems for government projects.",
                "description_np": "विद्युत उत्पादन, प्रसारण, वितरण र सरकारी परियोजनाको विद्युतीय प्रणाली।",
                "display_order": 3,
            },
            {
                "name_en": "Mechanical Engineering",
                "name_np": "मेकानिकल इन्जिनियरिङ",
                "slug": "mechanical-engineering",
                "description_en": "Heavy machinery, industrial equipment, and mechanical systems in government sectors.",
                "description_np": "भारी मेशिनरी, औद्योगिक उपकरण र सरकारी क्षेत्रमा मेकानिकल प्रणाली।",
                "display_order": 4,
            },
        ],
    },
    {
        "name_en": "Health Service",
        "name_np": "स्वास्थ्य सेवा",
        "slug": "health-service",
        "description_en": "Nepal Health Service — Medical, nursing, lab, pharmacy and public health posts across government hospitals and health centers.",
        "description_np": "नेपाल स्वास्थ्य सेवा — सरकारी अस्पताल र स्वास्थ्य केन्द्रमा चिकित्सा, नर्सिङ, प्रयोगशाला, फार्मेसी र सार्वजनिक स्वास्थ्य पदहरू।",
        "has_sub_branches": True,
        "display_order": 3,
        "sub_branches": [
            {
                "name_en": "General Medicine",
                "name_np": "सामान्य चिकित्सा",
                "slug": "general-medicine",
                "description_en": "Medical officer and doctor posts in government health facilities.",
                "description_np": "सरकारी स्वास्थ्य सुविधामा चिकित्सा अधिकृत र चिकित्सक पदहरू।",
                "display_order": 1,
            },
            {
                "name_en": "Nursing",
                "name_np": "नर्सिङ",
                "slug": "nursing",
                "description_en": "Staff nurse, nursing officer, and senior nursing posts.",
                "description_np": "स्टाफ नर्स, नर्सिङ अधिकृत र वरिष्ठ नर्सिङ पदहरू।",
                "display_order": 2,
            },
            {
                "name_en": "Lab Technology",
                "name_np": "प्रयोगशाला प्रविधि",
                "slug": "lab-technology",
                "description_en": "Medical laboratory technician and technologist posts.",
                "description_np": "चिकित्सा प्रयोगशाला प्रविधिक र प्रविधिज्ञ पदहरू।",
                "display_order": 3,
            },
            {
                "name_en": "Pharmacy",
                "name_np": "फार्मेसी",
                "slug": "pharmacy",
                "description_en": "Pharmacist and pharmacy assistant posts in government hospitals.",
                "description_np": "सरकारी अस्पतालमा फार्मासिस्ट र फार्मेसी सहायक पदहरू।",
                "display_order": 4,
            },
        ],
    },
    {
        "name_en": "Education Service",
        "name_np": "शिक्षा सेवा",
        "slug": "education-service",
        "description_en": "Nepal Education Service — Teaching and education administration posts at primary and secondary levels.",
        "description_np": "नेपाल शिक्षा सेवा — प्राथमिक र माध्यमिक तहमा शिक्षण र शिक्षा प्रशासन पदहरू।",
        "has_sub_branches": True,
        "display_order": 4,
        "sub_branches": [
            {
                "name_en": "Primary Level Teacher",
                "name_np": "प्राथमिक तह शिक्षक",
                "slug": "primary-teacher",
                "description_en": "Teaching posts for primary level (grades 1-5) in government schools.",
                "description_np": "सरकारी विद्यालयमा प्राथमिक तह (कक्षा १-५) को शिक्षण पदहरू।",
                "display_order": 1,
            },
            {
                "name_en": "Secondary Level Teacher",
                "name_np": "माध्यमिक तह शिक्षक",
                "slug": "secondary-teacher",
                "description_en": "Teaching posts for secondary level (grades 6-10) in government schools.",
                "description_np": "सरकारी विद्यालयमा माध्यमिक तह (कक्षा ६-१०) को शिक्षण पदहरू।",
                "display_order": 2,
            },
        ],
    },
    {
        "name_en": "Judicial Service",
        "name_np": "न्याय सेवा",
        "slug": "judicial-service",
        "description_en": "Nepal Judicial Service — Legal and judicial posts in courts and the justice system.",
        "description_np": "नेपाल न्याय सेवा — अदालत र न्याय प्रणालीमा कानुनी र न्यायिक पदहरू।",
        "has_sub_branches": False,
        "display_order": 5,
        "sub_branches": [],
    },
    {
        "name_en": "Agriculture Service",
        "name_np": "कृषि सेवा",
        "slug": "agriculture-service",
        "description_en": "Nepal Agriculture Service — Agricultural development, livestock, and veterinary posts.",
        "description_np": "नेपाल कृषि सेवा — कृषि विकास, पशुपालन र पशु चिकित्सा पदहरू।",
        "has_sub_branches": True,
        "display_order": 6,
        "sub_branches": [
            {
                "name_en": "Agriculture",
                "name_np": "कृषि",
                "slug": "agriculture",
                "description_en": "Crop science, agricultural extension, and farming technology posts.",
                "description_np": "बाली विज्ञान, कृषि प्रसार र कृषि प्रविधि पदहरू।",
                "display_order": 1,
            },
            {
                "name_en": "Livestock Development",
                "name_np": "पशुपालन विकास",
                "slug": "livestock-development",
                "description_en": "Animal husbandry, dairy development, and livestock service posts.",
                "description_np": "पशुपालन, दुग्ध विकास र पशु सेवा पदहरू।",
                "display_order": 2,
            },
        ],
    },
    {
        "name_en": "Forest Service",
        "name_np": "वन सेवा",
        "slug": "forest-service",
        "description_en": "Nepal Forest Service — Forestry, conservation, and environmental management posts.",
        "description_np": "नेपाल वन सेवा — वन, संरक्षण र वातावरण व्यवस्थापन पदहरू।",
        "has_sub_branches": True,
        "display_order": 7,
        "sub_branches": [
            {
                "name_en": "Forestry",
                "name_np": "वन",
                "slug": "forestry",
                "description_en": "Forest management, conservation, and community forestry posts.",
                "description_np": "वन व्यवस्थापन, संरक्षण र सामुदायिक वन पदहरू।",
                "display_order": 1,
            },
            {
                "name_en": "Soil Conservation",
                "name_np": "भू-संरक्षण",
                "slug": "soil-conservation",
                "description_en": "Soil conservation, watershed management, and land rehabilitation posts.",
                "description_np": "भू-संरक्षण, जलाधार व्यवस्थापन र भूमि पुनर्स्थापना पदहरू।",
                "display_order": 2,
            },
        ],
    },
    {
        "name_en": "Audit Service",
        "name_np": "लेखा परीक्षण सेवा",
        "slug": "audit-service",
        "description_en": "Nepal Audit Service — Government financial auditing, accounting, and fiscal oversight posts.",
        "description_np": "नेपाल लेखा परीक्षण सेवा — सरकारी वित्तीय लेखापरीक्षण, लेखा र आर्थिक निगरानी पदहरू।",
        "has_sub_branches": False,
        "display_order": 8,
        "sub_branches": [],
    },
    {
        "name_en": "Foreign Affairs Service",
        "name_np": "परराष्ट्र सेवा",
        "slug": "foreign-affairs-service",
        "description_en": "Nepal Foreign Affairs Service — Diplomatic, consular, and international relations posts.",
        "description_np": "नेपाल परराष्ट्र सेवा — कूटनीतिक, वाणिज्य दूतावास र अन्तर्राष्ट्रिय सम्बन्ध पदहरू।",
        "has_sub_branches": False,
        "display_order": 9,
        "sub_branches": [],
    },
    {
        "name_en": "Miscellaneous Service",
        "name_np": "विविध सेवा",
        "slug": "miscellaneous-service",
        "description_en": "Other government service posts including statistics, survey, planning, and general technical positions.",
        "description_np": "तथ्याङ्क, सर्वेक्षण, योजना र सामान्य प्राविधिक पदहरू सहित अन्य सरकारी सेवा पदहरू।",
        "has_sub_branches": False,
        "display_order": 10,
        "sub_branches": [],
    },
]
