"""
Category definitions organized by scope type.

scope_type=UNIVERSAL → visible to all users (target_branch=None, target_sub_branch=None)
scope_type=BRANCH → visible to users of that branch (target_branch required)
scope_type=SUBBRANCH → visible to users of that sub-branch (both targets required)

category_type=GENERAL → common/general subject
category_type=SPECIAL → technical/specialized subject
"""

from .constants import COLORS

# ─── UNIVERSAL CATEGORIES (12) ──────────────────────────────────────────────

UNIVERSAL_CATEGORIES = [
    {
        "name_en": "General Knowledge",
        "name_np": "सामान्य ज्ञान",
        "slug": "general-knowledge",
        "description_en": "Broad general knowledge covering Nepal and world affairs, science, sports, and culture.",
        "description_np": "नेपाल र विश्व मामिला, विज्ञान, खेलकुद र संस्कृति समेटेको व्यापक सामान्य ज्ञान।",
        "category_type": "GENERAL",
        "color_code": COLORS["green"],
        "display_order": 1,
    },
    {
        "name_en": "Constitution of Nepal",
        "name_np": "नेपालको संविधान",
        "slug": "constitution-of-nepal",
        "description_en": "Constitution of Nepal 2072 BS (2015 AD) — fundamental rights, directive principles, state structure, and governance.",
        "description_np": "नेपालको संविधान २०७२ — मौलिक हक, निर्देशक सिद्धान्त, राज्य संरचना र शासन।",
        "category_type": "GENERAL",
        "color_code": COLORS["blue"],
        "display_order": 2,
    },
    {
        "name_en": "Current Affairs",
        "name_np": "समसामयिक घटना",
        "slug": "current-affairs",
        "description_en": "Recent national and international events, government decisions, appointments, and developments.",
        "description_np": "हालका राष्ट्रिय र अन्तर्राष्ट्रिय घटनाहरू, सरकारी निर्णय, नियुक्ति र विकासहरू।",
        "category_type": "GENERAL",
        "color_code": COLORS["orange"],
        "display_order": 3,
    },
    {
        "name_en": "Lok Sewa Regulations",
        "name_np": "लोक सेवा नियमावली",
        "slug": "lok-sewa-regulations",
        "description_en": "Public Service Commission Act, Civil Service Act, regulations governing appointments, promotions, and conduct.",
        "description_np": "लोक सेवा आयोग ऐन, निजामती सेवा ऐन, नियुक्ति, बढुवा र आचरण सम्बन्धी नियमहरू।",
        "category_type": "GENERAL",
        "color_code": COLORS["purple"],
        "display_order": 4,
    },
    {
        "name_en": "Nepali Language & Grammar",
        "name_np": "नेपाली भाषा र व्याकरण",
        "slug": "nepali-language-grammar",
        "description_en": "Nepali grammar, vocabulary, sentence construction, comprehension, and language usage.",
        "description_np": "नेपाली व्याकरण, शब्दभण्डार, वाक्य निर्माण, बोधगम्यता र भाषा प्रयोग।",
        "category_type": "GENERAL",
        "color_code": COLORS["pink"],
        "display_order": 5,
    },
    {
        "name_en": "English Language",
        "name_np": "अंग्रेजी भाषा",
        "slug": "english-language",
        "description_en": "English grammar, vocabulary, reading comprehension, sentence correction, and usage.",
        "description_np": "अंग्रेजी व्याकरण, शब्दभण्डार, पढाइ बोधगम्यता, वाक्य सुधार र प्रयोग।",
        "category_type": "GENERAL",
        "color_code": COLORS["cyan"],
        "display_order": 6,
    },
    {
        "name_en": "Quantitative Aptitude",
        "name_np": "परिमाणात्मक योग्यता",
        "slug": "quantitative-aptitude",
        "description_en": "Mathematics — arithmetic, algebra, percentage, ratio, profit/loss, time & work, and data interpretation.",
        "description_np": "गणित — अंकगणित, बीजगणित, प्रतिशत, अनुपात, नाफा/नोक्सान, समय र काम, र तथ्याङ्क विश्लेषण।",
        "category_type": "GENERAL",
        "color_code": COLORS["deep_orange"],
        "display_order": 7,
    },
    {
        "name_en": "Reasoning & Mental Ability",
        "name_np": "तर्क र मानसिक क्षमता",
        "slug": "reasoning-mental-ability",
        "description_en": "Logical reasoning, number series, analogies, coding-decoding, puzzles, and mental ability.",
        "description_np": "तार्किक तर्क, संख्या श्रृंखला, उपमा, कोडिंग-डिकोडिंग, पजल र मानसिक क्षमता।",
        "category_type": "GENERAL",
        "color_code": COLORS["brown"],
        "display_order": 8,
    },
    {
        "name_en": "Computer Knowledge",
        "name_np": "कम्प्युटर ज्ञान",
        "slug": "computer-knowledge",
        "description_en": "Basic computer concepts, MS Office, internet, networking, hardware, software, and IT terminology.",
        "description_np": "आधारभूत कम्प्युटर अवधारणा, एमएस अफिस, इन्टरनेट, नेटवर्किङ, हार्डवेयर, सफ्टवेयर र आईटी शब्दावली।",
        "category_type": "GENERAL",
        "color_code": COLORS["blue_grey"],
        "display_order": 9,
    },
    {
        "name_en": "Good Governance & Ethics",
        "name_np": "सुशासन र नैतिकता",
        "slug": "good-governance-ethics",
        "description_en": "Principles of good governance, transparency, accountability, anti-corruption, and public service ethics.",
        "description_np": "सुशासनका सिद्धान्त, पारदर्शिता, जवाफदेहिता, भ्रष्टाचार विरोधी र सार्वजनिक सेवा नैतिकता।",
        "category_type": "GENERAL",
        "color_code": COLORS["indigo"],
        "display_order": 10,
    },
    {
        "name_en": "Geography of Nepal",
        "name_np": "नेपालको भूगोल",
        "slug": "geography-of-nepal",
        "description_en": "Physical geography, provinces, districts, rivers, mountains, climate, and natural resources of Nepal.",
        "description_np": "नेपालको भौतिक भूगोल, प्रदेश, जिल्ला, नदी, हिमाल, जलवायु र प्राकृतिक स्रोतहरू।",
        "category_type": "GENERAL",
        "color_code": COLORS["teal"],
        "display_order": 11,
    },
    {
        "name_en": "History of Nepal",
        "name_np": "नेपालको इतिहास",
        "slug": "history-of-nepal",
        "description_en": "Historical events, dynasties, unification, Rana period, democracy movements, and modern political history.",
        "description_np": "ऐतिहासिक घटना, राजवंश, एकीकरण, राणा काल, प्रजातन्त्र आन्दोलन र आधुनिक राजनीतिक इतिहास।",
        "category_type": "GENERAL",
        "color_code": COLORS["light_green"],
        "display_order": 12,
    },
]


# ─── BRANCH-SCOPED CATEGORIES ───────────────────────────────────────────────
# Key: branch slug → list of categories for that branch

BRANCH_CATEGORIES = {
    "administrative-service": [
        {
            "name_en": "Public Administration",
            "name_np": "सार्वजनिक प्रशासन",
            "slug": "public-administration",
            "description_en": "Principles of public administration, bureaucracy, administrative reforms, and government structure.",
            "description_np": "सार्वजनिक प्रशासनका सिद्धान्त, नौकरशाही, प्रशासनिक सुधार र सरकारी संरचना।",
            "category_type": "SPECIAL",
            "color_code": COLORS["amber"],
            "display_order": 1,
        },
        {
            "name_en": "Financial Administration",
            "name_np": "वित्तीय प्रशासन",
            "slug": "financial-administration",
            "description_en": "Government budgeting, financial regulations, revenue management, and fiscal policy.",
            "description_np": "सरकारी बजेट, वित्तीय नियमहरू, राजस्व व्यवस्थापन र आर्थिक नीति।",
            "category_type": "SPECIAL",
            "color_code": COLORS["red"],
            "display_order": 2,
        },
        {
            "name_en": "Public Service Management",
            "name_np": "सार्वजनिक सेवा व्यवस्थापन",
            "slug": "public-service-management",
            "description_en": "Human resource management in civil service, performance evaluation, and organizational development.",
            "description_np": "निजामती सेवामा मानव संसाधन व्यवस्थापन, कार्य मूल्याङ्कन र संगठनात्मक विकास।",
            "category_type": "SPECIAL",
            "color_code": COLORS["deep_purple"],
            "display_order": 3,
        },
        {
            "name_en": "Office Procedures & Management",
            "name_np": "कार्यालय प्रक्रिया र व्यवस्थापन",
            "slug": "office-procedures-management",
            "description_en": "Government office procedures, file management, correspondence, and record keeping regulations.",
            "description_np": "सरकारी कार्यालय प्रक्रिया, फाइल व्यवस्थापन, पत्राचार र अभिलेख व्यवस्थापन नियमहरू।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 4,
        },
    ],
    "engineering-service": [
        {
            "name_en": "Engineering Mathematics",
            "name_np": "ईन्जिनियरिङ गणित",
            "slug": "engineering-mathematics",
            "description_en": "Advanced mathematics — calculus, linear algebra, differential equations, and numerical methods.",
            "description_np": "उन्नत गणित — क्यालकुलस, रैखिक बीजगणित, अवकलन समीकरण र संख्यात्मक विधिहरू।",
            "category_type": "SPECIAL",
            "color_code": COLORS["amber"],
            "display_order": 1,
        },
        {
            "name_en": "Applied Mechanics",
            "name_np": "प्रयुक्त यान्त्रिकी",
            "slug": "applied-mechanics",
            "description_en": "Statics, dynamics, strength of materials, and fluid mechanics fundamentals.",
            "description_np": "स्टाटिक्स, डायनामिक्स, पदार्थको शक्ति र तरल यान्त्रिकी आधारभूत कुराहरू।",
            "category_type": "SPECIAL",
            "color_code": COLORS["red"],
            "display_order": 2,
        },
        {
            "name_en": "Engineering Drawing & Design",
            "name_np": "ईन्जिनियरिङ ड्रइङ र डिजाइन",
            "slug": "engineering-drawing",
            "description_en": "Technical drawing, orthographic projection, isometric views, and CAD fundamentals.",
            "description_np": "प्राविधिक ड्रइङ, अर्थोग्राफिक प्रक्षेपण, आइसोमेट्रिक दृश्य र क्याड आधारभूत कुराहरू।",
            "category_type": "SPECIAL",
            "color_code": COLORS["deep_purple"],
            "display_order": 3,
        },
    ],
    "health-service": [
        {
            "name_en": "Public Health",
            "name_np": "सार्वजनिक स्वास्थ्य",
            "slug": "public-health",
            "description_en": "Community health, disease prevention, sanitation, maternal health, and Nepal's health programs.",
            "description_np": "सामुदायिक स्वास्थ्य, रोग रोकथाम, सरसफाइ, मातृ स्वास्थ्य र नेपालका स्वास्थ्य कार्यक्रमहरू।",
            "category_type": "SPECIAL",
            "color_code": COLORS["amber"],
            "display_order": 1,
        },
        {
            "name_en": "Epidemiology & Biostatistics",
            "name_np": "महामारी विज्ञान र जैव-तथ्याङ्क",
            "slug": "epidemiology-biostatistics",
            "description_en": "Study of disease patterns, outbreak investigation, and health data analysis.",
            "description_np": "रोगको ढाँचाको अध्ययन, प्रकोप अनुसन्धान र स्वास्थ्य तथ्याङ्क विश्लेषण।",
            "category_type": "SPECIAL",
            "color_code": COLORS["red"],
            "display_order": 2,
        },
        {
            "name_en": "Health Policy & Planning",
            "name_np": "स्वास्थ्य नीति र योजना",
            "slug": "health-policy-planning",
            "description_en": "Nepal's health policy framework, health system planning, and health sector strategies.",
            "description_np": "नेपालको स्वास्थ्य नीति फ्रेमवर्क, स्वास्थ्य प्रणाली योजना र स्वास्थ्य क्षेत्र रणनीतिहरू।",
            "category_type": "SPECIAL",
            "color_code": COLORS["deep_purple"],
            "display_order": 3,
        },
    ],
    "education-service": [
        {
            "name_en": "Education Policy & Planning",
            "name_np": "शिक्षा नीति र योजना",
            "slug": "education-policy-planning",
            "description_en": "Nepal's education policies, Education Act, national curriculum framework, and planning.",
            "description_np": "नेपालको शिक्षा नीतिहरू, शिक्षा ऐन, राष्ट्रिय पाठ्यक्रम फ्रेमवर्क र योजना।",
            "category_type": "SPECIAL",
            "color_code": COLORS["amber"],
            "display_order": 1,
        },
        {
            "name_en": "Pedagogy & Teaching Methods",
            "name_np": "शिक्षाशास्त्र र शिक्षण विधि",
            "slug": "pedagogy-teaching-methods",
            "description_en": "Teaching methodologies, classroom management, student assessment, and learning theories.",
            "description_np": "शिक्षण विधिहरू, कक्षाकोठा व्यवस्थापन, विद्यार्थी मूल्याङ्कन र सिकाइ सिद्धान्तहरू।",
            "category_type": "SPECIAL",
            "color_code": COLORS["red"],
            "display_order": 2,
        },
        {
            "name_en": "Curriculum Development",
            "name_np": "पाठ्यक्रम विकास",
            "slug": "curriculum-development",
            "description_en": "Curriculum design principles, textbook development, and educational standards.",
            "description_np": "पाठ्यक्रम डिजाइन सिद्धान्त, पाठ्यपुस्तक विकास र शैक्षिक मापदण्डहरू।",
            "category_type": "SPECIAL",
            "color_code": COLORS["deep_purple"],
            "display_order": 3,
        },
    ],
    "judicial-service": [
        {
            "name_en": "Legal System of Nepal",
            "name_np": "नेपालको कानुनी प्रणाली",
            "slug": "legal-system-nepal",
            "description_en": "Nepal's legal system, court structure, judicial hierarchy, and legal procedures.",
            "description_np": "नेपालको कानुनी प्रणाली, अदालत संरचना, न्यायिक पदसोपान र कानुनी प्रक्रियाहरू।",
            "category_type": "SPECIAL",
            "color_code": COLORS["amber"],
            "display_order": 1,
        },
        {
            "name_en": "Criminal & Civil Law",
            "name_np": "फौजदारी र देवानी कानुन",
            "slug": "criminal-civil-law",
            "description_en": "Muluki Criminal Code, Muluki Civil Code, criminal procedure, and civil procedure.",
            "description_np": "मुलुकी फौजदारी संहिता, मुलुकी देवानी संहिता, फौजदारी कार्यविधि र देवानी कार्यविधि।",
            "category_type": "SPECIAL",
            "color_code": COLORS["red"],
            "display_order": 2,
        },
        {
            "name_en": "Constitutional Law & Jurisprudence",
            "name_np": "संवैधानिक कानुन र न्यायशास्त्र",
            "slug": "constitutional-law-jurisprudence",
            "description_en": "Constitutional interpretation, judicial review, fundamental rights, and legal philosophy.",
            "description_np": "संवैधानिक व्याख्या, न्यायिक पुनरावलोकन, मौलिक हक र कानुनी दर्शन।",
            "category_type": "SPECIAL",
            "color_code": COLORS["deep_purple"],
            "display_order": 3,
        },
    ],
    "agriculture-service": [
        {
            "name_en": "Agricultural Science",
            "name_np": "कृषि विज्ञान",
            "slug": "agricultural-science",
            "description_en": "Crop science, soil science, irrigation, agricultural economics, and farming systems.",
            "description_np": "बाली विज्ञान, माटो विज्ञान, सिँचाइ, कृषि अर्थशास्त्र र कृषि प्रणालीहरू।",
            "category_type": "SPECIAL",
            "color_code": COLORS["amber"],
            "display_order": 1,
        },
        {
            "name_en": "Crop Science & Technology",
            "name_np": "बाली विज्ञान र प्रविधि",
            "slug": "crop-science-technology",
            "description_en": "Crop production, pest management, seed technology, and post-harvest technology.",
            "description_np": "बाली उत्पादन, कीट व्यवस्थापन, बीउ प्रविधि र कटानी पश्चात प्रविधि।",
            "category_type": "SPECIAL",
            "color_code": COLORS["red"],
            "display_order": 2,
        },
    ],
    "forest-service": [
        {
            "name_en": "Forest Management",
            "name_np": "वन व्यवस्थापन",
            "slug": "forest-management",
            "description_en": "Forest types, silviculture, community forestry, forest policy, and Nepal's forest resources.",
            "description_np": "वन प्रकार, वन विज्ञान, सामुदायिक वन, वन नीति र नेपालका वन स्रोतहरू।",
            "category_type": "SPECIAL",
            "color_code": COLORS["amber"],
            "display_order": 1,
        },
        {
            "name_en": "Environmental Science",
            "name_np": "वातावरण विज्ञान",
            "slug": "environmental-science",
            "description_en": "Environmental impact assessment, climate change, biodiversity, and conservation.",
            "description_np": "वातावरणीय प्रभाव मूल्याङ्कन, जलवायु परिवर्तन, जैविक विविधता र संरक्षण।",
            "category_type": "SPECIAL",
            "color_code": COLORS["red"],
            "display_order": 2,
        },
    ],
    "audit-service": [
        {
            "name_en": "Accounting & Auditing",
            "name_np": "लेखा र लेखापरीक्षण",
            "slug": "accounting-auditing",
            "description_en": "Government accounting, auditing standards, financial statements, and internal control.",
            "description_np": "सरकारी लेखा, लेखापरीक्षण मापदण्ड, वित्तीय विवरण र आन्तरिक नियन्त्रण।",
            "category_type": "SPECIAL",
            "color_code": COLORS["amber"],
            "display_order": 1,
        },
        {
            "name_en": "Financial Management",
            "name_np": "वित्तीय व्यवस्थापन",
            "slug": "financial-management",
            "description_en": "Public financial management, budget analysis, fiscal policy, and revenue administration.",
            "description_np": "सार्वजनिक वित्तीय व्यवस्थापन, बजेट विश्लेषण, आर्थिक नीति र राजस्व प्रशासन।",
            "category_type": "SPECIAL",
            "color_code": COLORS["red"],
            "display_order": 2,
        },
    ],
    "foreign-affairs-service": [
        {
            "name_en": "International Relations",
            "name_np": "अन्तर्राष्ट्रिय सम्बन्ध",
            "slug": "international-relations",
            "description_en": "Nepal's foreign policy, diplomatic relations, international organizations, and treaties.",
            "description_np": "नेपालको विदेश नीति, कूटनीतिक सम्बन्ध, अन्तर्राष्ट्रिय संगठन र सन्धिहरू।",
            "category_type": "SPECIAL",
            "color_code": COLORS["amber"],
            "display_order": 1,
        },
        {
            "name_en": "Diplomatic Practice",
            "name_np": "कूटनीतिक अभ्यास",
            "slug": "diplomatic-practice",
            "description_en": "Diplomatic protocols, consular services, negotiation skills, and international law.",
            "description_np": "कूटनीतिक प्रोटोकल, वाणिज्य दूतावास सेवा, वार्ता सीप र अन्तर्राष्ट्रिय कानुन।",
            "category_type": "SPECIAL",
            "color_code": COLORS["red"],
            "display_order": 2,
        },
    ],
    "miscellaneous-service": [
        {
            "name_en": "Statistics & Data Analysis",
            "name_np": "तथ्याङ्क र तथ्याङ्क विश्लेषण",
            "slug": "statistics-data-analysis",
            "description_en": "Statistical methods, data collection, census, survey methodology, and data interpretation.",
            "description_np": "तथ्याङ्कीय विधिहरू, तथ्याङ्क सङ्कलन, जनगणना, सर्वेक्षण विधि र तथ्याङ्क व्याख्या।",
            "category_type": "SPECIAL",
            "color_code": COLORS["amber"],
            "display_order": 1,
        },
        {
            "name_en": "Planning & Development",
            "name_np": "योजना र विकास",
            "slug": "planning-development",
            "description_en": "Development planning, project management, monitoring & evaluation, and SDGs.",
            "description_np": "विकास योजना, परियोजना व्यवस्थापन, अनुगमन र मूल्याङ्कन, र दिगो विकास लक्ष्यहरू।",
            "category_type": "SPECIAL",
            "color_code": COLORS["red"],
            "display_order": 2,
        },
    ],
}


# ─── SUBBRANCH-SCOPED CATEGORIES ────────────────────────────────────────────
# Key: (branch_slug, subbranch_slug) → list of categories

SUBBRANCH_CATEGORIES = {
    ("administrative-service", "kharidar"): [
        {
            "name_en": "Office Management (Kharidar Level)",
            "name_np": "कार्यालय व्यवस्थापन (खरिदार तह)",
            "slug": "office-management-kharidar",
            "description_en": "Basic office operations, filing, record keeping, and clerical duties specific to Kharidar posts.",
            "description_np": "खरिदार पदसँग सम्बन्धित आधारभूत कार्यालय सञ्चालन, फाइलिङ, अभिलेख र लिपिक कार्य।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
        {
            "name_en": "Clerical Procedures",
            "name_np": "लिपिक प्रक्रिया",
            "slug": "clerical-procedures",
            "description_en": "Letter drafting, Darta-Chalani, document processing, and basic administrative procedures.",
            "description_np": "पत्र लेखन, दर्ता-चलानी, कागजात प्रशोधन र आधारभूत प्रशासनिक प्रक्रिया।",
            "category_type": "SPECIAL",
            "color_code": COLORS["yellow"],
            "display_order": 2,
        },
    ],
    ("administrative-service", "nayab-subba"): [
        {
            "name_en": "Administrative Supervision",
            "name_np": "प्रशासनिक सुपरिवेक्षण",
            "slug": "administrative-supervision",
            "description_en": "Supervisory skills, staff management, section coordination, and office administration at Nayab Subba level.",
            "description_np": "नायब सुब्बा तहमा सुपरिवेक्षण सीप, कर्मचारी व्यवस्थापन, शाखा समन्वय र कार्यालय प्रशासन।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
        {
            "name_en": "Revenue & Tax Administration",
            "name_np": "राजस्व र कर प्रशासन",
            "slug": "revenue-tax-administration",
            "description_en": "Tax collection, revenue laws, local revenue management, and fiscal procedures.",
            "description_np": "कर सङ्कलन, राजस्व कानुन, स्थानीय राजस्व व्यवस्थापन र आर्थिक प्रक्रिया।",
            "category_type": "SPECIAL",
            "color_code": COLORS["yellow"],
            "display_order": 2,
        },
    ],
    ("administrative-service", "section-officer"): [
        {
            "name_en": "Policy Analysis & Formulation",
            "name_np": "नीति विश्लेषण र निर्माण",
            "slug": "policy-analysis-formulation",
            "description_en": "Policy analysis frameworks, evidence-based policy making, and government policy formulation processes.",
            "description_np": "नीति विश्लेषण फ्रेमवर्क, प्रमाणमा आधारित नीति निर्माण र सरकारी नीति निर्माण प्रक्रिया।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
        {
            "name_en": "Organizational Behavior & Management",
            "name_np": "संगठनात्मक व्यवहार र व्यवस्थापन",
            "slug": "organizational-behavior-management",
            "description_en": "Leadership, motivation, organizational culture, change management, and strategic planning.",
            "description_np": "नेतृत्व, प्रेरणा, संगठनात्मक संस्कृति, परिवर्तन व्यवस्थापन र रणनीतिक योजना।",
            "category_type": "SPECIAL",
            "color_code": COLORS["yellow"],
            "display_order": 2,
        },
    ],
    ("engineering-service", "civil-engineering"): [
        {
            "name_en": "Structural Analysis & Design",
            "name_np": "संरचनात्मक विश्लेषण र डिजाइन",
            "slug": "structural-analysis-design",
            "description_en": "Structural mechanics, RCC design, steel structures, and seismic-resistant design.",
            "description_np": "संरचनात्मक यान्त्रिकी, आरसीसी डिजाइन, इस्पात संरचना र भूकम्प प्रतिरोधी डिजाइन।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
        {
            "name_en": "Surveying & Transportation",
            "name_np": "सर्वेक्षण र यातायात",
            "slug": "surveying-transportation",
            "description_en": "Surveying methods, road design, highway engineering, and transportation planning.",
            "description_np": "सर्वेक्षण विधिहरू, सडक डिजाइन, राजमार्ग ईन्जिनियरिङ र यातायात योजना।",
            "category_type": "SPECIAL",
            "color_code": COLORS["yellow"],
            "display_order": 2,
        },
    ],
    ("engineering-service", "computer-engineering"): [
        {
            "name_en": "Data Structures & Algorithms",
            "name_np": "डाटा संरचना र एल्गोरिदम",
            "slug": "data-structures-algorithms",
            "description_en": "Arrays, linked lists, trees, graphs, sorting, searching, and algorithm complexity analysis.",
            "description_np": "एरे, लिङ्क्ड लिस्ट, ट्री, ग्राफ, सोर्टिङ, सर्चिङ र एल्गोरिदम जटिलता विश्लेषण।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
        {
            "name_en": "Database & Networking",
            "name_np": "डाटाबेस र नेटवर्किङ",
            "slug": "database-networking",
            "description_en": "DBMS, SQL, normalization, network protocols, OSI model, and network security.",
            "description_np": "डीबीएमएस, एसक्यूएल, नर्मलाइजेसन, नेटवर्क प्रोटोकल, ओएसआई मोडेल र नेटवर्क सुरक्षा।",
            "category_type": "SPECIAL",
            "color_code": COLORS["yellow"],
            "display_order": 2,
        },
        {
            "name_en": "Operating Systems & Software Engineering",
            "name_np": "अपरेटिङ सिस्टम र सफ्टवेयर ईन्जिनियरिङ",
            "slug": "os-software-engineering",
            "description_en": "OS concepts, process management, memory management, SDLC, and software design patterns.",
            "description_np": "ओएस अवधारणा, प्रक्रिया व्यवस्थापन, मेमोरी व्यवस्थापन, एसडीएलसी र सफ्टवेयर डिजाइन ढाँचा।",
            "category_type": "SPECIAL",
            "color_code": COLORS["deep_purple"],
            "display_order": 3,
        },
    ],
    ("engineering-service", "electrical-engineering"): [
        {
            "name_en": "Circuit Theory & Electronics",
            "name_np": "सर्किट सिद्धान्त र इलेक्ट्रोनिक्स",
            "slug": "circuit-theory-electronics",
            "description_en": "Circuit analysis, analog/digital electronics, semiconductor devices, and signal processing.",
            "description_np": "सर्किट विश्लेषण, एनालग/डिजिटल इलेक्ट्रोनिक्स, सेमिकन्डक्टर उपकरण र सिग्नल प्रोसेसिङ।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
        {
            "name_en": "Power Systems & Machines",
            "name_np": "पावर सिस्टम र मेसिनहरू",
            "slug": "power-systems-machines",
            "description_en": "Power generation, transmission, distribution, transformers, motors, and generators.",
            "description_np": "विद्युत उत्पादन, प्रसारण, वितरण, ट्रान्सफर्मर, मोटर र जेनेरेटर।",
            "category_type": "SPECIAL",
            "color_code": COLORS["yellow"],
            "display_order": 2,
        },
    ],
    ("engineering-service", "mechanical-engineering"): [
        {
            "name_en": "Thermodynamics & Heat Transfer",
            "name_np": "तापगतिविज्ञान र ताप स्थानान्तरण",
            "slug": "thermodynamics-heat-transfer",
            "description_en": "Laws of thermodynamics, heat engines, refrigeration, and heat transfer mechanisms.",
            "description_np": "तापगतिविज्ञानका नियमहरू, ताप इन्जिन, प्रशीतन र ताप स्थानान्तरण प्रक्रिया।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
        {
            "name_en": "Manufacturing & Machine Design",
            "name_np": "निर्माण र मेसिन डिजाइन",
            "slug": "manufacturing-machine-design",
            "description_en": "Manufacturing processes, machine design, kinematics, and industrial engineering.",
            "description_np": "निर्माण प्रक्रिया, मेसिन डिजाइन, गतिविज्ञान र औद्योगिक ईन्जिनियरिङ।",
            "category_type": "SPECIAL",
            "color_code": COLORS["yellow"],
            "display_order": 2,
        },
    ],
    ("health-service", "general-medicine"): [
        {
            "name_en": "Clinical Medicine",
            "name_np": "क्लिनिकल मेडिसिन",
            "slug": "clinical-medicine",
            "description_en": "Internal medicine, diagnostic procedures, pharmacology, and patient management.",
            "description_np": "आन्तरिक चिकित्सा, निदान प्रक्रिया, औषधिशास्त्र र बिरामी व्यवस्थापन।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
    ],
    ("health-service", "nursing"): [
        {
            "name_en": "Nursing Fundamentals & Patient Care",
            "name_np": "नर्सिङ आधारभूत कुरा र बिरामी हेरचाह",
            "slug": "nursing-fundamentals-patient-care",
            "description_en": "Basic nursing skills, patient assessment, vital signs, medication administration, and care plans.",
            "description_np": "आधारभूत नर्सिङ सीप, बिरामी मूल्याङ्कन, जीवनशक्ति चिह्नहरू, औषधि प्रशासन र हेरचाह योजना।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
        {
            "name_en": "Midwifery & Community Nursing",
            "name_np": "सुत्केरी र सामुदायिक नर्सिङ",
            "slug": "midwifery-community-nursing",
            "description_en": "Maternal care, newborn care, family planning, community health nursing, and home visits.",
            "description_np": "मातृ हेरचाह, नवजात हेरचाह, परिवार नियोजन, सामुदायिक स्वास्थ्य नर्सिङ र घर भ्रमण।",
            "category_type": "SPECIAL",
            "color_code": COLORS["yellow"],
            "display_order": 2,
        },
    ],
    ("health-service", "lab-technology"): [
        {
            "name_en": "Medical Laboratory Science",
            "name_np": "चिकित्सा प्रयोगशाला विज्ञान",
            "slug": "medical-laboratory-science",
            "description_en": "Hematology, microbiology, clinical chemistry, blood banking, and lab safety.",
            "description_np": "हेमाटोलोजी, माइक्रोबायोलोजी, क्लिनिकल केमिस्ट्री, रक्त बैंकिङ र प्रयोगशाला सुरक्षा।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
    ],
    ("health-service", "pharmacy"): [
        {
            "name_en": "Pharmacology & Drug Management",
            "name_np": "औषधिशास्त्र र औषधि व्यवस्थापन",
            "slug": "pharmacology-drug-management",
            "description_en": "Drug classification, pharmacokinetics, drug interactions, and pharmaceutical management.",
            "description_np": "औषधि वर्गीकरण, फार्माकोकाइनेटिक्स, औषधि अन्तरक्रिया र औषधि व्यवस्थापन।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
    ],
    ("education-service", "primary-teacher"): [
        {
            "name_en": "Primary Education Methods",
            "name_np": "प्राथमिक शिक्षा विधि",
            "slug": "primary-education-methods",
            "description_en": "Activity-based learning, child-centered teaching, and primary-level assessment methods.",
            "description_np": "क्रियाकलापमा आधारित सिकाइ, बाल-केन्द्रित शिक्षण र प्राथमिक तह मूल्याङ्कन विधि।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
        {
            "name_en": "Child Development & Psychology",
            "name_np": "बाल विकास र मनोविज्ञान",
            "slug": "child-development-psychology",
            "description_en": "Stages of child development, learning psychology, and inclusive education practices.",
            "description_np": "बाल विकासका चरणहरू, सिकाइ मनोविज्ञान र समावेशी शिक्षा अभ्यासहरू।",
            "category_type": "SPECIAL",
            "color_code": COLORS["yellow"],
            "display_order": 2,
        },
    ],
    ("education-service", "secondary-teacher"): [
        {
            "name_en": "Secondary Education & Assessment",
            "name_np": "माध्यमिक शिक्षा र मूल्याङ्कन",
            "slug": "secondary-education-assessment",
            "description_en": "Subject-specific pedagogy, examination system, continuous assessment, and secondary curriculum.",
            "description_np": "विषयगत शिक्षाशास्त्र, परीक्षा प्रणाली, निरन्तर मूल्याङ्कन र माध्यमिक पाठ्यक्रम।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
    ],
    ("agriculture-service", "agriculture"): [
        {
            "name_en": "Crop Production & Protection",
            "name_np": "बाली उत्पादन र संरक्षण",
            "slug": "crop-production-protection",
            "description_en": "Major crops of Nepal, cropping patterns, plant protection, and integrated pest management.",
            "description_np": "नेपालका प्रमुख बालीहरू, बाली ढाँचा, बोट संरक्षण र एकीकृत कीट व्यवस्थापन।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
    ],
    ("agriculture-service", "livestock-development"): [
        {
            "name_en": "Animal Husbandry & Dairy",
            "name_np": "पशुपालन र दुग्ध",
            "slug": "animal-husbandry-dairy",
            "description_en": "Livestock breeds, feeding management, dairy production, and animal health.",
            "description_np": "पशु जातहरू, आहार व्यवस्थापन, दुग्ध उत्पादन र पशु स्वास्थ्य।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
    ],
    ("forest-service", "forestry"): [
        {
            "name_en": "Silviculture & Forest Ecology",
            "name_np": "वन विज्ञान र वन पारिस्थितिकी",
            "slug": "silviculture-forest-ecology",
            "description_en": "Tree species identification, forest regeneration, forest ecosystems, and community forestry management.",
            "description_np": "रूख प्रजाति पहिचान, वन पुनर्जनन, वन पारिस्थितिक प्रणाली र सामुदायिक वन व्यवस्थापन।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
    ],
    ("forest-service", "soil-conservation"): [
        {
            "name_en": "Soil & Watershed Management",
            "name_np": "माटो र जलाधार व्यवस्थापन",
            "slug": "soil-watershed-management",
            "description_en": "Soil erosion control, watershed management, land use planning, and river training.",
            "description_np": "माटो क्षय नियन्त्रण, जलाधार व्यवस्थापन, भूमि उपयोग योजना र नदी प्रशिक्षण।",
            "category_type": "SPECIAL",
            "color_code": COLORS["lime"],
            "display_order": 1,
        },
    ],
}
