"""
Mock Test definitions following real PSC exam patterns.

Each test specifies:
- branch/sub-branch targeting (by slug)
- total questions, duration, pass percentage
- category distribution: how many questions to pull from each category slug
"""

MOCK_TESTS = [
    # ─── Administrative Service ──────────────────────────────────────────
    {
        "title_en": "Kharidar Preliminary Exam - Set 1",
        "title_np": "खरिदार प्रारम्भिक परीक्षा - सेट १",
        "description_en": "Official PSC pattern preliminary exam for Kharidar (Non-Gazetted 2nd Class) with 50 MCQs.",
        "description_np": "खरिदार (राजपत्र अनंकित द्वितीय श्रेणी) को लागि लोक सेवा आयोगको ढाँचा अनुसारको प्रारम्भिक परीक्षा।",
        "test_type": "OFFICIAL",
        "branch_slug": "administrative-service",
        "sub_branch_slug": "kharidar",
        "total_questions": 50,
        "duration_minutes": 45,
        "pass_percentage": 40.0,
        "category_distribution": {
            "general-knowledge": 8,
            "constitution-of-nepal": 7,
            "current-affairs": 6,
            "lok-sewa-regulations": 5,
            "quantitative-aptitude": 5,
            "reasoning-mental-ability": 5,
            "nepali-language-grammar": 5,
            "english-language": 4,
            "computer-knowledge": 5,
        },
    },
    {
        "title_en": "Kharidar Preliminary Exam - Set 2",
        "title_np": "खरिदार प्रारम्भिक परीक्षा - सेट २",
        "description_en": "Practice set following official PSC pattern for Kharidar preliminary exam.",
        "description_np": "खरिदार प्रारम्भिक परीक्षाको लागि लोक सेवा आयोगको ढाँचा अनुसारको अभ्यास सेट।",
        "test_type": "OFFICIAL",
        "branch_slug": "administrative-service",
        "sub_branch_slug": "kharidar",
        "total_questions": 50,
        "duration_minutes": 45,
        "pass_percentage": 40.0,
        "category_distribution": {
            "general-knowledge": 7,
            "constitution-of-nepal": 6,
            "current-affairs": 7,
            "lok-sewa-regulations": 5,
            "quantitative-aptitude": 5,
            "reasoning-mental-ability": 5,
            "nepali-language-grammar": 5,
            "english-language": 5,
            "computer-knowledge": 5,
        },
    },
    {
        "title_en": "Nayab Subba Preliminary Exam - Set 1",
        "title_np": "नायब सुब्बा प्रारम्भिक परीक्षा - सेट १",
        "description_en": "Official PSC pattern preliminary exam for Nayab Subba (Non-Gazetted 1st Class).",
        "description_np": "नायब सुब्बा (राजपत्र अनंकित प्रथम श्रेणी) को लागि लोक सेवा आयोगको ढाँचा अनुसारको प्रारम्भिक परीक्षा।",
        "test_type": "OFFICIAL",
        "branch_slug": "administrative-service",
        "sub_branch_slug": "nayab-subba",
        "total_questions": 50,
        "duration_minutes": 45,
        "pass_percentage": 40.0,
        "category_distribution": {
            "general-knowledge": 8,
            "constitution-of-nepal": 7,
            "current-affairs": 7,
            "lok-sewa-regulations": 5,
            "good-governance-ethics": 3,
            "quantitative-aptitude": 5,
            "reasoning-mental-ability": 5,
            "nepali-language-grammar": 5,
            "computer-knowledge": 5,
        },
    },
    {
        "title_en": "Section Officer Preliminary Exam - Set 1",
        "title_np": "शाखा अधिकृत प्रारम्भिक परीक्षा - सेट १",
        "description_en": "Official PSC pattern preliminary exam for Section Officer (Gazetted 3rd Class).",
        "description_np": "शाखा अधिकृत (राजपत्रांकित तृतीय श्रेणी) को लागि लोक सेवा आयोगको ढाँचा अनुसारको प्रारम्भिक परीक्षा।",
        "test_type": "OFFICIAL",
        "branch_slug": "administrative-service",
        "sub_branch_slug": "section-officer",
        "total_questions": 50,
        "duration_minutes": 45,
        "pass_percentage": 40.0,
        "category_distribution": {
            "general-knowledge": 7,
            "constitution-of-nepal": 7,
            "current-affairs": 6,
            "lok-sewa-regulations": 5,
            "good-governance-ethics": 5,
            "quantitative-aptitude": 5,
            "reasoning-mental-ability": 5,
            "english-language": 5,
            "computer-knowledge": 5,
        },
    },
    # ─── Engineering Service ─────────────────────────────────────────────
    {
        "title_en": "Engineering Service General Exam - Set 1",
        "title_np": "ईन्जिनियरिङ सेवा सामान्य परीक्षा - सेट १",
        "description_en": "General preliminary exam for all Engineering Service candidates.",
        "description_np": "सबै ईन्जिनियरिङ सेवा उम्मेदवारको लागि सामान्य प्रारम्भिक परीक्षा।",
        "test_type": "OFFICIAL",
        "branch_slug": "engineering-service",
        "sub_branch_slug": None,
        "total_questions": 50,
        "duration_minutes": 45,
        "pass_percentage": 40.0,
        "category_distribution": {
            "general-knowledge": 8,
            "constitution-of-nepal": 5,
            "current-affairs": 5,
            "quantitative-aptitude": 7,
            "reasoning-mental-ability": 7,
            "computer-knowledge": 8,
            "english-language": 5,
            "good-governance-ethics": 5,
        },
    },
    {
        "title_en": "Civil Engineering Technical Exam - Set 1",
        "title_np": "सिभिल इन्जिनियरिङ प्राविधिक परीक्षा - सेट १",
        "description_en": "Technical exam for Civil Engineering specialization.",
        "description_np": "सिभिल इन्जिनियरिङ विशेषज्ञताको लागि प्राविधिक परीक्षा।",
        "test_type": "OFFICIAL",
        "branch_slug": "engineering-service",
        "sub_branch_slug": "civil-engineering",
        "total_questions": 50,
        "duration_minutes": 45,
        "pass_percentage": 40.0,
        "category_distribution": {
            "general-knowledge": 5,
            "engineering-mathematics": 8,
            "applied-mechanics": 7,
            "structural-analysis-design": 10,
            "surveying-transportation": 10,
            "computer-knowledge": 5,
            "good-governance-ethics": 5,
        },
    },
    {
        "title_en": "Computer Engineering Technical Exam - Set 1",
        "title_np": "कम्प्युटर इन्जिनियरिङ प्राविधिक परीक्षा - सेट १",
        "description_en": "Technical exam for Computer Engineering specialization.",
        "description_np": "कम्प्युटर इन्जिनियरिङ विशेषज्ञताको लागि प्राविधिक परीक्षा।",
        "test_type": "OFFICIAL",
        "branch_slug": "engineering-service",
        "sub_branch_slug": "computer-engineering",
        "total_questions": 50,
        "duration_minutes": 45,
        "pass_percentage": 40.0,
        "category_distribution": {
            "general-knowledge": 5,
            "data-structures-algorithms": 10,
            "database-networking": 10,
            "os-software-engineering": 10,
            "computer-knowledge": 5,
            "engineering-mathematics": 5,
            "good-governance-ethics": 5,
        },
    },
    # ─── Health Service ──────────────────────────────────────────────────
    {
        "title_en": "Health Service General Exam - Set 1",
        "title_np": "स्वास्थ्य सेवा सामान्य परीक्षा - सेट १",
        "description_en": "General preliminary exam for Health Service candidates.",
        "description_np": "स्वास्थ्य सेवा उम्मेदवारको लागि सामान्य प्रारम्भिक परीक्षा।",
        "test_type": "OFFICIAL",
        "branch_slug": "health-service",
        "sub_branch_slug": None,
        "total_questions": 50,
        "duration_minutes": 45,
        "pass_percentage": 40.0,
        "category_distribution": {
            "general-knowledge": 8,
            "constitution-of-nepal": 5,
            "current-affairs": 5,
            "public-health": 10,
            "epidemiology-biostatistics": 7,
            "computer-knowledge": 5,
            "english-language": 5,
            "good-governance-ethics": 5,
        },
    },
    {
        "title_en": "Nursing Technical Exam - Set 1",
        "title_np": "नर्सिङ प्राविधिक परीक्षा - सेट १",
        "description_en": "Technical exam for Nursing specialization.",
        "description_np": "नर्सिङ विशेषज्ञताको लागि प्राविधिक परीक्षा।",
        "test_type": "OFFICIAL",
        "branch_slug": "health-service",
        "sub_branch_slug": "nursing",
        "total_questions": 50,
        "duration_minutes": 45,
        "pass_percentage": 40.0,
        "category_distribution": {
            "general-knowledge": 5,
            "public-health": 8,
            "nursing-fundamentals-patient-care": 12,
            "midwifery-community-nursing": 10,
            "health-policy-planning": 5,
            "computer-knowledge": 5,
            "good-governance-ethics": 5,
        },
    },
    # ─── Education Service ───────────────────────────────────────────────
    {
        "title_en": "Education Service General Exam - Set 1",
        "title_np": "शिक्षा सेवा सामान्य परीक्षा - सेट १",
        "description_en": "General preliminary exam for Education Service candidates.",
        "description_np": "शिक्षा सेवा उम्मेदवारको लागि सामान्य प्रारम्भिक परीक्षा।",
        "test_type": "OFFICIAL",
        "branch_slug": "education-service",
        "sub_branch_slug": None,
        "total_questions": 50,
        "duration_minutes": 45,
        "pass_percentage": 40.0,
        "category_distribution": {
            "general-knowledge": 8,
            "constitution-of-nepal": 5,
            "current-affairs": 5,
            "education-policy-planning": 8,
            "pedagogy-teaching-methods": 8,
            "nepali-language-grammar": 5,
            "english-language": 5,
            "computer-knowledge": 3,
            "good-governance-ethics": 3,
        },
    },
    # ─── Judicial Service ────────────────────────────────────────────────
    {
        "title_en": "Judicial Service General Exam - Set 1",
        "title_np": "न्याय सेवा सामान्य परीक्षा - सेट १",
        "description_en": "General preliminary exam for Judicial Service candidates.",
        "description_np": "न्याय सेवा उम्मेदवारको लागि सामान्य प्रारम्भिक परीक्षा।",
        "test_type": "OFFICIAL",
        "branch_slug": "judicial-service",
        "sub_branch_slug": None,
        "total_questions": 50,
        "duration_minutes": 45,
        "pass_percentage": 40.0,
        "category_distribution": {
            "general-knowledge": 5,
            "constitution-of-nepal": 8,
            "current-affairs": 5,
            "legal-system-nepal": 10,
            "criminal-civil-law": 10,
            "constitutional-law-jurisprudence": 7,
            "english-language": 5,
        },
    },
    # ─── Agriculture Service ─────────────────────────────────────────────
    {
        "title_en": "Agriculture Service General Exam - Set 1",
        "title_np": "कृषि सेवा सामान्य परीक्षा - सेट १",
        "description_en": "General preliminary exam for Agriculture Service candidates.",
        "description_np": "कृषि सेवा उम्मेदवारको लागि सामान्य प्रारम्भिक परीक्षा।",
        "test_type": "OFFICIAL",
        "branch_slug": "agriculture-service",
        "sub_branch_slug": None,
        "total_questions": 50,
        "duration_minutes": 45,
        "pass_percentage": 40.0,
        "category_distribution": {
            "general-knowledge": 8,
            "constitution-of-nepal": 5,
            "current-affairs": 5,
            "agricultural-science": 10,
            "crop-science-technology": 7,
            "quantitative-aptitude": 5,
            "computer-knowledge": 5,
            "good-governance-ethics": 5,
        },
    },
]
