"""Administrative Service — BRANCH & SUBBRANCH category questions."""

QUESTIONS = {
    # ─── BRANCH-scoped categories ────────────────────────────────────────
    "public-administration": [
        {
            "question_text_en": "Who is considered the father of Public Administration?",
            "question_text_np": "सार्वजनिक प्रशासनका जनक कसलाई मानिन्छ?",
            "answers": [
                {"text_en": "Woodrow Wilson", "text_np": "वुड्रो विल्सन", "is_correct": True},
                {"text_en": "Max Weber", "text_np": "म्याक्स वेबर", "is_correct": False},
                {"text_en": "Frederick Taylor", "text_np": "फ्रेडरिक टेलर", "is_correct": False},
                {"text_en": "Henri Fayol", "text_np": "हेनरी फेयोल", "is_correct": False},
            ],
            "explanation_en": "Woodrow Wilson is considered the father of Public Administration. His 1887 essay 'The Study of Administration' laid the foundation of the discipline.",
            "explanation_np": "वुड्रो विल्सनलाई सार्वजनिक प्रशासनका जनक मानिन्छ। उनको १८८७ को निबन्ध 'The Study of Administration' ले यस विषयको आधार तयार गर्यो।",
            "difficulty": "EASY",
            "source_reference": "PSC Public Administration",
        },
        {
            "question_text_en": "Max Weber's theory of bureaucracy emphasizes which of the following?",
            "question_text_np": "म्याक्स वेबरको नौकरशाहीको सिद्धान्तले निम्नमध्ये कुन कुरामा जोड दिन्छ?",
            "answers": [
                {"text_en": "Hierarchy, rules, and impersonal relations", "text_np": "पदसोपान, नियम र निष्पक्ष सम्बन्ध", "is_correct": True},
                {"text_en": "Informal relationships", "text_np": "अनौपचारिक सम्बन्ध", "is_correct": False},
                {"text_en": "Political patronage", "text_np": "राजनीतिक संरक्षण", "is_correct": False},
                {"text_en": "Workers' self-management", "text_np": "कामदारको स्व-व्यवस्थापन", "is_correct": False},
            ],
            "explanation_en": "Weber's ideal bureaucracy is characterized by hierarchy, formal rules, specialization, and impersonal relationships.",
            "explanation_np": "वेबरको आदर्श नौकरशाही पदसोपान, औपचारिक नियम, विशेषज्ञता र निष्पक्ष सम्बन्धद्वारा विशेषता हो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Public Administration",
        },
        {
            "question_text_en": "POSDCORB was introduced by which scholar?",
            "question_text_np": "POSDCORB कुन विद्वानले प्रस्तुत गरेका हुन्?",
            "answers": [
                {"text_en": "Luther Gulick", "text_np": "लुथर गुलिक", "is_correct": True},
                {"text_en": "Herbert Simon", "text_np": "हर्बर्ट साइमन", "is_correct": False},
                {"text_en": "Dwight Waldo", "text_np": "ड्वाइट वाल्डो", "is_correct": False},
                {"text_en": "Chester Barnard", "text_np": "चेस्टर बर्नार्ड", "is_correct": False},
            ],
            "explanation_en": "POSDCORB (Planning, Organizing, Staffing, Directing, Coordinating, Reporting, Budgeting) was introduced by Luther Gulick to describe the functions of management.",
            "explanation_np": "POSDCORB (योजना, संगठन, कर्मचारी, निर्देशन, समन्वय, प्रतिवेदन, बजेट) व्यवस्थापनका कार्यहरू वर्णन गर्न लुथर गुलिकले प्रस्तुत गरेका हुन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Public Administration",
        },
        {
            "question_text_en": "How many ministries does the federal government of Nepal currently have?",
            "question_text_np": "नेपालको संघीय सरकारमा हाल कतिवटा मन्त्रालय छन्?",
            "answers": [
                {"text_en": "25", "text_np": "२५", "is_correct": True},
                {"text_en": "20", "text_np": "२०", "is_correct": False},
                {"text_en": "30", "text_np": "३०", "is_correct": False},
                {"text_en": "18", "text_np": "१८", "is_correct": False},
            ],
            "explanation_en": "The federal government of Nepal currently has 25 ministries.",
            "explanation_np": "नेपालको संघीय सरकारमा हाल २५ वटा मन्त्रालय छन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Public Administration",
        },
        {
            "question_text_en": "New Public Management (NPM) emphasizes which approach?",
            "question_text_np": "नयाँ सार्वजनिक व्यवस्थापन (NPM) ले कुन दृष्टिकोणमा जोड दिन्छ?",
            "answers": [
                {"text_en": "Market-oriented, result-based management", "text_np": "बजारमुखी, परिणाममा आधारित व्यवस्थापन", "is_correct": True},
                {"text_en": "Centralized bureaucratic control", "text_np": "केन्द्रीकृत नौकरशाही नियन्त्रण", "is_correct": False},
                {"text_en": "Political appointment of officials", "text_np": "अधिकारीहरूको राजनीतिक नियुक्ति", "is_correct": False},
                {"text_en": "Elimination of all government services", "text_np": "सबै सरकारी सेवा हटाउने", "is_correct": False},
            ],
            "explanation_en": "NPM emphasizes private sector management techniques, competition, performance measurement, and citizen-as-customer approach.",
            "explanation_np": "NPM ले निजी क्षेत्रको व्यवस्थापन प्रविधि, प्रतिस्पर्धा, कार्यसम्पादन मापन र नागरिक-ग्राहकको दृष्टिकोणमा जोड दिन्छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Public Administration",
        },
    ],
    "financial-administration": [
        {
            "question_text_en": "The annual budget of Nepal is presented in which month (BS)?",
            "question_text_np": "नेपालको वार्षिक बजेट कुन महिनामा प्रस्तुत गरिन्छ?",
            "answers": [
                {"text_en": "Jestha (May/June)", "text_np": "जेठ (मे/जुन)", "is_correct": True},
                {"text_en": "Shrawan (July/August)", "text_np": "श्रावण (जुलाई/अगस्ट)", "is_correct": False},
                {"text_en": "Poush (December/January)", "text_np": "पुस (डिसेम्बर/जनवरी)", "is_correct": False},
                {"text_en": "Chaitra (March/April)", "text_np": "चैत्र (मार्च/अप्रिल)", "is_correct": False},
            ],
            "explanation_en": "Nepal's annual budget is typically presented in Jestha (May/June) for the coming fiscal year starting Shrawan 1.",
            "explanation_np": "नेपालको वार्षिक बजेट सामान्यतया आगामी आर्थिक वर्ष श्रावण १ देखि सुरु हुने गरी जेठमा प्रस्तुत गरिन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Financial Administration",
        },
        {
            "question_text_en": "The Financial Procedure and Fiscal Accountability Act of Nepal was enacted in which year (BS)?",
            "question_text_np": "नेपालको आर्थिक कार्यविधि तथा वित्तीय उत्तरदायित्व ऐन कुन सालमा बनेको थियो?",
            "answers": [
                {"text_en": "2076 BS (2019 AD)", "text_np": "२०७६ साल (२०१९ ई.)", "is_correct": True},
                {"text_en": "2072 BS", "text_np": "२०७२ साल", "is_correct": False},
                {"text_en": "2064 BS", "text_np": "२०६४ साल", "is_correct": False},
                {"text_en": "2058 BS", "text_np": "२०५८ साल", "is_correct": False},
            ],
            "explanation_en": "The Financial Procedure and Fiscal Accountability Act was enacted in 2076 BS to improve government financial management.",
            "explanation_np": "आर्थिक कार्यविधि तथा वित्तीय उत्तरदायित्व ऐन सरकारी वित्तीय व्यवस्थापन सुधार गर्न २०७६ सालमा बनाइएको थियो।",
            "difficulty": "HARD",
            "source_reference": "PSC Financial Administration",
        },
        {
            "question_text_en": "Who presents the annual budget in the Federal Parliament?",
            "question_text_np": "संघीय संसदमा वार्षिक बजेट कसले प्रस्तुत गर्छन्?",
            "answers": [
                {"text_en": "Finance Minister", "text_np": "अर्थमन्त्री", "is_correct": True},
                {"text_en": "Prime Minister", "text_np": "प्रधानमन्त्री", "is_correct": False},
                {"text_en": "President", "text_np": "राष्ट्रपति", "is_correct": False},
                {"text_en": "Auditor General", "text_np": "महालेखा परीक्षक", "is_correct": False},
            ],
            "explanation_en": "The Finance Minister presents the annual budget in the Federal Parliament on behalf of the government.",
            "explanation_np": "अर्थमन्त्रीले सरकारको तर्फबाट संघीय संसदमा वार्षिक बजेट प्रस्तुत गर्छन्।",
            "difficulty": "EASY",
            "source_reference": "PSC Financial Administration",
        },
        {
            "question_text_en": "Nepal's fiscal year starts from which date?",
            "question_text_np": "नेपालको आर्थिक वर्ष कुन मितिबाट सुरु हुन्छ?",
            "answers": [
                {"text_en": "Shrawan 1 (Mid-July)", "text_np": "श्रावण १ (मध्य जुलाई)", "is_correct": True},
                {"text_en": "Baisakh 1 (Mid-April)", "text_np": "वैशाख १ (मध्य अप्रिल)", "is_correct": False},
                {"text_en": "January 1", "text_np": "जनवरी १", "is_correct": False},
                {"text_en": "Poush 1 (Mid-December)", "text_np": "पुस १ (मध्य डिसेम्बर)", "is_correct": False},
            ],
            "explanation_en": "Nepal's fiscal year runs from Shrawan 1 to Ashadh end (mid-July to mid-July).",
            "explanation_np": "नेपालको आर्थिक वर्ष श्रावण १ देखि असार मसान्तसम्म (मध्य जुलाई देखि मध्य जुलाई) हुन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Financial Administration",
        },
    ],
    "public-service-management": [
        {
            "question_text_en": "The Civil Service Act 2049 classifies civil servants into how many categories?",
            "question_text_np": "निजामती सेवा ऐन २०४९ ले निजामती कर्मचारीलाई कतिवटा वर्गमा वर्गीकरण गर्दछ?",
            "answers": [
                {"text_en": "Technical and Non-Technical", "text_np": "प्राविधिक र अप्राविधिक", "is_correct": True},
                {"text_en": "Three categories", "text_np": "तीन वर्ग", "is_correct": False},
                {"text_en": "Four categories", "text_np": "चार वर्ग", "is_correct": False},
                {"text_en": "Five categories", "text_np": "पाँच वर्ग", "is_correct": False},
            ],
            "explanation_en": "The Civil Service Act broadly classifies positions into Technical (Prabidhik) and Non-Technical (Aprabidhik) categories.",
            "explanation_np": "निजामती सेवा ऐनले पदहरूलाई मोटामोटी प्राविधिक र अप्राविधिक वर्गमा वर्गीकरण गर्दछ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Public Service Management",
        },
        {
            "question_text_en": "Performance evaluation of civil servants in Nepal is done how often?",
            "question_text_np": "नेपालमा निजामती कर्मचारीको कार्यसम्पादन मूल्याङ्कन कति समयमा गरिन्छ?",
            "answers": [
                {"text_en": "Annually", "text_np": "वार्षिक", "is_correct": True},
                {"text_en": "Monthly", "text_np": "मासिक", "is_correct": False},
                {"text_en": "Every 2 years", "text_np": "हरेक २ वर्ष", "is_correct": False},
                {"text_en": "Quarterly", "text_np": "त्रैमासिक", "is_correct": False},
            ],
            "explanation_en": "Performance evaluation (Karyasampadan Mulyankan) of civil servants is conducted annually.",
            "explanation_np": "निजामती कर्मचारीको कार्यसम्पादन मूल्याङ्कन वार्षिक रूपमा गरिन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Public Service Management",
        },
        {
            "question_text_en": "Which body handles civil service discipline and appeals in Nepal?",
            "question_text_np": "नेपालमा निजामती सेवाको अनुशासन र पुनरावेदन कुन निकायले हेर्छ?",
            "answers": [
                {"text_en": "Administrative Court", "text_np": "प्रशासकीय अदालत", "is_correct": True},
                {"text_en": "Supreme Court only", "text_np": "सर्वोच्च अदालत मात्र", "is_correct": False},
                {"text_en": "Election Commission", "text_np": "निर्वाचन आयोग", "is_correct": False},
                {"text_en": "Parliament", "text_np": "संसद", "is_correct": False},
            ],
            "explanation_en": "The Administrative Court handles disciplinary actions and appeals related to civil service employees.",
            "explanation_np": "प्रशासकीय अदालतले निजामती सेवा कर्मचारीसँग सम्बन्धित अनुशासन कारबाही र पुनरावेदन हेर्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Public Service Management",
        },
    ],
    "office-procedures-management": [
        {
            "question_text_en": "What is the Darta-Chalani system in Nepali government offices?",
            "question_text_np": "नेपाली सरकारी कार्यालयमा दर्ता-चलानी प्रणाली के हो?",
            "answers": [
                {"text_en": "A system for registering incoming and outgoing documents", "text_np": "आउने र जाने कागजातहरू दर्ता गर्ने प्रणाली", "is_correct": True},
                {"text_en": "A financial accounting method", "text_np": "वित्तीय लेखा विधि", "is_correct": False},
                {"text_en": "An employee attendance system", "text_np": "कर्मचारी हाजिरी प्रणाली", "is_correct": False},
                {"text_en": "A filing system for court cases", "text_np": "अदालतका मुद्दाको फाइलिङ प्रणाली", "is_correct": False},
            ],
            "explanation_en": "Darta (incoming registration) and Chalani (outgoing dispatch) is the fundamental document tracking system in Nepal's government offices.",
            "explanation_np": "दर्ता (आउने कागजात दर्ता) र चलानी (जाने कागजात पठाउने) नेपालको सरकारी कार्यालयमा कागजात ट्र्याकिङको आधारभूत प्रणाली हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Office Procedures",
        },
        {
            "question_text_en": "Government letters in Nepal follow which format?",
            "question_text_np": "नेपालमा सरकारी पत्रले कुन ढाँचा पालना गर्दछ?",
            "answers": [
                {"text_en": "Standard government letter format (Sarkari Patra)", "text_np": "मानक सरकारी पत्र ढाँचा (सरकारी पत्र)", "is_correct": True},
                {"text_en": "Any informal format", "text_np": "कुनै पनि अनौपचारिक ढाँचा", "is_correct": False},
                {"text_en": "Email format only", "text_np": "इमेल ढाँचा मात्र", "is_correct": False},
                {"text_en": "Business letter format", "text_np": "व्यापारिक पत्र ढाँचा", "is_correct": False},
            ],
            "explanation_en": "Government correspondence in Nepal follows a prescribed standard format (Sarkari Patra Byabastha) with specific elements like subject, reference, body, and official seal.",
            "explanation_np": "नेपालमा सरकारी पत्राचार निर्धारित मानक ढाँचा (सरकारी पत्र व्यवस्था) पालना गर्दछ जसमा विषय, सन्दर्भ, मूल भाग र आधिकारिक छाप जस्ता विशिष्ट तत्वहरू हुन्छन्।",
            "difficulty": "EASY",
            "source_reference": "PSC Office Procedures",
        },
    ],
    # ─── SUBBRANCH-scoped: Kharidar ──────────────────────────────────────
    "office-management-kharidar": [
        {
            "question_text_en": "What is the primary duty of a Kharidar in a government office?",
            "question_text_np": "सरकारी कार्यालयमा खरिदारको प्राथमिक कर्तव्य के हो?",
            "answers": [
                {"text_en": "Record keeping, filing, and clerical support", "text_np": "अभिलेख राख्ने, फाइलिङ र लिपिक सहयोग", "is_correct": True},
                {"text_en": "Policy making", "text_np": "नीति निर्माण", "is_correct": False},
                {"text_en": "Budget approval", "text_np": "बजेट स्वीकृति", "is_correct": False},
                {"text_en": "Court proceedings", "text_np": "अदालती कारबाही", "is_correct": False},
            ],
            "explanation_en": "A Kharidar performs clerical duties including record keeping, Darta-Chalani, filing, and basic office support.",
            "explanation_np": "खरिदारले अभिलेख राख्ने, दर्ता-चलानी, फाइलिङ र आधारभूत कार्यालय सहयोग सहित लिपिक कार्य गर्दछ।",
            "difficulty": "EASY",
            "source_reference": "PSC Kharidar",
        },
        {
            "question_text_en": "The minimum educational qualification required for the Kharidar post is:",
            "question_text_np": "खरिदार पदको लागि आवश्यक न्यूनतम शैक्षिक योग्यता के हो?",
            "answers": [
                {"text_en": "10+2 (Higher Secondary / Intermediate)", "text_np": "+२ (उच्च माध्यमिक / प्रवीणता प्रमाणपत्र)", "is_correct": True},
                {"text_en": "SLC only", "text_np": "एसएलसी मात्र", "is_correct": False},
                {"text_en": "Bachelor's degree", "text_np": "स्नातक", "is_correct": False},
                {"text_en": "Master's degree", "text_np": "स्नातकोत्तर", "is_correct": False},
            ],
            "explanation_en": "The Kharidar post requires a minimum qualification of 10+2 (Intermediate/Higher Secondary) from a recognized institution.",
            "explanation_np": "खरिदार पदको लागि मान्यताप्राप्त संस्थाबाट न्यूनतम +२ (प्रवीणता प्रमाणपत्र/उच्च माध्यमिक) योग्यता आवश्यक छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Kharidar",
        },
        {
            "question_text_en": "Which typing skill is required for a Kharidar post?",
            "question_text_np": "खरिदार पदको लागि कुन टाइपिङ सीप आवश्यक छ?",
            "answers": [
                {"text_en": "Both Nepali (Devanagari) and English typing", "text_np": "नेपाली (देवनागरी) र अंग्रेजी दुवै टाइपिङ", "is_correct": True},
                {"text_en": "English typing only", "text_np": "अंग्रेजी टाइपिङ मात्र", "is_correct": False},
                {"text_en": "No typing required", "text_np": "टाइपिङ आवश्यक छैन", "is_correct": False},
                {"text_en": "Shorthand only", "text_np": "शर्टह्यान्ड मात्र", "is_correct": False},
            ],
            "explanation_en": "Kharidar candidates must demonstrate proficiency in both Nepali (Devanagari) and English typing as part of the computer skill test.",
            "explanation_np": "खरिदार उम्मेदवारले कम्प्युटर सीप परीक्षाको भागको रूपमा नेपाली (देवनागरी) र अंग्रेजी दुवै टाइपिङमा दक्षता देखाउनुपर्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Kharidar",
        },
    ],
    "clerical-procedures": [
        {
            "question_text_en": "In government filing systems, what does 'Misil' (मिसिल) refer to?",
            "question_text_np": "सरकारी फाइलिङ प्रणालीमा 'मिसिल' भनेको के हो?",
            "answers": [
                {"text_en": "A file containing all documents related to a specific case or subject", "text_np": "कुनै विशेष मुद्दा वा विषयसँग सम्बन्धित सबै कागजात भएको फाइल", "is_correct": True},
                {"text_en": "An attendance register", "text_np": "हाजिरी रजिस्टर", "is_correct": False},
                {"text_en": "A budget document", "text_np": "बजेट कागजात", "is_correct": False},
                {"text_en": "A personal diary", "text_np": "व्यक्तिगत डायरी", "is_correct": False},
            ],
            "explanation_en": "Misil is the Nepali government term for a case file that contains all related documents, correspondence, and decisions on a specific subject.",
            "explanation_np": "मिसिल भनेको कुनै विशेष विषयमा सम्बन्धित सबै कागजात, पत्राचार र निर्णयहरू भएको केस फाइल हो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Clerical Procedures",
        },
        {
            "question_text_en": "What is a 'Tippani' (टिप्पणी) in government office procedures?",
            "question_text_np": "सरकारी कार्यालय प्रक्रियामा 'टिप्पणी' भनेको के हो?",
            "answers": [
                {"text_en": "A note sheet for writing comments and recommendations on a file", "text_np": "फाइलमा टिप्पणी र सिफारिस लेख्ने नोट शीट", "is_correct": True},
                {"text_en": "A complaint letter", "text_np": "उजुरी पत्र", "is_correct": False},
                {"text_en": "A budget proposal", "text_np": "बजेट प्रस्ताव", "is_correct": False},
                {"text_en": "An official notice", "text_np": "आधिकारिक सूचना", "is_correct": False},
            ],
            "explanation_en": "Tippani is a note sheet attached to government files where officials write their comments, analysis, and recommendations before decisions are made.",
            "explanation_np": "टिप्पणी सरकारी फाइलमा संलग्न नोट शीट हो जहाँ अधिकारीहरूले निर्णय अगाडि आफ्ना टिप्पणी, विश्लेषण र सिफारिसहरू लेख्छन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Clerical Procedures",
        },
    ],
    # ─── SUBBRANCH-scoped: Nayab Subba ───────────────────────────────────
    "administrative-supervision": [
        {
            "question_text_en": "A Nayab Subba is responsible for supervising which level of staff?",
            "question_text_np": "नायब सुब्बाले कुन तहको कर्मचारीको सुपरिवेक्षण गर्ने जिम्मेवारी हुन्छ?",
            "answers": [
                {"text_en": "Kharidars and classless staff", "text_np": "खरिदार र श्रेणीविहीन कर्मचारी", "is_correct": True},
                {"text_en": "Section Officers", "text_np": "शाखा अधिकृत", "is_correct": False},
                {"text_en": "Under Secretaries", "text_np": "उपसचिव", "is_correct": False},
                {"text_en": "Ministers", "text_np": "मन्त्री", "is_correct": False},
            ],
            "explanation_en": "Nayab Subba supervises Kharidars (Non-Gazetted 2nd Class) and classless staff within their section.",
            "explanation_np": "नायब सुब्बाले आफ्नो शाखाभित्र खरिदार (राजपत्र अनंकित द्वितीय श्रेणी) र श्रेणीविहीन कर्मचारीको सुपरिवेक्षण गर्दछ।",
            "difficulty": "EASY",
            "source_reference": "PSC Nayab Subba",
        },
        {
            "question_text_en": "What is the minimum qualification for the Nayab Subba post through open competition?",
            "question_text_np": "खुल्ला प्रतिस्पर्धाबाट नायब सुब्बा पदको लागि न्यूनतम योग्यता के हो?",
            "answers": [
                {"text_en": "10+2 or equivalent from a recognized institution", "text_np": "मान्यताप्राप्त संस्थाबाट +२ वा सो सरह", "is_correct": True},
                {"text_en": "Bachelor's degree", "text_np": "स्नातक", "is_correct": False},
                {"text_en": "SLC only", "text_np": "एसएलसी मात्र", "is_correct": False},
                {"text_en": "Master's degree", "text_np": "स्नातकोत्तर", "is_correct": False},
            ],
            "explanation_en": "For open competition, the Nayab Subba post requires a minimum of 10+2 (Intermediate) or equivalent from a recognized institution.",
            "explanation_np": "खुल्ला प्रतिस्पर्धाको लागि नायब सुब्बा पदमा मान्यताप्राप्त संस्थाबाट +२ वा सो सरह न्यूनतम योग्यता आवश्यक छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Nayab Subba",
        },
    ],
    "revenue-tax-administration": [
        {
            "question_text_en": "Value Added Tax (VAT) in Nepal is currently at what rate?",
            "question_text_np": "नेपालमा मूल्य अभिवृद्धि कर (VAT) हाल कति प्रतिशत छ?",
            "answers": [
                {"text_en": "13%", "text_np": "१३%", "is_correct": True},
                {"text_en": "10%", "text_np": "१०%", "is_correct": False},
                {"text_en": "15%", "text_np": "१५%", "is_correct": False},
                {"text_en": "18%", "text_np": "१८%", "is_correct": False},
            ],
            "explanation_en": "The standard VAT rate in Nepal is 13%, administered by the Inland Revenue Department.",
            "explanation_np": "नेपालमा मानक मूल्य अभिवृद्धि कर दर १३% छ, जुन आन्तरिक राजस्व विभागले प्रशासन गर्दछ।",
            "difficulty": "EASY",
            "source_reference": "PSC Revenue Administration",
        },
        {
            "question_text_en": "Which government body is responsible for internal revenue collection in Nepal?",
            "question_text_np": "नेपालमा आन्तरिक राजस्व सङ्कलनको लागि जिम्मेवार सरकारी निकाय कुन हो?",
            "answers": [
                {"text_en": "Inland Revenue Department (IRD)", "text_np": "आन्तरिक राजस्व विभाग", "is_correct": True},
                {"text_en": "Nepal Rastra Bank", "text_np": "नेपाल राष्ट्र बैंक", "is_correct": False},
                {"text_en": "Customs Department", "text_np": "भन्सार विभाग", "is_correct": False},
                {"text_en": "Auditor General", "text_np": "महालेखा परीक्षक", "is_correct": False},
            ],
            "explanation_en": "The Inland Revenue Department (Aantarik Rajaswa Bibhag) is responsible for collection of VAT, income tax, and excise duty in Nepal.",
            "explanation_np": "आन्तरिक राजस्व विभाग नेपालमा मूल्य अभिवृद्धि कर, आयकर र अन्तःशुल्कको सङ्कलनको लागि जिम्मेवार छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Revenue Administration",
        },
    ],
    # ─── SUBBRANCH-scoped: Section Officer ───────────────────────────────
    "policy-analysis-formulation": [
        {
            "question_text_en": "Evidence-based policy making primarily relies on:",
            "question_text_np": "प्रमाणमा आधारित नीति निर्माण मुख्यतया कुन कुरामा निर्भर हुन्छ?",
            "answers": [
                {"text_en": "Research data, analysis, and empirical evidence", "text_np": "अनुसन्धान तथ्याङ्क, विश्लेषण र प्रयोगजन्य प्रमाण", "is_correct": True},
                {"text_en": "Political pressure", "text_np": "राजनीतिक दबाब", "is_correct": False},
                {"text_en": "Media opinions", "text_np": "मिडियाको राय", "is_correct": False},
                {"text_en": "Personal experience only", "text_np": "व्यक्तिगत अनुभव मात्र", "is_correct": False},
            ],
            "explanation_en": "Evidence-based policy making uses research data, systematic analysis, and empirical evidence to inform government decisions and policy formulation.",
            "explanation_np": "प्रमाणमा आधारित नीति निर्माणले सरकारी निर्णय र नीति निर्माणलाई सूचित गर्न अनुसन्धान तथ्याङ्क, व्यवस्थित विश्लेषण र प्रयोगजन्य प्रमाण प्रयोग गर्दछ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Policy Analysis",
        },
        {
            "question_text_en": "The policy cycle typically includes which stages?",
            "question_text_np": "नीति चक्रमा सामान्यतया कुन चरणहरू हुन्छन्?",
            "answers": [
                {"text_en": "Agenda setting, formulation, adoption, implementation, evaluation", "text_np": "एजेन्डा निर्धारण, तर्जुमा, अपनाउने, कार्यान्वयन, मूल्याङ्कन", "is_correct": True},
                {"text_en": "Planning and execution only", "text_np": "योजना र कार्यान्वयन मात्र", "is_correct": False},
                {"text_en": "Research and publication", "text_np": "अनुसन्धान र प्रकाशन", "is_correct": False},
                {"text_en": "Drafting and signing", "text_np": "मस्यौदा र हस्ताक्षर", "is_correct": False},
            ],
            "explanation_en": "The policy cycle includes: agenda setting, policy formulation, policy adoption/legitimation, implementation, and evaluation.",
            "explanation_np": "नीति चक्रमा एजेन्डा निर्धारण, नीति तर्जुमा, नीति अपनाउने/वैधता, कार्यान्वयन र मूल्याङ्कन समावेश छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Policy Analysis",
        },
    ],
    "organizational-behavior-management": [
        {
            "question_text_en": "Maslow's Hierarchy of Needs places which need at the top?",
            "question_text_np": "मास्लोको आवश्यकताको पदसोपानमा शीर्षमा कुन आवश्यकता राखिएको छ?",
            "answers": [
                {"text_en": "Self-actualization", "text_np": "आत्म-साक्षात्कार", "is_correct": True},
                {"text_en": "Safety needs", "text_np": "सुरक्षाको आवश्यकता", "is_correct": False},
                {"text_en": "Physiological needs", "text_np": "शारीरिक आवश्यकता", "is_correct": False},
                {"text_en": "Social needs", "text_np": "सामाजिक आवश्यकता", "is_correct": False},
            ],
            "explanation_en": "Maslow's hierarchy from bottom to top: Physiological, Safety, Social/Love, Esteem, Self-actualization.",
            "explanation_np": "मास्लोको पदसोपान तलदेखि माथि: शारीरिक, सुरक्षा, सामाजिक/प्रेम, सम्मान, आत्म-साक्षात्कार।",
            "difficulty": "EASY",
            "source_reference": "PSC Organizational Behavior",
        },
        {
            "question_text_en": "Which leadership style involves sharing decision-making with subordinates?",
            "question_text_np": "कुन नेतृत्व शैलीमा अधीनस्थसँग निर्णय प्रक्रिया साझा गरिन्छ?",
            "answers": [
                {"text_en": "Democratic/Participative leadership", "text_np": "प्रजातान्त्रिक/सहभागी नेतृत्व", "is_correct": True},
                {"text_en": "Autocratic leadership", "text_np": "निरंकुश नेतृत्व", "is_correct": False},
                {"text_en": "Laissez-faire leadership", "text_np": "स्वतन्त्र नेतृत्व", "is_correct": False},
                {"text_en": "Bureaucratic leadership", "text_np": "नौकरशाही नेतृत्व", "is_correct": False},
            ],
            "explanation_en": "Democratic/participative leadership involves consulting with subordinates and considering their input in decision-making.",
            "explanation_np": "प्रजातान्त्रिक/सहभागी नेतृत्वमा अधीनस्थसँग परामर्श गर्ने र निर्णय प्रक्रियामा उनीहरूको योगदान विचार गर्ने समावेश हुन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Organizational Behavior",
        },
    ],
}
