"""Agriculture & Forest Service — BRANCH and SUBBRANCH category questions."""

QUESTIONS = {
    # ─── BRANCH-scoped: Agriculture Service ──────────────────────────────
    "agricultural-science": [
        {
            "question_text_en": "Which organization is responsible for agricultural research and development in Nepal?",
            "question_text_np": "नेपालमा कृषि अनुसन्धान र विकासको जिम्मेवार संस्था कुन हो?",
            "answers": [
                {"text_en": "Nepal Agricultural Research Council (NARC)", "text_np": "नेपाल कृषि अनुसन्धान परिषद् (NARC)", "is_correct": True},
                {"text_en": "Ministry of Agriculture and Livestock Development", "text_np": "कृषि तथा पशुपंछी विकास मन्त्रालय", "is_correct": False},
                {"text_en": "Agriculture Development Bank", "text_np": "कृषि विकास बैंक", "is_correct": False},
                {"text_en": "Department of Agriculture", "text_np": "कृषि विभाग", "is_correct": False},
            ],
            "explanation_en": "The Nepal Agricultural Research Council (NARC) is the apex agricultural research body in Nepal, established in 1991. It coordinates and conducts research on crops, livestock, fisheries, and horticulture.",
            "explanation_np": "नेपाल कृषि अनुसन्धान परिषद् (NARC) नेपालको सर्वोच्च कृषि अनुसन्धान निकाय हो, जो सन् १९९१ मा स्थापित भएको हो। यसले बाली, पशुपंछी, माछापालन र बागवानीमा अनुसन्धान समन्वय र सञ्चालन गर्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Agricultural Science",
        },
        {
            "question_text_en": "What percentage of Nepal's population is engaged in agriculture (approximately)?",
            "question_text_np": "नेपालको कति प्रतिशत जनसंख्या कृषिमा संलग्न छ (लगभग)?",
            "answers": [
                {"text_en": "Approximately 60-65%", "text_np": "लगभग ६०-६५%", "is_correct": True},
                {"text_en": "Approximately 30%", "text_np": "लगभग ३०%", "is_correct": False},
                {"text_en": "Approximately 80%", "text_np": "लगभग ८०%", "is_correct": False},
                {"text_en": "Approximately 40%", "text_np": "लगभग ४०%", "is_correct": False},
            ],
            "explanation_en": "Approximately 60-65% of Nepal's population is engaged in agriculture, which contributes around 25-27% to Nepal's GDP. Agriculture remains the backbone of Nepal's economy.",
            "explanation_np": "नेपालको लगभग ६०-६५% जनसंख्या कृषिमा संलग्न छ, जसले नेपालको GDP मा लगभग २५-२७% योगदान गर्छ। कृषि नेपालको अर्थतन्त्रको मेरुदण्ड हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Agricultural Science",
        },
        {
            "question_text_en": "What is the main staple food crop of Nepal?",
            "question_text_np": "नेपालको मुख्य खाद्यान्न बाली कुन हो?",
            "answers": [
                {"text_en": "Rice (Paddy)", "text_np": "धान", "is_correct": True},
                {"text_en": "Wheat", "text_np": "गहुँ", "is_correct": False},
                {"text_en": "Maize", "text_np": "मकै", "is_correct": False},
                {"text_en": "Millet", "text_np": "कोदो", "is_correct": False},
            ],
            "explanation_en": "Rice (paddy) is the most important staple food crop in Nepal, grown across the Terai, hills, and even some mountain areas. Nepal's rice growing season is primarily the monsoon (Kharif) season.",
            "explanation_np": "धान नेपालको सबैभन्दा महत्त्वपूर्ण खाद्यान्न बाली हो, जुन तराई, पहाड र केही हिमाली क्षेत्रहरूमा उगाइन्छ। नेपालमा धान खेती मुख्यतः मनसुन (खरिफ) मौसममा हुन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Agricultural Science",
        },
        {
            "question_text_en": "What is 'sustainable agriculture'?",
            "question_text_np": "'दिगो कृषि' के हो?",
            "answers": [
                {"text_en": "Farming that meets present needs without compromising the ability of future generations to meet their needs", "text_np": "भविष्यका पुस्ताको आवश्यकता पूरा गर्ने क्षमतामा सम्झौता नगरी वर्तमान आवश्यकता पूरा गर्ने खेतीपाती", "is_correct": True},
                {"text_en": "Agriculture that uses only chemical fertilizers", "text_np": "रासायनिक मलमात्र प्रयोग गर्ने कृषि", "is_correct": False},
                {"text_en": "Farming that produces the maximum yield at any cost", "text_np": "जुनसुकै लागतमा अधिकतम उत्पादन गर्ने खेती", "is_correct": False},
                {"text_en": "Agriculture practiced only in the Terai region", "text_np": "तराई क्षेत्रमा मात्र गरिने कृषि", "is_correct": False},
            ],
            "explanation_en": "Sustainable agriculture integrates three main goals: environmental health, economic profitability, and social equity. It aims to maintain productive farming long-term without degrading natural resources.",
            "explanation_np": "दिगो कृषिले तीन मुख्य लक्ष्यहरू एकीकृत गर्छ: वातावरणीय स्वास्थ्य, आर्थिक नाफा र सामाजिक समानता। यसले प्राकृतिक स्रोतहरूको क्षरण नगरी दीर्घकालीन रूपमा उत्पादक खेती कायम राख्ने लक्ष्य राख्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Agricultural Science",
        },
        {
            "question_text_en": "Which of the following is a cash crop widely grown in Nepal's Terai?",
            "question_text_np": "निम्नमध्ये कुन नेपालको तराईमा व्यापक रूपमा उगाइने नगदे बाली हो?",
            "answers": [
                {"text_en": "Sugarcane", "text_np": "उखु", "is_correct": True},
                {"text_en": "Buckwheat", "text_np": "फापर", "is_correct": False},
                {"text_en": "Barley", "text_np": "जौ", "is_correct": False},
                {"text_en": "Cardamom", "text_np": "अलैंची", "is_correct": False},
            ],
            "explanation_en": "Sugarcane is a major cash crop grown in Nepal's Terai region. Nepal has several sugar mills concentrated in districts like Bara, Parsa, Rautahat, and Sarlahi. Cardamom is a cash crop but grows in the eastern hills, not Terai.",
            "explanation_np": "उखु नेपालको तराई क्षेत्रमा उगाइने प्रमुख नगदे बाली हो। बारा, पर्सा, रौतहट र सर्लाही जस्ता जिल्लाहरूमा धेरै चिनी मिलहरू केन्द्रित छन्। अलैंची नगदे बाली हो तर पूर्वी पहाडमा उगाइन्छ, तराईमा होइन।",
            "difficulty": "EASY",
            "source_reference": "PSC Agricultural Science",
        },
        {
            "question_text_en": "What does 'Green Revolution' refer to in the context of agriculture?",
            "question_text_np": "कृषिको सन्दर्भमा 'हरित क्रान्ति' ले के जनाउँछ?",
            "answers": [
                {"text_en": "The period of rapid increase in agricultural productivity through HYV seeds, irrigation, and fertilizers (1960s-70s)", "text_np": "HYV बिउ, सिँचाइ र मलखादमार्फत कृषि उत्पादकत्वमा तीव्र वृद्धिको अवधि (१९६०-७० को दशक)", "is_correct": True},
                {"text_en": "Shift from farming to green energy production", "text_np": "खेतीबाट हरित ऊर्जा उत्पादनमा स्थानान्तरण", "is_correct": False},
                {"text_en": "Introduction of organic farming globally", "text_np": "विश्वभर जैविक खेतीको परिचय", "is_correct": False},
                {"text_en": "Reforestation campaigns by governments", "text_np": "सरकारद्वारा वृक्षारोपण अभियान", "is_correct": False},
            ],
            "explanation_en": "The Green Revolution (1960s-70s) transformed agriculture in developing countries through high-yielding variety (HYV) seeds, chemical fertilizers, pesticides, and expanded irrigation. It was pioneered by Norman Borlaug.",
            "explanation_np": "हरित क्रान्ति (१९६०-७० को दशक) ले उच्च उत्पादक जातका (HYV) बिउ, रासायनिक मलखाद, कीटनाशक र विस्तारित सिँचाइमार्फत विकासशील देशहरूको कृषिलाई रूपान्तरण गर्यो। यसको अगुवाई Norman Borlaug ले गरेका थिए।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Agricultural Science",
        },
        {
            "question_text_en": "Which soil type is most predominant and fertile in Nepal's Terai region?",
            "question_text_np": "नेपालको तराई क्षेत्रमा सबैभन्दा बढी पाइने र उर्वर माटोको प्रकार कुन हो?",
            "answers": [
                {"text_en": "Alluvial soil", "text_np": "जलोढ माटो", "is_correct": True},
                {"text_en": "Red laterite soil", "text_np": "रातो लेटेराइट माटो", "is_correct": False},
                {"text_en": "Sandy soil", "text_np": "बलौटे माटो", "is_correct": False},
                {"text_en": "Clay-heavy black soil", "text_np": "माटिलो कालो माटो", "is_correct": False},
            ],
            "explanation_en": "Alluvial soil, deposited by rivers flowing from the Himalayas, is the predominant and most fertile soil type in Nepal's Terai. It is ideal for rice, wheat, sugarcane, and other food crops.",
            "explanation_np": "हिमालयबाट बग्ने नदीहरूले थुपारेको जलोढ माटो नेपालको तराईमा सबैभन्दा बढी पाइने र उर्वर माटोको प्रकार हो। यो धान, गहुँ, उखु र अन्य खाद्यान्न बालीका लागि आदर्श हो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Agricultural Science",
        },
        {
            "question_text_en": "What is 'integrated pest management' (IPM) in agriculture?",
            "question_text_np": "कृषिमा 'एकीकृत कीटनाशक व्यवस्थापन' (IPM) के हो?",
            "answers": [
                {"text_en": "Using a combination of biological, cultural, and chemical methods to control pests with minimum environmental impact", "text_np": "न्यूनतम वातावरणीय प्रभावका साथ कीटपतंगहरू नियन्त्रण गर्न जैविक, सांस्कृतिक र रासायनिक विधिहरूको संयोजन प्रयोग गर्नु", "is_correct": True},
                {"text_en": "Using only pesticides to eliminate all pests", "text_np": "सबै कीटपतंग सफाया गर्न कीटनाशक मात्र प्रयोग गर्नु", "is_correct": False},
                {"text_en": "Importing pest-resistant seeds from abroad", "text_np": "विदेशबाट कीट-प्रतिरोधी बिउ आयात गर्नु", "is_correct": False},
                {"text_en": "Growing crops inside greenhouses only", "text_np": "हरितगृहमा मात्र बाली उगाउनु", "is_correct": False},
            ],
            "explanation_en": "IPM is an ecosystem-based approach combining biological control, habitat manipulation, resistant varieties, and chemical pesticides as a last resort. It reduces risks to human health and the environment.",
            "explanation_np": "IPM एक इकोसिस्टम-आधारित दृष्टिकोण हो जसले जैविक नियन्त्रण, आवास हेरफेर, प्रतिरोधी जातहरू र अन्तिम उपायको रूपमा रासायनिक कीटनाशकहरू संयोजन गर्छ। यसले मानव स्वास्थ्य र वातावरणको जोखिम घटाउँछ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Agricultural Science",
        },
        {
            "question_text_en": "The Agriculture Development Strategy (ADS) of Nepal covers which period?",
            "question_text_np": "नेपालको कृषि विकास रणनीति (ADS) कुन अवधि समेट्छ?",
            "answers": [
                {"text_en": "2015–2035 (20-year strategy)", "text_np": "२०१५–२०३५ (२० वर्षे रणनीति)", "is_correct": True},
                {"text_en": "2010–2020", "text_np": "२०१०–२०२०", "is_correct": False},
                {"text_en": "2020–2030", "text_np": "२०२०–२०३०", "is_correct": False},
                {"text_en": "2018–2028", "text_np": "२०१८–२०२८", "is_correct": False},
            ],
            "explanation_en": "Nepal's Agriculture Development Strategy (ADS) 2015–2035 is a 20-year strategy to transform Nepal's subsistence-based agriculture to a commercially competitive and sustainable sector.",
            "explanation_np": "नेपालको कृषि विकास रणनीति (ADS) २०१५–२०३५ एक २० वर्षे रणनीति हो जसले नेपालको निर्वाहमुखी कृषिलाई व्यावसायिक रूपमा प्रतिस्पर्धी र दिगो क्षेत्रमा रूपान्तरण गर्न लक्षित छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Agricultural Science",
        },
        {
            "question_text_en": "What is the main function of the Department of Agriculture (DoA) in Nepal?",
            "question_text_np": "नेपालमा कृषि विभाग (DoA) को मुख्य काम के हो?",
            "answers": [
                {"text_en": "Implementing agricultural programs, providing extension services, and regulating agro-inputs", "text_np": "कृषि कार्यक्रमहरू कार्यान्वयन, प्रसार सेवा प्रदान र कृषि आदानहरू नियमन गर्नु", "is_correct": True},
                {"text_en": "Conducting agricultural research only", "text_np": "कृषि अनुसन्धान मात्र गर्नु", "is_correct": False},
                {"text_en": "Providing agricultural loans to farmers", "text_np": "किसानहरूलाई कृषि ऋण प्रदान गर्नु", "is_correct": False},
                {"text_en": "Managing agricultural imports and exports", "text_np": "कृषि आयात र निर्यात व्यवस्थापन गर्नु", "is_correct": False},
            ],
            "explanation_en": "The Department of Agriculture (DoA) is responsible for implementing government agricultural development programs, providing extension services to farmers, and regulating agro-inputs like seeds, fertilizers, and pesticides.",
            "explanation_np": "कृषि विभाग (DoA) सरकारी कृषि विकास कार्यक्रमहरू कार्यान्वयन गर्न, किसानहरूलाई प्रसार सेवा प्रदान गर्न र बिउ, मलखाद र कीटनाशक जस्ता कृषि आदानहरू नियमन गर्न जिम्मेवार छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Agricultural Science",
        },
        {
            "question_text_en": "Photosynthesis in plants converts which inputs into glucose?",
            "question_text_np": "बिरुवाहरूमा प्रकाश संश्लेषणले कुन इनपुटहरूलाई ग्लुकोजमा रूपान्तरण गर्छ?",
            "answers": [
                {"text_en": "Carbon dioxide + Water + Sunlight → Glucose + Oxygen", "text_np": "कार्बन डाइअक्साइड + पानी + सूर्यको प्रकाश → ग्लुकोज + अक्सिजन", "is_correct": True},
                {"text_en": "Nitrogen + Water + Sunlight → Glucose + Carbon dioxide", "text_np": "नाइट्रोजन + पानी + सूर्यको प्रकाश → ग्लुकोज + कार्बन डाइअक्साइड", "is_correct": False},
                {"text_en": "Oxygen + Soil + Sunlight → Glucose + Water", "text_np": "अक्सिजन + माटो + सूर्यको प्रकाश → ग्लुकोज + पानी", "is_correct": False},
                {"text_en": "Glucose + Oxygen → Carbon dioxide + Water", "text_np": "ग्लुकोज + अक्सिजन → कार्बन डाइअक्साइड + पानी", "is_correct": False},
            ],
            "explanation_en": "Photosynthesis: 6CO₂ + 6H₂O + Light Energy → C₆H₁₂O₆ (glucose) + 6O₂. This process occurs in the chloroplasts of plant cells using chlorophyll to capture sunlight.",
            "explanation_np": "प्रकाश संश्लेषण: 6CO₂ + 6H₂O + प्रकाश ऊर्जा → C₆H₁₂O₆ (ग्लुकोज) + 6O₂। यो प्रक्रिया बिरुवाको कोशिकाहरूका क्लोरोप्लास्टमा क्लोरोफिलद्वारा सूर्यको प्रकाश अवशोषण गरी हुन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Agricultural Science",
        },
        {
            "question_text_en": "Which macronutrient is most essential for promoting leaf and vegetative growth in plants?",
            "question_text_np": "बिरुवाहरूमा पत्ती र वानस्पतिक वृद्धि प्रवर्द्धनका लागि कुन स्थूल पोषक तत्त्व सबैभन्दा आवश्यक छ?",
            "answers": [
                {"text_en": "Nitrogen (N)", "text_np": "नाइट्रोजन (N)", "is_correct": True},
                {"text_en": "Phosphorus (P)", "text_np": "फस्फोरस (P)", "is_correct": False},
                {"text_en": "Potassium (K)", "text_np": "पोटासियम (K)", "is_correct": False},
                {"text_en": "Calcium (Ca)", "text_np": "क्याल्सियम (Ca)", "is_correct": False},
            ],
            "explanation_en": "Nitrogen (N) is essential for vegetative/leaf growth as it is a key component of chlorophyll and amino acids. Phosphorus promotes root and flower development. Potassium aids water regulation and disease resistance.",
            "explanation_np": "नाइट्रोजन (N) वानस्पतिक/पत्तीको वृद्धिका लागि आवश्यक छ किनकि यो क्लोरोफिल र अमिनो एसिडको प्रमुख घटक हो। फस्फोरसले जरा र फूलको विकास प्रवर्द्धन गर्छ। पोटासियमले पानी नियमन र रोग प्रतिरोधमा सहयोग गर्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Agricultural Science",
        },
    ],

    "crop-science": [
        {
            "question_text_en": "What is the difference between Kharif and Rabi crops?",
            "question_text_np": "खरिफ र रबी बालीबीचको भिन्नता के हो?",
            "answers": [
                {"text_en": "Kharif are monsoon/summer crops; Rabi are winter/spring crops", "text_np": "खरिफ मनसुन/ग्रीष्म बाली हो; रबी शीत/वसन्त बाली हो", "is_correct": True},
                {"text_en": "Kharif grows in hills; Rabi grows in Terai", "text_np": "खरिफ पहाडमा उगाइन्छ; रबी तराईमा उगाइन्छ", "is_correct": False},
                {"text_en": "Kharif is food crop; Rabi is cash crop", "text_np": "खरिफ खाद्यान्न बाली हो; रबी नगदे बाली हो", "is_correct": False},
                {"text_en": "They are the same — different regional names", "text_np": "यी एउटै हुन् — विभिन्न क्षेत्रीय नामहरू", "is_correct": False},
            ],
            "explanation_en": "Kharif crops (monsoon season crops) are sown in summer and harvested in autumn — examples: rice, maize, millet. Rabi crops (winter season crops) are sown in winter and harvested in spring — examples: wheat, barley, mustard.",
            "explanation_np": "खरिफ बाली (मनसुन मौसमको बाली) ग्रीष्ममा रोपिन्छ र शरद ऋतुमा काटिन्छ — उदाहरण: धान, मकै, कोदो। रबी बाली (शीत मौसमको बाली) हिउँदमा रोपिन्छ र वसन्तमा काटिन्छ — उदाहरण: गहुँ, जौ, तोरी।",
            "difficulty": "EASY",
            "source_reference": "PSC Crop Science",
        },
        {
            "question_text_en": "Cardamom (Alainchi), a major cash crop export of Nepal, is primarily grown in which region?",
            "question_text_np": "नेपालको प्रमुख नगदे बाली निर्यात अलैंची मुख्य रूपमा कुन क्षेत्रमा उगाइन्छ?",
            "answers": [
                {"text_en": "Eastern hilly districts (Taplejung, Ilam, Panchthar)", "text_np": "पूर्वी पहाडी जिल्लाहरू (ताप्लेजुङ, इलाम, पाँचथर)", "is_correct": True},
                {"text_en": "Terai (plains) region", "text_np": "तराई (मैदान) क्षेत्र", "is_correct": False},
                {"text_en": "Kathmandu Valley", "text_np": "काठमाडौं उपत्यका", "is_correct": False},
                {"text_en": "High Himalayan districts", "text_np": "उच्च हिमाली जिल्लाहरू", "is_correct": False},
            ],
            "explanation_en": "Large cardamom (Amomum subulatum) is primarily grown in Nepal's eastern hill districts — Taplejung, Ilam, and Panchthar. Nepal is the world's largest producer of large cardamom.",
            "explanation_np": "ठूलो अलैंची (Amomum subulatum) मुख्य रूपमा नेपालको पूर्वी पहाडी जिल्लाहरू — ताप्लेजुङ, इलाम र पाँचथर — मा उगाइन्छ। नेपाल ठूलो अलैंचीको विश्वकै सबैभन्दा ठूलो उत्पादक हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Crop Science",
        },
        {
            "question_text_en": "What is the process of 'crop rotation' and why is it important?",
            "question_text_np": "'बालीचक्र' को प्रक्रिया के हो र यो किन महत्त्वपूर्ण छ?",
            "answers": [
                {"text_en": "Growing different crops sequentially on the same land to restore soil nutrients and reduce pests", "text_np": "माटोका पोषक तत्त्वहरू पुनर्स्थापित गर्न र कीटपतंग घटाउन एउटै जमिनमा क्रमिक रूपमा फरक बाली उगाउनु", "is_correct": True},
                {"text_en": "Rotating farmland between farmers every season", "text_np": "प्रत्येक मौसममा किसानहरूबीच खेतजमिन घुमाउनु", "is_correct": False},
                {"text_en": "Using machines to till the soil in rotation", "text_np": "माटो जोत्न घुमाइ क्रममा मेसिन प्रयोग गर्नु", "is_correct": False},
                {"text_en": "Planting crops in circular patterns", "text_np": "गोलाकार ढाँचामा बाली रोप्नु", "is_correct": False},
            ],
            "explanation_en": "Crop rotation is the practice of planting different types of crops in the same area across seasons. It replenishes soil nutrients (especially nitrogen via legumes), breaks pest and disease cycles, and reduces soil erosion.",
            "explanation_np": "बालीचक्र एउटै क्षेत्रमा मौसमभरि विभिन्न प्रकारका बालीहरू रोप्ने अभ्यास हो। यसले माटोका पोषक तत्त्वहरू (विशेषगरी फलीबोटद्वारा नाइट्रोजन) पुनर्स्थापित गर्छ, कीट र रोगका चक्रहरू तोड्छ र माटो क्षरण घटाउँछ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Crop Science",
        },
        {
            "question_text_en": "Which high-altitude crop is Nepal's famous 'Himalayan Herb' used in traditional medicine?",
            "question_text_np": "परम्परागत चिकित्सामा प्रयोग हुने नेपालको प्रसिद्ध 'हिमालयन जडिबुटी' कुन उच्च उचाइको बाली हो?",
            "answers": [
                {"text_en": "Yarsagumba (Caterpillar fungus / Ophiocordyceps sinensis)", "text_np": "यार्सागुम्बा (Ophiocordyceps sinensis)", "is_correct": True},
                {"text_en": "Timur (Sichuan pepper)", "text_np": "टिमुर (सिचुआन मिर्च)", "is_correct": False},
                {"text_en": "Chiuri (Butter tree)", "text_np": "चिउरी (मक्खन रुख)", "is_correct": False},
                {"text_en": "Amriso (Broom grass)", "text_np": "अम्रिसो", "is_correct": False},
            ],
            "explanation_en": "Yarsagumba (Ophiocordyceps sinensis) is a high-altitude fungus found in Nepal's alpine meadows above 3,500m. It is highly valued in traditional Chinese and Tibetan medicine and is one of Nepal's most expensive exports.",
            "explanation_np": "यार्सागुम्बा (Ophiocordyceps sinensis) नेपालको ३,५०० मिटरभन्दा माथिको उच्च उचाइको अल्पाइन मैदानहरूमा पाइने ढुसी हो। यो परम्परागत चिनियाँ र तिब्बती चिकित्सामा अत्यन्त मूल्यवान छ र नेपालको सबैभन्दा महँगो निर्यात वस्तुहरूमध्ये एक हो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Crop Science",
        },
        {
            "question_text_en": "What is 'hybrid seed' technology in crop production?",
            "question_text_np": "बाली उत्पादनमा 'हाइब्रिड बिउ' प्रविधि के हो?",
            "answers": [
                {"text_en": "Seeds produced by cross-pollinating two genetically different parent plants to produce higher-yielding offspring", "text_np": "उच्च उत्पादन दिने सन्तान उत्पादन गर्न दुई आनुवंशिक रूपमा फरक अभिभावक बिरुवाहरूलाई परकीय परागसेचन गरेर उत्पादित बिउ", "is_correct": True},
                {"text_en": "Seeds imported from foreign countries", "text_np": "विदेशबाट आयात गरिएका बिउ", "is_correct": False},
                {"text_en": "Seeds that have been chemically treated to resist disease", "text_np": "रोग प्रतिरोध गर्न रासायनिक उपचार गरिएका बिउ", "is_correct": False},
                {"text_en": "Traditional seeds saved from the previous harvest", "text_np": "अघिल्लो फसलबाट जोगाइएका परम्परागत बिउ", "is_correct": False},
            ],
            "explanation_en": "Hybrid seeds are produced by controlled cross-pollination between two genetically distinct parent lines. F1 hybrids show 'hybrid vigour' (heterosis), producing higher yields than either parent. However, farmers must buy new seeds each season.",
            "explanation_np": "हाइब्रिड बिउहरू दुई आनुवंशिक रूपमा भिन्न अभिभावक रेखाहरूबीच नियन्त्रित परकीय परागसेचनद्वारा उत्पादित हुन्छन्। F1 हाइब्रिडहरूले 'हाइब्रिड जोश' (heterosis) देखाउँछन्, जसले कुनै पनि अभिभावकभन्दा उच्च उत्पादन दिन्छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Crop Science",
        },
        {
            "question_text_en": "Nepal's tea (chiya) is primarily produced in which districts?",
            "question_text_np": "नेपालको चिया मुख्य रूपमा कुन जिल्लाहरूमा उत्पादन हुन्छ?",
            "answers": [
                {"text_en": "Ilam, Dhankuta, Taplejung, and Tehrathum (eastern hills)", "text_np": "इलाम, धनकुटा, ताप्लेजुङ र तेह्रथुम (पूर्वी पहाड)", "is_correct": True},
                {"text_en": "Chitwan, Nawalparasi, and Rupandehi (inner Terai)", "text_np": "चितवन, नवलपरासी र रुपन्देही (भित्री तराई)", "is_correct": False},
                {"text_en": "Mustang, Humla, and Dolpa (mountain districts)", "text_np": "मुस्ताङ, हुम्ला र डोल्पा (हिमाली जिल्लाहरू)", "is_correct": False},
                {"text_en": "Kaski, Syangja, and Parbat (western hills)", "text_np": "कास्की, स्याङ्जा र पर्वत (पश्चिमी पहाड)", "is_correct": False},
            ],
            "explanation_en": "Nepal's tea is produced primarily in the eastern hill districts — Ilam is the most famous tea-producing district, along with Dhankuta, Taplejung, and Tehrathum. Ilam tea is exported to international markets including Europe.",
            "explanation_np": "नेपालको चिया मुख्य रूपमा पूर्वी पहाडी जिल्लाहरूमा उत्पादन हुन्छ — इलाम सबैभन्दा प्रसिद्ध चिया उत्पादन जिल्ला हो, जसमा धनकुटा, ताप्लेजुङ र तेह्रथुम पनि समावेश छन्। इलामको चिया युरोप सहित अन्तर्राष्ट्रिय बजारमा निर्यात हुन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Crop Science",
        },
        {
            "question_text_en": "What is 'organic farming' and what label does Nepal's organic produce typically carry for export?",
            "question_text_np": "'जैविक खेती' के हो र नेपालको जैविक उपजले निर्यातका लागि सामान्यतया कुन लेबल बोक्छ?",
            "answers": [
                {"text_en": "Farming without synthetic chemicals; certified organic (e.g., USDA Organic, EU Organic)", "text_np": "कृत्रिम रसायनहरू बिना खेती; प्रमाणित जैविक (जस्तै, USDA Organic, EU Organic)", "is_correct": True},
                {"text_en": "Farming using only local seeds; labelled 'Made in Nepal'", "text_np": "स्थानीय बिउ मात्र प्रयोग गर्ने खेती; 'नेपालमा बनेको' लेबल", "is_correct": False},
                {"text_en": "Farming using rivers for irrigation; labelled 'Himalayan'", "text_np": "सिँचाइका लागि नदीहरू प्रयोग गर्ने खेती; 'हिमालयन' लेबल", "is_correct": False},
                {"text_en": "Traditional farming methods only; no special label needed", "text_np": "परम्परागत खेती विधिहरू मात्र; कुनै विशेष लेबल आवश्यक छैन", "is_correct": False},
            ],
            "explanation_en": "Organic farming avoids synthetic fertilizers and pesticides. For export, organic produce must be certified by recognized bodies (USDA, EU, India's NPOP). Nepal's DFTQC also certifies organic products domestically.",
            "explanation_np": "जैविक खेतीले कृत्रिम मलखाद र कीटनाशकहरू प्रयोग गर्दैन। निर्यातका लागि जैविक उपज मान्यता प्राप्त निकायहरू (USDA, EU, भारतको NPOP) द्वारा प्रमाणित हुनुपर्छ। नेपालको DFTQC ले पनि घरेलु रूपमा जैविक उत्पादनहरू प्रमाणित गर्छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Crop Science",
        },
        {
            "question_text_en": "Which government program supports small farmers with subsidized seeds and fertilizers in Nepal?",
            "question_text_np": "कुन सरकारी कार्यक्रमले नेपालमा साना किसानहरूलाई अनुदानित बिउ र मलखाद उपलब्ध गराउँछ?",
            "answers": [
                {"text_en": "Prime Minister Agriculture Modernization Project (PMAMP)", "text_np": "प्रधानमन्त्री कृषि आधुनिकीकरण परियोजना (PMAMP)", "is_correct": True},
                {"text_en": "Rural Development Fund (RDF)", "text_np": "ग्रामीण विकास कोष (RDF)", "is_correct": False},
                {"text_en": "National Agriculture Bank subsidy scheme", "text_np": "राष्ट्रिय कृषि बैंक अनुदान योजना", "is_correct": False},
                {"text_en": "Food Security Programme (FSP)", "text_np": "खाद्य सुरक्षा कार्यक्रम (FSP)", "is_correct": False},
            ],
            "explanation_en": "The Prime Minister Agriculture Modernization Project (PMAMP), launched in 2016, aims to modernize agriculture through pocket, block, and zone-based development, providing subsidies on seeds, fertilizers, and machinery.",
            "explanation_np": "प्रधानमन्त्री कृषि आधुनिकीकरण परियोजना (PMAMP), सन् २०१६ मा सुरु भएको, पकेट, ब्लक र जोन-आधारित विकासमार्फत कृषि आधुनिकीकरण गर्ने, बिउ, मलखाद र मेसिनरीमा अनुदान प्रदान गर्ने लक्ष्य राख्छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Crop Science",
        },
    ],

    # ─── BRANCH-scoped: Forest Service ───────────────────────────────────
    "forest-management": [
        {
            "question_text_en": "What percentage of Nepal's total land area is covered by forests?",
            "question_text_np": "नेपालको कुल भूमि क्षेत्रफलको कति प्रतिशत वनले ढाकेको छ?",
            "answers": [
                {"text_en": "Approximately 44-45%", "text_np": "लगभग ४४-४५%", "is_correct": True},
                {"text_en": "Approximately 20%", "text_np": "लगभग २०%", "is_correct": False},
                {"text_en": "Approximately 60%", "text_np": "लगभग ६०%", "is_correct": False},
                {"text_en": "Approximately 30%", "text_np": "लगभग ३०%", "is_correct": False},
            ],
            "explanation_en": "According to Nepal's Forest Survey, approximately 44-45% of Nepal's total land area is covered by forests (including forest, bush, and grasslands). Nepal's forest cover has been increasing due to community forestry programs.",
            "explanation_np": "नेपालको वन सर्वेक्षण अनुसार नेपालको कुल भूमि क्षेत्रफलको लगभग ४४-४५% वनले (वन, झाडी र घाँसे मैदान सहित) ढाकेको छ। सामुदायिक वन कार्यक्रमहरूले गर्दा नेपालको वन क्षेत्र बढ्दो छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Forest Management",
        },
        {
            "question_text_en": "Community forestry in Nepal involves transferring forest management to:",
            "question_text_np": "नेपालमा सामुदायिक वनले वन व्यवस्थापन कसमा हस्तान्तरण गर्छ?",
            "answers": [
                {"text_en": "Local community user groups (CFUGs)", "text_np": "स्थानीय सामुदायिक उपभोक्ता समूह (CFUGs)", "is_correct": True},
                {"text_en": "Private companies", "text_np": "निजी कम्पनीहरू", "is_correct": False},
                {"text_en": "Federal government departments", "text_np": "संघीय सरकारी विभागहरू", "is_correct": False},
                {"text_en": "International NGOs", "text_np": "अन्तर्राष्ट्रिय गैरसरकारी संस्थाहरू", "is_correct": False},
            ],
            "explanation_en": "Community forestry in Nepal hands over national forest management to local Community Forest User Groups (CFUGs). Nepal's community forestry program is globally recognized as a successful model of participatory natural resource management.",
            "explanation_np": "नेपालमा सामुदायिक वनले राष्ट्रिय वन व्यवस्थापन स्थानीय सामुदायिक वन उपभोक्ता समूह (CFUGs) लाई हस्तान्तरण गर्छ। नेपालको सामुदायिक वन कार्यक्रम सहभागितामूलक प्राकृतिक स्रोत व्यवस्थापनको सफल मोडेलको रूपमा विश्वव्यापी रूपमा मान्यता पाएको छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Forest Management",
        },
        {
            "question_text_en": "Which act governs community forestry in Nepal?",
            "question_text_np": "नेपालमा सामुदायिक वनलाई कुन ऐनले नियन्त्रण गर्छ?",
            "answers": [
                {"text_en": "Forest Act 2049 BS (1993 AD)", "text_np": "वन ऐन, २०४९ वि.सं.", "is_correct": True},
                {"text_en": "Environment Protection Act 2053 BS", "text_np": "वातावरण संरक्षण ऐन, २०५३ वि.सं.", "is_correct": False},
                {"text_en": "National Park and Wildlife Conservation Act 2029 BS", "text_np": "राष्ट्रिय निकुञ्ज तथा वन्यजन्तु संरक्षण ऐन, २०२९ वि.सं.", "is_correct": False},
                {"text_en": "Land Act 2021 BS", "text_np": "मुलुकी ऐन, २०२१ वि.सं.", "is_correct": False},
            ],
            "explanation_en": "The Forest Act 2049 BS (1993 AD) and its accompanying Forest Regulation 2051 BS provide the legal framework for community forestry, leasehold forestry, and other forest management modalities in Nepal.",
            "explanation_np": "वन ऐन, २०४९ वि.सं. (१९९३ ई.) र यसको साथमा रहेको वन नियमावली, २०५१ वि.सं. ले नेपालमा सामुदायिक वन, पट्टावन र अन्य वन व्यवस्थापन प्रणालीहरूको लागि कानुनी ढाँचा प्रदान गर्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Forest Management",
        },
        {
            "question_text_en": "What is the main objective of Nepal's protected area network?",
            "question_text_np": "नेपालको संरक्षित क्षेत्र नेटवर्कको मुख्य उद्देश्य के हो?",
            "answers": [
                {"text_en": "Conservation of biodiversity, wildlife, and natural heritage", "text_np": "जैविक विविधता, वन्यजन्तु र प्राकृतिक सम्पदाको संरक्षण", "is_correct": True},
                {"text_en": "Generating revenue through timber extraction", "text_np": "काठ उत्खनन मार्फत राजस्व उत्पादन गर्नु", "is_correct": False},
                {"text_en": "Providing land for agricultural expansion", "text_np": "कृषि विस्तारका लागि जमिन उपलब्ध गराउनु", "is_correct": False},
                {"text_en": "Creating employment in forestry sector only", "text_np": "वन क्षेत्रमा मात्र रोजगारी सिर्जना गर्नु", "is_correct": False},
            ],
            "explanation_en": "Nepal's protected area network covers about 23% of the total land area and includes national parks, wildlife reserves, conservation areas, and buffer zones. Its primary purpose is conservation of biodiversity and wildlife.",
            "explanation_np": "नेपालको संरक्षित क्षेत्र नेटवर्कले कुल भूमि क्षेत्रफलको लगभग २३% समेट्छ र राष्ट्रिय निकुञ्ज, वन्यजन्तु आरक्ष, संरक्षण क्षेत्र र मध्यवर्ती क्षेत्रहरू समावेश गर्छ। यसको प्राथमिक उद्देश्य जैविक विविधता र वन्यजन्तुको संरक्षण हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Forest Management",
        },
        {
            "question_text_en": "How many national parks does Nepal have?",
            "question_text_np": "नेपालमा कतिवटा राष्ट्रिय निकुञ्जहरू छन्?",
            "answers": [
                {"text_en": "12 national parks", "text_np": "१२ राष्ट्रिय निकुञ्जहरू", "is_correct": True},
                {"text_en": "7 national parks", "text_np": "७ राष्ट्रिय निकुञ्जहरू", "is_correct": False},
                {"text_en": "20 national parks", "text_np": "२० राष्ट्रिय निकुञ्जहरू", "is_correct": False},
                {"text_en": "5 national parks", "text_np": "५ राष्ट्रिय निकुञ्जहरू", "is_correct": False},
            ],
            "explanation_en": "Nepal has 12 national parks (including Rara, Shivapuri-Nagarjun, Sagarmatha, Langtang, Bardiya, Chitwan, etc.), 1 wildlife reserve, 6 conservation areas, 1 hunting reserve, and buffer zones.",
            "explanation_np": "नेपालमा १२ राष्ट्रिय निकुञ्जहरू (रारा, शिवपुरी-नागार्जुन, सगरमाथा, लाङटाङ, बर्दिया, चितवन आदि सहित), १ वन्यजन्तु आरक्ष, ६ संरक्षण क्षेत्र, १ शिकार आरक्ष र मध्यवर्ती क्षेत्रहरू छन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Forest Management",
        },
        {
            "question_text_en": "REDD+ in the context of forests and climate change stands for:",
            "question_text_np": "वन र जलवायु परिवर्तनको सन्दर्भमा REDD+ को पूरा रूप के हो?",
            "answers": [
                {"text_en": "Reducing Emissions from Deforestation and Forest Degradation Plus", "text_np": "वनविनाश र वन अवक्रमणबाट उत्सर्जन कटौती प्लस", "is_correct": True},
                {"text_en": "Regional Environmental Development and Deforestation Plus", "text_np": "क्षेत्रीय वातावरणीय विकास र वनविनाश प्लस", "is_correct": False},
                {"text_en": "Reforestation and Ecological Development Plus", "text_np": "पुनर्वनीकरण र पारिस्थितिक विकास प्लस", "is_correct": False},
                {"text_en": "Resource Extraction and Degradation Prevention Plus", "text_np": "स्रोत निष्कर्षण र अवक्रमण रोकथाम प्लस", "is_correct": False},
            ],
            "explanation_en": "REDD+ is a UN climate change framework that provides financial incentives to developing countries to reduce emissions from deforestation, sustainably manage forests, and enhance forest carbon stocks.",
            "explanation_np": "REDD+ एक संयुक्त राष्ट्र जलवायु परिवर्तन ढाँचा हो जसले विकासशील देशहरूलाई वनविनाशबाट उत्सर्जन घटाउन, दिगो रूपमा वन व्यवस्थापन गर्न र वन कार्बन भण्डार बढाउन वित्तीय प्रोत्साहन प्रदान गर्छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Forest Management",
        },
        {
            "question_text_en": "Chitwan National Park was Nepal's first national park, established in which year?",
            "question_text_np": "चितवन राष्ट्रिय निकुञ्ज नेपालको पहिलो राष्ट्रिय निकुञ्ज हो, जो कुन वर्षमा स्थापना भएको थियो?",
            "answers": [
                {"text_en": "1973 AD (2029 BS)", "text_np": "१९७३ ई. (२०२९ वि.सं.)", "is_correct": True},
                {"text_en": "1960 AD", "text_np": "१९६० ई.", "is_correct": False},
                {"text_en": "1985 AD", "text_np": "१९८५ ई.", "is_correct": False},
                {"text_en": "1950 AD", "text_np": "१९५० ई.", "is_correct": False},
            ],
            "explanation_en": "Chitwan National Park was established in 1973 as Nepal's first national park. It was declared a UNESCO World Heritage Site in 1984 and is home to one-horned rhinoceros, Bengal tigers, and gharial crocodiles.",
            "explanation_np": "चितवन राष्ट्रिय निकुञ्ज १९७३ मा नेपालको पहिलो राष्ट्रिय निकुञ्जको रूपमा स्थापना भएको थियो। यसलाई १९८४ मा UNESCO विश्व सम्पदा स्थल घोषित गरियो र यहाँ एकसिंगे गैंडा, बंगाल बाघ र घडियाल गोही पाइन्छन्।",
            "difficulty": "EASY",
            "source_reference": "PSC Forest Management",
        },
        {
            "question_text_en": "Which body administers Nepal's national parks and wildlife reserves?",
            "question_text_np": "नेपालका राष्ट्रिय निकुञ्ज र वन्यजन्तु आरक्षहरू कुन निकायले प्रशासन गर्छ?",
            "answers": [
                {"text_en": "Department of National Parks and Wildlife Conservation (DNPWC)", "text_np": "राष्ट्रिय निकुञ्ज तथा वन्यजन्तु संरक्षण विभाग (DNPWC)", "is_correct": True},
                {"text_en": "Department of Forests and Soil Conservation", "text_np": "वन तथा भूसंरक्षण विभाग", "is_correct": False},
                {"text_en": "Ministry of Forest and Environment directly", "text_np": "वन तथा वातावरण मन्त्रालय सिधा", "is_correct": False},
                {"text_en": "Nepal Army", "text_np": "नेपाली सेना", "is_correct": False},
            ],
            "explanation_en": "The Department of National Parks and Wildlife Conservation (DNPWC), under the Ministry of Forest and Environment, is responsible for management of Nepal's protected area network.",
            "explanation_np": "वन तथा वातावरण मन्त्रालय अन्तर्गतको राष्ट्रिय निकुञ्ज तथा वन्यजन्तु संरक्षण विभाग (DNPWC) नेपालको संरक्षित क्षेत्र नेटवर्कको व्यवस्थापनका लागि जिम्मेवार छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Forest Management",
        },
    ],

    "environmental-science": [
        {
            "question_text_en": "What is 'biodiversity'?",
            "question_text_np": "'जैविक विविधता' के हो?",
            "answers": [
                {"text_en": "The variety of life on Earth — genes, species, and ecosystems", "text_np": "पृथ्वीमा जीवनको विविधता — जीन, प्रजाति र पारिस्थितिक प्रणाली", "is_correct": True},
                {"text_en": "The study of chemical reactions in nature", "text_np": "प्रकृतिमा रासायनिक प्रतिक्रियाहरूको अध्ययन", "is_correct": False},
                {"text_en": "The number of different ecosystems only", "text_np": "विभिन्न पारिस्थितिक प्रणालीहरूको संख्या मात्र", "is_correct": False},
                {"text_en": "The total weight of all organisms in an area", "text_np": "एउटा क्षेत्रका सबै जीवहरूको कुल तौल", "is_correct": False},
            ],
            "explanation_en": "Biodiversity refers to the variety of life on Earth at all levels — genetic diversity within species, species diversity, and ecosystem diversity. Nepal is one of the world's most biodiverse countries for its size.",
            "explanation_np": "जैविक विविधताले पृथ्वीमा जीवनको सबै स्तरमा विविधतालाई जनाउँछ — प्रजाति भित्रको आनुवंशिक विविधता, प्रजाति विविधता र पारिस्थितिक प्रणाली विविधता। नेपाल आफ्नो आकारका हिसाबले विश्वका सबैभन्दा जैविक विविधतासम्पन्न देशहरूमध्ये एक हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Environmental Science",
        },
        {
            "question_text_en": "What is the 'greenhouse effect'?",
            "question_text_np": "'हरितगृह प्रभाव' के हो?",
            "answers": [
                {"text_en": "The trapping of heat in Earth's atmosphere by greenhouse gases, warming the planet", "text_np": "हरितगृह ग्यासहरूद्वारा पृथ्वीको वायुमण्डलमा तापलाई थुनेर ग्रहलाई तताउनु", "is_correct": True},
                {"text_en": "Growing plants in glass greenhouses to control temperature", "text_np": "तापक्रम नियन्त्रण गर्न काँचको हरितगृहमा बिरुवाहरू उगाउनु", "is_correct": False},
                {"text_en": "The cooling effect of forests on local climate", "text_np": "स्थानीय जलवायुमा वनहरूको शीतल प्रभाव", "is_correct": False},
                {"text_en": "Ozone layer depletion", "text_np": "ओजोन तहको ह्रास", "is_correct": False},
            ],
            "explanation_en": "The greenhouse effect occurs when greenhouse gases (CO₂, CH₄, N₂O, water vapour) in the atmosphere absorb and re-emit infrared radiation, trapping heat. While natural greenhouse effect is essential for life, human-enhanced greenhouse effect causes global warming.",
            "explanation_np": "हरितगृह प्रभाव तब हुन्छ जब वायुमण्डलमा हरितगृह ग्यासहरू (CO₂, CH₄, N₂O, जलवाष्प) ले अवरक्त विकिरण अवशोषण र पुनः उत्सर्जन गर्छन्, जसले गर्मी थुन्छ। प्राकृतिक हरितगृह प्रभाव जीवनका लागि आवश्यक छ, तर मानव-वर्धित हरितगृह प्रभावले विश्व तापमान बढाउँछ।",
            "difficulty": "EASY",
            "source_reference": "PSC Environmental Science",
        },
        {
            "question_text_en": "Nepal is ranked among the most climate-vulnerable countries. Which phenomenon most directly threatens Nepal's water security?",
            "question_text_np": "नेपाल जलवायु जोखिममा सबैभन्दा बढी प्रभावित देशहरूमा पर्छ। कुन घटनाले नेपालको जल सुरक्षालाई सबैभन्दा प्रत्यक्ष खतरा पुर्‍याउँछ?",
            "answers": [
                {"text_en": "Glacial retreat and Glacial Lake Outburst Floods (GLOFs)", "text_np": "हिमनदीको पछाडि हट्नु र हिमताल विस्फोट बाढी (GLOFs)", "is_correct": True},
                {"text_en": "Volcanic eruptions", "text_np": "ज्वालामुखी विस्फोट", "is_correct": False},
                {"text_en": "Rising sea levels directly", "text_np": "समुद्र स्तरको सिधा वृद्धि", "is_correct": False},
                {"text_en": "Desertification in the Terai", "text_np": "तराईमा मरुस्थलीकरण", "is_correct": False},
            ],
            "explanation_en": "Nepal's glaciers are retreating due to climate change, reducing long-term river flow. Glacial Lake Outburst Floods (GLOFs) pose immediate threats to downstream communities. Nepal has over 3,000 glacial lakes.",
            "explanation_np": "जलवायु परिवर्तनका कारण नेपालका हिमनदीहरू पछाडि हट्दैछन्, जसले दीर्घकालीन नदी प्रवाह घटाउँछ। हिमताल विस्फोट बाढी (GLOFs) ले तल्लो भागका समुदायहरूलाई तत्काल खतरा पुर्‍याउँछ। नेपालमा ३,००० भन्दा बढी हिमताल छन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Environmental Science",
        },
        {
            "question_text_en": "Which international agreement obligates Nepal to report its greenhouse gas emissions and climate action plans?",
            "question_text_np": "कुन अन्तर्राष्ट्रिय सम्झौताले नेपाललाई आफ्नो हरितगृह ग्यास उत्सर्जन र जलवायु कार्य योजनाहरू प्रतिवेदन गर्न बाध्य बनाउँछ?",
            "answers": [
                {"text_en": "Paris Agreement (2015) under UNFCCC", "text_np": "UNFCCC अन्तर्गत पेरिस सम्झौता (२०१५)", "is_correct": True},
                {"text_en": "Kyoto Protocol (1997) only", "text_np": "क्योटो प्रोटोकल (१९९७) मात्र", "is_correct": False},
                {"text_en": "CITES Convention", "text_np": "CITES महासन्धि", "is_correct": False},
                {"text_en": "Convention on Biological Diversity (CBD)", "text_np": "जैविक विविधतामा महासन्धि (CBD)", "is_correct": False},
            ],
            "explanation_en": "Nepal is a signatory to the Paris Agreement under UNFCCC and must submit Nationally Determined Contributions (NDCs) outlining climate targets and Biennial Transparency Reports on emissions.",
            "explanation_np": "नेपाल UNFCCC अन्तर्गत पेरिस सम्झौताको हस्ताक्षरकर्ता हो र जलवायु लक्ष्यहरू उल्लेख गर्ने राष्ट्रिय रूपमा निर्धारित योगदान (NDCs) र उत्सर्जनमा द्विवार्षिक पारदर्शिता प्रतिवेदनहरू पेश गर्नुपर्छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Environmental Science",
        },
        {
            "question_text_en": "What is 'deforestation' and what is its primary cause in Nepal's context?",
            "question_text_np": "'वनविनाश' के हो र नेपालको सन्दर्भमा यसको प्राथमिक कारण के हो?",
            "answers": [
                {"text_en": "Permanent removal of forests; caused primarily by agricultural expansion, fuelwood collection, and development", "text_np": "वनको स्थायी हटाउनु; मुख्य रूपमा कृषि विस्तार, दाउरा संकलन र विकासका कारण", "is_correct": True},
                {"text_en": "Natural forest fires only", "text_np": "प्राकृतिक वन डढेलो मात्र", "is_correct": False},
                {"text_en": "International timber companies illegally logging", "text_np": "अन्तर्राष्ट्रिय काठ कम्पनीहरूले अवैध रूपमा काटछाँट गर्नु", "is_correct": False},
                {"text_en": "Climate change alone", "text_np": "जलवायु परिवर्तन मात्र", "is_correct": False},
            ],
            "explanation_en": "Deforestation is the large-scale removal of forest cover. In Nepal, it was historically driven by agricultural land expansion, fuelwood/fodder collection, and infrastructure development. Community forestry has helped reverse this trend.",
            "explanation_np": "वनविनाश भनेको ठूलो स्तरमा वन आवरण हटाउनु हो। नेपालमा यो ऐतिहासिक रूपमा कृषि भूमि विस्तार, दाउरा/घाँस संकलन र पूर्वाधार विकासद्वारा सञ्चालित थियो। सामुदायिक वनले यो प्रवृत्ति उल्टाउन मद्दत गरेको छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Environmental Science",
        },
        {
            "question_text_en": "Nepal's Environment Protection Act 2076 BS requires Environmental Impact Assessments (EIA) for which types of projects?",
            "question_text_np": "नेपालको वातावरण संरक्षण ऐन, २०७६ वि.सं. ले कुन प्रकारका आयोजनाहरूका लागि वातावरणीय प्रभाव मूल्यांकन (EIA) आवश्यक पार्छ?",
            "answers": [
                {"text_en": "Large-scale development projects likely to cause significant environmental impact", "text_np": "महत्त्वपूर्ण वातावरणीय प्रभाव पार्ने सम्भावना भएका ठूलो पैमानाका विकास आयोजनाहरू", "is_correct": True},
                {"text_en": "All projects including small household construction", "text_np": "साना घरेलु निर्माण सहित सबै आयोजनाहरू", "is_correct": False},
                {"text_en": "Only hydropower projects", "text_np": "जलविद्युत आयोजनाहरू मात्र", "is_correct": False},
                {"text_en": "Foreign-funded projects only", "text_np": "विदेशी वित्त पोषित आयोजनाहरू मात्र", "is_correct": False},
            ],
            "explanation_en": "Nepal's Environment Protection Act 2076 BS requires an EIA for projects above specified thresholds that may cause significant environmental impact — such as hydropower plants, road construction, mining, and industrial projects.",
            "explanation_np": "नेपालको वातावरण संरक्षण ऐन, २०७६ ले महत्त्वपूर्ण वातावरणीय प्रभाव पार्न सक्ने — जस्तै जलविद्युत संयन्त्र, सडक निर्माण, खनन र औद्योगिक आयोजनाहरू — निर्दिष्ट सीमाभन्दा माथिका आयोजनाहरूका लागि EIA आवश्यक पार्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Environmental Science",
        },
        {
            "question_text_en": "What does 'carbon sequestration' in forests mean?",
            "question_text_np": "वनमा 'कार्बन अनुक्रम' को अर्थ के हो?",
            "answers": [
                {"text_en": "The process by which forests absorb CO₂ from the atmosphere and store it in biomass and soil", "text_np": "वनले वायुमण्डलबाट CO₂ अवशोषण गरी जैवभार र माटोमा भण्डारण गर्ने प्रक्रिया", "is_correct": True},
                {"text_en": "Burning wood to release stored carbon", "text_np": "भण्डारित कार्बन छोड्न काठ जलाउनु", "is_correct": False},
                {"text_en": "Measuring carbon dioxide levels in forest air", "text_np": "वनको हावामा कार्बन डाइअक्साइडको स्तर मापन गर्नु", "is_correct": False},
                {"text_en": "Extracting carbon from forest soil for energy", "text_np": "ऊर्जाका लागि वनको माटोबाट कार्बन निकाल्नु", "is_correct": False},
            ],
            "explanation_en": "Carbon sequestration is the long-term storage of carbon dioxide in forests through photosynthesis. Trees absorb CO₂ and store carbon in their trunks, branches, roots, and soil. Forests act as important carbon sinks, mitigating climate change.",
            "explanation_np": "कार्बन अनुक्रम प्रकाश संश्लेषणमार्फत वनमा दीर्घकालीन रूपमा कार्बन डाइअक्साइड भण्डारण हो। रुखहरूले CO₂ अवशोषण गर्छन् र आफ्ना ट्रंक, हाँगा, जरा र माटोमा कार्बन भण्डार गर्छन्। वनहरू महत्त्वपूर्ण कार्बन सिंकको रूपमा कार्य गर्छन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Environmental Science",
        },
    ],

    # ─── SUBBRANCH-scoped: Agriculture ───────────────────────────────────
    "agriculture": [
        {
            "question_text_en": "What is 'agroforestry' and why is it practiced in Nepal's hills?",
            "question_text_np": "'कृषि वानिकी' के हो र नेपालको पहाडमा यो किन अभ्यास गरिन्छ?",
            "answers": [
                {"text_en": "Integrating trees with crops/livestock to improve productivity and environmental sustainability", "text_np": "उत्पादकता र वातावरणीय दिगोपन सुधार गर्न रुखहरूलाई बाली/पशुसँग एकीकृत गर्नु", "is_correct": True},
                {"text_en": "Converting forests into farmland", "text_np": "वनलाई खेतीयोग्य जमिनमा रूपान्तरण गर्नु", "is_correct": False},
                {"text_en": "Using forests only for collecting fuelwood", "text_np": "दाउरा संकलनका लागि मात्र वन प्रयोग गर्नु", "is_correct": False},
                {"text_en": "Farming exclusively in forested areas", "text_np": "वन क्षेत्रमा मात्र खेती गर्नु", "is_correct": False},
            ],
            "explanation_en": "Agroforestry integrates trees, crops, and/or livestock on the same land. In Nepal's hills, it prevents soil erosion, provides fodder, fuelwood, and fruit while maintaining soil fertility — critical in fragile mountain ecosystems.",
            "explanation_np": "कृषि वानिकीले एउटै जमिनमा रुख, बाली र/वा पशुलाई एकीकृत गर्छ। नेपालको पहाडमा यसले माटो क्षरण रोक्छ, घाँस, दाउरा र फल प्रदान गर्छ र माटोको उर्वरता कायम राख्छ — जो भंगुर पर्वतीय पारिस्थितिक प्रणालीमा महत्त्वपूर्ण छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Agriculture (Subbranch)",
        },
        {
            "question_text_en": "Which irrigation system is most common in Nepal's Terai for paddy cultivation?",
            "question_text_np": "धान खेतीका लागि नेपालको तराईमा सबैभन्दा सामान्य सिँचाइ प्रणाली कुन हो?",
            "answers": [
                {"text_en": "Canal irrigation (from rivers like Koshi, Gandaki, Karnali)", "text_np": "नहर सिँचाइ (कोशी, गण्डकी, कर्णाली जस्ता नदीहरूबाट)", "is_correct": True},
                {"text_en": "Drip irrigation", "text_np": "थोपा सिँचाइ", "is_correct": False},
                {"text_en": "Sprinkler irrigation", "text_np": "फोहोरा सिँचाइ", "is_correct": False},
                {"text_en": "Rainwater harvesting only", "text_np": "वर्षाजल संकलन मात्र", "is_correct": False},
            ],
            "explanation_en": "Canal irrigation using river water (from Koshi, Gandaki, Karnali river systems) is the dominant irrigation method in Nepal's Terai. Major irrigation projects include the Sunsari-Morang, Kankai, and Narayani irrigation systems.",
            "explanation_np": "नदीको पानी (कोशी, गण्डकी, कर्णाली नदी प्रणालीहरूबाट) प्रयोग गरी नहर सिँचाइ नेपालको तराईमा प्रमुख सिँचाइ विधि हो। प्रमुख सिँचाइ आयोजनाहरूमा सुनसरी-मोरङ, कंकाई र नारायणी सिँचाइ प्रणालीहरू पर्छन्।",
            "difficulty": "EASY",
            "source_reference": "PSC Agriculture (Subbranch)",
        },
        {
            "question_text_en": "What is 'terrace farming' (Pakho kheti) and why is it important in Nepal?",
            "question_text_np": "'भित्रे खेती' (पाखो खेती) के हो र नेपालमा यो किन महत्त्वपूर्ण छ?",
            "answers": [
                {"text_en": "Cutting hillside slopes into flat steps to grow crops and prevent soil erosion", "text_np": "बाली उगाउन र माटो क्षरण रोक्न पहाडी भिरालोहरूलाई समतल सिँढीहरूमा काट्नु", "is_correct": True},
                {"text_en": "Farming inside buildings on multiple floors", "text_np": "धेरै तल्लामा भवनभित्र खेती गर्नु", "is_correct": False},
                {"text_en": "Growing crops on riverbanks only", "text_np": "नदी किनारामा मात्र बाली उगाउनु", "is_correct": False},
                {"text_en": "A modern greenhouse technique", "text_np": "आधुनिक हरितगृह प्रविधि", "is_correct": False},
            ],
            "explanation_en": "Terrace farming (pakho kheti) carves flat steps into hillsides to create farmland. It conserves water, reduces runoff and erosion, and makes steep slopes farmable. It is the defining agricultural practice in Nepal's hilly areas.",
            "explanation_np": "भित्रे खेती (पाखो खेती) खेतीयोग्य जमिन बनाउन पहाडी भिरालोहरूमा समतल सिँढीहरू काट्छ। यसले पानी संरक्षण गर्छ, बहाव र क्षरण घटाउँछ र ठाडो भिरालोहरूलाई खेतीयोग्य बनाउँछ। यो नेपालको पहाडी क्षेत्रको प्रमुख कृषि अभ्यास हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Agriculture (Subbranch)",
        },
        {
            "question_text_en": "What is the role of the Agriculture Knowledge Centre (AKC) at district level in Nepal?",
            "question_text_np": "नेपालमा जिल्ला स्तरमा कृषि ज्ञान केन्द्र (AKC) को भूमिका के हो?",
            "answers": [
                {"text_en": "Providing agricultural extension services, technical advice, and input support directly to farmers", "text_np": "किसानहरूलाई सिधै कृषि प्रसार सेवा, प्राविधिक सल्लाह र आदान सहायता प्रदान गर्नु", "is_correct": True},
                {"text_en": "Conducting university-level agricultural research", "text_np": "विश्वविद्यालय स्तरको कृषि अनुसन्धान सञ्चालन गर्नु", "is_correct": False},
                {"text_en": "Regulating agricultural imports and exports", "text_np": "कृषि आयात र निर्यात नियमन गर्नु", "is_correct": False},
                {"text_en": "Providing agricultural loans to farmers", "text_np": "किसानहरूलाई कृषि ऋण प्रदान गर्नु", "is_correct": False},
            ],
            "explanation_en": "Agriculture Knowledge Centres (AKCs) operate at district level as the frontline delivery points for the Department of Agriculture. They provide technical extension services, conduct demonstrations, and distribute seeds and inputs to farmers.",
            "explanation_np": "कृषि ज्ञान केन्द्र (AKC) हरू कृषि विभागको अग्रिम सेवा वितरण बिन्दुको रूपमा जिल्ला स्तरमा सञ्चालन हुन्छन्। तिनीहरूले प्राविधिक प्रसार सेवाहरू प्रदान गर्छन्, प्रदर्शनीहरू सञ्चालन गर्छन् र किसानहरूलाई बिउ र आदानहरू वितरण गर्छन्।",
            "difficulty": "HARD",
            "source_reference": "PSC Agriculture (Subbranch)",
        },
        {
            "question_text_en": "Which crop is Nepal's largest agricultural export by value?",
            "question_text_np": "मूल्यका हिसाबले नेपालको सबैभन्दा ठूलो कृषि निर्यात बाली कुन हो?",
            "answers": [
                {"text_en": "Large cardamom (Alaichi)", "text_np": "ठूलो अलैंची", "is_correct": True},
                {"text_en": "Tea (Chiya)", "text_np": "चिया", "is_correct": False},
                {"text_en": "Ginger (Aduwa)", "text_np": "अदुवा", "is_correct": False},
                {"text_en": "Lentils (Daal)", "text_np": "दाल", "is_correct": False},
            ],
            "explanation_en": "Large cardamom is Nepal's most valuable agricultural export. Nepal is the world's largest producer and exporter of large cardamom (Amomum subulatum), primarily exported to India.",
            "explanation_np": "ठूलो अलैंची नेपालको सबैभन्दा मूल्यवान कृषि निर्यात हो। नेपाल ठूलो अलैंची (Amomum subulatum) को विश्वकै सबैभन्दा ठूलो उत्पादक र निर्यातकर्ता हो, जुन मुख्य रूपमा भारतमा निर्यात गरिन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Agriculture (Subbranch)",
        },
    ],

    # ─── SUBBRANCH-scoped: Livestock Development ─────────────────────────
    "livestock-development": [
        {
            "question_text_en": "Which organization is responsible for livestock development and animal health in Nepal?",
            "question_text_np": "नेपालमा पशुपालन विकास र पशु स्वास्थ्यको जिम्मेवार संस्था कुन हो?",
            "answers": [
                {"text_en": "Department of Livestock Services (DoLS)", "text_np": "पशुसेवा विभाग (DoLS)", "is_correct": True},
                {"text_en": "Nepal Agricultural Research Council (NARC)", "text_np": "नेपाल कृषि अनुसन्धान परिषद् (NARC)", "is_correct": False},
                {"text_en": "Department of Agriculture (DoA)", "text_np": "कृषि विभाग (DoA)", "is_correct": False},
                {"text_en": "Ministry of Health and Population", "text_np": "स्वास्थ्य तथा जनसंख्या मन्त्रालय", "is_correct": False},
            ],
            "explanation_en": "The Department of Livestock Services (DoLS), under the Ministry of Agriculture and Livestock Development, is responsible for animal health services, breed improvement, veterinary services, and livestock development programs.",
            "explanation_np": "कृषि तथा पशुपंछी विकास मन्त्रालय अन्तर्गतको पशुसेवा विभाग (DoLS) पशु स्वास्थ्य सेवा, नस्ल सुधार, पशु चिकित्सा सेवा र पशुपालन विकास कार्यक्रमहरूका लागि जिम्मेवार छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Livestock Development",
        },
        {
            "question_text_en": "What is 'artificial insemination' (AI) in livestock development?",
            "question_text_np": "पशुपालन विकासमा 'कृत्रिम गर्भाधान' (AI) के हो?",
            "answers": [
                {"text_en": "Depositing semen into a female animal's reproductive tract without natural mating to improve breed quality", "text_np": "नस्ल गुणस्तर सुधार गर्न प्राकृतिक सम्पर्क बिना पोथी जनावरको प्रजनन नलीमा वीर्य प्रविष्ट गराउनु", "is_correct": True},
                {"text_en": "Using machines to feed animals automatically", "text_np": "स्वचालित रूपमा जनावरहरूलाई खाना खुवाउन मेसिन प्रयोग गर्नु", "is_correct": False},
                {"text_en": "A surgical procedure to increase milk production", "text_np": "दूध उत्पादन बढाउन शल्यक्रिया प्रक्रिया", "is_correct": False},
                {"text_en": "Introducing foreign animal species into Nepal", "text_np": "नेपालमा विदेशी जनावरका प्रजातिहरू पेश गर्नु", "is_correct": False},
            ],
            "explanation_en": "Artificial Insemination (AI) is a livestock improvement technique where semen from superior sires is collected, processed, and deposited into the female's uterus. It is widely used in Nepal to improve cattle and buffalo milk/meat productivity.",
            "explanation_np": "कृत्रिम गर्भाधान (AI) एक पशुपालन सुधार प्रविधि हो जसमा उत्कृष्ट नर जनावरहरूबाट वीर्य संकलन, प्रशोधन र पोथीको गर्भाशयमा प्रविष्ट गराइन्छ। यो नेपालमा गाई र भैंसीको दूध/मासु उत्पादकता सुधार गर्न व्यापक रूपमा प्रयोग गरिन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Livestock Development",
        },
        {
            "question_text_en": "Nepal's yak is a high-altitude livestock. In which region of Nepal is yak herding primarily practiced?",
            "question_text_np": "नेपालको च्यांग्रा (याक) एक उच्च उचाइको पशुधन हो। नेपालको कुन क्षेत्रमा च्यांग्रा पालन मुख्य रूपमा अभ्यास गरिन्छ?",
            "answers": [
                {"text_en": "High Himalayan and alpine zones above 3,000 metres", "text_np": "३,०००  मिटरभन्दा माथिको उच्च हिमाली र अल्पाइन क्षेत्रहरू", "is_correct": True},
                {"text_en": "Terai plains", "text_np": "तराई मैदान", "is_correct": False},
                {"text_en": "Kathmandu Valley", "text_np": "काठमाडौं उपत्यका", "is_correct": False},
                {"text_en": "Inner Terai (Chitwan, Dang)", "text_np": "भित्री तराई (चितवन, दाङ)", "is_correct": False},
            ],
            "explanation_en": "Yak (Bos grunniens) are adapted to high altitudes and are herded in Nepal's Himalayan districts (Solukhumbu, Humla, Dolpa, Mustang, etc.) above 3,000 metres. They provide milk, meat, wool, and serve as pack animals.",
            "explanation_np": "याक (Bos grunniens) उच्च उचाइमा अनुकूलित छन् र नेपालका हिमाली जिल्लाहरू (सोलुखुम्बु, हुम्ला, डोल्पा, मुस्ताङ आदि) मा ३,००० मिटरभन्दा माथि पालिन्छन्। तिनीहरूले दूध, मासु, ऊन प्रदान गर्छन् र भरियाका रूपमा काम गर्छन्।",
            "difficulty": "EASY",
            "source_reference": "PSC Livestock Development",
        },
        {
            "question_text_en": "What is the main objective of Nepal's commercial poultry sector?",
            "question_text_np": "नेपालको व्यावसायिक कुखुरापालन क्षेत्रको मुख्य उद्देश्य के हो?",
            "answers": [
                {"text_en": "Producing eggs and broiler meat to meet domestic protein demand", "text_np": "घरेलु प्रोटिन माग पूरा गर्न अण्डा र ब्रोइलर मासु उत्पादन गर्नु", "is_correct": True},
                {"text_en": "Exporting live poultry to international markets", "text_np": "अन्तर्राष्ट्रिय बजारमा जीवित कुखुरा निर्यात गर्नु", "is_correct": False},
                {"text_en": "Producing feathers for export", "text_np": "निर्यातका लागि प्वाँखहरू उत्पादन गर्नु", "is_correct": False},
                {"text_en": "Wildlife conservation of wild bird species", "text_np": "जंगली चरा प्रजातिहरूको वन्यजन्तु संरक्षण", "is_correct": False},
            ],
            "explanation_en": "Nepal's commercial poultry sector is a major source of eggs and broiler chicken meat, primarily concentrated in areas around Chitwan, Pokhara, and the Kathmandu Valley. It helps meet domestic protein needs.",
            "explanation_np": "नेपालको व्यावसायिक कुखुरापालन क्षेत्र अण्डा र ब्रोइलर कुखुराको मासुको प्रमुख स्रोत हो, जुन मुख्य रूपमा चितवन, पोखरा र काठमाडौं उपत्यकाको वरिपरिका क्षेत्रहरूमा केन्द्रित छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Livestock Development",
        },
        {
            "question_text_en": "What is 'foot and mouth disease' (FMD) and why is it significant for Nepal's livestock sector?",
            "question_text_np": "'खुरपाका रोग' (FMD) के हो र नेपालको पशुपालन क्षेत्रका लागि यो किन महत्त्वपूर्ण छ?",
            "answers": [
                {"text_en": "A highly contagious viral disease of cloven-hoofed animals causing major economic losses", "text_np": "खुरिया जनावरहरूको अत्यन्त संक्रामक भाइरल रोग जसले ठूलो आर्थिक क्षति पुर्‍याउँछ", "is_correct": True},
                {"text_en": "A fungal disease affecting crop roots", "text_np": "बालीको जरालाई प्रभावित गर्ने ढुसी रोग", "is_correct": False},
                {"text_en": "A parasitic infection in poultry", "text_np": "कुखुरामा परजीवी संक्रमण", "is_correct": False},
                {"text_en": "A nutritional deficiency in high-altitude yaks", "text_np": "उच्च उचाइका याकमा पोषण सम्बन्धी कमी", "is_correct": False},
            ],
            "explanation_en": "Foot and Mouth Disease (FMD) is a highly contagious viral disease affecting cattle, buffalo, pigs, and sheep. It causes severe production losses and restricts livestock trade. Nepal conducts regular FMD vaccination campaigns.",
            "explanation_np": "खुरपाका रोग (FMD) गाई, भैंसी, बंगुर र भेडालाई प्रभावित गर्ने अत्यन्त संक्रामक भाइरल रोग हो। यसले उत्पादनमा ठूलो नोक्सान पुर्‍याउँछ र पशुपालन व्यापार रोक्छ। नेपालले नियमित FMD खोपकार्यक्रमहरू सञ्चालन गर्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Livestock Development",
        },
    ],

    # ─── SUBBRANCH-scoped: Forestry ──────────────────────────────────────
    "forestry": [
        {
            "question_text_en": "What is 'silviculture' in forestry?",
            "question_text_np": "वन विज्ञानमा 'वृक्ष वर्द्धन विज्ञान' (silviculture) के हो?",
            "answers": [
                {"text_en": "The science and art of controlling the establishment, growth, and quality of forest stands", "text_np": "वन स्टान्डहरूको स्थापना, वृद्धि र गुणस्तर नियन्त्रण गर्ने विज्ञान र कला", "is_correct": True},
                {"text_en": "The study of silver ore extraction from forests", "text_np": "वनबाट चाँदी अयस्क निष्कर्षणको अध्ययन", "is_correct": False},
                {"text_en": "A type of forest fire prevention technique", "text_np": "वन डढेलो रोकथामको एक प्रकारको प्रविधि", "is_correct": False},
                {"text_en": "The science of counting trees in a forest area", "text_np": "वन क्षेत्रमा रुखहरू गन्ने विज्ञान", "is_correct": False},
            ],
            "explanation_en": "Silviculture is the practice and science of controlling the establishment, growth, composition, health, and quality of forests to meet specific objectives. It includes methods like clear-cutting, selective logging, and reforestation.",
            "explanation_np": "वृक्ष वर्द्धन विज्ञान (silviculture) विशिष्ट उद्देश्यहरू पूरा गर्न वनहरूको स्थापना, वृद्धि, संरचना, स्वास्थ्य र गुणस्तर नियन्त्रण गर्ने अभ्यास र विज्ञान हो।",
            "difficulty": "HARD",
            "source_reference": "PSC Forestry (Subbranch)",
        },
        {
            "question_text_en": "What is the primary goal of 'reforestation' programs in Nepal?",
            "question_text_np": "नेपालमा 'पुनर्वनीकरण' कार्यक्रमहरूको प्राथमिक लक्ष्य के हो?",
            "answers": [
                {"text_en": "Restoring tree cover on degraded, cleared, or lost forest land", "text_np": "क्षरण भएको, खाली गरिएको वा हराएको वन भूमिमा वृक्षावरण पुनर्स्थापना गर्नु", "is_correct": True},
                {"text_en": "Building new roads through forest areas", "text_np": "वन क्षेत्रहरूमा नयाँ सडकहरू निर्माण गर्नु", "is_correct": False},
                {"text_en": "Replacing forests with commercial plantations only", "text_np": "वनहरूलाई व्यावसायिक बगानहरूले मात्र प्रतिस्थापन गर्नु", "is_correct": False},
                {"text_en": "Converting forests to agricultural land", "text_np": "वनलाई कृषि भूमिमा रूपान्तरण गर्नु", "is_correct": False},
            ],
            "explanation_en": "Reforestation restores tree cover on deforested or degraded lands. In Nepal, major reforestation programs include community forest programs, watershed management projects, and the National Tree Planting Campaign.",
            "explanation_np": "पुनर्वनीकरणले वनविनाश भएको वा क्षरित भूमिमा वृक्षावरण पुनर्स्थापित गर्छ। नेपालमा प्रमुख पुनर्वनीकरण कार्यक्रमहरूमा सामुदायिक वन कार्यक्रम, जलाधार व्यवस्थापन आयोजनाहरू र राष्ट्रिय वृक्षारोपण अभियान पर्छन्।",
            "difficulty": "EASY",
            "source_reference": "PSC Forestry (Subbranch)",
        },
        {
            "question_text_en": "What is the main function of the Department of Forest and Soil Conservation (DFSC) in Nepal?",
            "question_text_np": "नेपालमा वन तथा भूसंरक्षण विभाग (DFSC) को मुख्य काम के हो?",
            "answers": [
                {"text_en": "Managing government-managed forests, implementing forestry programs, and soil conservation", "text_np": "सरकार-व्यवस्थित वनहरूको व्यवस्थापन, वन कार्यक्रमहरूको कार्यान्वयन र माटो संरक्षण", "is_correct": True},
                {"text_en": "Managing national parks and wildlife", "text_np": "राष्ट्रिय निकुञ्ज र वन्यजन्तुको व्यवस्थापन", "is_correct": False},
                {"text_en": "Agricultural research and crop development", "text_np": "कृषि अनुसन्धान र बाली विकास", "is_correct": False},
                {"text_en": "Monitoring climate change at meteorological stations", "text_np": "मौसम विज्ञान केन्द्रहरूमा जलवायु परिवर्तन अनुगमन", "is_correct": False},
            ],
            "explanation_en": "The Department of Forest and Soil Conservation (DFSC) manages government-managed forests, implements community and leasehold forestry programs, and conducts soil conservation activities across Nepal.",
            "explanation_np": "वन तथा भूसंरक्षण विभाग (DFSC) सरकार-व्यवस्थित वनहरूको व्यवस्थापन गर्छ, सामुदायिक र पट्टा वन कार्यक्रमहरू कार्यान्वयन गर्छ र नेपालभरि माटो संरक्षण गतिविधिहरू सञ्चालन गर्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Forestry (Subbranch)",
        },
        {
            "question_text_en": "Non-Timber Forest Products (NTFPs) are important for Nepal. Which of the following is an example?",
            "question_text_np": "गैर-काष्ठ वन उत्पादन (NTFPs) नेपालका लागि महत्त्वपूर्ण छन्। निम्नमध्ये कुन उदाहरण हो?",
            "answers": [
                {"text_en": "Honey, medicinal herbs (Jatamasi, Kutki), resin, and bamboo products", "text_np": "मह, औषधीय जडिबुटी (जटामसी, कुटकी), रेजिन र बाँस उत्पादनहरू", "is_correct": True},
                {"text_en": "Timber logs for construction", "text_np": "निर्माणका लागि काठको टुक्राहरू", "is_correct": False},
                {"text_en": "Charcoal from burning wood", "text_np": "काठ जलाएर बनेको कोइला", "is_correct": False},
                {"text_en": "Wood pulp for paper production", "text_np": "कागज उत्पादनका लागि काठको लुगदी", "is_correct": False},
            ],
            "explanation_en": "NTFPs include all forest products other than timber — honey, medicinal plants (Yarsagumba, Jatamasi, Kutki), essential oils, resin, cane, bamboo, and wild fruits. NTFPs are a critical livelihood source for mountain communities in Nepal.",
            "explanation_np": "NTFPs मा काठ बाहेकका सबै वन उत्पादनहरू पर्छन् — मह, औषधीय बिरुवाहरू (यार्सागुम्बा, जटामसी, कुटकी), आवश्यक तेलहरू, रेजिन, बेत, बाँस र जंगली फलफूल। NTFPs नेपालका पर्वतीय समुदायहरूको लागि महत्त्वपूर्ण जीविकोपार्जन स्रोत हो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Forestry (Subbranch)",
        },
        {
            "question_text_en": "What is 'social forestry' and how does it differ from community forestry in Nepal?",
            "question_text_np": "'सामाजिक वानिकी' के हो र यो नेपालमा सामुदायिक वनबाट कसरी भिन्न छ?",
            "answers": [
                {"text_en": "Forestry programs on non-forest land (roads, farms, degraded land) to meet local needs; community forestry manages handover of national forest to user groups", "text_np": "स्थानीय आवश्यकताहरू पूरा गर्न गैर-वन भूमि (सडक, खेत, क्षरित भूमि) मा वन कार्यक्रम; सामुदायिक वनले उपभोक्ता समूहलाई राष्ट्रिय वन हस्तान्तरण व्यवस्थापन गर्छ", "is_correct": True},
                {"text_en": "They are exactly the same program", "text_np": "यी बिल्कुल एउटै कार्यक्रम हुन्", "is_correct": False},
                {"text_en": "Social forestry is only for wealthy landowners", "text_np": "सामाजिक वानिकी केवल धनी जमिन मालिकहरूका लागि हो", "is_correct": False},
                {"text_en": "Social forestry involves only tree planting without management", "text_np": "सामाजिक वानिकीमा व्यवस्थापन बिना वृक्षारोपण मात्र हुन्छ", "is_correct": False},
            ],
            "explanation_en": "Social forestry involves growing trees on non-forest land (farms, roadsides, degraded wasteland) to meet local needs for fuel, fodder, and timber. Community forestry specifically involves handing over national forest management to local user groups.",
            "explanation_np": "सामाजिक वानिकीमा इन्धन, घाँस र काठका लागि स्थानीय आवश्यकताहरू पूरा गर्न गैर-वन भूमि (खेत, सडक किनारा, क्षरित बाँझो जमिन) मा रुखहरू उगाउनु पर्छ। सामुदायिक वनले विशेष रूपमा स्थानीय उपभोक्ता समूहलाई राष्ट्रिय वन व्यवस्थापन हस्तान्तरण समावेश गर्छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Forestry (Subbranch)",
        },
    ],

    # ─── SUBBRANCH-scoped: Soil Conservation ─────────────────────────────
    "soil-conservation": [
        {
            "question_text_en": "What is soil erosion and which type is most severe in Nepal's hilly areas?",
            "question_text_np": "माटो क्षरण के हो र नेपालको पहाडी क्षेत्रमा कुन प्रकार सबैभन्दा गम्भीर छ?",
            "answers": [
                {"text_en": "Removal of topsoil by water or wind; water erosion (sheet, rill, and gully erosion) is most severe in Nepal's hills", "text_np": "पानी वा हावाद्वारा माथिल्लो माटोको हटाउनु; पानी क्षरण (पाना, नाली र खड्किलो क्षरण) नेपालको पहाडमा सबैभन्दा गम्भीर छ", "is_correct": True},
                {"text_en": "Soil contamination by chemicals only", "text_np": "रसायनहरूद्वारा मात्र माटो प्रदूषण", "is_correct": False},
                {"text_en": "Earthquake damage to farmland", "text_np": "खेतीयोग्य जमिनमा भूकम्पको क्षति", "is_correct": False},
                {"text_en": "Frost damage to topsoil", "text_np": "माथिल्लो माटोमा हिमपातको क्षति", "is_correct": False},
            ],
            "explanation_en": "Soil erosion is the wearing away and displacement of topsoil. In Nepal's steep hilly terrain, water erosion (sheet erosion on slopes, rill erosion, and gully formation) is the dominant form due to monsoon rainfall and deforestation.",
            "explanation_np": "माटो क्षरण भनेको माथिल्लो माटोको क्षय र विस्थापन हो। नेपालको ठाडो पहाडी भूभागमा मनसुन वर्षा र वनविनाशका कारण पानी क्षरण (भिरालोमा पाना क्षरण, नाली क्षरण र खड्किलो निर्माण) प्रमुख रूप हो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Soil Conservation",
        },
        {
            "question_text_en": "Which of the following is a biological method used for soil conservation in Nepal?",
            "question_text_np": "निम्नमध्ये कुन नेपालमा माटो संरक्षणका लागि प्रयोग गरिने जैविक विधि हो?",
            "answers": [
                {"text_en": "Planting vetiver grass (Khus Khus) on slopes to stabilize soil", "text_np": "माटो स्थिर गर्न भिरालोमा बेनी घाँस (खस खस) रोप्नु", "is_correct": True},
                {"text_en": "Building concrete retaining walls", "text_np": "कंक्रीट भिमभित्ता निर्माण गर्नु", "is_correct": False},
                {"text_en": "Using chemical soil hardeners", "text_np": "रासायनिक माटो कठोरकहरू प्रयोग गर्नु", "is_correct": False},
                {"text_en": "Installing drainpipes underground", "text_np": "भूमिगत रूपमा नाली पाइप जडान गर्नु", "is_correct": False},
            ],
            "explanation_en": "Vetiver grass (Chrysopogon zizanioides / Khus Khus) is widely used as a biological soil conservation measure in Nepal. Its deep, dense root system holds soil on slopes, prevents erosion, and can tolerate extreme conditions.",
            "explanation_np": "बेनी घाँस (Chrysopogon zizanioides / खस खस) नेपालमा जैविक माटो संरक्षण उपायको रूपमा व्यापक रूपमा प्रयोग गरिन्छ। यसको गहिरो, घना जरा प्रणालीले भिरालोमा माटो समात्छ, क्षरण रोक्छ र चरम अवस्थाहरू सहन सक्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Soil Conservation",
        },
        {
            "question_text_en": "What is 'land capability classification' in soil and land management?",
            "question_text_np": "माटो र भूमि व्यवस्थापनमा 'भूमि क्षमता वर्गीकरण' के हो?",
            "answers": [
                {"text_en": "A system of grouping soils by their suitability for general agriculture and limiting factors like slope, erosion, and wetness", "text_np": "ढलान, क्षरण र आर्द्रता जस्ता सीमित कारकहरू र सामान्य कृषिको उपयुक्तताले माटोहरूलाई समूहीकरण गर्ने प्रणाली", "is_correct": True},
                {"text_en": "Classification of land by ownership and legal title", "text_np": "स्वामित्व र कानुनी शीर्षकद्वारा भूमि वर्गीकरण", "is_correct": False},
                {"text_en": "Classification of land based on market value only", "text_np": "बजार मूल्यमा मात्र आधारित भूमि वर्गीकरण", "is_correct": False},
                {"text_en": "Measuring the total area of farmable land in a district", "text_np": "जिल्लामा खेतीयोग्य जमिनको कुल क्षेत्रफल मापन गर्नु", "is_correct": False},
            ],
            "explanation_en": "Land Capability Classification (USDA system) groups soils into 8 classes (I-VIII) based on their limitations for sustained use. Class I is ideal for all crops; Class VIII is only suitable for wildlife/watershed protection.",
            "explanation_np": "भूमि क्षमता वर्गीकरण (USDA प्रणाली) ले माटोहरूलाई निरन्तर प्रयोगका लागि सीमाहरूका आधारमा ८ वर्गहरूमा (I-VIII) समूहीकृत गर्छ। वर्ग I सबै बालीका लागि आदर्श हो; वर्ग VIII केवल वन्यजन्तु/जलाधार संरक्षणका लागि उपयुक्त छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Soil Conservation",
        },
        {
            "question_text_en": "Gabion structures are used for which purpose in Nepal's watershed management?",
            "question_text_np": "नेपालको जलाधार व्यवस्थापनमा ग्याबियन संरचनाहरू कुन उद्देश्यका लागि प्रयोग गरिन्छन्?",
            "answers": [
                {"text_en": "Controlling river bank erosion and stabilizing hillside gullies using wire mesh filled with stones", "text_np": "ढुंगाले भरिएको तार जाल प्रयोग गरी नदी किनारको क्षरण नियन्त्रण र पहाडी खड्किलो स्थिरीकरण गर्नु", "is_correct": True},
                {"text_en": "Building dams for hydropower generation", "text_np": "जलविद्युत उत्पादनका लागि बाँध निर्माण गर्नु", "is_correct": False},
                {"text_en": "Creating fish ponds in rivers", "text_np": "नदीहरूमा माछापोखरी बनाउनु", "is_correct": False},
                {"text_en": "Measuring rainfall in a watershed area", "text_np": "जलाधार क्षेत्रमा वर्षा मापन गर्नु", "is_correct": False},
            ],
            "explanation_en": "Gabion structures are wire mesh baskets filled with rocks, used to control erosion on river banks, stabilize gullies and landslide-prone slopes. They are widely used in Nepal's watershed management and bioengineering projects.",
            "explanation_np": "ग्याबियन संरचनाहरू ढुंगाले भरिएका तार जाल टोकरीहरू हुन्, जो नदी किनारमा क्षरण नियन्त्रण गर्न, खड्किलो र भूस्खलन-प्रवण भिरालोहरू स्थिर गर्न प्रयोग गरिन्छन्। यिनीहरू नेपालको जलाधार व्यवस्थापन र जैव-ईन्जिनियरिङ आयोजनाहरूमा व्यापक रूपमा प्रयोग गरिन्छन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Soil Conservation",
        },
        {
            "question_text_en": "What does 'watershed management' aim to achieve?",
            "question_text_np": "'जलाधार व्यवस्थापन' ले के हासिल गर्ने लक्ष्य राख्छ?",
            "answers": [
                {"text_en": "Managing land and water resources within a drainage basin to optimize water yield, reduce erosion, and support livelihoods", "text_np": "जलापूर्ति अनुकूलन, क्षरण घटाउन र जीविकोपार्जन समर्थन गर्न जल निकास बेसिनभित्रको भूमि र जल स्रोतहरूको व्यवस्थापन गर्नु", "is_correct": True},
                {"text_en": "Building reservoirs only for drinking water", "text_np": "पिउने पानीका लागि मात्र जलाशयहरू निर्माण गर्नु", "is_correct": False},
                {"text_en": "Draining all wetlands to expand farmland", "text_np": "खेतीयोग्य जमिन विस्तार गर्न सबै सिमसार सुकाउनु", "is_correct": False},
                {"text_en": "Preventing all human activities in river catchment areas", "text_np": "नदी जलग्रहण क्षेत्रहरूमा सबै मानव गतिविधिहरू रोक्नु", "is_correct": False},
            ],
            "explanation_en": "Watershed management involves coordinated management of land, water, vegetation, and other resources within a watershed to optimize use, minimize damage from floods and droughts, and sustain livelihoods and ecosystem services.",
            "explanation_np": "जलाधार व्यवस्थापनमा उपयोग अनुकूलन गर्न, बाढी र खडेरीबाट हुने क्षति न्यूनीकरण गर्न र जीविकोपार्जन र पारिस्थितिक सेवाहरू दिगो बनाउन जलाधारभित्रको भूमि, जल, वनस्पति र अन्य स्रोतहरूको समन्वित व्यवस्थापन समावेश हुन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Soil Conservation",
        },
    ],
}