"""Computer Knowledge (कम्प्युटर ज्ञान) — UNIVERSAL category questions."""

QUESTIONS = [
    {
        "question_text_en": "What does 'CPU' stand for?",
        "question_text_np": "'CPU' को पूरा रूप के हो?",
        "answers": [
            {"text_en": "Central Processing Unit", "text_np": "सेन्ट्रल प्रोसेसिङ युनिट", "is_correct": True},
            {"text_en": "Central Programming Unit", "text_np": "सेन्ट्रल प्रोग्रामिङ युनिट", "is_correct": False},
            {"text_en": "Computer Processing Unit", "text_np": "कम्प्युटर प्रोसेसिङ युनिट", "is_correct": False},
            {"text_en": "Core Processing Utility", "text_np": "कोर प्रोसेसिङ युटिलिटी", "is_correct": False},
        ],
        "explanation_en": "CPU stands for Central Processing Unit. It is the primary component of a computer that performs most of the processing inside a computer.",
        "explanation_np": "CPU को पूरा रूप Central Processing Unit हो। यो कम्प्युटरको मुख्य घटक हो जसले कम्प्युटर भित्रको अधिकांश प्रक्रिया सम्पन्न गर्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "What is 1 Gigabyte (GB) equal to?",
        "question_text_np": "१ गिगाबाइट (GB) कतिको बराबर हो?",
        "answers": [
            {"text_en": "1024 Megabytes", "text_np": "१०२४ मेगाबाइट", "is_correct": True},
            {"text_en": "1000 Megabytes", "text_np": "१००० मेगाबाइट", "is_correct": False},
            {"text_en": "1024 Kilobytes", "text_np": "१०२४ किलोबाइट", "is_correct": False},
            {"text_en": "512 Megabytes", "text_np": "५१२ मेगाबाइट", "is_correct": False},
        ],
        "explanation_en": "1 GB = 1024 MB (Megabytes). The full hierarchy: 1 KB = 1024 Bytes, 1 MB = 1024 KB, 1 GB = 1024 MB.",
        "explanation_np": "१ GB = १०२४ MB (मेगाबाइट)। पूर्ण क्रमबद्धता: १ KB = १०२४ Bytes, १ MB = १०२४ KB, १ GB = १०२४ MB।",
        "difficulty": "EASY",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "Which of the following is an example of an operating system?",
        "question_text_np": "निम्नमध्ये कुन अपरेटिङ सिस्टमको उदाहरण हो?",
        "answers": [
            {"text_en": "Windows 11", "text_np": "विन्डोज ११", "is_correct": True},
            {"text_en": "Microsoft Word", "text_np": "माइक्रोसफ्ट वर्ड", "is_correct": False},
            {"text_en": "Google Chrome", "text_np": "गुगल क्रोम", "is_correct": False},
            {"text_en": "Photoshop", "text_np": "फोटोशप", "is_correct": False},
        ],
        "explanation_en": "Windows 11, macOS, Linux, and Android are examples of operating systems. MS Word, Chrome, and Photoshop are application software that run on top of an OS.",
        "explanation_np": "Windows 11, macOS, Linux र Android अपरेटिङ सिस्टमका उदाहरण हुन्। MS Word, Chrome र Photoshop application software हुन् जुन OS मा चल्छन्।",
        "difficulty": "EASY",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "What is the function of the 'RAM' in a computer?",
        "question_text_np": "कम्प्युटरमा 'RAM' को कार्य के हो?",
        "answers": [
            {"text_en": "To temporarily store data for active processes", "text_np": "सक्रिय प्रक्रियाहरूको लागि डेटा अस्थायी रूपमा भण्डारण गर्नु", "is_correct": True},
            {"text_en": "To permanently store all files and programs", "text_np": "सबै फाइलहरू र कार्यक्रमहरू स्थायी रूपमा भण्डारण गर्नु", "is_correct": False},
            {"text_en": "To process and execute instructions", "text_np": "निर्देशनहरू प्रशोधन र कार्यान्वयन गर्नु", "is_correct": False},
            {"text_en": "To display output on the monitor", "text_np": "मनिटरमा आउटपुट देखाउनु", "is_correct": False},
        ],
        "explanation_en": "RAM (Random Access Memory) temporarily stores data that the CPU is currently using. It is volatile — data is lost when power is off. The hard disk stores data permanently.",
        "explanation_np": "RAM (Random Access Memory) CPU ले हाल प्रयोग गरिरहेको डेटा अस्थायी रूपमा भण्डारण गर्छ। यो volatile हो — बिजुली गएपछि डेटा हराउँछ।",
        "difficulty": "EASY",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "What does 'URL' stand for?",
        "question_text_np": "'URL' को पूरा रूप के हो?",
        "answers": [
            {"text_en": "Uniform Resource Locator", "text_np": "युनिफर्म रिसोर्स लोकेटर", "is_correct": True},
            {"text_en": "Universal Reference Link", "text_np": "युनिभर्सल रेफरेन्स लिंक", "is_correct": False},
            {"text_en": "Unified Resource Location", "text_np": "युनिफाइड रिसोर्स लोकेसन", "is_correct": False},
            {"text_en": "Uniform Remote Link", "text_np": "युनिफर्म रिमोट लिंक", "is_correct": False},
        ],
        "explanation_en": "URL stands for Uniform Resource Locator. It is the address used to access resources on the internet, e.g., https://www.nepal.gov.np",
        "explanation_np": "URL को पूरा रूप Uniform Resource Locator हो। यो इन्टरनेटमा स्रोतहरू पहुँच गर्न प्रयोग गरिने ठेगाना हो, जस्तै: https://www.nepal.gov.np",
        "difficulty": "EASY",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "Which Microsoft Office application is primarily used for creating presentations?",
        "question_text_np": "प्रेजेन्टेसन बनाउनको लागि मुख्य रूपमा कुन Microsoft Office अनुप्रयोग प्रयोग गरिन्छ?",
        "answers": [
            {"text_en": "Microsoft PowerPoint", "text_np": "माइक्रोसफ्ट पावरप्वाइन्ट", "is_correct": True},
            {"text_en": "Microsoft Word", "text_np": "माइक्रोसफ्ट वर्ड", "is_correct": False},
            {"text_en": "Microsoft Excel", "text_np": "माइक्रोसफ्ट एक्सेल", "is_correct": False},
            {"text_en": "Microsoft Access", "text_np": "माइक्रोसफ्ट एक्सेस", "is_correct": False},
        ],
        "explanation_en": "Microsoft PowerPoint is used for creating slide presentations. Word is for documents, Excel for spreadsheets, and Access for databases.",
        "explanation_np": "Microsoft PowerPoint स्लाइड प्रेजेन्टेसन बनाउन प्रयोग गरिन्छ। Word कागजातका लागि, Excel स्प्रेडसिटका लागि र Access डेटाबेसका लागि हो।",
        "difficulty": "EASY",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "What is the keyboard shortcut to 'Copy' selected content in Windows?",
        "question_text_np": "Windows मा चयन गरिएको सामग्री 'Copy' गर्ने किबोर्ड सर्टकट के हो?",
        "answers": [
            {"text_en": "Ctrl + C", "text_np": "Ctrl + C", "is_correct": True},
            {"text_en": "Ctrl + V", "text_np": "Ctrl + V", "is_correct": False},
            {"text_en": "Ctrl + X", "text_np": "Ctrl + X", "is_correct": False},
            {"text_en": "Ctrl + Z", "text_np": "Ctrl + Z", "is_correct": False},
        ],
        "explanation_en": "Ctrl+C = Copy, Ctrl+V = Paste, Ctrl+X = Cut, Ctrl+Z = Undo. These are standard shortcuts in most Windows applications.",
        "explanation_np": "Ctrl+C = Copy, Ctrl+V = Paste, Ctrl+X = Cut, Ctrl+Z = Undo। यी Windows को अधिकांश अनुप्रयोगहरूमा मानक सर्टकटहरू हुन्।",
        "difficulty": "EASY",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "What is an 'IP Address'?",
        "question_text_np": "'IP ठेगाना' के हो?",
        "answers": [
            {"text_en": "A unique numerical address identifying a device on a network", "text_np": "नेटवर्कमा एउटा यन्त्र पहिचान गर्ने अद्वितीय संख्यात्मक ठेगाना", "is_correct": True},
            {"text_en": "A type of internet browser", "text_np": "एक प्रकारको इन्टरनेट ब्राउजर", "is_correct": False},
            {"text_en": "A storage device for internet data", "text_np": "इन्टरनेट डेटाको भण्डारण उपकरण", "is_correct": False},
            {"text_en": "A password for network access", "text_np": "नेटवर्क पहुँचको लागि पासवर्ड", "is_correct": False},
        ],
        "explanation_en": "An IP (Internet Protocol) Address is a unique numerical label assigned to each device connected to a computer network. Example: 192.168.1.1",
        "explanation_np": "IP (Internet Protocol) ठेगाना कम्प्युटर नेटवर्कमा जोडिएको प्रत्येक यन्त्रलाई दिइने अद्वितीय संख्यात्मक लेबल हो। उदाहरण: 192.168.1.1",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "What does 'PDF' stand for?",
        "question_text_np": "'PDF' को पूरा रूप के हो?",
        "answers": [
            {"text_en": "Portable Document Format", "text_np": "पोर्टेबल डकुमेन्ट फर्म्याट", "is_correct": True},
            {"text_en": "Printable Document File", "text_np": "प्रिन्टेबल डकुमेन्ट फाइल", "is_correct": False},
            {"text_en": "Personal Data Format", "text_np": "पर्सनल डेटा फर्म्याट", "is_correct": False},
            {"text_en": "Processing Data File", "text_np": "प्रोसेसिङ डेटा फाइल", "is_correct": False},
        ],
        "explanation_en": "PDF stands for Portable Document Format, developed by Adobe. It preserves document formatting across different platforms and devices.",
        "explanation_np": "PDF को पूरा रूप Portable Document Format हो, जुन Adobe द्वारा विकसित गरिएको हो। यसले विभिन्न प्लेटफर्म र यन्त्रहरूमा कागजातको ढाँचा सुरक्षित राख्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "In MS Word, which key combination is used to 'Save' a document?",
        "question_text_np": "MS Word मा कागजात 'Save' गर्न कुन Key combination प्रयोग गरिन्छ?",
        "answers": [
            {"text_en": "Ctrl + S", "text_np": "Ctrl + S", "is_correct": True},
            {"text_en": "Ctrl + P", "text_np": "Ctrl + P", "is_correct": False},
            {"text_en": "Ctrl + A", "text_np": "Ctrl + A", "is_correct": False},
            {"text_en": "Alt + F4", "text_np": "Alt + F4", "is_correct": False},
        ],
        "explanation_en": "Ctrl+S saves the document. Ctrl+P = Print, Ctrl+A = Select All, Alt+F4 = Close/Exit application.",
        "explanation_np": "Ctrl+S ले कागजात save गर्छ। Ctrl+P = Print, Ctrl+A = Select All, Alt+F4 = अनुप्रयोग बन्द गर्ने।",
        "difficulty": "EASY",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "Which of the following is an input device?",
        "question_text_np": "निम्नमध्ये कुन इनपुट उपकरण हो?",
        "answers": [
            {"text_en": "Scanner", "text_np": "स्क्यानर", "is_correct": True},
            {"text_en": "Printer", "text_np": "प्रिन्टर", "is_correct": False},
            {"text_en": "Monitor", "text_np": "मनिटर", "is_correct": False},
            {"text_en": "Speaker", "text_np": "स्पिकर", "is_correct": False},
        ],
        "explanation_en": "Input devices send data to the computer: scanner, keyboard, mouse, webcam. Output devices receive data from the computer: printer, monitor, speaker.",
        "explanation_np": "इनपुट उपकरणहरूले कम्प्युटरमा डेटा पठाउँछन्: स्क्यानर, किबोर्ड, माउस, वेबक्याम। आउटपुट उपकरणहरूले कम्प्युटरबाट डेटा प्राप्त गर्छन्: प्रिन्टर, मनिटर, स्पिकर।",
        "difficulty": "EASY",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "What is 'e-governance'?",
        "question_text_np": "'इ-शासन' (e-governance) के हो?",
        "answers": [
            {"text_en": "Use of digital technology to deliver government services efficiently", "text_np": "सरकारी सेवाहरू प्रभावकारी रूपमा प्रदान गर्न डिजिटल प्रविधिको प्रयोग", "is_correct": True},
            {"text_en": "Electronic voting in national elections", "text_np": "राष्ट्रिय निर्वाचनमा इलेक्ट्रोनिक मतदान", "is_correct": False},
            {"text_en": "Government-owned email systems", "text_np": "सरकारी स्वामित्वको इमेल प्रणाली", "is_correct": False},
            {"text_en": "Social media platforms run by the government", "text_np": "सरकारद्वारा सञ्चालित सोशल मिडिया प्लेटफर्म", "is_correct": False},
        ],
        "explanation_en": "E-governance refers to the application of ICT (Information and Communication Technology) to deliver government services, exchange information, and conduct transactions efficiently.",
        "explanation_np": "इ-शासन भनेको सरकारी सेवाहरू प्रदान गर्न, जानकारी आदानप्रदान गर्न र कारोबार सञ्चालन गर्न ICT (सूचना र सञ्चार प्रविधि) को प्रयोग हो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "What is the function of the 'Delete' key on a keyboard?",
        "question_text_np": "किबोर्डमा 'Delete' key को कार्य के हो?",
        "answers": [
            {"text_en": "Deletes the character to the right of the cursor", "text_np": "कर्सरको दायाँतर्फको अक्षर मेटाउँछ", "is_correct": True},
            {"text_en": "Deletes the character to the left of the cursor", "text_np": "कर्सरको बायाँतर्फको अक्षर मेटाउँछ", "is_correct": False},
            {"text_en": "Deletes the entire line", "text_np": "सम्पूर्ण लाइन मेटाउँछ", "is_correct": False},
            {"text_en": "Deletes the entire file", "text_np": "सम्पूर्ण फाइल मेटाउँछ", "is_correct": False},
        ],
        "explanation_en": "'Delete' key removes the character to the right of the cursor. 'Backspace' removes the character to the left of the cursor.",
        "explanation_np": "'Delete' key ले कर्सरको दायाँतर्फको अक्षर मेटाउँछ। 'Backspace' ले कर्सरको बायाँतर्फको अक्षर मेटाउँछ।",
        "difficulty": "EASY",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "What does 'WWW' stand for in internet terminology?",
        "question_text_np": "इन्टरनेट शब्दावलीमा 'WWW' को पूरा रूप के हो?",
        "answers": [
            {"text_en": "World Wide Web", "text_np": "वर्ल्ड वाइड वेब", "is_correct": True},
            {"text_en": "World Web Wireless", "text_np": "वर्ल्ड वेब वायरलेस", "is_correct": False},
            {"text_en": "Wide World Website", "text_np": "वाइड वर्ल्ड वेबसाइट", "is_correct": False},
            {"text_en": "Web Worldwide Window", "text_np": "वेब वर्ल्डवाइड विन्डो", "is_correct": False},
        ],
        "explanation_en": "WWW stands for World Wide Web, invented by Tim Berners-Lee in 1989. It is an information system on the internet allowing documents to be linked via hyperlinks.",
        "explanation_np": "WWW को पूरा रूप World Wide Web हो, जुन Tim Berners-Lee ले सन् १९८९ मा आविष्कार गरेका थिए। यो इन्टरनेटमा सूचना प्रणाली हो जसले hyperlinks मार्फत कागजातहरू जोड्न अनुमति दिन्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "In MS Excel, which symbol is used to begin a formula?",
        "question_text_np": "MS Excel मा सूत्र शुरू गर्न कुन प्रतीक प्रयोग गरिन्छ?",
        "answers": [
            {"text_en": "= (Equal sign)", "text_np": "= (बराबर चिह्न)", "is_correct": True},
            {"text_en": "+ (Plus sign)", "text_np": "+ (जोड चिह्न)", "is_correct": False},
            {"text_en": "@ (At sign)", "text_np": "@ (At चिह्न)", "is_correct": False},
            {"text_en": "# (Hash sign)", "text_np": "# (ह्यास चिह्न)", "is_correct": False},
        ],
        "explanation_en": "In MS Excel, all formulas must begin with an '=' sign. For example, =SUM(A1:A10) adds all values from A1 to A10.",
        "explanation_np": "MS Excel मा सबै सूत्रहरू '=' चिह्नले शुरू हुनुपर्छ। उदाहरणका लागि, =SUM(A1:A10) ले A1 देखि A10 सम्मका सबै मानहरू जोड्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "What is 'Phishing' in cybersecurity?",
        "question_text_np": "साइबर सुरक्षामा 'Phishing' के हो?",
        "answers": [
            {"text_en": "Fraudulent attempt to obtain sensitive information by disguising as a trusted entity", "text_np": "विश्वसनीय संस्थाको रूप धारण गरी संवेदनशील जानकारी चोर्ने धोखाधडी प्रयास", "is_correct": True},
            {"text_en": "A type of computer virus", "text_np": "एक प्रकारको कम्प्युटर भाइरस", "is_correct": False},
            {"text_en": "High-speed internet fishing for data", "text_np": "डेटाको लागि उच्च गति इन्टरनेट खोज", "is_correct": False},
            {"text_en": "Encrypting data for secure transmission", "text_np": "सुरक्षित प्रसारणको लागि डेटा इन्क्रिप्ट गर्ने", "is_correct": False},
        ],
        "explanation_en": "Phishing is a cybercrime where attackers send fake emails, messages, or create fake websites that appear to be from trusted sources to steal passwords, credit card numbers, etc.",
        "explanation_np": "Phishing एक साइबर अपराध हो जहाँ आक्रमणकारीहरूले पासवर्ड, क्रेडिट कार्ड नम्बर आदि चोर्न नक्कली इमेल, सन्देश पठाउँछन् वा नक्कली वेबसाइट बनाउँछन्।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "What does 'HTTP' stand for?",
        "question_text_np": "'HTTP' को पूरा रूप के हो?",
        "answers": [
            {"text_en": "HyperText Transfer Protocol", "text_np": "हाइपरटेक्स्ट ट्रान्सफर प्रोटोकल", "is_correct": True},
            {"text_en": "High Text Transfer Process", "text_np": "हाई टेक्स्ट ट्रान्सफर प्रोसेस", "is_correct": False},
            {"text_en": "Hyperlink Text Transport Protocol", "text_np": "हाइपरलिंक टेक्स्ट ट्रान्सपोर्ट प्रोटोकल", "is_correct": False},
            {"text_en": "Home Terminal Transfer Protocol", "text_np": "होम टर्मिनल ट्रान्सफर प्रोटोकल", "is_correct": False},
        ],
        "explanation_en": "HTTP stands for HyperText Transfer Protocol. HTTPS (with 'S' for Secure) is the encrypted version. Government websites in Nepal typically use HTTPS.",
        "explanation_np": "HTTP को पूरा रूप HyperText Transfer Protocol हो। HTTPS ('S' Secure को लागि) इन्क्रिप्टेड संस्करण हो। नेपालका सरकारी वेबसाइटहरूले सामान्यतया HTTPS प्रयोग गर्छन्।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "Which generation of computers uses VLSI (Very Large Scale Integration) chips?",
        "question_text_np": "कम्प्युटरको कुन पुस्ताले VLSI चिप प्रयोग गर्छ?",
        "answers": [
            {"text_en": "Fourth Generation", "text_np": "चौथो पुस्ता", "is_correct": True},
            {"text_en": "First Generation", "text_np": "पहिलो पुस्ता", "is_correct": False},
            {"text_en": "Second Generation", "text_np": "दोस्रो पुस्ता", "is_correct": False},
            {"text_en": "Third Generation", "text_np": "तेस्रो पुस्ता", "is_correct": False},
        ],
        "explanation_en": "Generations: 1st = Vacuum tubes, 2nd = Transistors, 3rd = Integrated circuits (ICs), 4th = VLSI microprocessors (current PCs), 5th = AI/parallel processing.",
        "explanation_np": "पुस्ताहरू: १ म = Vacuum tubes, २ रो = Transistors, ३ रो = ICs, ४ थो = VLSI microprocessors (हालका PC), ५ औं = AI/parallel processing।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "What is the primary purpose of an 'antivirus' program?",
        "question_text_np": "'एन्टिभाइरस' कार्यक्रमको मुख्य उद्देश्य के हो?",
        "answers": [
            {"text_en": "To detect and remove malicious software from a computer", "text_np": "कम्प्युटरबाट हानिकारक सफ्टवेयर पत्ता लगाउने र हटाउने", "is_correct": True},
            {"text_en": "To speed up internet connection", "text_np": "इन्टरनेट जडानको गति बढाउने", "is_correct": False},
            {"text_en": "To compress and store files", "text_np": "फाइलहरू कम्प्रेस र भण्डारण गर्ने", "is_correct": False},
            {"text_en": "To manage computer network settings", "text_np": "कम्प्युटर नेटवर्क सेटिङ व्यवस्थापन गर्ने", "is_correct": False},
        ],
        "explanation_en": "Antivirus software detects, prevents, and removes malware (malicious software) including viruses, worms, Trojans, ransomware, and spyware from computer systems.",
        "explanation_np": "एन्टिभाइरस सफ्टवेयरले कम्प्युटर प्रणालीबाट भाइरस, वर्म, ट्रोजन, र्यान्समवेयर र स्पाइवेयर सहितका मालवेयरहरू पत्ता लगाउँछ, रोक्छ र हटाउँछ।",
        "difficulty": "EASY",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "Nepal's national portal for e-government services is:",
        "question_text_np": "इ-सरकार सेवाहरूको लागि नेपालको राष्ट्रिय पोर्टल कुन हो?",
        "answers": [
            {"text_en": "nepal.gov.np", "text_np": "nepal.gov.np", "is_correct": True},
            {"text_en": "gov.nepal.np", "text_np": "gov.nepal.np", "is_correct": False},
            {"text_en": "eservice.nepal.com", "text_np": "eservice.nepal.com", "is_correct": False},
            {"text_en": "government.np", "text_np": "government.np", "is_correct": False},
        ],
        "explanation_en": "Nepal's national e-government portal is nepal.gov.np. It serves as the central gateway to government information and services in Nepal.",
        "explanation_np": "नेपालको राष्ट्रिय इ-सरकार पोर्टल nepal.gov.np हो। यो नेपालमा सरकारी जानकारी र सेवाहरूको केन्द्रीय प्रवेशद्वारको रूपमा काम गर्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "Which of the following file extensions is associated with MS Word documents?",
        "question_text_np": "निम्नमध्ये कुन फाइल एक्सटेन्सन MS Word कागजातसँग सम्बन्धित छ?",
        "answers": [
            {"text_en": ".docx", "text_np": ".docx", "is_correct": True},
            {"text_en": ".xlsx", "text_np": ".xlsx", "is_correct": False},
            {"text_en": ".pptx", "text_np": ".pptx", "is_correct": False},
            {"text_en": ".pdf", "text_np": ".pdf", "is_correct": False},
        ],
        "explanation_en": ".docx = MS Word, .xlsx = MS Excel, .pptx = MS PowerPoint, .pdf = Adobe PDF. These are the standard file extensions for Microsoft Office applications.",
        "explanation_np": ".docx = MS Word, .xlsx = MS Excel, .pptx = MS PowerPoint, .pdf = Adobe PDF। यी Microsoft Office अनुप्रयोगहरूका मानक फाइल एक्सटेन्सनहरू हुन्।",
        "difficulty": "EASY",
        "source_reference": "PSC Computer Knowledge",
    },
    {
        "question_text_en": "What does 'GUI' stand for?",
        "question_text_np": "'GUI' को पूरा रूप के हो?",
        "answers": [
            {"text_en": "Graphical User Interface", "text_np": "ग्राफिकल युजर इन्टरफेस", "is_correct": True},
            {"text_en": "General User Interface", "text_np": "जेनेरल युजर इन्टरफेस", "is_correct": False},
            {"text_en": "Graphical Utility Interface", "text_np": "ग्राफिकल युटिलिटी इन्टरफेस", "is_correct": False},
            {"text_en": "Global User Integration", "text_np": "ग्लोबल युजर इन्टिग्रेसन", "is_correct": False},
        ],
        "explanation_en": "GUI (Graphical User Interface) allows users to interact with computers through visual elements like icons, buttons, and menus rather than text commands. Windows is a GUI-based OS.",
        "explanation_np": "GUI (Graphical User Interface) ले प्रयोगकर्ताहरूलाई पाठ आदेशहरूको सट्टा आइकन, बटन र मेनुजस्ता दृश्य तत्त्वहरूमार्फत कम्प्युटरसँग अन्तरक्रिया गर्न अनुमति दिन्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Computer Knowledge",
    },
]