"""Constitution of Nepal (नेपालको संविधान) — UNIVERSAL category questions."""

QUESTIONS = [
    {
        "question_text_en": "When was the Constitution of Nepal 2072 promulgated?",
        "question_text_np": "नेपालको संविधान २०७२ कहिले जारी भएको थियो?",
        "answers": [
            {"text_en": "Asoj 3, 2072 BS (September 20, 2015)", "text_np": "असोज ३, २०७२ (सेप्टेम्बर २०, २०१५)", "is_correct": True},
            {"text_en": "Jestha 15, 2065 BS", "text_np": "जेठ १५, २०६५", "is_correct": False},
            {"text_en": "Poush 1, 2074 BS", "text_np": "पुस १, २०७४", "is_correct": False},
            {"text_en": "Baisakh 1, 2072 BS", "text_np": "वैशाख १, २०७२", "is_correct": False},
        ],
        "explanation_en": "The Constitution of Nepal 2072 was promulgated on Asoj 3, 2072 BS (September 20, 2015) by the second Constituent Assembly.",
        "explanation_np": "नेपालको संविधान २०७२ दोस्रो संविधानसभाबाट असोज ३, २०७२ (सेप्टेम्बर २०, २०१५) मा जारी भएको थियो।",
        "difficulty": "EASY",
        "source_reference": "PSC Constitution",
    },
    {
        "question_text_en": "How many parts does the Constitution of Nepal 2072 have?",
        "question_text_np": "नेपालको संविधान २०७२ मा कतिवटा भाग छन्?",
        "answers": [
            {"text_en": "35 parts", "text_np": "३५ भाग", "is_correct": True},
            {"text_en": "25 parts", "text_np": "२५ भाग", "is_correct": False},
            {"text_en": "30 parts", "text_np": "३० भाग", "is_correct": False},
            {"text_en": "40 parts", "text_np": "४० भाग", "is_correct": False},
        ],
        "explanation_en": "The Constitution of Nepal 2072 has 35 parts, 308 articles, and 9 schedules.",
        "explanation_np": "नेपालको संविधान २०७२ मा ३५ भाग, ३०८ धारा र ९ अनुसूची छन्।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Constitution",
    },
    {
        "question_text_en": "How many articles are there in the Constitution of Nepal 2072?",
        "question_text_np": "नेपालको संविधान २०७२ मा कतिवटा धारा छन्?",
        "answers": [
            {"text_en": "308", "text_np": "३०८", "is_correct": True},
            {"text_en": "296", "text_np": "२९६", "is_correct": False},
            {"text_en": "275", "text_np": "२७५", "is_correct": False},
            {"text_en": "320", "text_np": "३२०", "is_correct": False},
        ],
        "explanation_en": "The Constitution of Nepal 2072 contains 308 articles.",
        "explanation_np": "नेपालको संविधान २०७२ मा ३०८ वटा धारा छन्।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Constitution",
    },
    {
        "question_text_en": "According to Article 1, Nepal is a/an ____.",
        "question_text_np": "धारा १ अनुसार, नेपाल एक ____ हो।",
        "answers": [
            {"text_en": "Independent, indivisible, sovereign, secular, inclusive, democratic, socialism-oriented, federal democratic republican state", "text_np": "स्वतन्त्र, अविभाज्य, सार्वभौमसत्तासम्पन्न, धर्मनिरपेक्ष, समावेशी, लोकतान्त्रिक, समाजवादमुखी, संघीय लोकतान्त्रिक गणतन्त्रात्मक राज्य", "is_correct": True},
            {"text_en": "Hindu Kingdom", "text_np": "हिन्दू अधिराज्य", "is_correct": False},
            {"text_en": "Constitutional Monarchy", "text_np": "संवैधानिक राजतन्त्र", "is_correct": False},
            {"text_en": "Unitary Republic", "text_np": "एकात्मक गणतन्त्र", "is_correct": False},
        ],
        "explanation_en": "Article 1 of the Constitution defines Nepal as an independent, indivisible, sovereign, secular, inclusive, democratic, socialism-oriented, federal democratic republican state.",
        "explanation_np": "संविधानको धारा १ ले नेपाललाई स्वतन्त्र, अविभाज्य, सार्वभौमसत्तासम्पन्न, धर्मनिरपेक्ष, समावेशी, लोकतान्त्रिक, समाजवादमुखी, संघीय लोकतान्त्रिक गणतन्त्रात्मक राज्यको रूपमा परिभाषित गर्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Constitution - Article 1",
    },
    {
        "question_text_en": "According to the Constitution, the sovereignty of Nepal is vested in ____.",
        "question_text_np": "संविधान अनुसार, नेपालको सार्वभौमसत्ता ____ मा निहित छ।",
        "answers": [
            {"text_en": "The Nepalese People", "text_np": "नेपाली जनतामा", "is_correct": True},
            {"text_en": "The President", "text_np": "राष्ट्रपतिमा", "is_correct": False},
            {"text_en": "The Parliament", "text_np": "संसदमा", "is_correct": False},
            {"text_en": "The Supreme Court", "text_np": "सर्वोच्च अदालतमा", "is_correct": False},
        ],
        "explanation_en": "Article 2 of the Constitution states that the sovereignty of Nepal is vested in the Nepalese people.",
        "explanation_np": "संविधानको धारा २ ले नेपालको सार्वभौमसत्ता नेपाली जनतामा निहित रहेको व्यवस्था गर्दछ।",
        "difficulty": "EASY",
        "source_reference": "PSC Constitution - Article 2",
    },
    {
        "question_text_en": "How many Fundamental Rights are listed in Part 3 of the Constitution of Nepal?",
        "question_text_np": "नेपालको संविधानको भाग ३ मा कतिवटा मौलिक हक सूचीबद्ध छन्?",
        "answers": [
            {"text_en": "31", "text_np": "३१", "is_correct": True},
            {"text_en": "24", "text_np": "२४", "is_correct": False},
            {"text_en": "18", "text_np": "१८", "is_correct": False},
            {"text_en": "46", "text_np": "४६", "is_correct": False},
        ],
        "explanation_en": "Part 3 (Articles 16-46) of the Constitution lists 31 Fundamental Rights.",
        "explanation_np": "संविधानको भाग ३ (धारा १६-४६) मा ३१ वटा मौलिक हक सूचीबद्ध छन्।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Constitution - Part 3",
    },
    {
        "question_text_en": "Which article of the Constitution guarantees the Right to Equality?",
        "question_text_np": "संविधानको कुन धाराले समानताको अधिकारको ग्यारेन्टी गर्छ?",
        "answers": [
            {"text_en": "Article 18", "text_np": "धारा १८", "is_correct": True},
            {"text_en": "Article 16", "text_np": "धारा १६", "is_correct": False},
            {"text_en": "Article 24", "text_np": "धारा २४", "is_correct": False},
            {"text_en": "Article 31", "text_np": "धारा ३१", "is_correct": False},
        ],
        "explanation_en": "Article 18 of the Constitution guarantees the Right to Equality. It prohibits discrimination based on origin, religion, race, caste, tribe, sex, etc.",
        "explanation_np": "संविधानको धारा १८ ले समानताको अधिकारको ग्यारेन्टी गर्छ। यसले उत्पत्ति, धर्म, जात, जाति, लिङ्ग आदिमा आधारित भेदभावलाई निषेध गर्दछ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Constitution - Article 18",
    },
    {
        "question_text_en": "The Right to Constitutional Remedy is guaranteed by which article?",
        "question_text_np": "संवैधानिक उपचारको अधिकार कुन धारामा व्यवस्था गरिएको छ?",
        "answers": [
            {"text_en": "Article 46", "text_np": "धारा ४६", "is_correct": True},
            {"text_en": "Article 32", "text_np": "धारा ३२", "is_correct": False},
            {"text_en": "Article 42", "text_np": "धारा ४२", "is_correct": False},
            {"text_en": "Article 50", "text_np": "धारा ५०", "is_correct": False},
        ],
        "explanation_en": "Article 46 provides the Right to Constitutional Remedy, allowing citizens to approach the Supreme Court for enforcement of fundamental rights.",
        "explanation_np": "धारा ४६ ले संवैधानिक उपचारको अधिकार प्रदान गर्छ, जसले नागरिकलाई मौलिक हकको कार्यान्वयनका लागि सर्वोच्च अदालतमा जान अनुमति दिन्छ।",
        "difficulty": "HARD",
        "source_reference": "PSC Constitution - Article 46",
    },
    {
        "question_text_en": "According to Article 74, who is the head of state in Nepal?",
        "question_text_np": "धारा ७४ अनुसार, नेपालको राज्यको प्रमुख को हो?",
        "answers": [
            {"text_en": "The President", "text_np": "राष्ट्रपति", "is_correct": True},
            {"text_en": "The Prime Minister", "text_np": "प्रधानमन्त्री", "is_correct": False},
            {"text_en": "The Chief Justice", "text_np": "प्रधानन्यायाधीश", "is_correct": False},
            {"text_en": "The Speaker of Parliament", "text_np": "संसदको सभामुख", "is_correct": False},
        ],
        "explanation_en": "Article 74 states that the President is the head of state of Nepal and represents the unity of the nation.",
        "explanation_np": "धारा ७४ ले राष्ट्रपतिलाई नेपालको राज्यको प्रमुखको रूपमा र राष्ट्रिय एकताको प्रतिनिधित्व गर्ने व्यवस्था गर्दछ।",
        "difficulty": "EASY",
        "source_reference": "PSC Constitution - Article 74",
    },
    {
        "question_text_en": "The Federal Parliament of Nepal consists of how many houses?",
        "question_text_np": "नेपालको संघीय संसद कतिवटा सदनबाट बनेको छ?",
        "answers": [
            {"text_en": "Two (House of Representatives and National Assembly)", "text_np": "दुईवटा (प्रतिनिधिसभा र राष्ट्रियसभा)", "is_correct": True},
            {"text_en": "One", "text_np": "एउटा", "is_correct": False},
            {"text_en": "Three", "text_np": "तीनवटा", "is_correct": False},
            {"text_en": "Four", "text_np": "चारवटा", "is_correct": False},
        ],
        "explanation_en": "Article 84 provides that the Federal Parliament consists of two houses: the House of Representatives (Pratinidhi Sabha) with 275 members and the National Assembly (Rastriya Sabha) with 59 members.",
        "explanation_np": "धारा ८४ ले संघीय संसद दुई सदनबाट बनेको व्यवस्था गर्दछ: प्रतिनिधिसभा (२७५ सदस्य) र राष्ट्रियसभा (५९ सदस्य)।",
        "difficulty": "EASY",
        "source_reference": "PSC Constitution - Article 84",
    },
    {
        "question_text_en": "How many members are there in the House of Representatives?",
        "question_text_np": "प्रतिनिधिसभामा कति सदस्य हुन्छन्?",
        "answers": [
            {"text_en": "275", "text_np": "२७५", "is_correct": True},
            {"text_en": "330", "text_np": "३३०", "is_correct": False},
            {"text_en": "250", "text_np": "२५०", "is_correct": False},
            {"text_en": "205", "text_np": "२०५", "is_correct": False},
        ],
        "explanation_en": "The House of Representatives has 275 members: 165 elected through First Past the Post (FPTP) and 110 through Proportional Representation (PR).",
        "explanation_np": "प्रतिनिधिसभामा २७५ सदस्य हुन्छन्: १६५ प्रत्यक्ष निर्वाचन (FPTP) र ११० समानुपातिक प्रतिनिधित्व (PR) बाट।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Constitution - Article 84",
    },
    {
        "question_text_en": "How many schedules are in the Constitution of Nepal 2072?",
        "question_text_np": "नेपालको संविधान २०७२ मा कतिवटा अनुसूची छन्?",
        "answers": [
            {"text_en": "9", "text_np": "९", "is_correct": True},
            {"text_en": "7", "text_np": "७", "is_correct": False},
            {"text_en": "12", "text_np": "१२", "is_correct": False},
            {"text_en": "10", "text_np": "१०", "is_correct": False},
        ],
        "explanation_en": "The Constitution of Nepal 2072 has 9 schedules that detail various lists such as federal, provincial, and concurrent powers.",
        "explanation_np": "नेपालको संविधान २०७२ मा ९ वटा अनुसूची छन् जसमा संघ, प्रदेश र साझा अधिकारको सूची जस्ता विवरणहरू छन्।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Constitution",
    },
    {
        "question_text_en": "Which article deals with the Right to Education?",
        "question_text_np": "शिक्षाको अधिकार कुन धारामा व्यवस्था गरिएको छ?",
        "answers": [
            {"text_en": "Article 31", "text_np": "धारा ३१", "is_correct": True},
            {"text_en": "Article 25", "text_np": "धारा २५", "is_correct": False},
            {"text_en": "Article 35", "text_np": "धारा ३५", "is_correct": False},
            {"text_en": "Article 28", "text_np": "धारा २८", "is_correct": False},
        ],
        "explanation_en": "Article 31 guarantees the Right to Education. Every citizen has the right to access basic education free of cost.",
        "explanation_np": "धारा ३१ ले शिक्षाको अधिकारको ग्यारेन्टी गर्दछ। प्रत्येक नागरिकलाई आधारभूत शिक्षा निःशुल्क पहुँच गर्ने अधिकार छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Constitution - Article 31",
    },
    {
        "question_text_en": "The Directive Principles, Policies, and Obligations of the State are in which Part of the Constitution?",
        "question_text_np": "राज्यका निर्देशक सिद्धान्त, नीति र दायित्व संविधानको कुन भागमा छन्?",
        "answers": [
            {"text_en": "Part 4", "text_np": "भाग ४", "is_correct": True},
            {"text_en": "Part 3", "text_np": "भाग ३", "is_correct": False},
            {"text_en": "Part 5", "text_np": "भाग ५", "is_correct": False},
            {"text_en": "Part 6", "text_np": "भाग ६", "is_correct": False},
        ],
        "explanation_en": "Part 4 (Articles 49-55) of the Constitution contains the Directive Principles, Policies, and Obligations of the State.",
        "explanation_np": "संविधानको भाग ४ (धारा ४९-५५) मा राज्यका निर्देशक सिद्धान्त, नीति र दायित्व समावेश छन्।",
        "difficulty": "HARD",
        "source_reference": "PSC Constitution - Part 4",
    },
    {
        "question_text_en": "Which article provides for the amendment of the Constitution?",
        "question_text_np": "संविधान संशोधनको व्यवस्था कुन धारामा छ?",
        "answers": [
            {"text_en": "Article 274", "text_np": "धारा २७४", "is_correct": True},
            {"text_en": "Article 300", "text_np": "धारा ३००", "is_correct": False},
            {"text_en": "Article 250", "text_np": "धारा २५०", "is_correct": False},
            {"text_en": "Article 308", "text_np": "धारा ३०८", "is_correct": False},
        ],
        "explanation_en": "Article 274 provides the procedure for amendment of the Constitution, requiring a two-thirds majority in both houses of the Federal Parliament.",
        "explanation_np": "धारा २७४ ले संविधान संशोधनको प्रक्रिया प्रदान गर्दछ, जसमा संघीय संसदको दुवै सदनमा दुई-तिहाइ बहुमत आवश्यक हुन्छ।",
        "difficulty": "HARD",
        "source_reference": "PSC Constitution - Article 274",
    },
]
