"""Current Affairs (समसामयिक घटना) — UNIVERSAL category questions."""

QUESTIONS = [
    {
        "question_text_en": "Which country hosted the 2022 FIFA World Cup?",
        "question_text_np": "२०२२ फिफा विश्वकप कुन देशमा आयोजना भएको थियो?",
        "answers": [
            {"text_en": "Qatar", "text_np": "कतार", "is_correct": True},
            {"text_en": "Russia", "text_np": "रुस", "is_correct": False},
            {"text_en": "Brazil", "text_np": "ब्राजिल", "is_correct": False},
            {"text_en": "France", "text_np": "फ्रान्स", "is_correct": False},
        ],
        "explanation_en": "The 2022 FIFA World Cup was hosted by Qatar, making it the first World Cup held in the Middle East.",
        "explanation_np": "२०२२ फिफा विश्वकप कतारमा आयोजना भएको थियो, यो मध्यपूर्वमा भएको पहिलो विश्वकप हो।",
        "difficulty": "EASY",
        "source_reference": "PSC Current Affairs",
    },
    {
        "question_text_en": "Which organization awards the Nobel Prize?",
        "question_text_np": "नोबेल पुरस्कार कुन संगठनले प्रदान गर्छ?",
        "answers": [
            {"text_en": "The Nobel Foundation (Sweden & Norway)", "text_np": "नोबेल फाउन्डेसन (स्वीडेन र नर्वे)", "is_correct": True},
            {"text_en": "United Nations", "text_np": "संयुक्त राष्ट्रसंघ", "is_correct": False},
            {"text_en": "World Bank", "text_np": "विश्व बैंक", "is_correct": False},
            {"text_en": "European Union", "text_np": "युरोपेली संघ", "is_correct": False},
        ],
        "explanation_en": "The Nobel Prizes are awarded by the Nobel Foundation based in Stockholm, Sweden, except the Peace Prize which is awarded in Oslo, Norway.",
        "explanation_np": "नोबेल पुरस्कार स्टकहोम, स्वीडेनमा रहेको नोबेल फाउन्डेसनले प्रदान गर्छ, शान्ति पुरस्कार बाहेक जुन ओस्लो, नर्वेमा प्रदान गरिन्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Current Affairs",
    },
    {
        "question_text_en": "The Paris Agreement on climate change was adopted in which year?",
        "question_text_np": "जलवायु परिवर्तनसम्बन्धी पेरिस सम्झौता कुन वर्षमा अपनाइएको थियो?",
        "answers": [
            {"text_en": "2015", "text_np": "२०१५", "is_correct": True},
            {"text_en": "2012", "text_np": "२०१२", "is_correct": False},
            {"text_en": "2018", "text_np": "२०१८", "is_correct": False},
            {"text_en": "2020", "text_np": "२०२०", "is_correct": False},
        ],
        "explanation_en": "The Paris Agreement was adopted on December 12, 2015 at COP21 in Paris, France, signed by 196 parties.",
        "explanation_np": "पेरिस सम्झौता डिसेम्बर १२, २०१५ मा पेरिस, फ्रान्समा COP21 मा अपनाइएको थियो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Current Affairs",
    },
    {
        "question_text_en": "What are the Sustainable Development Goals (SDGs) target year?",
        "question_text_np": "दिगो विकास लक्ष्य (SDGs) को लक्षित वर्ष कुन हो?",
        "answers": [
            {"text_en": "2030", "text_np": "२०३०", "is_correct": True},
            {"text_en": "2025", "text_np": "२०२५", "is_correct": False},
            {"text_en": "2035", "text_np": "२०३५", "is_correct": False},
            {"text_en": "2050", "text_np": "२०५०", "is_correct": False},
        ],
        "explanation_en": "The 17 Sustainable Development Goals (SDGs) adopted by the UN in 2015 aim to be achieved by 2030.",
        "explanation_np": "संयुक्त राष्ट्रसंघले सन् २०१५ मा अपनाएका १७ दिगो विकास लक्ष्यहरू (SDGs) सन् २०३० सम्ममा प्राप्त गर्ने लक्ष्य राखिएको छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Current Affairs",
    },
    {
        "question_text_en": "How many Sustainable Development Goals (SDGs) are there?",
        "question_text_np": "कतिवटा दिगो विकास लक्ष्यहरू (SDGs) छन्?",
        "answers": [
            {"text_en": "17", "text_np": "१७", "is_correct": True},
            {"text_en": "15", "text_np": "१५", "is_correct": False},
            {"text_en": "21", "text_np": "२१", "is_correct": False},
            {"text_en": "12", "text_np": "१२", "is_correct": False},
        ],
        "explanation_en": "There are 17 Sustainable Development Goals adopted by the UN General Assembly in September 2015.",
        "explanation_np": "सन् २०१५ सेप्टेम्बरमा संयुक्त राष्ट्र महासभाले अपनाएका १७ दिगो विकास लक्ष्यहरू छन्।",
        "difficulty": "EASY",
        "source_reference": "PSC Current Affairs",
    },
    {
        "question_text_en": "Nepal became a member of the United Nations in which year?",
        "question_text_np": "नेपाल कुन वर्षमा संयुक्त राष्ट्रसंघको सदस्य बनेको थियो?",
        "answers": [
            {"text_en": "1955", "text_np": "१९५५", "is_correct": True},
            {"text_en": "1945", "text_np": "१९४५", "is_correct": False},
            {"text_en": "1960", "text_np": "१९६०", "is_correct": False},
            {"text_en": "1950", "text_np": "१९५०", "is_correct": False},
        ],
        "explanation_en": "Nepal became a member of the United Nations on December 14, 1955.",
        "explanation_np": "नेपाल डिसेम्बर १४, १९५५ मा संयुक्त राष्ट्रसंघको सदस्य बनेको थियो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Current Affairs",
    },
    {
        "question_text_en": "What is the full form of WHO?",
        "question_text_np": "WHO को पूरा रूप के हो?",
        "answers": [
            {"text_en": "World Health Organization", "text_np": "विश्व स्वास्थ्य संगठन", "is_correct": True},
            {"text_en": "World Housing Organization", "text_np": "विश्व आवास संगठन", "is_correct": False},
            {"text_en": "World Humanitarian Organization", "text_np": "विश्व मानवतावादी संगठन", "is_correct": False},
            {"text_en": "World Heritage Organization", "text_np": "विश्व सम्पदा संगठन", "is_correct": False},
        ],
        "explanation_en": "WHO stands for World Health Organization, a specialized agency of the United Nations headquartered in Geneva, Switzerland.",
        "explanation_np": "WHO को पूरा रूप World Health Organization (विश्व स्वास्थ्य संगठन) हो, जुन जिनेभा, स्विट्जरल्यान्डमा मुख्यालय रहेको संयुक्त राष्ट्रको विशेष एजेन्सी हो।",
        "difficulty": "EASY",
        "source_reference": "PSC Current Affairs",
    },
    {
        "question_text_en": "The headquarters of the United Nations is located in which city?",
        "question_text_np": "संयुक्त राष्ट्रसंघको मुख्यालय कुन शहरमा अवस्थित छ?",
        "answers": [
            {"text_en": "New York", "text_np": "न्यूयोर्क", "is_correct": True},
            {"text_en": "Geneva", "text_np": "जिनेभा", "is_correct": False},
            {"text_en": "London", "text_np": "लण्डन", "is_correct": False},
            {"text_en": "Washington D.C.", "text_np": "वाशिङ्टन डी.सी.", "is_correct": False},
        ],
        "explanation_en": "The United Nations headquarters is located in New York City, United States.",
        "explanation_np": "संयुक्त राष्ट्रसंघको मुख्यालय न्यूयोर्क शहर, संयुक्त राज्य अमेरिकामा अवस्थित छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Current Affairs",
    },
    {
        "question_text_en": "The BRICS group of nations includes which of the following countries?",
        "question_text_np": "BRICS राष्ट्रहरूको समूहमा निम्नमध्ये कुन देश पर्दछ?",
        "answers": [
            {"text_en": "Brazil, Russia, India, China, South Africa", "text_np": "ब्राजिल, रसिया, भारत, चीन, दक्षिण अफ्रिका", "is_correct": True},
            {"text_en": "Britain, Russia, Indonesia, China, Singapore", "text_np": "बेलायत, रसिया, इन्डोनेसिया, चीन, सिंगापुर", "is_correct": False},
            {"text_en": "Brazil, Romania, India, Canada, Spain", "text_np": "ब्राजिल, रोमानिया, भारत, क्यानडा, स्पेन", "is_correct": False},
            {"text_en": "Belgium, Russia, Iran, China, Sweden", "text_np": "बेल्जियम, रसिया, इरान, चीन, स्वीडेन", "is_correct": False},
        ],
        "explanation_en": "BRICS stands for Brazil, Russia, India, China, and South Africa — an association of major emerging economies.",
        "explanation_np": "BRICS भनेको ब्राजिल, रसिया, भारत, चीन र दक्षिण अफ्रिका — प्रमुख उदीयमान अर्थतन्त्रहरूको संगठन हो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Current Affairs",
    },
    {
        "question_text_en": "What is Nepal's current periodic plan called?",
        "question_text_np": "नेपालको हालको आवधिक योजनालाई के भनिन्छ?",
        "answers": [
            {"text_en": "16th Periodic Plan (2081/82-2085/86)", "text_np": "सोह्रौं आवधिक योजना (२०८१/८२-२०८५/८६)", "is_correct": True},
            {"text_en": "14th Periodic Plan", "text_np": "चौधौं आवधिक योजना", "is_correct": False},
            {"text_en": "15th Periodic Plan", "text_np": "पन्ध्रौं आवधिक योजना", "is_correct": False},
            {"text_en": "13th Periodic Plan", "text_np": "तेह्रौं आवधिक योजना", "is_correct": False},
        ],
        "explanation_en": "Nepal is currently implementing the 16th Periodic Plan (2081/82-2085/86 BS).",
        "explanation_np": "नेपालले हाल सोह्रौं आवधिक योजना (२०८१/८२-२०८५/८६) कार्यान्वयन गरिरहेको छ।",
        "difficulty": "HARD",
        "source_reference": "PSC Current Affairs",
    },
    {
        "question_text_en": "Which international organization has its headquarters in Kathmandu?",
        "question_text_np": "कुन अन्तर्राष्ट्रिय संगठनको मुख्यालय काठमाडौंमा छ?",
        "answers": [
            {"text_en": "SAARC Secretariat", "text_np": "सार्क सचिवालय", "is_correct": True},
            {"text_en": "ASEAN Secretariat", "text_np": "आसियान सचिवालय", "is_correct": False},
            {"text_en": "Asian Development Bank", "text_np": "एसियाली विकास बैंक", "is_correct": False},
            {"text_en": "World Bank", "text_np": "विश्व बैंक", "is_correct": False},
        ],
        "explanation_en": "The SAARC (South Asian Association for Regional Cooperation) Secretariat is located in Kathmandu, Nepal.",
        "explanation_np": "सार्क (दक्षिण एसियाली क्षेत्रीय सहयोग संगठन) सचिवालय काठमाडौं, नेपालमा अवस्थित छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Current Affairs",
    },
    {
        "question_text_en": "World Environment Day is celebrated on which date?",
        "question_text_np": "विश्व वातावरण दिवस कुन मितिमा मनाइन्छ?",
        "answers": [
            {"text_en": "June 5", "text_np": "जुन ५", "is_correct": True},
            {"text_en": "March 22", "text_np": "मार्च २२", "is_correct": False},
            {"text_en": "April 22", "text_np": "अप्रिल २२", "is_correct": False},
            {"text_en": "October 16", "text_np": "अक्टोबर १६", "is_correct": False},
        ],
        "explanation_en": "World Environment Day is celebrated on June 5 every year, led by the United Nations Environment Programme (UNEP).",
        "explanation_np": "विश्व वातावरण दिवस हरेक वर्ष जुन ५ मा मनाइन्छ, जुन संयुक्त राष्ट्र वातावरण कार्यक्रम (UNEP) ले नेतृत्व गर्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Current Affairs",
    },
]
