"""Education Service — BRANCH & SUBBRANCH category questions."""

QUESTIONS = {
    # ─── BRANCH-scoped categories ────────────────────────────────────────
    "education-policy-planning": [
        {
            "question_text_en": "Which act governs the overall education system in Nepal?",
            "question_text_np": "नेपालको समग्र शिक्षा प्रणाली कुन ऐनले नियन्त्रण गर्छ?",
            "answers": [
                {"text_en": "Education Act, 2028 (1971)", "text_np": "शिक्षा ऐन, २०२८", "is_correct": True},
                {"text_en": "University Act, 2049", "text_np": "विश्वविद्यालय ऐन, २०४९", "is_correct": False},
                {"text_en": "Children's Act, 2075", "text_np": "बालबालिका ऐन, २०७५", "is_correct": False},
                {"text_en": "Civil Service Act, 2049", "text_np": "निजामती सेवा ऐन, २०४९", "is_correct": False},
            ],
            "explanation_en": "The Education Act, 2028 (1971) is the primary legislation governing Nepal's education system, covering school education, teacher management, and institutional governance.",
            "explanation_np": "शिक्षा ऐन, २०२८ नेपालको शिक्षा प्रणालीलाई नियन्त्रण गर्ने प्रमुख कानुन हो, जसले विद्यालय शिक्षा, शिक्षक व्यवस्थापन र संस्थागत सुशासनलाई समेट्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Education Policy",
        },
        {
            "question_text_en": "The School Sector Development Plan (SSDP) in Nepal covers which period?",
            "question_text_np": "नेपालको विद्यालय क्षेत्र विकास योजना (SSDP) कुन अवधिको लागि हो?",
            "answers": [
                {"text_en": "2016/17 – 2022/23", "text_np": "२०७३/७४ – २०७९/८०", "is_correct": True},
                {"text_en": "2010/11 – 2015/16", "text_np": "२०६७/६८ – २०७२/७३", "is_correct": False},
                {"text_en": "2020/21 – 2025/26", "text_np": "२०७७/७८ – २०८२/८३", "is_correct": False},
                {"text_en": "2005/06 – 2010/11", "text_np": "२०६२/६३ – २०६७/६८", "is_correct": False},
            ],
            "explanation_en": "The School Sector Development Plan (SSDP) covers the period 2016/17 – 2022/23 (BS 2073/74 – 2079/80) and is the national framework for school education reform in Nepal.",
            "explanation_np": "विद्यालय क्षेत्र विकास योजना (SSDP) ले २०७३/७४ – २०७९/८० को अवधि समेट्छ र यो नेपालमा विद्यालय शिक्षा सुधारको राष्ट्रिय ढाँचा हो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Education Policy",
        },
        {
            "question_text_en": "Which body is primarily responsible for formulating national education policy in Nepal?",
            "question_text_np": "नेपालमा राष्ट्रिय शिक्षा नीति तर्जुमा गर्ने प्रमुख निकाय कुन हो?",
            "answers": [
                {"text_en": "Ministry of Education, Science and Technology", "text_np": "शिक्षा, विज्ञान तथा प्रविधि मन्त्रालय", "is_correct": True},
                {"text_en": "National Planning Commission", "text_np": "राष्ट्रिय योजना आयोग", "is_correct": False},
                {"text_en": "Tribhuvan University", "text_np": "त्रिभुवन विश्वविद्यालय", "is_correct": False},
                {"text_en": "Office of the Prime Minister", "text_np": "प्रधानमन्त्री कार्यालय", "is_correct": False},
            ],
            "explanation_en": "The Ministry of Education, Science and Technology (MoEST) is the primary body responsible for formulating and implementing national education policies in Nepal.",
            "explanation_np": "शिक्षा, विज्ञान तथा प्रविधि मन्त्रालय (MoEST) नेपालमा राष्ट्रिय शिक्षा नीति तर्जुमा र कार्यान्वयन गर्ने प्रमुख निकाय हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Education Policy",
        },
        {
            "question_text_en": "The National Education Policy 2076 emphasizes which of the following?",
            "question_text_np": "राष्ट्रिय शिक्षा नीति २०७६ ले निम्नमध्ये कुन कुरामा जोड दिन्छ?",
            "answers": [
                {"text_en": "Technical and vocational education alongside academic education", "text_np": "शैक्षिक शिक्षासँगै प्राविधिक तथा व्यावसायिक शिक्षा", "is_correct": True},
                {"text_en": "Abolition of private schools", "text_np": "निजी विद्यालय खारेजी", "is_correct": False},
                {"text_en": "English-only medium of instruction", "text_np": "अंग्रेजी मात्र शिक्षाको माध्यम", "is_correct": False},
                {"text_en": "Elimination of examination systems", "text_np": "परीक्षा प्रणाली हटाउने", "is_correct": False},
            ],
            "explanation_en": "The National Education Policy 2076 (2019) emphasizes integrating technical and vocational education with academic education to produce skilled human resources.",
            "explanation_np": "राष्ट्रिय शिक्षा नीति २०७६ ले दक्ष जनशक्ति उत्पादन गर्न प्राविधिक तथा व्यावसायिक शिक्षालाई शैक्षिक शिक्षासँग एकीकरण गर्नमा जोड दिन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Education Policy",
        },
        {
            "question_text_en": "Under Nepal's federal structure, school-level education management falls under which level of government?",
            "question_text_np": "नेपालको संघीय संरचनामा विद्यालय तहको शिक्षा व्यवस्थापन कुन तहको सरकार अन्तर्गत पर्छ?",
            "answers": [
                {"text_en": "Local government", "text_np": "स्थानीय सरकार", "is_correct": True},
                {"text_en": "Federal government", "text_np": "संघीय सरकार", "is_correct": False},
                {"text_en": "Provincial government", "text_np": "प्रदेश सरकार", "is_correct": False},
                {"text_en": "District administration", "text_np": "जिल्ला प्रशासन", "is_correct": False},
            ],
            "explanation_en": "Under Nepal's Constitution 2072, basic and secondary school education management is the responsibility of local governments (municipalities and rural municipalities).",
            "explanation_np": "नेपालको संविधान २०७२ अनुसार आधारभूत तथा माध्यमिक विद्यालय शिक्षा व्यवस्थापन स्थानीय सरकार (नगरपालिका र गाउँपालिका) को जिम्मेवारी हो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Education Policy",
        },
        {
            "question_text_en": "Which commission recommended the establishment of a National Education Board in Nepal?",
            "question_text_np": "नेपालमा राष्ट्रिय शिक्षा बोर्ड स्थापना गर्न कुन आयोगले सिफारिस गरेको थियो?",
            "answers": [
                {"text_en": "High Level National Education Commission (2075)", "text_np": "उच्चस्तरीय राष्ट्रिय शिक्षा आयोग (२०७५)", "is_correct": True},
                {"text_en": "NNEPC (2011 BS)", "text_np": "NNEPC (२०११)", "is_correct": False},
                {"text_en": "Wood Commission (1854)", "text_np": "वुड आयोग (१८५४)", "is_correct": False},
                {"text_en": "Kothari Commission", "text_np": "कोठारी आयोग", "is_correct": False},
            ],
            "explanation_en": "The High Level National Education Commission (2075/2018) recommended establishing a National Education Board to oversee education quality and standards.",
            "explanation_np": "उच्चस्तरीय राष्ट्रिय शिक्षा आयोग (२०७५) ले शिक्षाको गुणस्तर र मापदण्ड हेर्न राष्ट्रिय शिक्षा बोर्ड स्थापना गर्न सिफारिस गरेको थियो।",
            "difficulty": "HARD",
            "source_reference": "PSC Education Policy",
        },
    ],
    "pedagogy-teaching-methods": [
        {
            "question_text_en": "Which teaching method emphasizes learning through direct experience and reflection?",
            "question_text_np": "कुन शिक्षण विधिले प्रत्यक्ष अनुभव र चिन्तनबाट सिक्नमा जोड दिन्छ?",
            "answers": [
                {"text_en": "Experiential learning", "text_np": "अनुभवजन्य शिक्षा", "is_correct": True},
                {"text_en": "Rote memorization", "text_np": "रट्ने तरिका", "is_correct": False},
                {"text_en": "Lecture method", "text_np": "व्याख्यान विधि", "is_correct": False},
                {"text_en": "Dictation method", "text_np": "श्रुतलेख विधि", "is_correct": False},
            ],
            "explanation_en": "Experiential learning, proposed by David Kolb, emphasizes a cycle of concrete experience, reflective observation, abstract conceptualization, and active experimentation.",
            "explanation_np": "डेभिड कोल्बद्वारा प्रस्तावित अनुभवजन्य शिक्षाले ठोस अनुभव, चिन्तनशील अवलोकन, अमूर्त अवधारणा र सक्रिय प्रयोगको चक्रमा जोड दिन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Pedagogy",
        },
        {
            "question_text_en": "Bloom's Taxonomy classifies cognitive learning objectives into how many levels?",
            "question_text_np": "ब्लुमको वर्गीकरणले संज्ञानात्मक सिकाइ उद्देश्यलाई कतिवटा तहमा वर्गीकरण गर्छ?",
            "answers": [
                {"text_en": "Six", "text_np": "छ", "is_correct": True},
                {"text_en": "Four", "text_np": "चार", "is_correct": False},
                {"text_en": "Five", "text_np": "पाँच", "is_correct": False},
                {"text_en": "Eight", "text_np": "आठ", "is_correct": False},
            ],
            "explanation_en": "Bloom's Taxonomy has six levels: Remember, Understand, Apply, Analyze, Evaluate, and Create (revised version).",
            "explanation_np": "ब्लुमको वर्गीकरणमा छवटा तह छन्: सम्झनु, बुझ्नु, प्रयोग गर्नु, विश्लेषण गर्नु, मूल्याङ्कन गर्नु र सिर्जना गर्नु (संशोधित संस्करण)।",
            "difficulty": "EASY",
            "source_reference": "PSC Pedagogy",
        },
        {
            "question_text_en": "Which of the following is an example of a learner-centered teaching approach?",
            "question_text_np": "निम्नमध्ये कुन सिकारु-केन्द्रित शिक्षण दृष्टिकोणको उदाहरण हो?",
            "answers": [
                {"text_en": "Project-based learning", "text_np": "परियोजनामा आधारित शिक्षा", "is_correct": True},
                {"text_en": "Teacher lecture", "text_np": "शिक्षक व्याख्यान", "is_correct": False},
                {"text_en": "Textbook reading aloud", "text_np": "पाठ्यपुस्तक ठूलो स्वरमा पढ्ने", "is_correct": False},
                {"text_en": "Dictation from blackboard", "text_np": "कालोपाटीबाट श्रुतलेख", "is_correct": False},
            ],
            "explanation_en": "Project-based learning is a learner-centered approach where students actively explore real-world problems and challenges to gain deeper knowledge.",
            "explanation_np": "परियोजनामा आधारित शिक्षा सिकारु-केन्द्रित दृष्टिकोण हो जहाँ विद्यार्थीहरूले गहिरो ज्ञान प्राप्त गर्न वास्तविक समस्या र चुनौतीहरूको सक्रिय अन्वेषण गर्छन्।",
            "difficulty": "EASY",
            "source_reference": "PSC Pedagogy",
        },
        {
            "question_text_en": "The Zone of Proximal Development (ZPD) concept was introduced by which psychologist?",
            "question_text_np": "निकटतम विकास क्षेत्र (ZPD) को अवधारणा कुन मनोवैज्ञानिकले प्रस्तुत गरेका हुन्?",
            "answers": [
                {"text_en": "Lev Vygotsky", "text_np": "लेभ भाइगोत्स्की", "is_correct": True},
                {"text_en": "Jean Piaget", "text_np": "जीन पियाजे", "is_correct": False},
                {"text_en": "B.F. Skinner", "text_np": "बी.एफ. स्किनर", "is_correct": False},
                {"text_en": "Jerome Bruner", "text_np": "जेरोम ब्रुनर", "is_correct": False},
            ],
            "explanation_en": "Lev Vygotsky introduced the concept of the Zone of Proximal Development, which describes the gap between what a learner can do independently and what they can achieve with guidance.",
            "explanation_np": "लेभ भाइगोत्स्कीले निकटतम विकास क्षेत्रको अवधारणा प्रस्तुत गरे, जसले सिकारुले स्वतन्त्र रूपमा गर्न सक्ने र मार्गदर्शनसँग प्राप्त गर्न सक्ने बीचको अन्तरलाई वर्णन गर्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Pedagogy",
        },
        {
            "question_text_en": "Formative assessment is primarily used to:",
            "question_text_np": "निर्माणात्मक मूल्याङ्कन मुख्यतया कुन उद्देश्यका लागि प्रयोग गरिन्छ?",
            "answers": [
                {"text_en": "Monitor student learning and provide ongoing feedback", "text_np": "विद्यार्थीको सिकाइ अनुगमन गर्न र निरन्तर प्रतिक्रिया दिन", "is_correct": True},
                {"text_en": "Assign final grades at the end of a course", "text_np": "पाठ्यक्रमको अन्त्यमा अन्तिम ग्रेड दिन", "is_correct": False},
                {"text_en": "Rank students for selection purposes", "text_np": "छनोटको उद्देश्यले विद्यार्थीलाई दर्जा दिन", "is_correct": False},
                {"text_en": "Evaluate the school's overall performance", "text_np": "विद्यालयको समग्र कार्यसम्पादन मूल्याङ्कन गर्न", "is_correct": False},
            ],
            "explanation_en": "Formative assessment is an ongoing process used to monitor student learning progress and provide feedback to improve teaching and learning.",
            "explanation_np": "निर्माणात्मक मूल्याङ्कन विद्यार्थीको सिकाइ प्रगति अनुगमन गर्न र शिक्षण तथा सिकाइ सुधार गर्न प्रतिक्रिया प्रदान गर्ने निरन्तर प्रक्रिया हो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Pedagogy",
        },
        {
            "question_text_en": "In the constructivist theory of learning, knowledge is:",
            "question_text_np": "सिकाइको निर्माणवादी सिद्धान्तमा ज्ञान भनेको:",
            "answers": [
                {"text_en": "Actively constructed by the learner through experience", "text_np": "सिकारुद्वारा अनुभवमार्फत सक्रिय रूपमा निर्माण गरिएको", "is_correct": True},
                {"text_en": "Passively received from the teacher", "text_np": "शिक्षकबाट निष्क्रिय रूपमा प्राप्त गरिएको", "is_correct": False},
                {"text_en": "Innately present in the learner's mind", "text_np": "सिकारुको दिमागमा जन्मजात रूपमा उपस्थित", "is_correct": False},
                {"text_en": "Only acquired through repetition and memorization", "text_np": "दोहोर्‍याइ र कण्ठस्थबाट मात्र प्राप्त गरिएको", "is_correct": False},
            ],
            "explanation_en": "Constructivism holds that learners actively construct knowledge through experience, social interaction, and reflection rather than passively receiving information.",
            "explanation_np": "निर्माणवादले विश्वास गर्छ कि सिकारुहरूले निष्क्रिय रूपमा जानकारी प्राप्त गर्नुको सट्टा अनुभव, सामाजिक अन्तरक्रिया र चिन्तनमार्फत सक्रिय रूपमा ज्ञान निर्माण गर्छन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Pedagogy",
        },
        {
            "question_text_en": "Which instructional strategy involves an expert gradually reducing support as the learner gains competence?",
            "question_text_np": "कुन शिक्षण रणनीतिमा सिकारुले दक्षता प्राप्त गर्दै जाँदा विशेषज्ञले बिस्तारै सहयोग घटाउँदै जान्छ?",
            "answers": [
                {"text_en": "Scaffolding", "text_np": "स्क्याफोल्डिङ (भर्‍याङ विधि)", "is_correct": True},
                {"text_en": "Direct instruction", "text_np": "प्रत्यक्ष निर्देशन", "is_correct": False},
                {"text_en": "Discovery learning", "text_np": "खोज शिक्षा", "is_correct": False},
                {"text_en": "Peer tutoring", "text_np": "साथी शिक्षण", "is_correct": False},
            ],
            "explanation_en": "Scaffolding is an instructional technique where the teacher provides structured support and gradually removes it as students develop competence, originating from Vygotsky's ZPD concept.",
            "explanation_np": "स्क्याफोल्डिङ एक शिक्षण प्रविधि हो जहाँ शिक्षकले संरचित सहयोग प्रदान गर्छ र विद्यार्थीहरूले दक्षता विकास गर्दै जाँदा बिस्तारै हटाउँछ, यो भाइगोत्स्कीको ZPD अवधारणाबाट उत्पन्न भएको हो।",
            "difficulty": "HARD",
            "source_reference": "PSC Pedagogy",
        },
    ],
    "curriculum-development": [
        {
            "question_text_en": "The Curriculum Development Centre (CDC) in Nepal was established in which year?",
            "question_text_np": "नेपालमा पाठ्यक्रम विकास केन्द्र (CDC) कुन सालमा स्थापना भयो?",
            "answers": [
                {"text_en": "2028 BS (1971 AD)", "text_np": "२०२८ वि.सं.", "is_correct": True},
                {"text_en": "2035 BS (1978 AD)", "text_np": "२०३५ वि.सं.", "is_correct": False},
                {"text_en": "2020 BS (1963 AD)", "text_np": "२०२० वि.सं.", "is_correct": False},
                {"text_en": "2045 BS (1988 AD)", "text_np": "२०४५ वि.सं.", "is_correct": False},
            ],
            "explanation_en": "The Curriculum Development Centre (CDC) was established in 2028 BS (1971 AD) as the primary body for developing school-level curricula in Nepal.",
            "explanation_np": "पाठ्यक्रम विकास केन्द्र (CDC) नेपालमा विद्यालय स्तरको पाठ्यक्रम विकास गर्ने प्रमुख निकायको रूपमा २०२८ वि.सं.मा स्थापना भयो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Curriculum Development",
        },
        {
            "question_text_en": "Tyler's model of curriculum development follows which sequence?",
            "question_text_np": "टाइलरको पाठ्यक्रम विकास मोडेलले कुन क्रम पालना गर्छ?",
            "answers": [
                {"text_en": "Objectives → Content → Methods → Evaluation", "text_np": "उद्देश्य → विषयवस्तु → विधि → मूल्याङ्कन", "is_correct": True},
                {"text_en": "Content → Methods → Objectives → Evaluation", "text_np": "विषयवस्तु → विधि → उद्देश्य → मूल्याङ्कन", "is_correct": False},
                {"text_en": "Methods → Content → Evaluation → Objectives", "text_np": "विधि → विषयवस्तु → मूल्याङ्कन → उद्देश्य", "is_correct": False},
                {"text_en": "Evaluation → Objectives → Content → Methods", "text_np": "मूल्याङ्कन → उद्देश्य → विषयवस्तु → विधि", "is_correct": False},
            ],
            "explanation_en": "Ralph Tyler's model (1949) follows a linear sequence: define objectives, select content, organize learning experiences, and evaluate outcomes.",
            "explanation_np": "राल्फ टाइलरको मोडेल (१९४९) ले रेखीय क्रम पालना गर्छ: उद्देश्य परिभाषित गर्नु, विषयवस्तु छान्नु, सिकाइ अनुभव व्यवस्थित गर्नु र नतिजा मूल्याङ्कन गर्नु।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Curriculum Development",
        },
        {
            "question_text_en": "Nepal's National Curriculum Framework (NCF) 2076 envisions education in how many levels?",
            "question_text_np": "नेपालको राष्ट्रिय पाठ्यक्रम प्रारूप (NCF) २०७६ ले शिक्षालाई कतिवटा तहमा विभाजन गर्छ?",
            "answers": [
                {"text_en": "Three (basic, secondary, higher)", "text_np": "तीन (आधारभूत, माध्यमिक, उच्च)", "is_correct": True},
                {"text_en": "Four", "text_np": "चार", "is_correct": False},
                {"text_en": "Five", "text_np": "पाँच", "is_correct": False},
                {"text_en": "Two", "text_np": "दुई", "is_correct": False},
            ],
            "explanation_en": "The NCF 2076 structures education into three broad levels: basic education (grades 1-8), secondary education (grades 9-12), and higher education.",
            "explanation_np": "NCF २०७६ ले शिक्षालाई तीन व्यापक तहमा संरचना गर्छ: आधारभूत शिक्षा (कक्षा १-८), माध्यमिक शिक्षा (कक्षा ९-१२) र उच्च शिक्षा।",
            "difficulty": "EASY",
            "source_reference": "PSC Curriculum Development",
        },
        {
            "question_text_en": "Which type of curriculum refers to what students actually learn in practice, as opposed to the intended curriculum?",
            "question_text_np": "कुन प्रकारको पाठ्यक्रमले विद्यार्थीहरूले अभिप्रेत पाठ्यक्रमको विपरित व्यवहारमा वास्तवमा के सिक्छन् भन्ने बुझाउँछ?",
            "answers": [
                {"text_en": "Experienced curriculum", "text_np": "अनुभूत पाठ्यक्रम", "is_correct": True},
                {"text_en": "Formal curriculum", "text_np": "औपचारिक पाठ्यक्रम", "is_correct": False},
                {"text_en": "Hidden curriculum", "text_np": "लुकेको पाठ्यक्रम", "is_correct": False},
                {"text_en": "Null curriculum", "text_np": "शून्य पाठ्यक्रम", "is_correct": False},
            ],
            "explanation_en": "The experienced (or learned) curriculum is what students actually take away from their learning experience, which may differ from the official intended curriculum.",
            "explanation_np": "अनुभूत (वा सिकिएको) पाठ्यक्रम भनेको विद्यार्थीहरूले आफ्नो सिकाइ अनुभवबाट वास्तवमा ग्रहण गर्ने कुरा हो, जुन आधिकारिक अभिप्रेत पाठ्यक्रमभन्दा फरक हुन सक्छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Curriculum Development",
        },
        {
            "question_text_en": "The concept of 'hidden curriculum' refers to:",
            "question_text_np": "'लुकेको पाठ्यक्रम' को अवधारणाले के बुझाउँछ?",
            "answers": [
                {"text_en": "Unintended lessons, values, and norms learned through the school environment", "text_np": "विद्यालय वातावरणबाट सिकिएको अनभिप्रेत पाठ, मूल्य र मान्यता", "is_correct": True},
                {"text_en": "Topics deliberately excluded from the syllabus", "text_np": "पाठ्यक्रमबाट जानाजानी हटाइएका विषय", "is_correct": False},
                {"text_en": "Extra classes taught after school hours", "text_np": "विद्यालय समय पछि पढाइने अतिरिक्त कक्षा", "is_correct": False},
                {"text_en": "Secret exams given by teachers", "text_np": "शिक्षकहरूद्वारा दिइने गोप्य परीक्षा", "is_correct": False},
            ],
            "explanation_en": "Hidden curriculum refers to the unwritten, unofficial, and often unintended lessons, values, and perspectives that students learn in school beyond the formal curriculum.",
            "explanation_np": "लुकेको पाठ्यक्रमले औपचारिक पाठ्यक्रमभन्दा बाहिर विद्यार्थीहरूले विद्यालयमा सिक्ने अलिखित, अनौपचारिक र प्रायः अनभिप्रेत पाठ, मूल्य र दृष्टिकोणलाई बुझाउँछ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Curriculum Development",
        },
        {
            "question_text_en": "Who proposed the spiral curriculum model?",
            "question_text_np": "सर्पिल पाठ्यक्रम मोडेल कसले प्रस्ताव गरेका हुन्?",
            "answers": [
                {"text_en": "Jerome Bruner", "text_np": "जेरोम ब्रुनर", "is_correct": True},
                {"text_en": "John Dewey", "text_np": "जोन डिउई", "is_correct": False},
                {"text_en": "Ralph Tyler", "text_np": "राल्फ टाइलर", "is_correct": False},
                {"text_en": "Hilda Taba", "text_np": "हिल्डा ताबा", "is_correct": False},
            ],
            "explanation_en": "Jerome Bruner proposed the spiral curriculum in 1960, where key concepts are revisited repeatedly with increasing complexity as learners develop.",
            "explanation_np": "जेरोम ब्रुनरले १९६० मा सर्पिल पाठ्यक्रम प्रस्ताव गरे, जहाँ सिकारुहरूको विकास हुँदै जाँदा प्रमुख अवधारणाहरू बढ्दो जटिलतासँग बारम्बार दोहोर्‍याइन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Curriculum Development",
        },
    ],
    # ─── SUBBRANCH-scoped categories ─────────────────────────────────────
    "primary-education-methods": [
        {
            "question_text_en": "At what age do children typically start basic education (Grade 1) in Nepal?",
            "question_text_np": "नेपालमा बालबालिकाले सामान्यतया कति उमेरमा आधारभूत शिक्षा (कक्षा १) सुरु गर्छन्?",
            "answers": [
                {"text_en": "5 years", "text_np": "५ वर्ष", "is_correct": True},
                {"text_en": "4 years", "text_np": "४ वर्ष", "is_correct": False},
                {"text_en": "6 years", "text_np": "६ वर्ष", "is_correct": False},
                {"text_en": "7 years", "text_np": "७ वर्ष", "is_correct": False},
            ],
            "explanation_en": "In Nepal, children typically start Grade 1 (basic education) at the age of 5 years as per the Education Act and related regulations.",
            "explanation_np": "नेपालमा बालबालिकाले शिक्षा ऐन र सम्बन्धित नियमावली अनुसार सामान्यतया ५ वर्षको उमेरमा कक्षा १ (आधारभूत शिक्षा) सुरु गर्छन्।",
            "difficulty": "EASY",
            "source_reference": "PSC Primary Education",
        },
        {
            "question_text_en": "Which teaching approach is most appropriate for early primary grades?",
            "question_text_np": "प्रारम्भिक प्राथमिक कक्षाका लागि कुन शिक्षण दृष्टिकोण सबैभन्दा उपयुक्त छ?",
            "answers": [
                {"text_en": "Play-based and activity-based learning", "text_np": "खेलमा आधारित र क्रियाकलापमा आधारित शिक्षा", "is_correct": True},
                {"text_en": "Lecture-based instruction", "text_np": "व्याख्यानमा आधारित शिक्षण", "is_correct": False},
                {"text_en": "Self-study with textbooks", "text_np": "पाठ्यपुस्तकसँग स्वाध्ययन", "is_correct": False},
                {"text_en": "Computer-based instruction only", "text_np": "कम्प्युटरमा आधारित शिक्षण मात्र", "is_correct": False},
            ],
            "explanation_en": "Play-based and activity-based learning is most suitable for early primary grades as young children learn best through hands-on activities, games, and exploration.",
            "explanation_np": "खेलमा आधारित र क्रियाकलापमा आधारित शिक्षा प्रारम्भिक प्राथमिक कक्षाका लागि सबैभन्दा उपयुक्त छ किनभने साना बालबालिकाहरूले हातेमालो क्रियाकलाप, खेल र अन्वेषणबाट राम्रोसँग सिक्छन्।",
            "difficulty": "EASY",
            "source_reference": "PSC Primary Education",
        },
        {
            "question_text_en": "The Continuous Assessment System (CAS) in Nepal's basic education focuses on:",
            "question_text_np": "नेपालको आधारभूत शिक्षामा निरन्तर मूल्याङ्कन प्रणाली (CAS) ले कुन कुरामा केन्द्रित हुन्छ?",
            "answers": [
                {"text_en": "Assessing student progress throughout the year using multiple methods", "text_np": "विभिन्न विधिहरू प्रयोग गरी वर्षभरि विद्यार्थीको प्रगति मूल्याङ्कन गर्ने", "is_correct": True},
                {"text_en": "Conducting one final exam at the end of the year", "text_np": "वर्षको अन्त्यमा एउटा अन्तिम परीक्षा सञ्चालन गर्ने", "is_correct": False},
                {"text_en": "Evaluating teachers' performance", "text_np": "शिक्षकहरूको कार्यसम्पादन मूल्याङ्कन गर्ने", "is_correct": False},
                {"text_en": "Ranking schools based on student scores", "text_np": "विद्यार्थीको अंकको आधारमा विद्यालयलाई दर्जा दिने", "is_correct": False},
            ],
            "explanation_en": "CAS assesses student progress throughout the academic year using portfolios, observations, projects, classwork, and periodic tests rather than relying solely on final examinations.",
            "explanation_np": "CAS ले अन्तिम परीक्षामा मात्र निर्भर हुनुको सट्टा पोर्टफोलियो, अवलोकन, परियोजना, कक्षाकार्य र आवधिक परीक्षा प्रयोग गरी शैक्षिक वर्षभरि विद्यार्थीको प्रगति मूल्याङ्कन गर्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Primary Education",
        },
        {
            "question_text_en": "Mother tongue-based multilingual education (MTB-MLE) in Nepal aims to:",
            "question_text_np": "नेपालमा मातृभाषामा आधारित बहुभाषिक शिक्षा (MTB-MLE) को उद्देश्य के हो?",
            "answers": [
                {"text_en": "Begin instruction in the child's mother tongue and gradually transition to Nepali and English", "text_np": "बालबालिकाको मातृभाषामा शिक्षण सुरु गरी बिस्तारै नेपाली र अंग्रेजीमा रूपान्तरण गर्ने", "is_correct": True},
                {"text_en": "Replace Nepali with local languages completely", "text_np": "नेपालीलाई स्थानीय भाषाहरूले पूर्ण रूपमा प्रतिस्थापन गर्ने", "is_correct": False},
                {"text_en": "Teach only in English medium", "text_np": "अंग्रेजी माध्यममा मात्र पढाउने", "is_correct": False},
                {"text_en": "Eliminate all minority languages from schools", "text_np": "विद्यालयहरूबाट सबै अल्पसंख्यक भाषाहरू हटाउने", "is_correct": False},
            ],
            "explanation_en": "MTB-MLE starts instruction in the child's mother tongue for better comprehension in early grades, then gradually transitions to Nepali and English, supporting linguistic diversity.",
            "explanation_np": "MTB-MLE ले प्रारम्भिक कक्षामा राम्रो बुझाइका लागि बालबालिकाको मातृभाषामा शिक्षण सुरु गर्छ, त्यसपछि बिस्तारै नेपाली र अंग्रेजीमा रूपान्तरण गर्छ, भाषिक विविधतालाई सहयोग गर्दै।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Primary Education",
        },
        {
            "question_text_en": "Which is a key feature of Nepal's Early Childhood Education and Development (ECED) program?",
            "question_text_np": "नेपालको प्रारम्भिक बाल शिक्षा तथा विकास (ECED) कार्यक्रमको प्रमुख विशेषता कुन हो?",
            "answers": [
                {"text_en": "Providing one year of pre-primary education for 4-year-olds", "text_np": "४ वर्षका बालबालिकाका लागि एक वर्षको पूर्व-प्राथमिक शिक्षा प्रदान गर्ने", "is_correct": True},
                {"text_en": "Teaching advanced mathematics", "text_np": "उन्नत गणित पढाउने", "is_correct": False},
                {"text_en": "Preparing children for competitive exams", "text_np": "बालबालिकालाई प्रतिस्पर्धात्मक परीक्षाका लागि तयार पार्ने", "is_correct": False},
                {"text_en": "Formal classroom instruction for toddlers", "text_np": "बाटोबाटा बालबालिकाका लागि औपचारिक कक्षाकोठा शिक्षण", "is_correct": False},
            ],
            "explanation_en": "Nepal's ECED program provides one year of pre-primary education to children aged 4 years to prepare them for formal schooling through play-based activities.",
            "explanation_np": "नेपालको ECED कार्यक्रमले ४ वर्षका बालबालिकालाई खेलमा आधारित क्रियाकलापहरूमार्फत औपचारिक विद्यालय शिक्षाका लागि तयार पार्न एक वर्षको पूर्व-प्राथमिक शिक्षा प्रदान गर्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Primary Education",
        },
    ],
    "child-development-psychology": [
        {
            "question_text_en": "According to Jean Piaget, children in the 'concrete operational' stage (ages 7-11) can:",
            "question_text_np": "जीन पियाजे अनुसार 'ठोस सञ्चालनात्मक' चरण (उमेर ७-११) का बालबालिकाले के गर्न सक्छन्?",
            "answers": [
                {"text_en": "Think logically about concrete objects and events", "text_np": "ठोस वस्तु र घटनाहरूबारे तार्किक रूपमा सोच्न", "is_correct": True},
                {"text_en": "Think abstractly about hypothetical situations", "text_np": "काल्पनिक परिस्थितिहरूबारे अमूर्त रूपमा सोच्न", "is_correct": False},
                {"text_en": "Only respond to sensory stimuli", "text_np": "इन्द्रिय उत्तेजनामा मात्र प्रतिक्रिया दिन", "is_correct": False},
                {"text_en": "Use complex symbolic language fluently", "text_np": "जटिल प्रतीकात्मक भाषा धाराप्रवाह प्रयोग गर्न", "is_correct": False},
            ],
            "explanation_en": "In Piaget's concrete operational stage (ages 7-11), children develop logical thinking about concrete events, understand conservation, and can classify objects, but struggle with abstract thinking.",
            "explanation_np": "पियाजेको ठोस सञ्चालनात्मक चरणमा (उमेर ७-११), बालबालिकाले ठोस घटनाहरूबारे तार्किक सोच विकास गर्छन्, संरक्षण बुझ्छन् र वस्तुहरूको वर्गीकरण गर्न सक्छन्, तर अमूर्त सोचमा कठिनाइ अनुभव गर्छन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Child Psychology",
        },
        {
            "question_text_en": "Erik Erikson's psychosocial stage for school-age children (6-12 years) is:",
            "question_text_np": "एरिक एरिक्सनको विद्यालय उमेरका बालबालिका (६-१२ वर्ष) को मनोसामाजिक चरण कुन हो?",
            "answers": [
                {"text_en": "Industry vs. Inferiority", "text_np": "उद्यम बनाम हीनता", "is_correct": True},
                {"text_en": "Trust vs. Mistrust", "text_np": "विश्वास बनाम अविश्वास", "is_correct": False},
                {"text_en": "Identity vs. Role Confusion", "text_np": "पहिचान बनाम भूमिका भ्रम", "is_correct": False},
                {"text_en": "Autonomy vs. Shame and Doubt", "text_np": "स्वायत्तता बनाम लाज र शंका", "is_correct": False},
            ],
            "explanation_en": "Erikson's fourth psychosocial stage, Industry vs. Inferiority (6-12 years), involves children developing a sense of competence through mastering new skills and knowledge.",
            "explanation_np": "एरिक्सनको चौथो मनोसामाजिक चरण, उद्यम बनाम हीनता (६-१२ वर्ष), मा बालबालिकाहरूले नयाँ सीप र ज्ञान आत्मसात गरेर क्षमताको भावना विकास गर्छन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Child Psychology",
        },
        {
            "question_text_en": "Which of the following is a characteristic of Piaget's preoperational stage?",
            "question_text_np": "पियाजेको पूर्व-सञ्चालनात्मक चरणको विशेषता निम्नमध्ये कुन हो?",
            "answers": [
                {"text_en": "Egocentrism — difficulty seeing others' perspectives", "text_np": "आत्मकेन्द्रितता — अरूको दृष्टिकोण बुझ्न कठिनाइ", "is_correct": True},
                {"text_en": "Abstract reasoning ability", "text_np": "अमूर्त तर्क क्षमता", "is_correct": False},
                {"text_en": "Mastery of conservation tasks", "text_np": "संरक्षण कार्यमा दक्षता", "is_correct": False},
                {"text_en": "Systematic hypothesis testing", "text_np": "व्यवस्थित परिकल्पना परीक्षण", "is_correct": False},
            ],
            "explanation_en": "The preoperational stage (ages 2-7) is characterized by egocentrism, where children have difficulty understanding perspectives other than their own.",
            "explanation_np": "पूर्व-सञ्चालनात्मक चरण (उमेर २-७) आत्मकेन्द्रितताद्वारा विशेषता हो, जहाँ बालबालिकाहरूले आफ्नो बाहेक अन्य दृष्टिकोण बुझ्न कठिनाइ अनुभव गर्छन्।",
            "difficulty": "EASY",
            "source_reference": "PSC Child Psychology",
        },
        {
            "question_text_en": "Lawrence Kohlberg's theory of moral development identifies how many stages?",
            "question_text_np": "लरेन्स कोलबर्गको नैतिक विकासको सिद्धान्तले कतिवटा चरण पहिचान गर्छ?",
            "answers": [
                {"text_en": "Six stages in three levels", "text_np": "तीन तहमा छवटा चरण", "is_correct": True},
                {"text_en": "Four stages in two levels", "text_np": "दुई तहमा चारवटा चरण", "is_correct": False},
                {"text_en": "Eight stages in four levels", "text_np": "चार तहमा आठवटा चरण", "is_correct": False},
                {"text_en": "Five stages in one level", "text_np": "एक तहमा पाँचवटा चरण", "is_correct": False},
            ],
            "explanation_en": "Kohlberg identified six stages of moral development across three levels: pre-conventional (stages 1-2), conventional (stages 3-4), and post-conventional (stages 5-6).",
            "explanation_np": "कोलबर्गले तीन तहमा नैतिक विकासका छवटा चरण पहिचान गरे: पूर्व-पारम्परिक (चरण १-२), पारम्परिक (चरण ३-४) र उत्तर-पारम्परिक (चरण ५-६)।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Child Psychology",
        },
        {
            "question_text_en": "Howard Gardner's theory of Multiple Intelligences suggests that intelligence is:",
            "question_text_np": "हावर्ड गार्डनरको बहु बुद्धिमत्ताको सिद्धान्तले बुद्धिमत्ता भनेको के हो भनी सुझाव दिन्छ?",
            "answers": [
                {"text_en": "Composed of multiple distinct abilities, not a single factor", "text_np": "एकल कारक नभई विभिन्न क्षमताहरूको संयोजन", "is_correct": True},
                {"text_en": "Measured only by IQ tests", "text_np": "IQ परीक्षाद्वारा मात्र मापन गरिने", "is_correct": False},
                {"text_en": "Fixed and unchangeable from birth", "text_np": "जन्मदेखि स्थिर र अपरिवर्तनीय", "is_correct": False},
                {"text_en": "Dependent solely on genetics", "text_np": "जेनेटिक्समा मात्र निर्भर", "is_correct": False},
            ],
            "explanation_en": "Gardner proposed that intelligence comprises multiple distinct types (linguistic, logical-mathematical, spatial, musical, bodily-kinesthetic, interpersonal, intrapersonal, naturalistic), not a single general ability.",
            "explanation_np": "गार्डनरले प्रस्ताव गरे कि बुद्धिमत्ता एकल सामान्य क्षमता नभई विभिन्न प्रकारहरू (भाषिक, तार्किक-गणितीय, स्थानिक, सांगीतिक, शारीरिक-गतिशील, अन्तरवैयक्तिक, आन्तरवैयक्तिक, प्रकृतिवादी) समावेश गर्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Child Psychology",
        },
        {
            "question_text_en": "According to Maslow's hierarchy of needs, which need must be fulfilled before a child can focus on learning?",
            "question_text_np": "मास्लोको आवश्यकताको पदसोपान अनुसार बालबालिकाले सिकाइमा ध्यान केन्द्रित गर्नुअघि कुन आवश्यकता पूरा हुनुपर्छ?",
            "answers": [
                {"text_en": "Physiological needs (food, water, shelter)", "text_np": "शारीरिक आवश्यकता (खाना, पानी, बासस्थान)", "is_correct": True},
                {"text_en": "Self-actualization", "text_np": "आत्म-साक्षात्कार", "is_correct": False},
                {"text_en": "Esteem needs", "text_np": "सम्मानको आवश्यकता", "is_correct": False},
                {"text_en": "Aesthetic needs", "text_np": "सौन्दर्य आवश्यकता", "is_correct": False},
            ],
            "explanation_en": "According to Maslow, physiological needs (food, water, shelter, rest) are the most basic and must be satisfied first before higher-level needs like learning and self-actualization can be pursued.",
            "explanation_np": "मास्लो अनुसार शारीरिक आवश्यकता (खाना, पानी, बासस्थान, आराम) सबैभन्दा आधारभूत हुन् र सिकाइ र आत्म-साक्षात्कार जस्ता उच्चस्तरीय आवश्यकताहरू पूरा गर्नुअघि यी पहिले पूरा हुनुपर्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Child Psychology",
        },
    ],
    "secondary-education-assessment": [
        {
            "question_text_en": "The Secondary Education Examination (SEE) in Nepal is conducted at the end of which grade?",
            "question_text_np": "नेपालमा माध्यमिक शिक्षा परीक्षा (SEE) कुन कक्षाको अन्त्यमा सञ्चालन गरिन्छ?",
            "answers": [
                {"text_en": "Grade 10", "text_np": "कक्षा १०", "is_correct": True},
                {"text_en": "Grade 12", "text_np": "कक्षा १२", "is_correct": False},
                {"text_en": "Grade 8", "text_np": "कक्षा ८", "is_correct": False},
                {"text_en": "Grade 11", "text_np": "कक्षा ११", "is_correct": False},
            ],
            "explanation_en": "The Secondary Education Examination (SEE), which replaced the SLC, is conducted at the end of Grade 10 and is managed by the National Examinations Board (NEB).",
            "explanation_np": "माध्यमिक शिक्षा परीक्षा (SEE), जसले SLC लाई प्रतिस्थापन गर्‍यो, कक्षा १० को अन्त्यमा सञ्चालन गरिन्छ र राष्ट्रिय परीक्षा बोर्ड (NEB) ले व्यवस्थापन गर्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Secondary Education",
        },
        {
            "question_text_en": "Nepal's SEE grading system uses which scale?",
            "question_text_np": "नेपालको SEE ग्रेडिङ प्रणालीले कुन मापन प्रयोग गर्छ?",
            "answers": [
                {"text_en": "Letter grading (A+, A, B+, B, C+, C, D, E)", "text_np": "अक्षर ग्रेडिङ (A+, A, B+, B, C+, C, D, E)", "is_correct": True},
                {"text_en": "Percentage marks only", "text_np": "प्रतिशत अंक मात्र", "is_correct": False},
                {"text_en": "Pass/Fail system", "text_np": "उत्तीर्ण/अनुत्तीर्ण प्रणाली", "is_correct": False},
                {"text_en": "Division system (First, Second, Third)", "text_np": "श्रेणी प्रणाली (प्रथम, द्वितीय, तृतीय)", "is_correct": False},
            ],
            "explanation_en": "Since 2072 BS, the SEE uses a letter grading system (A+ to E) replacing the old percentage and division system used in the SLC examination.",
            "explanation_np": "२०७२ वि.सं. देखि SEE ले SLC परीक्षामा प्रयोग हुने पुरानो प्रतिशत र श्रेणी प्रणालीको सट्टा अक्षर ग्रेडिङ प्रणाली (A+ देखि E) प्रयोग गर्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Secondary Education",
        },
        {
            "question_text_en": "Which body is responsible for conducting the Grade 12 board examination in Nepal?",
            "question_text_np": "नेपालमा कक्षा १२ को बोर्ड परीक्षा सञ्चालन गर्ने जिम्मेवार निकाय कुन हो?",
            "answers": [
                {"text_en": "National Examinations Board (NEB)", "text_np": "राष्ट्रिय परीक्षा बोर्ड (NEB)", "is_correct": True},
                {"text_en": "Tribhuvan University", "text_np": "त्रिभुवन विश्वविद्यालय", "is_correct": False},
                {"text_en": "Higher Secondary Education Board (HSEB)", "text_np": "उच्च माध्यमिक शिक्षा बोर्ड (HSEB)", "is_correct": False},
                {"text_en": "Ministry of Education", "text_np": "शिक्षा मन्त्रालय", "is_correct": False},
            ],
            "explanation_en": "The National Examinations Board (NEB) is responsible for conducting both SEE (Grade 10) and Grade 12 board examinations in Nepal, having absorbed the former HSEB.",
            "explanation_np": "राष्ट्रिय परीक्षा बोर्ड (NEB) ले पूर्व HSEB लाई समाहित गर्दै नेपालमा SEE (कक्षा १०) र कक्षा १२ दुवैको बोर्ड परीक्षा सञ्चालन गर्ने जिम्मेवारी लिएको छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Secondary Education",
        },
        {
            "question_text_en": "What is the primary purpose of criterion-referenced assessment?",
            "question_text_np": "मापदण्ड-सन्दर्भित मूल्याङ्कनको प्राथमिक उद्देश्य के हो?",
            "answers": [
                {"text_en": "To measure student performance against predetermined learning standards", "text_np": "पूर्वनिर्धारित सिकाइ मापदण्ड विरुद्ध विद्यार्थीको कार्यसम्पादन मापन गर्ने", "is_correct": True},
                {"text_en": "To rank students relative to each other", "text_np": "विद्यार्थीहरूलाई एकअर्काको तुलनामा दर्जा दिने", "is_correct": False},
                {"text_en": "To select the top 10% of students", "text_np": "शीर्ष १०% विद्यार्थी छान्ने", "is_correct": False},
                {"text_en": "To compare performance across different schools", "text_np": "विभिन्न विद्यालयहरूको कार्यसम्पादन तुलना गर्ने", "is_correct": False},
            ],
            "explanation_en": "Criterion-referenced assessment measures student performance against fixed, predetermined criteria or learning standards, unlike norm-referenced assessment which ranks students against each other.",
            "explanation_np": "मापदण्ड-सन्दर्भित मूल्याङ्कनले विद्यार्थीको कार्यसम्पादनलाई स्थिर, पूर्वनिर्धारित मापदण्ड विरुद्ध मापन गर्छ, मानक-सन्दर्भित मूल्याङ्कनको विपरित जसले विद्यार्थीहरूलाई एकअर्काको तुलनामा दर्जा दिन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Secondary Education",
        },
        {
            "question_text_en": "Which assessment tool is used to evaluate practical skills and real-world task performance?",
            "question_text_np": "व्यावहारिक सीप र वास्तविक कार्य सम्पादन मूल्याङ्कन गर्न कुन मूल्याङ्कन उपकरण प्रयोग गरिन्छ?",
            "answers": [
                {"text_en": "Rubric", "text_np": "रुब्रिक", "is_correct": True},
                {"text_en": "Multiple choice test", "text_np": "बहुवैकल्पिक परीक्षा", "is_correct": False},
                {"text_en": "True/False test", "text_np": "सत्य/असत्य परीक्षा", "is_correct": False},
                {"text_en": "Fill in the blanks", "text_np": "खाली ठाउँ भर्ने", "is_correct": False},
            ],
            "explanation_en": "A rubric is a scoring guide that clearly defines performance criteria and levels, making it ideal for evaluating practical skills, projects, and complex tasks.",
            "explanation_np": "रुब्रिक एक अंकन मार्गदर्शन हो जसले कार्यसम्पादन मापदण्ड र तह स्पष्ट रूपमा परिभाषित गर्छ, व्यावहारिक सीप, परियोजना र जटिल कार्यहरूको मूल्याङ्कनका लागि यो आदर्श हो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Secondary Education",
        },
        {
            "question_text_en": "The concept of 'validity' in educational assessment means:",
            "question_text_np": "शैक्षिक मूल्याङ्कनमा 'वैधता' को अवधारणाले के बुझाउँछ?",
            "answers": [
                {"text_en": "The test measures what it is intended to measure", "text_np": "परीक्षाले मापन गर्न खोजेको कुरा नै मापन गर्छ", "is_correct": True},
                {"text_en": "The test gives consistent results every time", "text_np": "परीक्षाले हरेक पटक एकसमान नतिजा दिन्छ", "is_correct": False},
                {"text_en": "The test is easy for all students", "text_np": "परीक्षा सबै विद्यार्थीका लागि सजिलो छ", "is_correct": False},
                {"text_en": "The test can be administered quickly", "text_np": "परीक्षा छिटो सञ्चालन गर्न सकिन्छ", "is_correct": False},
            ],
            "explanation_en": "Validity refers to the degree to which a test accurately measures the construct or learning outcome it claims to assess. It is distinct from reliability, which concerns consistency.",
            "explanation_np": "वैधताले परीक्षाले मूल्याङ्कन गर्न दावी गरेको अवधारणा वा सिकाइ नतिजालाई कत्तिको सही रूपमा मापन गर्छ भन्ने बुझाउँछ। यो विश्वसनीयताभन्दा भिन्न हो, जुन एकरूपतासँग सम्बन्धित छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Secondary Education",
        },
    ],
}
