"""Engineering Service — BRANCH & SUBBRANCH category questions."""

QUESTIONS = {
    # ──────────────────────────────────────────────
    # BRANCH-scoped categories (Engineering Service)
    # ──────────────────────────────────────────────
    "engineering-mathematics": [
        {
            "question_text_en": "What is the Laplace transform of f(t) = e^(at)?",
            "question_text_np": "f(t) = e^(at) को Laplace रूपान्तरण के हो?",
            "answers": [
                {"text_en": "1/(s - a), s > a", "text_np": "1/(s - a), s > a", "is_correct": True},
                {"text_en": "1/(s + a), s > 0", "text_np": "1/(s + a), s > 0", "is_correct": False},
                {"text_en": "a/(s - a), s > a", "text_np": "a/(s - a), s > a", "is_correct": False},
                {"text_en": "1/(s^2 - a^2)", "text_np": "1/(s^2 - a^2)", "is_correct": False},
            ],
            "explanation_en": "The Laplace transform of e^(at) is 1/(s - a) for s > a, derived directly from the definition integral.",
            "explanation_np": "e^(at) को Laplace रूपान्तरण 1/(s - a) हो जहाँ s > a, यो परिभाषा इन्टिग्रलबाट सिधै निकालिन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The eigenvalues of a 2x2 identity matrix are:",
            "question_text_np": "2x2 एकाइ म्याट्रिक्सको eigenvalues कति हुन्?",
            "answers": [
                {"text_en": "1 and 1", "text_np": "१ र १", "is_correct": True},
                {"text_en": "0 and 1", "text_np": "० र १", "is_correct": False},
                {"text_en": "0 and 0", "text_np": "० र ०", "is_correct": False},
                {"text_en": "1 and -1", "text_np": "१ र -१", "is_correct": False},
            ],
            "explanation_en": "The eigenvalues of an identity matrix are all 1, since Ix = 1·x for any vector x.",
            "explanation_np": "एकाइ म्याट्रिक्सको सबै eigenvalues 1 हुन्छन्, किनभने Ix = 1·x कुनै पनि भेक्टर x को लागि।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The divergence of a vector field F = (x², y², z²) at point (1, 1, 1) is:",
            "question_text_np": "भेक्टर फिल्ड F = (x², y², z²) को बिन्दु (1, 1, 1) मा divergence कति हो?",
            "answers": [
                {"text_en": "6", "text_np": "६", "is_correct": True},
                {"text_en": "3", "text_np": "३", "is_correct": False},
                {"text_en": "2", "text_np": "२", "is_correct": False},
                {"text_en": "9", "text_np": "९", "is_correct": False},
            ],
            "explanation_en": "div(F) = ∂(x²)/∂x + ∂(y²)/∂y + ∂(z²)/∂z = 2x + 2y + 2z. At (1,1,1): 2+2+2 = 6.",
            "explanation_np": "div(F) = ∂(x²)/∂x + ∂(y²)/∂y + ∂(z²)/∂z = 2x + 2y + 2z। बिन्दु (1,1,1) मा: 2+2+2 = 6।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "Which numerical method is used to find roots of an equation iteratively starting from an initial guess?",
            "question_text_np": "कुन सांख्यिक विधि प्रारम्भिक अनुमानबाट सुरु गरी समीकरणको मूल पुनरावृत्तिद्वारा खोज्न प्रयोग गरिन्छ?",
            "answers": [
                {"text_en": "Newton-Raphson method", "text_np": "न्यूटन-र्याफसन विधि", "is_correct": True},
                {"text_en": "Gauss elimination", "text_np": "गाउस एलिमिनेसन", "is_correct": False},
                {"text_en": "Trapezoidal rule", "text_np": "ट्रापिजोइडल नियम", "is_correct": False},
                {"text_en": "Simpson's rule", "text_np": "सिम्पसनको नियम", "is_correct": False},
            ],
            "explanation_en": "Newton-Raphson method uses the formula x_(n+1) = x_n - f(x_n)/f'(x_n) to iteratively converge to a root from an initial guess.",
            "explanation_np": "न्यूटन-र्याफसन विधिले x_(n+1) = x_n - f(x_n)/f'(x_n) सूत्र प्रयोग गरी प्रारम्भिक अनुमानबाट मूलमा पुनरावृत्तिद्वारा अभिसरण गर्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The rank of a 3x3 matrix with all rows identical is:",
            "question_text_np": "सबै पङ्क्ति एउटै भएको 3x3 म्याट्रिक्सको rank कति हो?",
            "answers": [
                {"text_en": "1", "text_np": "१", "is_correct": True},
                {"text_en": "3", "text_np": "३", "is_correct": False},
                {"text_en": "0", "text_np": "०", "is_correct": False},
                {"text_en": "2", "text_np": "२", "is_correct": False},
            ],
            "explanation_en": "If all rows are identical, only one linearly independent row exists, so the rank is 1.",
            "explanation_np": "यदि सबै पङ्क्ति एउटै छन् भने एउटा मात्र रैखिक स्वतन्त्र पङ्क्ति हुन्छ, त्यसैले rank 1 हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The order of the differential equation d²y/dx² + 3(dy/dx)³ + y = 0 is:",
            "question_text_np": "अवकल समीकरण d²y/dx² + 3(dy/dx)³ + y = 0 को कोटि (order) कति हो?",
            "answers": [
                {"text_en": "2", "text_np": "२", "is_correct": True},
                {"text_en": "3", "text_np": "३", "is_correct": False},
                {"text_en": "1", "text_np": "१", "is_correct": False},
                {"text_en": "6", "text_np": "६", "is_correct": False},
            ],
            "explanation_en": "The order of a differential equation is the highest derivative present. Here d²y/dx² is the highest, so the order is 2.",
            "explanation_np": "अवकल समीकरणको कोटि भनेको उच्चतम derivation हो। यहाँ d²y/dx² उच्चतम भएकोले कोटि 2 हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
    ],
    "applied-mechanics": [
        {
            "question_text_en": "A body is in static equilibrium when the sum of all forces and the sum of all moments acting on it are:",
            "question_text_np": "एउटा वस्तु स्थैतिक सन्तुलनमा हुन्छ जब सबै बलहरूको योग र सबै आघूर्णहरूको योग कति हुन्छ?",
            "answers": [
                {"text_en": "Zero", "text_np": "शून्य", "is_correct": True},
                {"text_en": "Maximum", "text_np": "अधिकतम", "is_correct": False},
                {"text_en": "Equal to weight", "text_np": "तौलबराबर", "is_correct": False},
                {"text_en": "Constant but non-zero", "text_np": "स्थिर तर शून्य नभएको", "is_correct": False},
            ],
            "explanation_en": "For static equilibrium, ΣF = 0 and ΣM = 0. Both the net force and net moment must be zero.",
            "explanation_np": "स्थैतिक सन्तुलनको लागि ΣF = 0 र ΣM = 0 हुनुपर्छ। खुद बल र खुद आघूर्ण दुवै शून्य हुनुपर्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The moment of inertia of a circular cross-section of diameter d about its centroidal axis is:",
            "question_text_np": "व्यास d भएको वृत्ताकार क्रस-सेक्सनको केन्द्रीय अक्षको जडत्व आघूर्ण कति हो?",
            "answers": [
                {"text_en": "πd⁴/64", "text_np": "πd⁴/64", "is_correct": True},
                {"text_en": "πd⁴/32", "text_np": "πd⁴/32", "is_correct": False},
                {"text_en": "πd²/4", "text_np": "πd²/4", "is_correct": False},
                {"text_en": "πd⁴/16", "text_np": "πd⁴/16", "is_correct": False},
            ],
            "explanation_en": "The moment of inertia of a circular section about its centroidal axis is πd⁴/64. The polar moment is πd⁴/32.",
            "explanation_np": "वृत्ताकार सेक्सनको केन्द्रीय अक्षको जडत्व आघूर्ण πd⁴/64 हो। ध्रुवीय आघूर्ण πd⁴/32 हो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "In a simple truss, the relationship between the number of members (m), joints (j), and reactions (r) for a stable truss is:",
            "question_text_np": "साधारण ट्रसमा स्थिर ट्रसको लागि सदस्य (m), जोड (j) र प्रतिक्रिया (r) बीचको सम्बन्ध के हो?",
            "answers": [
                {"text_en": "m = 2j - r", "text_np": "m = 2j - r", "is_correct": True},
                {"text_en": "m = j - r", "text_np": "m = j - r", "is_correct": False},
                {"text_en": "m = 3j - r", "text_np": "m = 3j - r", "is_correct": False},
                {"text_en": "m = 2j + r", "text_np": "m = 2j + r", "is_correct": False},
            ],
            "explanation_en": "For a statically determinate truss, m + r = 2j, or equivalently m = 2j - r.",
            "explanation_np": "स्थैतिक रूपमा निश्चित ट्रसको लागि m + r = 2j, अर्थात् m = 2j - r।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The coefficient of friction between two surfaces is the ratio of:",
            "question_text_np": "दुई सतहहरू बीचको घर्षण गुणाङ्क कसको अनुपात हो?",
            "answers": [
                {"text_en": "Frictional force to normal reaction", "text_np": "घर्षण बल र अभिलम्ब प्रतिक्रिया", "is_correct": True},
                {"text_en": "Normal reaction to frictional force", "text_np": "अभिलम्ब प्रतिक्रिया र घर्षण बल", "is_correct": False},
                {"text_en": "Applied force to weight", "text_np": "प्रयुक्त बल र तौल", "is_correct": False},
                {"text_en": "Weight to normal reaction", "text_np": "तौल र अभिलम्ब प्रतिक्रिया", "is_correct": False},
            ],
            "explanation_en": "The coefficient of friction μ = F/N, where F is the frictional force and N is the normal reaction.",
            "explanation_np": "घर्षण गुणाङ्क μ = F/N, जहाँ F घर्षण बल र N अभिलम्ब प्रतिक्रिया हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The maximum bending moment in a simply supported beam of span L carrying a uniformly distributed load w per unit length occurs at:",
            "question_text_np": "L स्प्यान भएको साधारण आधारित बीममा प्रति एकाइ लम्बाइ w समान वितरित भार हुँदा अधिकतम बेन्डिङ मोमेन्ट कहाँ हुन्छ?",
            "answers": [
                {"text_en": "Mid-span, and equals wL²/8", "text_np": "बीचमा, र wL²/8 बराबर हुन्छ", "is_correct": True},
                {"text_en": "At the supports, and equals wL²/2", "text_np": "आधारमा, र wL²/2 बराबर हुन्छ", "is_correct": False},
                {"text_en": "Mid-span, and equals wL²/2", "text_np": "बीचमा, र wL²/2 बराबर हुन्छ", "is_correct": False},
                {"text_en": "Quarter-span, and equals wL²/16", "text_np": "चौथाइमा, र wL²/16 बराबर हुन्छ", "is_correct": False},
            ],
            "explanation_en": "For a simply supported beam with UDL, maximum bending moment = wL²/8 and occurs at the mid-span.",
            "explanation_np": "समान वितरित भार भएको साधारण आधारित बीमको अधिकतम बेन्डिङ मोमेन्ट = wL²/8 हो र यो बीचमा हुन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "D'Alembert's principle converts a dynamic problem into an equivalent:",
            "question_text_np": "D'Alembert को सिद्धान्तले गतिशील समस्यालाई समतुल्य कुन समस्यामा रूपान्तरण गर्छ?",
            "answers": [
                {"text_en": "Static equilibrium problem", "text_np": "स्थैतिक सन्तुलन समस्या", "is_correct": True},
                {"text_en": "Vibration problem", "text_np": "कम्पन समस्या", "is_correct": False},
                {"text_en": "Energy conservation problem", "text_np": "ऊर्जा संरक्षण समस्या", "is_correct": False},
                {"text_en": "Fluid dynamics problem", "text_np": "तरल गतिकी समस्या", "is_correct": False},
            ],
            "explanation_en": "D'Alembert's principle introduces an inertial force (-ma), converting Newton's second law into a static equilibrium equation: F - ma = 0.",
            "explanation_np": "D'Alembert को सिद्धान्तले जडत्व बल (-ma) थपेर न्यूटनको दोस्रो नियमलाई स्थैतिक सन्तुलन समीकरणमा रूपान्तरण गर्छ: F - ma = 0।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
    ],
    "engineering-drawing": [
        {
            "question_text_en": "In first-angle projection, the object is placed between the:",
            "question_text_np": "प्रथम कोण प्रक्षेपणमा वस्तु कहाँ राखिन्छ?",
            "answers": [
                {"text_en": "Observer and the plane of projection", "text_np": "पर्यवेक्षक र प्रक्षेपण तलबीचमा", "is_correct": True},
                {"text_en": "Two planes of projection", "text_np": "दुई प्रक्षेपण तलहरूबीचमा", "is_correct": False},
                {"text_en": "Plane of projection and the observer is behind", "text_np": "प्रक्षेपण तलमा र पर्यवेक्षक पछाडि", "is_correct": False},
                {"text_en": "None of the above", "text_np": "माथिको कुनै पनि होइन", "is_correct": False},
            ],
            "explanation_en": "In first-angle projection, the object lies between the observer and the projection plane. The view is projected through the object onto the plane behind it.",
            "explanation_np": "प्रथम कोण प्रक्षेपणमा वस्तु पर्यवेक्षक र प्रक्षेपण तलबीच हुन्छ। दृश्य वस्तुमार्फत पछाडिको तलमा प्रक्षेपित हुन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "A section plane cutting a cone parallel to its base produces a:",
            "question_text_np": "एउटा सेक्सन प्लेनले कोनलाई यसको आधारसँग समानान्तर काट्दा कुन आकार बन्छ?",
            "answers": [
                {"text_en": "Circle", "text_np": "वृत्त", "is_correct": True},
                {"text_en": "Ellipse", "text_np": "दीर्घवृत्त", "is_correct": False},
                {"text_en": "Parabola", "text_np": "परावलय", "is_correct": False},
                {"text_en": "Hyperbola", "text_np": "अतिपरावलय", "is_correct": False},
            ],
            "explanation_en": "When a section plane cuts a cone parallel to its base, the resulting cross-section is always a circle.",
            "explanation_np": "जब सेक्सन प्लेनले कोनलाई यसको आधारसँग समानान्तर काट्छ, परिणामस्वरूप क्रस-सेक्सन सधैं वृत्त हुन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The standard ratio of line thickness for visible outlines to hidden lines in engineering drawing is:",
            "question_text_np": "इन्जिनियरिङ ड्रइङमा देखिने बाह्यरेखा र लुकेका रेखाको रेखा मोटाइको मानक अनुपात कति हो?",
            "answers": [
                {"text_en": "2:1", "text_np": "२:१", "is_correct": True},
                {"text_en": "3:1", "text_np": "३:१", "is_correct": False},
                {"text_en": "1:1", "text_np": "१:१", "is_correct": False},
                {"text_en": "4:1", "text_np": "४:१", "is_correct": False},
            ],
            "explanation_en": "As per IS/ISO standards, visible outlines are drawn with thick lines and hidden lines with thin lines in a ratio of approximately 2:1.",
            "explanation_np": "IS/ISO मापदण्ड अनुसार देखिने बाह्यरेखा बाक्लो रेखा र लुकेका रेखा पातलो रेखामा लगभग २:१ को अनुपातमा कोरिन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "An isometric drawing has all axes inclined at what angle to each other?",
            "question_text_np": "आइसोमेट्रिक ड्रइङमा सबै अक्षहरू एकअर्कासँग कति कोणमा झुकेका हुन्छन्?",
            "answers": [
                {"text_en": "120°", "text_np": "१२०°", "is_correct": True},
                {"text_en": "90°", "text_np": "९०°", "is_correct": False},
                {"text_en": "60°", "text_np": "६०°", "is_correct": False},
                {"text_en": "150°", "text_np": "१५०°", "is_correct": False},
            ],
            "explanation_en": "In isometric projection, the three axes are equally spaced at 120° to each other, with two axes at 30° to the horizontal.",
            "explanation_np": "आइसोमेट्रिक प्रक्षेपणमा तीन अक्षहरू एकअर्कासँग १२०° मा समान दूरीमा हुन्छन्, दुई अक्ष तेर्सोसँग ३०° मा।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "In engineering drawing, the development of a cylinder results in a:",
            "question_text_np": "इन्जिनियरिङ ड्रइङमा सिलिन्डरको विकास (development) गर्दा कुन आकार बन्छ?",
            "answers": [
                {"text_en": "Rectangle", "text_np": "आयत", "is_correct": True},
                {"text_en": "Triangle", "text_np": "त्रिभुज", "is_correct": False},
                {"text_en": "Circle", "text_np": "वृत्त", "is_correct": False},
                {"text_en": "Trapezoid", "text_np": "ट्रापिजोइड", "is_correct": False},
            ],
            "explanation_en": "When a cylinder is developed (unrolled), the lateral surface becomes a rectangle with height equal to the cylinder height and width equal to its circumference (πd).",
            "explanation_np": "सिलिन्डरलाई विकास (अनरोल) गर्दा पार्श्व सतह आयतमा परिणत हुन्छ जसको उचाइ सिलिन्डरको उचाइ र चौडाइ यसको परिधि (πd) बराबर हुन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "Which type of line represents a cutting plane in a sectional view?",
            "question_text_np": "सेक्सनल भ्यूमा काट्ने तललाई कुन प्रकारको रेखाले प्रतिनिधित्व गर्छ?",
            "answers": [
                {"text_en": "Chain thin line with thick ends", "text_np": "बाक्लो छेउ भएको चेन पातलो रेखा", "is_correct": True},
                {"text_en": "Continuous thick line", "text_np": "निरन्तर बाक्लो रेखा", "is_correct": False},
                {"text_en": "Short dashed line", "text_np": "छोटो ड्यास रेखा", "is_correct": False},
                {"text_en": "Continuous thin line", "text_np": "निरन्तर पातलो रेखा", "is_correct": False},
            ],
            "explanation_en": "A cutting plane is represented by a chain thin line with thick ends (and arrows showing the direction of viewing).",
            "explanation_np": "काट्ने तललाई बाक्लो छेउ भएको चेन पातलो रेखाले प्रतिनिधित्व गर्छ (र हेर्ने दिशा देखाउने तीरहरूसहित)।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
    ],

    # ──────────────────────────────────────────────
    # SUBBRANCH: Civil Engineering
    # ──────────────────────────────────────────────
    "structural-analysis-design": [
        {
            "question_text_en": "The degree of static indeterminacy of a fixed beam is:",
            "question_text_np": "स्थिर बीम (fixed beam) को स्थैतिक अनिश्चितताको डिग्री कति हो?",
            "answers": [
                {"text_en": "3", "text_np": "३", "is_correct": True},
                {"text_en": "2", "text_np": "२", "is_correct": False},
                {"text_en": "1", "text_np": "१", "is_correct": False},
                {"text_en": "0", "text_np": "०", "is_correct": False},
            ],
            "explanation_en": "A fixed beam has 6 reactions (3 at each end) and only 3 equilibrium equations, so the degree of static indeterminacy is 6 - 3 = 3.",
            "explanation_np": "स्थिर बीमको ६ प्रतिक्रिया (प्रत्येक छेउमा ३) र ३ मात्र सन्तुलन समीकरण हुन्छन्, त्यसैले स्थैतिक अनिश्चितताको डिग्री ६ - ३ = ३ हो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "In the limit state method of design, the partial safety factor for dead load is typically:",
            "question_text_np": "डिजाइनको सीमा अवस्था विधिमा मृत भार (dead load) को लागि आंशिक सुरक्षा गुणाङ्क सामान्यतया कति हुन्छ?",
            "answers": [
                {"text_en": "1.5", "text_np": "१.५", "is_correct": True},
                {"text_en": "1.0", "text_np": "१.०", "is_correct": False},
                {"text_en": "2.0", "text_np": "२.०", "is_correct": False},
                {"text_en": "1.2", "text_np": "१.२", "is_correct": False},
            ],
            "explanation_en": "As per IS 456:2000, the partial safety factor for dead load in limit state of collapse is 1.5 (when only DL is considered).",
            "explanation_np": "IS 456:2000 अनुसार, ढल्ने सीमा अवस्थामा मृत भारको आंशिक सुरक्षा गुणाङ्क १.५ हो (जब DL मात्र विचार गरिन्छ)।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The bending moment at any point on a cantilever beam carrying a point load W at its free end, at distance x from the free end, is:",
            "question_text_np": "खुला छेउमा बिन्दु भार W भएको क्यान्टिलिभर बीमको खुला छेउबाट x दूरीमा बेन्डिङ मोमेन्ट कति हो?",
            "answers": [
                {"text_en": "W × x", "text_np": "W × x", "is_correct": True},
                {"text_en": "W × x²", "text_np": "W × x²", "is_correct": False},
                {"text_en": "W / x", "text_np": "W / x", "is_correct": False},
                {"text_en": "W × L (constant)", "text_np": "W × L (स्थिर)", "is_correct": False},
            ],
            "explanation_en": "For a cantilever with point load W at the free end, the bending moment at distance x from the free end is M = W × x, varying linearly.",
            "explanation_np": "खुला छेउमा बिन्दु भार W भएको क्यान्टिलिभरमा खुला छेउबाट x दूरीमा बेन्डिङ मोमेन्ट M = W × x हो, रेखीय रूपमा भिन्न हुन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "Which method of structural analysis uses the concept of releasing redundant constraints?",
            "question_text_np": "संरचनात्मक विश्लेषणको कुन विधिले अतिरिक्त बाधा हटाउने अवधारणा प्रयोग गर्छ?",
            "answers": [
                {"text_en": "Flexibility (force) method", "text_np": "लचिलोपन (बल) विधि", "is_correct": True},
                {"text_en": "Stiffness (displacement) method", "text_np": "कठोरता (विस्थापन) विधि", "is_correct": False},
                {"text_en": "Moment distribution method", "text_np": "आघूर्ण वितरण विधि", "is_correct": False},
                {"text_en": "Slope deflection method", "text_np": "ढलान विक्षेपण विधि", "is_correct": False},
            ],
            "explanation_en": "The flexibility (force/compatibility) method works by releasing redundant constraints to form a primary structure and then solving for the redundant forces using compatibility conditions.",
            "explanation_np": "लचिलोपन (बल/अनुकूलता) विधि अतिरिक्त बाधा हटाएर प्राथमिक संरचना बनाउँछ र त्यसपछि अनुकूलता सर्तहरू प्रयोग गरी अतिरिक्त बलहरू समाधान गर्छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The effective length of a column with both ends fixed is:",
            "question_text_np": "दुवै छेउ स्थिर भएको स्तम्भको प्रभावकारी लम्बाइ कति हो?",
            "answers": [
                {"text_en": "0.5L", "text_np": "0.5L", "is_correct": True},
                {"text_en": "L", "text_np": "L", "is_correct": False},
                {"text_en": "0.7L", "text_np": "0.7L", "is_correct": False},
                {"text_en": "2L", "text_np": "2L", "is_correct": False},
            ],
            "explanation_en": "For a column with both ends fixed, the effective length is 0.5L, where L is the actual length. This gives the highest load-carrying capacity among standard end conditions.",
            "explanation_np": "दुवै छेउ स्थिर भएको स्तम्भको प्रभावकारी लम्बाइ 0.5L हो, जहाँ L वास्तविक लम्बाइ हो। यसले मानक अन्त्य सर्तहरूमा सबैभन्दा बढी भार वहन क्षमता दिन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "In reinforced concrete design, the maximum strain in concrete at the extreme compression fiber in limit state of collapse is:",
            "question_text_np": "प्रबलित कंक्रीट डिजाइनमा ढल्ने सीमा अवस्थामा अत्यधिक सङ्कुचन फाइबरमा कंक्रीटको अधिकतम स्ट्रेन कति हो?",
            "answers": [
                {"text_en": "0.0035", "text_np": "०.००३५", "is_correct": True},
                {"text_en": "0.002", "text_np": "०.००२", "is_correct": False},
                {"text_en": "0.005", "text_np": "०.००५", "is_correct": False},
                {"text_en": "0.0015", "text_np": "०.००१५", "is_correct": False},
            ],
            "explanation_en": "As per IS 456, the maximum compressive strain in concrete at collapse is 0.0035 (at the extreme compression fiber).",
            "explanation_np": "IS 456 अनुसार, ढल्ने अवस्थामा कंक्रीटमा अधिकतम सङ्कुचन स्ट्रेन ०.००३५ हो (अत्यधिक सङ्कुचन फाइबरमा)।",
            "difficulty": "HARD",
            "source_reference": "PSC Engineering",
        },
    ],
    "surveying-transportation": [
        {
            "question_text_en": "The principle of surveying is to work from:",
            "question_text_np": "सर्वेक्षणको सिद्धान्त भनेको कहाँबाट कहाँ काम गर्ने हो?",
            "answers": [
                {"text_en": "Whole to part", "text_np": "सम्पूर्णबाट भागमा", "is_correct": True},
                {"text_en": "Part to whole", "text_np": "भागबाट सम्पूर्णमा", "is_correct": False},
                {"text_en": "Left to right", "text_np": "बायाँबाट दायाँ", "is_correct": False},
                {"text_en": "Top to bottom", "text_np": "माथिबाट तल", "is_correct": False},
            ],
            "explanation_en": "The fundamental principle of surveying is to work from whole to part, establishing a framework of control points first and then filling in details.",
            "explanation_np": "सर्वेक्षणको मौलिक सिद्धान्त सम्पूर्णबाट भागमा काम गर्ने हो, पहिले नियन्त्रण बिन्दुहरूको ढाँचा स्थापना गरी त्यसपछि विवरणहरू भर्ने।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The CBR (California Bearing Ratio) test is used to determine the:",
            "question_text_np": "CBR (क्यालिफोर्निया बेयरिङ रेसियो) परीक्षण के निर्धारण गर्न प्रयोग गरिन्छ?",
            "answers": [
                {"text_en": "Strength of subgrade soil for pavement design", "text_np": "सडक डिजाइनको लागि सबग्रेड माटोको बल", "is_correct": True},
                {"text_en": "Water content of soil", "text_np": "माटोको पानीको मात्रा", "is_correct": False},
                {"text_en": "Compressive strength of concrete", "text_np": "कंक्रीटको सङ्कुचन बल", "is_correct": False},
                {"text_en": "Permeability of soil", "text_np": "माटोको पारगम्यता", "is_correct": False},
            ],
            "explanation_en": "The CBR test evaluates the strength of subgrade and base course materials for pavement design by comparing penetration resistance to a standard crushed stone.",
            "explanation_np": "CBR परीक्षणले सडक डिजाइनको लागि सबग्रेड र बेस कोर्स सामग्रीको बल मानक कुचिएको ढुङ्गासँग प्रवेश प्रतिरोध तुलना गरी मूल्याङ्कन गर्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "In a contour map, closely spaced contours indicate:",
            "question_text_np": "कन्टुर नक्सामा नजिक-नजिक भएका कन्टुरहरूले के जनाउँछन्?",
            "answers": [
                {"text_en": "Steep slope", "text_np": "भिरालो ढलान", "is_correct": True},
                {"text_en": "Gentle slope", "text_np": "सामान्य ढलान", "is_correct": False},
                {"text_en": "Flat terrain", "text_np": "समतल भूभाग", "is_correct": False},
                {"text_en": "Valley", "text_np": "उपत्यका", "is_correct": False},
            ],
            "explanation_en": "Closely spaced contours indicate a steep slope because the elevation changes rapidly over a short horizontal distance.",
            "explanation_np": "नजिक-नजिक भएका कन्टुरहरूले भिरालो ढलान जनाउँछन् किनभने छोटो तेर्सो दूरीमा उचाइ छिटो परिवर्तन हुन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The superelevation on a highway curve is provided to counteract:",
            "question_text_np": "राजमार्गको मोडमा सुपरएलिभेसन के प्रतिकार गर्न दिइन्छ?",
            "answers": [
                {"text_en": "Centrifugal force", "text_np": "केन्द्रापसारी बल", "is_correct": True},
                {"text_en": "Gravitational force", "text_np": "गुरुत्वाकर्षण बल", "is_correct": False},
                {"text_en": "Braking force", "text_np": "ब्रेकिङ बल", "is_correct": False},
                {"text_en": "Wind force", "text_np": "हावा बल", "is_correct": False},
            ],
            "explanation_en": "Superelevation is the banking of the road surface on a curve to counteract the centrifugal force acting on a moving vehicle.",
            "explanation_np": "सुपरएलिभेसन भनेको मोडमा सडक सतह बैंकिंग गर्ने हो जसले चलिरहेको सवारीमा लाग्ने केन्द्रापसारी बललाई प्रतिकार गर्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The most common type of curve used in highway alignment is:",
            "question_text_np": "राजमार्ग एलाइनमेन्टमा प्रयोग हुने सबैभन्दा सामान्य प्रकारको curve कुन हो?",
            "answers": [
                {"text_en": "Simple circular curve", "text_np": "साधारण वृत्ताकार curve", "is_correct": True},
                {"text_en": "Spiral curve", "text_np": "स्पाइरल curve", "is_correct": False},
                {"text_en": "Parabolic curve", "text_np": "परावलयिक curve", "is_correct": False},
                {"text_en": "Compound curve", "text_np": "कम्पाउन्ड curve", "is_correct": False},
            ],
            "explanation_en": "Simple circular curves are the most commonly used horizontal curves in highway alignment due to their simplicity in design and setting out.",
            "explanation_np": "साधारण वृत्ताकार curve राजमार्ग एलाइनमेन्टमा सबैभन्दा सामान्य तेर्सो curve हो किनभने डिजाइन र सेटिङमा सरल हुन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "What is the minimum stopping sight distance on a highway with a design speed of 80 km/h on a flat road?",
            "question_text_np": "समतल सडकमा ८० किमी/घ डिजाइन गतिमा राजमार्गमा न्यूनतम रोक्ने दृष्टि दूरी (SSD) लगभग कति हो?",
            "answers": [
                {"text_en": "120 m", "text_np": "१२० मि", "is_correct": True},
                {"text_en": "80 m", "text_np": "८० मि", "is_correct": False},
                {"text_en": "60 m", "text_np": "६० मि", "is_correct": False},
                {"text_en": "200 m", "text_np": "२०० मि", "is_correct": False},
            ],
            "explanation_en": "For a design speed of 80 km/h with standard reaction time (2.5s) and braking friction (0.35), the SSD is approximately 120 m on flat terrain (IRC standards).",
            "explanation_np": "८० किमी/घ डिजाइन गतिमा मानक प्रतिक्रिया समय (२.५ से) र ब्रेकिङ घर्षण (०.३५) सहित SSD समतल भूभागमा लगभग १२० मि हो (IRC मापदण्ड)।",
            "difficulty": "HARD",
            "source_reference": "PSC Engineering",
        },
    ],

    # ──────────────────────────────────────────────
    # SUBBRANCH: Computer Engineering
    # ──────────────────────────────────────────────
    "data-structures-algorithms": [
        {
            "question_text_en": "The time complexity of binary search on a sorted array of n elements is:",
            "question_text_np": "n तत्वहरू भएको क्रमबद्ध एरेमा बाइनरी सर्चको समय जटिलता कति हो?",
            "answers": [
                {"text_en": "O(log n)", "text_np": "O(log n)", "is_correct": True},
                {"text_en": "O(n)", "text_np": "O(n)", "is_correct": False},
                {"text_en": "O(n log n)", "text_np": "O(n log n)", "is_correct": False},
                {"text_en": "O(1)", "text_np": "O(1)", "is_correct": False},
            ],
            "explanation_en": "Binary search divides the search space in half at each step, resulting in O(log n) time complexity.",
            "explanation_np": "बाइनरी सर्चले प्रत्येक चरणमा खोज स्थानलाई आधामा विभाजन गर्छ, जसले O(log n) समय जटिलता दिन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "Which data structure follows the Last In First Out (LIFO) principle?",
            "question_text_np": "कुन डाटा संरचनाले Last In First Out (LIFO) सिद्धान्त पालना गर्छ?",
            "answers": [
                {"text_en": "Stack", "text_np": "स्ट्याक", "is_correct": True},
                {"text_en": "Queue", "text_np": "क्यु", "is_correct": False},
                {"text_en": "Linked List", "text_np": "लिंक्ड लिस्ट", "is_correct": False},
                {"text_en": "Array", "text_np": "एरे", "is_correct": False},
            ],
            "explanation_en": "A stack follows LIFO — the last element pushed is the first to be popped. Common applications include function call management, undo operations, and expression evaluation.",
            "explanation_np": "स्ट्याकले LIFO पालना गर्छ — अन्तिममा थपिएको तत्व पहिले निकालिन्छ। सामान्य अनुप्रयोगहरूमा फंक्शन कल व्यवस्थापन, अन्डू कार्य, र अभिव्यक्ति मूल्याङ्कन पर्छन्।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The worst-case time complexity of QuickSort is:",
            "question_text_np": "QuickSort को सबैभन्दा खराब अवस्थाको समय जटिलता कति हो?",
            "answers": [
                {"text_en": "O(n²)", "text_np": "O(n²)", "is_correct": True},
                {"text_en": "O(n log n)", "text_np": "O(n log n)", "is_correct": False},
                {"text_en": "O(n)", "text_np": "O(n)", "is_correct": False},
                {"text_en": "O(log n)", "text_np": "O(log n)", "is_correct": False},
            ],
            "explanation_en": "QuickSort's worst case occurs when the pivot always selects the smallest or largest element, leading to O(n²). However, its average case is O(n log n).",
            "explanation_np": "QuickSort को सबैभन्दा खराब अवस्था तब हुन्छ जब pivot ले सधैं सबैभन्दा सानो वा ठूलो तत्व छान्छ, जसले O(n²) दिन्छ। तर यसको औसत अवस्था O(n log n) हो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "In a balanced Binary Search Tree (AVL tree), the maximum difference in heights of left and right subtrees of any node is:",
            "question_text_np": "सन्तुलित बाइनरी सर्च ट्री (AVL ट्री) मा कुनै पनि नोडको बायाँ र दायाँ सबट्रीको उचाइमा अधिकतम भिन्नता कति हो?",
            "answers": [
                {"text_en": "1", "text_np": "१", "is_correct": True},
                {"text_en": "2", "text_np": "२", "is_correct": False},
                {"text_en": "0", "text_np": "०", "is_correct": False},
                {"text_en": "3", "text_np": "३", "is_correct": False},
            ],
            "explanation_en": "In an AVL tree, the balance factor (difference between left and right subtree heights) of every node must be -1, 0, or 1. Maximum difference is 1.",
            "explanation_np": "AVL ट्रीमा प्रत्येक नोडको सन्तुलन गुणाङ्क (बायाँ र दायाँ सबट्री उचाइको भिन्नता) -1, 0 वा 1 हुनुपर्छ। अधिकतम भिन्नता 1 हो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "Dijkstra's algorithm is used to find:",
            "question_text_np": "Dijkstra को एल्गोरिदम के खोज्न प्रयोग गरिन्छ?",
            "answers": [
                {"text_en": "Shortest path from a single source in a weighted graph", "text_np": "भारित ग्राफमा एकल स्रोतबाट सबैभन्दा छोटो बाटो", "is_correct": True},
                {"text_en": "Minimum spanning tree", "text_np": "न्यूनतम स्प्यानिङ ट्री", "is_correct": False},
                {"text_en": "Maximum flow in a network", "text_np": "नेटवर्कमा अधिकतम प्रवाह", "is_correct": False},
                {"text_en": "Topological ordering of a graph", "text_np": "ग्राफको टोपोलोजिकल क्रम", "is_correct": False},
            ],
            "explanation_en": "Dijkstra's algorithm finds the shortest path from a single source vertex to all other vertices in a graph with non-negative edge weights.",
            "explanation_np": "Dijkstra को एल्गोरिदमले गैर-ऋणात्मक किनारा भार भएको ग्राफमा एकल स्रोत शीर्षबाट अन्य सबै शीर्षहरूमा सबैभन्दा छोटो बाटो खोज्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "Which of the following is NOT a stable sorting algorithm?",
            "question_text_np": "तलका मध्ये कुन स्थिर (stable) छुट्याउने एल्गोरिदम होइन?",
            "answers": [
                {"text_en": "Selection Sort", "text_np": "सेलेक्सन सोर्ट", "is_correct": True},
                {"text_en": "Merge Sort", "text_np": "मर्ज सोर्ट", "is_correct": False},
                {"text_en": "Bubble Sort", "text_np": "बबल सोर्ट", "is_correct": False},
                {"text_en": "Insertion Sort", "text_np": "इन्सर्सन सोर्ट", "is_correct": False},
            ],
            "explanation_en": "Selection Sort is not stable because it may change the relative order of equal elements during swaps. Merge Sort, Bubble Sort, and Insertion Sort are all stable.",
            "explanation_np": "सेलेक्सन सोर्ट स्थिर छैन किनभने स्वैप गर्दा बराबर तत्वहरूको सापेक्ष क्रम परिवर्तन हुन सक्छ। मर्ज सोर्ट, बबल सोर्ट, र इन्सर्सन सोर्ट सबै स्थिर हुन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
    ],
    "database-networking": [
        {
            "question_text_en": "Which normal form eliminates transitive dependency?",
            "question_text_np": "कुन सामान्य रूपले सङ्क्रमणशील निर्भरता (transitive dependency) हटाउँछ?",
            "answers": [
                {"text_en": "Third Normal Form (3NF)", "text_np": "तेस्रो सामान्य रूप (3NF)", "is_correct": True},
                {"text_en": "First Normal Form (1NF)", "text_np": "पहिलो सामान्य रूप (1NF)", "is_correct": False},
                {"text_en": "Second Normal Form (2NF)", "text_np": "दोस्रो सामान्य रूप (2NF)", "is_correct": False},
                {"text_en": "BCNF", "text_np": "BCNF", "is_correct": False},
            ],
            "explanation_en": "3NF eliminates transitive dependencies — where a non-prime attribute depends on another non-prime attribute through the primary key.",
            "explanation_np": "3NF ले सङ्क्रमणशील निर्भरता हटाउँछ — जहाँ गैर-प्रमुख विशेषता प्राथमिक कुञ्जी मार्फत अर्को गैर-प्रमुख विशेषतामा निर्भर हुन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The OSI model has how many layers?",
            "question_text_np": "OSI मोडेलमा कति तह (layers) हुन्छन्?",
            "answers": [
                {"text_en": "7", "text_np": "७", "is_correct": True},
                {"text_en": "5", "text_np": "५", "is_correct": False},
                {"text_en": "4", "text_np": "४", "is_correct": False},
                {"text_en": "6", "text_np": "६", "is_correct": False},
            ],
            "explanation_en": "The OSI model has 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, and Application.",
            "explanation_np": "OSI मोडेलमा ७ तह हुन्छन्: भौतिक, डाटा लिंक, नेटवर्क, ट्रान्सपोर्ट, सेसन, प्रेजेन्टेसन, र एप्लिकेसन।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "In SQL, which command is used to remove all rows from a table without logging individual row deletions?",
            "question_text_np": "SQL मा व्यक्तिगत पङ्क्ति मेटाइको लग नराखी तालिकाबाट सबै पङ्क्तिहरू हटाउन कुन कमाण्ड प्रयोग गरिन्छ?",
            "answers": [
                {"text_en": "TRUNCATE", "text_np": "TRUNCATE", "is_correct": True},
                {"text_en": "DELETE", "text_np": "DELETE", "is_correct": False},
                {"text_en": "DROP", "text_np": "DROP", "is_correct": False},
                {"text_en": "REMOVE", "text_np": "REMOVE", "is_correct": False},
            ],
            "explanation_en": "TRUNCATE removes all rows from a table without logging individual deletions, making it faster than DELETE. DROP removes the entire table structure.",
            "explanation_np": "TRUNCATE ले व्यक्तिगत मेटाइको लग नराखी तालिकाबाट सबै पङ्क्तिहरू हटाउँछ, जसले DELETE भन्दा छिटो बनाउँछ। DROP ले सम्पूर्ण तालिका संरचना हटाउँछ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "Which protocol is used to resolve IP addresses to MAC addresses?",
            "question_text_np": "IP ठेगानालाई MAC ठेगानामा रूपान्तरण गर्न कुन प्रोटोकल प्रयोग गरिन्छ?",
            "answers": [
                {"text_en": "ARP (Address Resolution Protocol)", "text_np": "ARP (एड्रेस रिजोल्युसन प्रोटोकल)", "is_correct": True},
                {"text_en": "RARP", "text_np": "RARP", "is_correct": False},
                {"text_en": "DHCP", "text_np": "DHCP", "is_correct": False},
                {"text_en": "DNS", "text_np": "DNS", "is_correct": False},
            ],
            "explanation_en": "ARP (Address Resolution Protocol) maps IP addresses to MAC (hardware) addresses within a local network.",
            "explanation_np": "ARP (एड्रेस रिजोल्युसन प्रोटोकल) ले स्थानीय नेटवर्कमा IP ठेगानालाई MAC (हार्डवेयर) ठेगानामा म्याप गर्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "A deadlock in a database occurs when:",
            "question_text_np": "डाटाबेसमा deadlock कहिले हुन्छ?",
            "answers": [
                {"text_en": "Two or more transactions are waiting for each other to release locks", "text_np": "दुई वा बढी लेनदेनहरू एकअर्काको lock छोड्नको लागि पर्खिरहेका हुन्छन्", "is_correct": True},
                {"text_en": "A single transaction holds all locks", "text_np": "एउटा लेनदेनले सबै lock राखेको हुन्छ", "is_correct": False},
                {"text_en": "No transactions are running", "text_np": "कुनै लेनदेन चलिरहेको हुँदैन", "is_correct": False},
                {"text_en": "The database runs out of storage", "text_np": "डाटाबेसको भण्डारण सकिन्छ", "is_correct": False},
            ],
            "explanation_en": "A deadlock occurs when two or more transactions form a circular wait, each holding a lock that the other needs.",
            "explanation_np": "Deadlock तब हुन्छ जब दुई वा बढी लेनदेनहरूले वृत्ताकार प्रतीक्षा बनाउँछन्, प्रत्येकले अर्कोलाई चाहिने lock राखेको हुन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "In the TCP/IP model, which layer is responsible for end-to-end communication and flow control?",
            "question_text_np": "TCP/IP मोडेलमा कुन तहले end-to-end सञ्चार र प्रवाह नियन्त्रणको जिम्मेवारी लिन्छ?",
            "answers": [
                {"text_en": "Transport layer", "text_np": "ट्रान्सपोर्ट तह", "is_correct": True},
                {"text_en": "Application layer", "text_np": "एप्लिकेसन तह", "is_correct": False},
                {"text_en": "Internet layer", "text_np": "इन्टरनेट तह", "is_correct": False},
                {"text_en": "Network access layer", "text_np": "नेटवर्क एक्सेस तह", "is_correct": False},
            ],
            "explanation_en": "The Transport layer (TCP/UDP) provides end-to-end communication, flow control, error recovery, and segmentation.",
            "explanation_np": "ट्रान्सपोर्ट तह (TCP/UDP) ले end-to-end सञ्चार, प्रवाह नियन्त्रण, त्रुटि रिकभरी, र सेगमेन्टेसन प्रदान गर्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
    ],
    "os-software-engineering": [
        {
            "question_text_en": "Which CPU scheduling algorithm can cause starvation?",
            "question_text_np": "कुन CPU शेड्युलिङ एल्गोरिदमले भोकमरी (starvation) गराउन सक्छ?",
            "answers": [
                {"text_en": "Shortest Job First (SJF)", "text_np": "सबैभन्दा छोटो काम पहिले (SJF)", "is_correct": True},
                {"text_en": "Round Robin", "text_np": "राउन्ड रोबिन", "is_correct": False},
                {"text_en": "First Come First Served (FCFS)", "text_np": "पहिले आउने पहिले सेवा (FCFS)", "is_correct": False},
                {"text_en": "Multilevel Queue (with feedback)", "text_np": "बहुस्तरीय क्यु (फिडब्याक सहित)", "is_correct": False},
            ],
            "explanation_en": "SJF can cause starvation because longer processes may wait indefinitely if shorter processes keep arriving. Aging can be used as a solution.",
            "explanation_np": "SJF ले भोकमरी गराउन सक्छ किनभने छोटा प्रक्रियाहरू आइरहेमा लामा प्रक्रियाहरू अनिश्चितकालसम्म पर्खन सक्छन्। Aging समाधानको रूपमा प्रयोग गर्न सकिन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "In the Waterfall model of software development, which phase comes after requirements analysis?",
            "question_text_np": "सफ्टवेयर विकासको Waterfall मोडेलमा आवश्यकता विश्लेषण पछि कुन चरण आउँछ?",
            "answers": [
                {"text_en": "System design", "text_np": "प्रणाली डिजाइन", "is_correct": True},
                {"text_en": "Implementation", "text_np": "कार्यान्वयन", "is_correct": False},
                {"text_en": "Testing", "text_np": "परीक्षण", "is_correct": False},
                {"text_en": "Maintenance", "text_np": "मर्मत सम्भार", "is_correct": False},
            ],
            "explanation_en": "The Waterfall model follows: Requirements → System Design → Implementation → Testing → Deployment → Maintenance.",
            "explanation_np": "Waterfall मोडेलको क्रम: आवश्यकता → प्रणाली डिजाइन → कार्यान्वयन → परीक्षण → तैनाती → मर्मत सम्भार।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "A semaphore is used in operating systems for:",
            "question_text_np": "अपरेटिङ सिस्टममा सेमाफोर (semaphore) कसको लागि प्रयोग गरिन्छ?",
            "answers": [
                {"text_en": "Process synchronization", "text_np": "प्रक्रिया सिंक्रोनाइजेसन", "is_correct": True},
                {"text_en": "Memory allocation", "text_np": "मेमोरी आवंटन", "is_correct": False},
                {"text_en": "File compression", "text_np": "फाइल कम्प्रेसन", "is_correct": False},
                {"text_en": "Disk scheduling", "text_np": "डिस्क शेड्युलिङ", "is_correct": False},
            ],
            "explanation_en": "A semaphore is a synchronization primitive used to control access to shared resources by multiple processes, preventing race conditions.",
            "explanation_np": "सेमाफोर एउटा सिंक्रोनाइजेसन प्रिमिटिभ हो जुन बहु प्रक्रियाहरूद्वारा साझा स्रोतहरूमा पहुँच नियन्त्रण गर्न प्रयोग गरिन्छ, जसले race conditions रोक्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "Which page replacement algorithm suffers from Belady's anomaly?",
            "question_text_np": "कुन पेज प्रतिस्थापन एल्गोरिदमले Belady's anomaly बाट ग्रस्त हुन्छ?",
            "answers": [
                {"text_en": "FIFO (First In First Out)", "text_np": "FIFO (पहिले आउने पहिले जाने)", "is_correct": True},
                {"text_en": "LRU (Least Recently Used)", "text_np": "LRU (हालै सबैभन्दा कम प्रयोग भएको)", "is_correct": False},
                {"text_en": "Optimal", "text_np": "इष्टतम", "is_correct": False},
                {"text_en": "LFU (Least Frequently Used)", "text_np": "LFU (सबैभन्दा कम प्रयोग भएको)", "is_correct": False},
            ],
            "explanation_en": "Belady's anomaly is the phenomenon where increasing the number of page frames results in more page faults. FIFO is the known algorithm that suffers from this.",
            "explanation_np": "Belady's anomaly भनेको पेज फ्रेमको संख्या बढाउँदा पनि पेज फल्ट बढ्ने घटना हो। FIFO यो समस्याबाट ग्रस्त हुने ज्ञात एल्गोरिदम हो।",
            "difficulty": "HARD",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "In Agile methodology, a 'Sprint' typically lasts:",
            "question_text_np": "Agile विधिमा 'Sprint' सामान्यतया कतिसम्म चल्छ?",
            "answers": [
                {"text_en": "1 to 4 weeks", "text_np": "१ देखि ४ हप्ता", "is_correct": True},
                {"text_en": "1 to 2 months", "text_np": "१ देखि २ महिना", "is_correct": False},
                {"text_en": "1 day", "text_np": "१ दिन", "is_correct": False},
                {"text_en": "6 months", "text_np": "६ महिना", "is_correct": False},
            ],
            "explanation_en": "In Scrum (an Agile framework), a Sprint is a time-boxed iteration typically lasting 1 to 4 weeks, with 2 weeks being the most common.",
            "explanation_np": "Scrum (एउटा Agile फ्रेमवर्क) मा Sprint सामान्यतया १ देखि ४ हप्तासम्म चल्ने समय-सीमित पुनरावृत्ति हो, २ हप्ता सबैभन्दा सामान्य हुन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The critical section problem in operating systems requires which of the following conditions to be satisfied?",
            "question_text_np": "अपरेटिङ सिस्टममा critical section समस्यालाई तलका मध्ये कुन सर्तहरू पूरा गर्नुपर्छ?",
            "answers": [
                {"text_en": "Mutual exclusion, progress, and bounded waiting", "text_np": "पारस्परिक बहिष्करण, प्रगति, र सीमित प्रतीक्षा", "is_correct": True},
                {"text_en": "Only mutual exclusion", "text_np": "पारस्परिक बहिष्करण मात्र", "is_correct": False},
                {"text_en": "Deadlock prevention and mutual exclusion", "text_np": "Deadlock रोकथाम र पारस्परिक बहिष्करण", "is_correct": False},
                {"text_en": "Starvation freedom only", "text_np": "भोकमरी मुक्ति मात्र", "is_correct": False},
            ],
            "explanation_en": "A correct solution to the critical section problem must satisfy three conditions: mutual exclusion, progress, and bounded waiting.",
            "explanation_np": "Critical section समस्याको सही समाधानले तीन सर्तहरू पूरा गर्नुपर्छ: पारस्परिक बहिष्करण, प्रगति, र सीमित प्रतीक्षा।",
            "difficulty": "HARD",
            "source_reference": "PSC Engineering",
        },
    ],

    # ──────────────────────────────────────────────
    # SUBBRANCH: Electrical Engineering
    # ──────────────────────────────────────────────
    "circuit-theory-electronics": [
        {
            "question_text_en": "According to Kirchhoff's Current Law (KCL), the algebraic sum of currents at any node is:",
            "question_text_np": "Kirchhoff को विद्युत् प्रवाह नियम (KCL) अनुसार कुनै पनि नोडमा विद्युत् प्रवाहहरूको बीजगणितीय योग कति हुन्छ?",
            "answers": [
                {"text_en": "Zero", "text_np": "शून्य", "is_correct": True},
                {"text_en": "Equal to supply voltage", "text_np": "आपूर्ति भोल्टेज बराबर", "is_correct": False},
                {"text_en": "Maximum", "text_np": "अधिकतम", "is_correct": False},
                {"text_en": "Equal to total resistance", "text_np": "कुल प्रतिरोध बराबर", "is_correct": False},
            ],
            "explanation_en": "KCL states that the algebraic sum of currents entering and leaving any junction (node) in a circuit is zero, based on conservation of charge.",
            "explanation_np": "KCL ले भन्छ कि सर्किटमा कुनै पनि जंक्सन (नोड) मा प्रवेश र प्रस्थान गर्ने विद्युत् प्रवाहहरूको बीजगणितीय योग शून्य हो, चार्ज संरक्षणमा आधारित।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The Thevenin equivalent of a circuit consists of:",
            "question_text_np": "सर्किटको Thevenin समतुल्य कसबाट बनेको हुन्छ?",
            "answers": [
                {"text_en": "A voltage source in series with a resistance", "text_np": "प्रतिरोधसँग श्रृंखलामा भोल्टेज स्रोत", "is_correct": True},
                {"text_en": "A current source in parallel with a resistance", "text_np": "प्रतिरोधसँग समानान्तरमा विद्युत् प्रवाह स्रोत", "is_correct": False},
                {"text_en": "Two voltage sources in series", "text_np": "श्रृंखलामा दुई भोल्टेज स्रोत", "is_correct": False},
                {"text_en": "A voltage source with no resistance", "text_np": "प्रतिरोध बिनाको भोल्टेज स्रोत", "is_correct": False},
            ],
            "explanation_en": "Thevenin's theorem states that any linear circuit can be replaced by an equivalent voltage source (V_th) in series with an equivalent resistance (R_th).",
            "explanation_np": "Thevenin को प्रमेय भन्छ कि कुनै पनि रैखिक सर्किटलाई समतुल्य भोल्टेज स्रोत (V_th) र समतुल्य प्रतिरोध (R_th) श्रृंखलामा राखेर प्रतिस्थापन गर्न सकिन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "In a pure capacitive AC circuit, the current:",
            "question_text_np": "शुद्ध क्यापासिटिभ AC सर्किटमा विद्युत् प्रवाह:",
            "answers": [
                {"text_en": "Leads the voltage by 90°", "text_np": "भोल्टेजभन्दा ९०° अगाडि हुन्छ", "is_correct": True},
                {"text_en": "Lags the voltage by 90°", "text_np": "भोल्टेजभन्दा ९०° पछाडि हुन्छ", "is_correct": False},
                {"text_en": "Is in phase with voltage", "text_np": "भोल्टेजसँग फेजमा हुन्छ", "is_correct": False},
                {"text_en": "Leads the voltage by 45°", "text_np": "भोल्टेजभन्दा ४५° अगाडि हुन्छ", "is_correct": False},
            ],
            "explanation_en": "In a pure capacitive circuit, current leads voltage by 90° (π/2 radians). Remember: 'ICE' — In a Capacitor, current (I) leads EMF (E).",
            "explanation_np": "शुद्ध क्यापासिटिभ सर्किटमा विद्युत् प्रवाह भोल्टेजभन्दा ९०° (π/2 रेडियन) अगाडि हुन्छ। सम्झनुहोस्: 'ICE' — Capacitor मा current (I) ले EMF (E) लाई अगाडि गर्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The forbidden energy gap of silicon at room temperature is approximately:",
            "question_text_np": "कोठाको तापक्रममा सिलिकनको निषिद्ध ऊर्जा ग्याप लगभग कति हो?",
            "answers": [
                {"text_en": "1.1 eV", "text_np": "१.१ eV", "is_correct": True},
                {"text_en": "0.7 eV", "text_np": "०.७ eV", "is_correct": False},
                {"text_en": "1.5 eV", "text_np": "१.५ eV", "is_correct": False},
                {"text_en": "0.3 eV", "text_np": "०.३ eV", "is_correct": False},
            ],
            "explanation_en": "Silicon has a band gap of approximately 1.1 eV at room temperature. Germanium has about 0.7 eV, and GaAs about 1.4 eV.",
            "explanation_np": "सिलिकनको कोठाको तापक्रममा ब्यान्ड ग्याप लगभग १.१ eV छ। जर्मेनियमको लगभग ०.७ eV र GaAs को लगभग १.४ eV छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "An ideal op-amp has:",
            "question_text_np": "आदर्श op-amp मा के हुन्छ?",
            "answers": [
                {"text_en": "Infinite input impedance and zero output impedance", "text_np": "अनन्त इनपुट इम्पिडेन्स र शून्य आउटपुट इम्पिडेन्स", "is_correct": True},
                {"text_en": "Zero input impedance and infinite output impedance", "text_np": "शून्य इनपुट इम्पिडेन्स र अनन्त आउटपुट इम्पिडेन्स", "is_correct": False},
                {"text_en": "Finite input and output impedance", "text_np": "परिमित इनपुट र आउटपुट इम्पिडेन्स", "is_correct": False},
                {"text_en": "Zero input impedance and zero output impedance", "text_np": "शून्य इनपुट इम्पिडेन्स र शून्य आउटपुट इम्पिडेन्स", "is_correct": False},
            ],
            "explanation_en": "An ideal op-amp has infinite input impedance (draws no current), zero output impedance (perfect voltage source), and infinite open-loop gain.",
            "explanation_np": "आदर्श op-amp को अनन्त इनपुट इम्पिडेन्स (कुनै विद्युत् प्रवाह तान्दैन), शून्य आउटपुट इम्पिडेन्स (पूर्ण भोल्टेज स्रोत), र अनन्त ओपन-लुप गेन हुन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The resonant frequency of a series RLC circuit is given by:",
            "question_text_np": "श्रृंखला RLC सर्किटको अनुनाद आवृत्ति कसरी दिइन्छ?",
            "answers": [
                {"text_en": "1 / (2π√(LC))", "text_np": "1 / (2π√(LC))", "is_correct": True},
                {"text_en": "2π√(LC)", "text_np": "2π√(LC)", "is_correct": False},
                {"text_en": "1 / (2πRC)", "text_np": "1 / (2πRC)", "is_correct": False},
                {"text_en": "R / (2πL)", "text_np": "R / (2πL)", "is_correct": False},
            ],
            "explanation_en": "At resonance, the inductive reactance equals capacitive reactance. The resonant frequency f₀ = 1/(2π√(LC)), independent of resistance R.",
            "explanation_np": "अनुनादमा इन्डक्टिभ रिएक्टेन्स क्यापासिटिभ रिएक्टेन्स बराबर हुन्छ। अनुनाद आवृत्ति f₀ = 1/(2π√(LC)), प्रतिरोध R बाट स्वतन्त्र।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
    ],
    "power-systems-machines": [
        {
            "question_text_en": "In a three-phase power system, the relationship between line voltage (V_L) and phase voltage (V_Ph) in a star connection is:",
            "question_text_np": "तीन-फेज पावर सिस्टममा स्टार कनेक्सनमा लाइन भोल्टेज (V_L) र फेज भोल्टेज (V_Ph) बीचको सम्बन्ध के हो?",
            "answers": [
                {"text_en": "V_L = √3 × V_Ph", "text_np": "V_L = √3 × V_Ph", "is_correct": True},
                {"text_en": "V_L = V_Ph", "text_np": "V_L = V_Ph", "is_correct": False},
                {"text_en": "V_L = 3 × V_Ph", "text_np": "V_L = 3 × V_Ph", "is_correct": False},
                {"text_en": "V_L = V_Ph / √3", "text_np": "V_L = V_Ph / √3", "is_correct": False},
            ],
            "explanation_en": "In a star (Y) connection, the line voltage is √3 times the phase voltage. In delta connection, line voltage equals phase voltage.",
            "explanation_np": "स्टार (Y) कनेक्सनमा लाइन भोल्टेज फेज भोल्टेजको √3 गुणा हुन्छ। डेल्टा कनेक्सनमा लाइन भोल्टेज फेज भोल्टेज बराबर हुन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The synchronous speed of a 4-pole, 50 Hz AC motor is:",
            "question_text_np": "४-पोल, ५० Hz AC मोटरको सिंक्रोनस गति कति हो?",
            "answers": [
                {"text_en": "1500 RPM", "text_np": "१५०० RPM", "is_correct": True},
                {"text_en": "3000 RPM", "text_np": "३००० RPM", "is_correct": False},
                {"text_en": "750 RPM", "text_np": "७५० RPM", "is_correct": False},
                {"text_en": "1000 RPM", "text_np": "१००० RPM", "is_correct": False},
            ],
            "explanation_en": "Synchronous speed N_s = 120f/P = 120 × 50/4 = 1500 RPM, where f is frequency and P is the number of poles.",
            "explanation_np": "सिंक्रोनस गति N_s = 120f/P = 120 × 50/4 = 1500 RPM, जहाँ f आवृत्ति र P पोलको संख्या हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "A transformer works on the principle of:",
            "question_text_np": "ट्रान्सफर्मर कुन सिद्धान्तमा काम गर्छ?",
            "answers": [
                {"text_en": "Mutual electromagnetic induction", "text_np": "पारस्परिक विद्युत चुम्बकीय प्रेरण", "is_correct": True},
                {"text_en": "Electrostatic induction", "text_np": "स्थिर विद्युत प्रेरण", "is_correct": False},
                {"text_en": "Self induction only", "text_np": "आत्म प्रेरण मात्र", "is_correct": False},
                {"text_en": "Coulomb's law", "text_np": "कूलम्बको नियम", "is_correct": False},
            ],
            "explanation_en": "A transformer works on Faraday's principle of mutual electromagnetic induction — a changing magnetic flux in one coil induces EMF in the other.",
            "explanation_np": "ट्रान्सफर्मर फ्याराडेको पारस्परिक विद्युत चुम्बकीय प्रेरणको सिद्धान्तमा काम गर्छ — एउटा कोइलमा परिवर्तनशील चुम्बकीय फ्लक्सले अर्को कोइलमा EMF प्रेरित गर्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The power factor of a purely resistive AC circuit is:",
            "question_text_np": "शुद्ध प्रतिरोधात्मक AC सर्किटको पावर फ्याक्टर कति हो?",
            "answers": [
                {"text_en": "1 (unity)", "text_np": "१ (एकता)", "is_correct": True},
                {"text_en": "0", "text_np": "०", "is_correct": False},
                {"text_en": "0.5", "text_np": "०.५", "is_correct": False},
                {"text_en": "0.8 lagging", "text_np": "०.८ ल्यागिंग", "is_correct": False},
            ],
            "explanation_en": "In a purely resistive circuit, voltage and current are in phase (phase angle = 0°), so the power factor = cos(0°) = 1.",
            "explanation_np": "शुद्ध प्रतिरोधात्मक सर्किटमा भोल्टेज र विद्युत् प्रवाह फेजमा हुन्छन् (फेज कोण = 0°), त्यसैले पावर फ्याक्टर = cos(0°) = 1।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "Which type of DC motor has the highest starting torque?",
            "question_text_np": "कुन प्रकारको DC मोटरको सबैभन्दा उच्च सुरुवाती टर्क हुन्छ?",
            "answers": [
                {"text_en": "Series motor", "text_np": "सिरिज मोटर", "is_correct": True},
                {"text_en": "Shunt motor", "text_np": "शन्ट मोटर", "is_correct": False},
                {"text_en": "Compound motor", "text_np": "कम्पाउन्ड मोटर", "is_correct": False},
                {"text_en": "Separately excited motor", "text_np": "छुट्टै उत्तेजित मोटर", "is_correct": False},
            ],
            "explanation_en": "A DC series motor has the highest starting torque because the armature current flows through the field winding, and torque is proportional to the square of current (T ∝ I²) at start.",
            "explanation_np": "DC सिरिज मोटरको सबैभन्दा उच्च सुरुवाती टर्क हुन्छ किनभने आर्मेचर विद्युत् प्रवाह फिल्ड वाइन्डिङ मार्फत बग्छ, र सुरुमा टर्क विद्युत् प्रवाहको वर्गसँग समानुपाती हुन्छ (T ∝ I²)।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The per-unit system in power systems is advantageous because:",
            "question_text_np": "पावर सिस्टममा per-unit प्रणाली फाइदाजनक हुन्छ किनभने:",
            "answers": [
                {"text_en": "It simplifies calculations across different voltage levels", "text_np": "यसले विभिन्न भोल्टेज स्तरमा गणनालाई सरल बनाउँछ", "is_correct": True},
                {"text_en": "It increases accuracy of measurements", "text_np": "यसले मापनको सटीकता बढाउँछ", "is_correct": False},
                {"text_en": "It eliminates the need for transformers", "text_np": "यसले ट्रान्सफर्मरको आवश्यकता हटाउँछ", "is_correct": False},
                {"text_en": "It reduces power losses", "text_np": "यसले पावर हानि घटाउँछ", "is_correct": False},
            ],
            "explanation_en": "The per-unit system normalizes quantities to a common base, simplifying calculations especially in systems with multiple voltage levels and transformers.",
            "explanation_np": "Per-unit प्रणालीले परिमाणहरूलाई साझा आधारमा सामान्यीकरण गर्छ, विशेषगरी बहु भोल्टेज स्तर र ट्रान्सफर्मर भएका प्रणालीहरूमा गणना सरल बनाउँछ।",
            "difficulty": "HARD",
            "source_reference": "PSC Engineering",
        },
    ],

    # ──────────────────────────────────────────────
    # SUBBRANCH: Mechanical Engineering
    # ──────────────────────────────────────────────
    "thermodynamics-heat-transfer": [
        {
            "question_text_en": "According to the first law of thermodynamics, for an isolated system:",
            "question_text_np": "ऊष्मागतिकीको पहिलो नियम अनुसार, विलगित प्रणालीको लागि:",
            "answers": [
                {"text_en": "Total energy remains constant", "text_np": "कुल ऊर्जा स्थिर रहन्छ", "is_correct": True},
                {"text_en": "Entropy remains constant", "text_np": "एन्ट्रोपी स्थिर रहन्छ", "is_correct": False},
                {"text_en": "Temperature remains constant", "text_np": "तापक्रम स्थिर रहन्छ", "is_correct": False},
                {"text_en": "Pressure remains constant", "text_np": "चाप स्थिर रहन्छ", "is_correct": False},
            ],
            "explanation_en": "The first law of thermodynamics (conservation of energy) states that in an isolated system, the total energy is conserved — it can neither be created nor destroyed.",
            "explanation_np": "ऊष्मागतिकीको पहिलो नियम (ऊर्जा संरक्षण) ले भन्छ कि विलगित प्रणालीमा कुल ऊर्जा संरक्षित हुन्छ — यो न त सिर्जना गर्न सकिन्छ न त नष्ट।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The Carnot cycle efficiency depends only on:",
            "question_text_np": "कार्नो चक्रको दक्षता कसमा मात्र निर्भर गर्छ?",
            "answers": [
                {"text_en": "Temperatures of the hot and cold reservoirs", "text_np": "तातो र चिसो जलाशयको तापक्रम", "is_correct": True},
                {"text_en": "Type of working fluid", "text_np": "काम गर्ने तरल पदार्थको प्रकार", "is_correct": False},
                {"text_en": "Pressure of the system", "text_np": "प्रणालीको चाप", "is_correct": False},
                {"text_en": "Volume of the cylinder", "text_np": "सिलिन्डरको आयतन", "is_correct": False},
            ],
            "explanation_en": "Carnot efficiency η = 1 - T_cold/T_hot depends only on the absolute temperatures of the hot and cold reservoirs, not on the working fluid.",
            "explanation_np": "कार्नो दक्षता η = 1 - T_cold/T_hot तातो र चिसो जलाशयको निरपेक्ष तापक्रममा मात्र निर्भर गर्छ, काम गर्ने तरल पदार्थमा होइन।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "Heat transfer by conduction through a plane wall is governed by:",
            "question_text_np": "समतल भित्ता मार्फत चालनद्वारा ऊष्मा स्थानान्तरण कुन नियमले शासन गर्छ?",
            "answers": [
                {"text_en": "Fourier's law", "text_np": "फुरियरको नियम", "is_correct": True},
                {"text_en": "Newton's law of cooling", "text_np": "न्यूटनको शीतलन नियम", "is_correct": False},
                {"text_en": "Stefan-Boltzmann law", "text_np": "स्टेफन-बोल्ट्जम्यान नियम", "is_correct": False},
                {"text_en": "Kirchhoff's law", "text_np": "किर्चहफको नियम", "is_correct": False},
            ],
            "explanation_en": "Fourier's law governs heat conduction: q = -kA(dT/dx), where k is thermal conductivity, A is area, and dT/dx is the temperature gradient.",
            "explanation_np": "फुरियरको नियमले ऊष्मा चालन शासन गर्छ: q = -kA(dT/dx), जहाँ k ऊष्मीय चालकता, A क्षेत्रफल, र dT/dx तापक्रम ग्रेडियन्ट हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "In an Otto cycle, the efficiency increases with increase in:",
            "question_text_np": "अटो चक्रमा दक्षता कसको वृद्धिसँग बढ्छ?",
            "answers": [
                {"text_en": "Compression ratio", "text_np": "सङ्कुचन अनुपात", "is_correct": True},
                {"text_en": "Cut-off ratio", "text_np": "कट-अफ अनुपात", "is_correct": False},
                {"text_en": "Back work ratio", "text_np": "ब्याक वर्क अनुपात", "is_correct": False},
                {"text_en": "Specific heat ratio only", "text_np": "विशिष्ट ऊष्मा अनुपात मात्र", "is_correct": False},
            ],
            "explanation_en": "Otto cycle efficiency η = 1 - 1/(r^(γ-1)), where r is the compression ratio and γ is the specific heat ratio. Efficiency increases with higher compression ratio.",
            "explanation_np": "अटो चक्र दक्षता η = 1 - 1/(r^(γ-1)), जहाँ r सङ्कुचन अनुपात र γ विशिष्ट ऊष्मा अनुपात हो। उच्च सङ्कुचन अनुपातसँग दक्षता बढ्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The Nusselt number in heat transfer represents the ratio of:",
            "question_text_np": "ऊष्मा स्थानान्तरणमा Nusselt संख्याले कसको अनुपात प्रतिनिधित्व गर्छ?",
            "answers": [
                {"text_en": "Convective to conductive heat transfer", "text_np": "संवहनात्मक र चालनात्मक ऊष्मा स्थानान्तरण", "is_correct": True},
                {"text_en": "Inertia to viscous forces", "text_np": "जडत्व र चिपचिपा बल", "is_correct": False},
                {"text_en": "Momentum to thermal diffusivity", "text_np": "संवेग र ऊष्मीय प्रसारिता", "is_correct": False},
                {"text_en": "Buoyancy to viscous forces", "text_np": "उत्प्लावकता र चिपचिपा बल", "is_correct": False},
            ],
            "explanation_en": "The Nusselt number (Nu = hL/k) represents the ratio of convective to conductive heat transfer across the boundary layer.",
            "explanation_np": "Nusselt संख्या (Nu = hL/k) ले सीमा तहमा संवहनात्मक र चालनात्मक ऊष्मा स्थानान्तरणको अनुपात प्रतिनिधित्व गर्छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "A reversible process is one that:",
            "question_text_np": "उत्क्रमणीय प्रक्रिया भनेको:",
            "answers": [
                {"text_en": "Can be reversed without leaving any change in the system or surroundings", "text_np": "प्रणाली वा वरिपरिमा कुनै परिवर्तन नछोडी उल्टाउन सकिन्छ", "is_correct": True},
                {"text_en": "Always occurs at constant temperature", "text_np": "सधैं स्थिर तापक्रममा हुन्छ", "is_correct": False},
                {"text_en": "Produces maximum entropy", "text_np": "अधिकतम एन्ट्रोपी उत्पादन गर्छ", "is_correct": False},
                {"text_en": "Cannot occur in practice", "text_np": "व्यवहारमा हुन सक्दैन मात्र", "is_correct": False},
            ],
            "explanation_en": "A reversible process can be reversed without any net change in the system and surroundings. It is an idealization — real processes are always irreversible.",
            "explanation_np": "उत्क्रमणीय प्रक्रिया प्रणाली र वरिपरिमा कुनै खुद परिवर्तन बिना उल्टाउन सकिन्छ। यो एक आदर्शीकरण हो — वास्तविक प्रक्रियाहरू सधैं अनुत्क्रमणीय हुन्छन्।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
    ],
    "manufacturing-machine-design": [
        {
            "question_text_en": "The purpose of a flywheel in a machine is to:",
            "question_text_np": "मेसिनमा फ्लाइह्विलको उद्देश्य के हो?",
            "answers": [
                {"text_en": "Store energy and reduce speed fluctuations", "text_np": "ऊर्जा भण्डारण गर्ने र गति उतार-चढाव घटाउने", "is_correct": True},
                {"text_en": "Increase the speed of the engine", "text_np": "इन्जिनको गति बढाउने", "is_correct": False},
                {"text_en": "Reduce friction in bearings", "text_np": "बेयरिङमा घर्षण घटाउने", "is_correct": False},
                {"text_en": "Connect the engine to the gearbox", "text_np": "इन्जिनलाई गियरबक्ससँग जोड्ने", "is_correct": False},
            ],
            "explanation_en": "A flywheel stores kinetic energy during the power stroke and releases it during other strokes, reducing speed fluctuations in the engine cycle.",
            "explanation_np": "फ्लाइह्विलले पावर स्ट्रोकमा गतिज ऊर्जा भण्डारण गर्छ र अन्य स्ट्रोकमा छोड्छ, इन्जिन चक्रमा गति उतार-चढाव घटाउँछ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "In CNC machining, G01 code represents:",
            "question_text_np": "CNC मेसिनिङमा G01 कोडले के प्रतिनिधित्व गर्छ?",
            "answers": [
                {"text_en": "Linear interpolation (feed move)", "text_np": "रैखिक इन्टरपोलेसन (फिड मुभ)", "is_correct": True},
                {"text_en": "Rapid positioning", "text_np": "द्रुत पोजिसनिङ", "is_correct": False},
                {"text_en": "Circular interpolation clockwise", "text_np": "घडीको दिशामा वृत्ताकार इन्टरपोलेसन", "is_correct": False},
                {"text_en": "Tool change", "text_np": "उपकरण परिवर्तन", "is_correct": False},
            ],
            "explanation_en": "G01 is linear interpolation — the tool moves in a straight line at a specified feed rate. G00 is rapid positioning, G02/G03 are circular interpolation.",
            "explanation_np": "G01 रैखिक इन्टरपोलेसन हो — उपकरण निर्दिष्ट फिड दरमा सिधा रेखामा चल्छ। G00 द्रुत पोजिसनिङ हो, G02/G03 वृत्ताकार इन्टरपोलेसन हो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "The factor of safety in machine design is defined as the ratio of:",
            "question_text_np": "मेसिन डिजाइनमा सुरक्षा गुणाङ्क कसको अनुपातको रूपमा परिभाषित गरिन्छ?",
            "answers": [
                {"text_en": "Failure stress to allowable (working) stress", "text_np": "विफलता तनाव र अनुमति (काम गर्ने) तनाव", "is_correct": True},
                {"text_en": "Working stress to failure stress", "text_np": "काम गर्ने तनाव र विफलता तनाव", "is_correct": False},
                {"text_en": "Applied load to weight", "text_np": "प्रयुक्त भार र तौल", "is_correct": False},
                {"text_en": "Elastic limit to proportional limit", "text_np": "लचिलो सीमा र आनुपातिक सीमा", "is_correct": False},
            ],
            "explanation_en": "Factor of Safety (FoS) = Failure stress / Working stress. It ensures the component operates well below its failure point.",
            "explanation_np": "सुरक्षा गुणाङ्क (FoS) = विफलता तनाव / काम गर्ने तनाव। यसले कम्पोनेन्ट यसको विफलता बिन्दुभन्दा धेरै तल सञ्चालन हुने सुनिश्चित गर्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "Welding, brazing, and soldering are differentiated primarily by:",
            "question_text_np": "वेल्डिङ, ब्रेजिङ, र सोल्डरिङ मुख्य रूपमा कसद्वारा भिन्न हुन्छन्?",
            "answers": [
                {"text_en": "The temperature range used in the joining process", "text_np": "जोड्ने प्रक्रियामा प्रयोग हुने तापक्रम दायरा", "is_correct": True},
                {"text_en": "The materials being joined", "text_np": "जोडिने सामग्रीहरू", "is_correct": False},
                {"text_en": "The shape of the joint", "text_np": "जोइन्टको आकार", "is_correct": False},
                {"text_en": "The speed of the process", "text_np": "प्रक्रियाको गति", "is_correct": False},
            ],
            "explanation_en": "Welding melts base metals (highest temperature), brazing uses filler metal above 450°C without melting base metal, and soldering uses filler below 450°C.",
            "explanation_np": "वेल्डिङले आधार धातु पगाल्छ (उच्चतम तापक्रम), ब्रेजिङले आधार धातु नपगाली ४५०°C माथि फिलर धातु प्रयोग गर्छ, र सोल्डरिङले ४५०°C तल फिलर प्रयोग गर्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "In a gear train, if the driver gear has 20 teeth and the driven gear has 60 teeth, the gear ratio is:",
            "question_text_np": "गियर ट्रेनमा ड्राइभर गियरमा २० दाँत र ड्रिभन गियरमा ६० दाँत छ भने गियर अनुपात कति हो?",
            "answers": [
                {"text_en": "3:1", "text_np": "३:१", "is_correct": True},
                {"text_en": "1:3", "text_np": "१:३", "is_correct": False},
                {"text_en": "2:1", "text_np": "२:१", "is_correct": False},
                {"text_en": "1:2", "text_np": "१:२", "is_correct": False},
            ],
            "explanation_en": "Gear ratio = Number of teeth on driven gear / Number of teeth on driver gear = 60/20 = 3:1. The driven gear rotates 3 times slower.",
            "explanation_np": "गियर अनुपात = ड्रिभन गियरको दाँत / ड्राइभर गियरको दाँत = 60/20 = 3:1। ड्रिभन गियर ३ गुणा ढिलो घुम्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Engineering",
        },
        {
            "question_text_en": "Endurance limit in fatigue loading is the stress below which a material can withstand:",
            "question_text_np": "थकान भारमा सहनशीलता सीमा (endurance limit) भनेको कुन तनावभन्दा तल सामग्रीले सहन सक्छ?",
            "answers": [
                {"text_en": "Infinite number of stress cycles without failure", "text_np": "विफलता बिना अनन्त तनाव चक्र", "is_correct": True},
                {"text_en": "Exactly 1000 cycles", "text_np": "ठ्याक्कै १००० चक्र", "is_correct": False},
                {"text_en": "Only static loading", "text_np": "स्थैतिक भार मात्र", "is_correct": False},
                {"text_en": "Exactly 10,000 cycles", "text_np": "ठ्याक्कै १०,००० चक्र", "is_correct": False},
            ],
            "explanation_en": "The endurance limit (or fatigue limit) is the maximum stress amplitude below which a material can theoretically endure an infinite number of loading cycles.",
            "explanation_np": "सहनशीलता सीमा (वा थकान सीमा) अधिकतम तनाव आयाम हो जसभन्दा तल सामग्रीले सैद्धान्तिक रूपमा अनन्त भार चक्र सहन सक्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Engineering",
        },
    ],
}
