"""English Language (अंग्रेजी भाषा) — UNIVERSAL category questions."""

QUESTIONS = [
    {
        "question_text_en": "Which of the following is a correct sentence?",
        "question_text_np": "निम्नमध्ये कुन वाक्य सही छ?",
        "answers": [
            {"text_en": "She has been working here since five years.", "text_np": "She has been working here since five years.", "is_correct": False},
            {"text_en": "She has been working here for five years.", "text_np": "She has been working here for five years.", "is_correct": True},
            {"text_en": "She is working here since five years.", "text_np": "She is working here since five years.", "is_correct": False},
            {"text_en": "She was working here for five years ago.", "text_np": "She was working here for five years ago.", "is_correct": False},
        ],
        "explanation_en": "'For' is used with a period/duration of time (five years). 'Since' is used with a point in time (2019, Monday, etc.).",
        "explanation_np": "'For' समयको अवधिसँग (five years) र 'Since' समयको बिन्दुसँग (2019, सोमबार आदि) प्रयोग गरिन्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "Choose the correct synonym of 'Benevolent'.",
        "question_text_np": "'Benevolent' शब्दको सही समानार्थी शब्द छान्नुहोस्।",
        "answers": [
            {"text_en": "Kind", "text_np": "Kind", "is_correct": True},
            {"text_en": "Cruel", "text_np": "Cruel", "is_correct": False},
            {"text_en": "Greedy", "text_np": "Greedy", "is_correct": False},
            {"text_en": "Strict", "text_np": "Strict", "is_correct": False},
        ],
        "explanation_en": "'Benevolent' means well-meaning and kind. Its synonym is 'kind' or 'charitable'. Antonym is 'malevolent'.",
        "explanation_np": "'Benevolent' को अर्थ दयालु र परोपकारी हो। यसको समानार्थी शब्द 'kind' वा 'charitable' हो।",
        "difficulty": "EASY",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "Choose the correct antonym of 'Transparent'.",
        "question_text_np": "'Transparent' शब्दको सही विपरीतार्थी शब्द छान्नुहोस्।",
        "answers": [
            {"text_en": "Opaque", "text_np": "Opaque", "is_correct": True},
            {"text_en": "Clear", "text_np": "Clear", "is_correct": False},
            {"text_en": "Bright", "text_np": "Bright", "is_correct": False},
            {"text_en": "Open", "text_np": "Open", "is_correct": False},
        ],
        "explanation_en": "'Transparent' means see-through or easy to perceive. Its antonym is 'opaque', meaning not able to be seen through.",
        "explanation_np": "'Transparent' को अर्थ पारदर्शी हो। यसको विपरीतार्थी 'opaque' हो, जसको अर्थ अपारदर्शी हो।",
        "difficulty": "EASY",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "Fill in the blank: The manager, along with his team members, _____ present at the meeting.",
        "question_text_np": "खाली ठाउँ भर्नुहोस्: The manager, along with his team members, _____ present at the meeting.",
        "answers": [
            {"text_en": "was", "text_np": "was", "is_correct": True},
            {"text_en": "were", "text_np": "were", "is_correct": False},
            {"text_en": "are", "text_np": "are", "is_correct": False},
            {"text_en": "have been", "text_np": "have been", "is_correct": False},
        ],
        "explanation_en": "When a singular subject is followed by 'along with', 'as well as', or 'together with', the verb agrees with the main subject (manager = singular = 'was').",
        "explanation_np": "जब एकवचन subject पछि 'along with', 'as well as' वा 'together with' आउँछ, verb मुख्य subject (manager = एकवचन = 'was') सँग मिल्नुपर्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "What is the passive voice of: 'The government announced a new policy'?",
        "question_text_np": "'The government announced a new policy' वाक्यको passive voice के हो?",
        "answers": [
            {"text_en": "A new policy was announced by the government.", "text_np": "A new policy was announced by the government.", "is_correct": True},
            {"text_en": "A new policy is announced by the government.", "text_np": "A new policy is announced by the government.", "is_correct": False},
            {"text_en": "A new policy has been announced by the government.", "text_np": "A new policy has been announced by the government.", "is_correct": False},
            {"text_en": "A new policy had been announced by the government.", "text_np": "A new policy had been announced by the government.", "is_correct": False},
        ],
        "explanation_en": "Simple past active (announced) converts to 'was/were + past participle' in passive. Subject becomes object after 'by'.",
        "explanation_np": "Simple past active (announced) passive मा 'was/were + past participle' हुन्छ। Subject 'by' पछि object बन्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "Which of the following words is spelled correctly?",
        "question_text_np": "निम्नमध्ये कुन शब्द सही लेखिएको छ?",
        "answers": [
            {"text_en": "Accommodation", "text_np": "Accommodation", "is_correct": True},
            {"text_en": "Accomodation", "text_np": "Accomodation", "is_correct": False},
            {"text_en": "Acommodation", "text_np": "Acommodation", "is_correct": False},
            {"text_en": "Accomodatoin", "text_np": "Accomodatoin", "is_correct": False},
        ],
        "explanation_en": "'Accommodation' has double 'c' and double 'm'. It is one of the most commonly misspelled English words.",
        "explanation_np": "'Accommodation' मा दोहोरो 'c' र दोहोरो 'm' हुन्छ। यो अंग्रेजीमा सबैभन्दा बढी गलत लेखिने शब्दहरूमध्ये एक हो।",
        "difficulty": "EASY",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "Choose the correct meaning of the idiom: 'Beat around the bush'.",
        "question_text_np": "'Beat around the bush' मुहावराको सही अर्थ छान्नुहोस्।",
        "answers": [
            {"text_en": "To avoid talking about the main topic", "text_np": "मुख्य विषयमा कुरा गर्नबाट जोगिनु", "is_correct": True},
            {"text_en": "To work very hard", "text_np": "धेरै कडा परिश्रम गर्नु", "is_correct": False},
            {"text_en": "To defeat someone easily", "text_np": "कसैलाई सजिलैसँग हराउनु", "is_correct": False},
            {"text_en": "To search for something in a forest", "text_np": "जंगलमा केही खोज्नु", "is_correct": False},
        ],
        "explanation_en": "'Beat around the bush' means to avoid coming to the main point, often by talking about less important things first.",
        "explanation_np": "'Beat around the bush' को अर्थ मुख्य विषयमा आउनु नअघि अन्य कम महत्त्वपूर्ण कुराहरूबारे बोल्दै मुख्य कुरा टाल्नु हो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "Select the correctly punctuated sentence.",
        "question_text_np": "सही विराम चिह्न भएको वाक्य छान्नुहोस्।",
        "answers": [
            {"text_en": "The report, which was submitted late, was rejected.", "text_np": "The report, which was submitted late, was rejected.", "is_correct": True},
            {"text_en": "The report which was submitted late was rejected.", "text_np": "The report which was submitted late was rejected.", "is_correct": False},
            {"text_en": "The report, which was submitted late was rejected.", "text_np": "The report, which was submitted late was rejected.", "is_correct": False},
            {"text_en": "The report which, was submitted late, was rejected.", "text_np": "The report which, was submitted late, was rejected.", "is_correct": False},
        ],
        "explanation_en": "Non-restrictive (non-defining) relative clauses introduced by 'which' must be enclosed in commas on both sides.",
        "explanation_np": "'Which' ले शुरू भएको non-restrictive relative clause दुवै तर्फ अल्पविरामले घेरिएको हुनुपर्छ।",
        "difficulty": "HARD",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "What does the abbreviation 'e.g.' stand for?",
        "question_text_np": "'e.g.' संक्षेपको पूरा रूप के हो?",
        "answers": [
            {"text_en": "Exempli gratia (for example)", "text_np": "Exempli gratia (उदाहरणका लागि)", "is_correct": True},
            {"text_en": "Et cetera (and so on)", "text_np": "Et cetera (र यस्तै)", "is_correct": False},
            {"text_en": "Id est (that is)", "text_np": "Id est (अर्थात्)", "is_correct": False},
            {"text_en": "English grammar", "text_np": "अंग्रेजी व्याकरण", "is_correct": False},
        ],
        "explanation_en": "'e.g.' comes from Latin 'exempli gratia' meaning 'for example'. 'i.e.' means 'that is' (id est), and 'etc.' means 'and so on' (et cetera).",
        "explanation_np": "'e.g.' ल्याटिन 'exempli gratia' बाट आएको हो जसको अर्थ 'उदाहरणका लागि' हो। 'i.e.' को अर्थ 'अर्थात्' र 'etc.' को अर्थ 'र यस्तै' हो।",
        "difficulty": "EASY",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "Choose the word that best completes the sentence: The committee will _____ the proposal at its next meeting.",
        "question_text_np": "वाक्य पूरा गर्ने सबैभन्दा उचित शब्द छान्नुहोस्: The committee will _____ the proposal at its next meeting.",
        "answers": [
            {"text_en": "consider", "text_np": "consider", "is_correct": True},
            {"text_en": "considers", "text_np": "considers", "is_correct": False},
            {"text_en": "considered", "text_np": "considered", "is_correct": False},
            {"text_en": "considering", "text_np": "considering", "is_correct": False},
        ],
        "explanation_en": "After modal verbs (will, shall, can, may, must), the base form of the verb is used without 'to' or '-ing'.",
        "explanation_np": "Modal verbs (will, shall, can, may, must) पछि verb को base form प्रयोग हुन्छ, 'to' वा '-ing' बिना।",
        "difficulty": "EASY",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "Identify the type of sentence: 'What a beautiful morning it is!'",
        "question_text_np": "वाक्यको प्रकार पहिचान गर्नुहोस्: 'What a beautiful morning it is!'",
        "answers": [
            {"text_en": "Exclamatory", "text_np": "विस्मयादिबोधक", "is_correct": True},
            {"text_en": "Interrogative", "text_np": "प्रश्नवाचक", "is_correct": False},
            {"text_en": "Imperative", "text_np": "आज्ञावाचक", "is_correct": False},
            {"text_en": "Declarative", "text_np": "कथनवाचक", "is_correct": False},
        ],
        "explanation_en": "An exclamatory sentence expresses strong emotion and ends with an exclamation mark (!). It often begins with 'What' or 'How'.",
        "explanation_np": "विस्मयादिबोधक वाक्यले तीव्र भावना व्यक्त गर्छ र विस्मयादिबोधक चिह्न (!) ले समाप्त हुन्छ। यो प्रायः 'What' वा 'How' बाट शुरू हुन्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "Which of the following is a collective noun?",
        "question_text_np": "निम्नमध्ये कुन समूहवाचक संज्ञा (collective noun) हो?",
        "answers": [
            {"text_en": "Flock", "text_np": "Flock", "is_correct": True},
            {"text_en": "Running", "text_np": "Running", "is_correct": False},
            {"text_en": "Beautiful", "text_np": "Beautiful", "is_correct": False},
            {"text_en": "Quickly", "text_np": "Quickly", "is_correct": False},
        ],
        "explanation_en": "A collective noun refers to a group of things or people. 'Flock' (a flock of birds/sheep) is a collective noun. 'Running' is a verb/gerund, 'beautiful' is an adjective, 'quickly' is an adverb.",
        "explanation_np": "समूहवाचक संज्ञाले वस्तु वा व्यक्तिहरूको समूहलाई जनाउँछ। 'Flock' (पंछी/भेडाहरूको बथान) समूहवाचक संज्ञा हो।",
        "difficulty": "EASY",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "Choose the correct preposition: She has been working _____ the Ministry of Finance _____ 2018.",
        "question_text_np": "सही preposition छान्नुहोस्: She has been working _____ the Ministry of Finance _____ 2018.",
        "answers": [
            {"text_en": "at / since", "text_np": "at / since", "is_correct": True},
            {"text_en": "in / for", "text_np": "in / for", "is_correct": False},
            {"text_en": "for / since", "text_np": "for / since", "is_correct": False},
            {"text_en": "at / for", "text_np": "at / for", "is_correct": False},
        ],
        "explanation_en": "'At' is used for organizations/institutions. 'Since' is used with a specific point in time (2018). Together: working 'at' an organization 'since' a year.",
        "explanation_np": "'At' संगठन/संस्थाका लागि प्रयोग हुन्छ। 'Since' एउटा निश्चित समय बिन्दु (2018) सँग प्रयोग हुन्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "The word 'Bureaucracy' refers to:",
        "question_text_np": "'Bureaucracy' शब्दले के जनाउँछ?",
        "answers": [
            {"text_en": "A system of government through departments managed by officials", "text_np": "अधिकारीहरूद्वारा सञ्चालित विभागहरूमार्फत सरकारको प्रणाली", "is_correct": True},
            {"text_en": "A type of democratic election system", "text_np": "एक प्रकारको लोकतान्त्रिक निर्वाचन प्रणाली", "is_correct": False},
            {"text_en": "A system of military governance", "text_np": "सैन्य शासनको प्रणाली", "is_correct": False},
            {"text_en": "A judicial review process", "text_np": "न्यायिक पुनरावलोकन प्रक्रिया", "is_correct": False},
        ],
        "explanation_en": "Bureaucracy refers to a system of government where most decisions are made by state officials (bureaucrats) rather than by elected representatives.",
        "explanation_np": "Bureaucracy भनेको सरकारको त्यस्तो प्रणाली हो जहाँ अधिकांश निर्णयहरू निर्वाचित प्रतिनिधिहरूको सट्टा राज्य अधिकारीहरूद्वारा लिइन्छन्।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "Choose the sentence with correct use of articles.",
        "question_text_np": "articles को सही प्रयोग भएको वाक्य छान्नुहोस्।",
        "answers": [
            {"text_en": "He is an honest officer working at the Ministry.", "text_np": "He is an honest officer working at the Ministry.", "is_correct": True},
            {"text_en": "He is a honest officer working at a Ministry.", "text_np": "He is a honest officer working at a Ministry.", "is_correct": False},
            {"text_en": "He is the honest officer working at an Ministry.", "text_np": "He is the honest officer working at an Ministry.", "is_correct": False},
            {"text_en": "He is a honest officer working at the Ministry.", "text_np": "He is a honest officer working at the Ministry.", "is_correct": False},
        ],
        "explanation_en": "'An' is used before words beginning with a vowel sound — 'honest' begins with a silent 'h' so the vowel sound 'o' takes 'an'. 'The' is used before a specific/known noun.",
        "explanation_np": "स्वर ध्वनिले शुरू हुने शब्दहरू अघि 'an' प्रयोग हुन्छ। 'Honest' मा 'h' मौन छ, त्यसैले 'o' ध्वनि आउँछ र 'an' प्रयोग हुन्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "Which tense is used in: 'The officer had already left when the minister arrived'?",
        "question_text_np": "'The officer had already left when the minister arrived' मा कुन tense प्रयोग भएको छ?",
        "answers": [
            {"text_en": "Past Perfect and Simple Past", "text_np": "Past Perfect र Simple Past", "is_correct": True},
            {"text_en": "Simple Past and Past Continuous", "text_np": "Simple Past र Past Continuous", "is_correct": False},
            {"text_en": "Past Perfect and Past Perfect Continuous", "text_np": "Past Perfect र Past Perfect Continuous", "is_correct": False},
            {"text_en": "Simple Past and Present Perfect", "text_np": "Simple Past र Present Perfect", "is_correct": False},
        ],
        "explanation_en": "'Had left' is Past Perfect (action completed before another past action). 'Arrived' is Simple Past. When two past actions occur, the earlier one uses Past Perfect.",
        "explanation_np": "'Had left' Past Perfect हो (अर्को past action भन्दा पहिले सम्पन्न भएको कार्य)। 'Arrived' Simple Past हो। दुई past actions मा पहिलेको Past Perfect हुन्छ।",
        "difficulty": "HARD",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "What is the one-word substitute for 'One who studies the development of mankind'?",
        "question_text_np": "'मानव जातिको विकास अध्ययन गर्ने व्यक्ति' को एक शब्द प्रतिस्थापन के हो?",
        "answers": [
            {"text_en": "Anthropologist", "text_np": "Anthropologist", "is_correct": True},
            {"text_en": "Archaeologist", "text_np": "Archaeologist", "is_correct": False},
            {"text_en": "Sociologist", "text_np": "Sociologist", "is_correct": False},
            {"text_en": "Philologist", "text_np": "Philologist", "is_correct": False},
        ],
        "explanation_en": "An anthropologist studies human societies, cultures, and their development. An archaeologist studies human history through excavation. A sociologist studies society.",
        "explanation_np": "Anthropologist ले मानव समाज, संस्कृति र तिनीहरूको विकास अध्ययन गर्छ। Archaeologist ले उत्खननद्वारा इतिहास र Sociologist ले समाज अध्ययन गर्छ।",
        "difficulty": "HARD",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "Choose the direct speech for: He said that he was going to Kathmandu the next day.",
        "question_text_np": "He said that he was going to Kathmandu the next day — को direct speech छान्नुहोस्।",
        "answers": [
            {"text_en": "He said, \"I am going to Kathmandu tomorrow.\"", "text_np": "He said, \"I am going to Kathmandu tomorrow.\"", "is_correct": True},
            {"text_en": "He said, \"He was going to Kathmandu tomorrow.\"", "text_np": "He said, \"He was going to Kathmandu tomorrow.\"", "is_correct": False},
            {"text_en": "He said, \"I will go to Kathmandu the next day.\"", "text_np": "He said, \"I will go to Kathmandu the next day.\"", "is_correct": False},
            {"text_en": "He said, \"I was going to Kathmandu tomorrow.\"", "text_np": "He said, \"I was going to Kathmandu tomorrow.\"", "is_correct": False},
        ],
        "explanation_en": "Converting indirect to direct speech: 'was going' → 'am going', 'the next day' → 'tomorrow', pronoun 'he' → 'I' (first person).",
        "explanation_np": "Indirect बाट direct speech: 'was going' → 'am going', 'the next day' → 'tomorrow', 'he' → 'I' (first person) हुन्छ।",
        "difficulty": "HARD",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "Which of the following is an example of a compound sentence?",
        "question_text_np": "निम्नमध्ये कुन compound sentence को उदाहरण हो?",
        "answers": [
            {"text_en": "She studied hard, but she could not pass the exam.", "text_np": "She studied hard, but she could not pass the exam.", "is_correct": True},
            {"text_en": "Although she studied hard, she could not pass.", "text_np": "Although she studied hard, she could not pass.", "is_correct": False},
            {"text_en": "She studied hard to pass the exam.", "text_np": "She studied hard to pass the exam.", "is_correct": False},
            {"text_en": "Studying hard, she passed the exam.", "text_np": "Studying hard, she passed the exam.", "is_correct": False},
        ],
        "explanation_en": "A compound sentence has two or more independent clauses joined by coordinating conjunctions (for, and, nor, but, or, yet, so — FANBOYS). 'But' joins two independent clauses here.",
        "explanation_np": "Compound sentence मा दुई वा सोभन्दा बढी independent clauses coordinating conjunctions (FANBOYS: for, and, nor, but, or, yet, so) ले जोडिएका हुन्छन्।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "What is the meaning of the phrase 'prima facie'?",
        "question_text_np": "'prima facie' वाक्यांशको अर्थ के हो?",
        "answers": [
            {"text_en": "At first glance / on the face of it", "text_np": "पहिलो दृष्टिमा / देखिएअनुसार", "is_correct": True},
            {"text_en": "Final verdict", "text_np": "अन्तिम फैसला", "is_correct": False},
            {"text_en": "By legal authority", "text_np": "कानुनी अधिकारद्वारा", "is_correct": False},
            {"text_en": "After thorough investigation", "text_np": "गहन अनुसन्धानपछि", "is_correct": False},
        ],
        "explanation_en": "'Prima facie' is a Latin term used in law meaning 'at first sight' or 'based on first impression'. A prima facie case is one that appears valid without in-depth investigation.",
        "explanation_np": "'Prima facie' ल्याटिन कानुनी शब्द हो जसको अर्थ 'पहिलो दृष्टिमा' वा 'पहिलो छापमा आधारित' हो। यो शब्द कानुनमा र लोक सेवा परीक्षामा प्रयोग हुन्छ।",
        "difficulty": "HARD",
        "source_reference": "PSC English Language",
    },
    {
        "question_text_en": "Choose the correct indirect speech for: The teacher said, \"Work hard and you will succeed.\"",
        "question_text_np": "The teacher said, \"Work hard and you will succeed.\" को सही indirect speech छान्नुहोस्।",
        "answers": [
            {"text_en": "The teacher advised to work hard and said that they would succeed.", "text_np": "The teacher advised to work hard and said that they would succeed.", "is_correct": True},
            {"text_en": "The teacher said that work hard and they will succeed.", "text_np": "The teacher said that work hard and they will succeed.", "is_correct": False},
            {"text_en": "The teacher told to work hard and will succeed.", "text_np": "The teacher told to work hard and will succeed.", "is_correct": False},
            {"text_en": "The teacher advised work hard or you will succeed.", "text_np": "The teacher advised work hard or you will succeed.", "is_correct": False},
        ],
        "explanation_en": "Imperative sentences in indirect speech use 'advised/told/ordered + to + infinitive'. 'Will' changes to 'would' in reported speech.",
        "explanation_np": "Imperative वाक्यको indirect speech मा 'advised/told/ordered + to + infinitive' प्रयोग हुन्छ। 'Will' reported speech मा 'would' हुन्छ।",
        "difficulty": "HARD",
        "source_reference": "PSC English Language",
    },
]