"""General Knowledge (सामान्य ज्ञान) — UNIVERSAL category questions."""

QUESTIONS = [
    {
        "question_text_en": "Who was the first President of Nepal?",
        "question_text_np": "नेपालको पहिलो राष्ट्रपति को हुन्?",
        "answers": [
            {"text_en": "Ram Baran Yadav", "text_np": "रामवरण यादव", "is_correct": True},
            {"text_en": "Bidya Devi Bhandari", "text_np": "विद्यादेवी भण्डारी", "is_correct": False},
            {"text_en": "KP Sharma Oli", "text_np": "केपी शर्मा ओली", "is_correct": False},
            {"text_en": "Girija Prasad Koirala", "text_np": "गिरिजाप्रसाद कोइराला", "is_correct": False},
        ],
        "explanation_en": "Dr. Ram Baran Yadav was elected as the first President of Nepal on July 23, 2008 by the Constituent Assembly.",
        "explanation_np": "डा. रामवरण यादव सन् २००८ जुलाई २३ मा संविधानसभाबाट नेपालको पहिलो राष्ट्रपतिमा निर्वाचित भए।",
        "difficulty": "EASY",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "How many provinces does Nepal currently have?",
        "question_text_np": "नेपालमा हाल कतिवटा प्रदेश छन्?",
        "answers": [
            {"text_en": "7", "text_np": "७", "is_correct": True},
            {"text_en": "5", "text_np": "५", "is_correct": False},
            {"text_en": "14", "text_np": "१४", "is_correct": False},
            {"text_en": "9", "text_np": "९", "is_correct": False},
        ],
        "explanation_en": "Nepal is divided into 7 provinces as per the Constitution of Nepal 2072.",
        "explanation_np": "नेपालको संविधान २०७२ अनुसार नेपाललाई ७ प्रदेशमा विभाजन गरिएको छ।",
        "difficulty": "EASY",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "What is the total number of districts in Nepal?",
        "question_text_np": "नेपालमा जम्मा कतिवटा जिल्ला छन्?",
        "answers": [
            {"text_en": "77", "text_np": "७७", "is_correct": True},
            {"text_en": "75", "text_np": "७५", "is_correct": False},
            {"text_en": "80", "text_np": "८०", "is_correct": False},
            {"text_en": "72", "text_np": "७२", "is_correct": False},
        ],
        "explanation_en": "Nepal has 77 districts distributed across 7 provinces.",
        "explanation_np": "नेपालमा ७ प्रदेशमा वितरित ७७ वटा जिल्ला छन्।",
        "difficulty": "EASY",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "Which is the highest peak in the world?",
        "question_text_np": "संसारको सबैभन्दा अग्लो चुचुरो कुन हो?",
        "answers": [
            {"text_en": "Mount Everest (Sagarmatha)", "text_np": "सगरमाथा", "is_correct": True},
            {"text_en": "K2", "text_np": "के-२", "is_correct": False},
            {"text_en": "Kangchenjunga", "text_np": "कञ्चनजङ्घा", "is_correct": False},
            {"text_en": "Makalu", "text_np": "मकालु", "is_correct": False},
        ],
        "explanation_en": "Mount Everest (Sagarmatha) at 8,848.86m is the highest peak in the world, located in Nepal.",
        "explanation_np": "सगरमाथा ८,८४८.८६ मिटर उचाइमा संसारको सबैभन्दा अग्लो चुचुरो हो, जुन नेपालमा अवस्थित छ।",
        "difficulty": "EASY",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "What is the national animal of Nepal?",
        "question_text_np": "नेपालको राष्ट्रिय पशु कुन हो?",
        "answers": [
            {"text_en": "Cow", "text_np": "गाई", "is_correct": True},
            {"text_en": "Tiger", "text_np": "बाघ", "is_correct": False},
            {"text_en": "Elephant", "text_np": "हात्ती", "is_correct": False},
            {"text_en": "One-horned Rhinoceros", "text_np": "एकसिँगे गैंडा", "is_correct": False},
        ],
        "explanation_en": "The cow is the national animal of Nepal.",
        "explanation_np": "गाई नेपालको राष्ट्रिय पशु हो।",
        "difficulty": "EASY",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "What is the national flower of Nepal?",
        "question_text_np": "नेपालको राष्ट्रिय फूल कुन हो?",
        "answers": [
            {"text_en": "Rhododendron (Lali Gurans)", "text_np": "लालीगुराँस", "is_correct": True},
            {"text_en": "Lotus", "text_np": "कमल", "is_correct": False},
            {"text_en": "Jasmine", "text_np": "चमेली", "is_correct": False},
            {"text_en": "Sunflower", "text_np": "सूर्यमुखी", "is_correct": False},
        ],
        "explanation_en": "Rhododendron (Lali Gurans) is the national flower of Nepal.",
        "explanation_np": "लालीगुराँस नेपालको राष्ट्रिय फूल हो।",
        "difficulty": "EASY",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "Which organization is responsible for conducting civil service examinations in Nepal?",
        "question_text_np": "नेपालमा निजामती सेवाको परीक्षा सञ्चालन गर्ने निकाय कुन हो?",
        "answers": [
            {"text_en": "Public Service Commission (Lok Sewa Aayog)", "text_np": "लोक सेवा आयोग", "is_correct": True},
            {"text_en": "Election Commission", "text_np": "निर्वाचन आयोग", "is_correct": False},
            {"text_en": "National Planning Commission", "text_np": "राष्ट्रिय योजना आयोग", "is_correct": False},
            {"text_en": "Ministry of General Administration", "text_np": "सामान्य प्रशासन मन्त्रालय", "is_correct": False},
        ],
        "explanation_en": "The Public Service Commission (Lok Sewa Aayog) is the constitutional body responsible for conducting examinations for civil service positions in Nepal.",
        "explanation_np": "लोक सेवा आयोग नेपालमा निजामती सेवाको पद पूर्तिका लागि परीक्षा सञ्चालन गर्ने संवैधानिक निकाय हो।",
        "difficulty": "EASY",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "What is the currency of Nepal?",
        "question_text_np": "नेपालको मुद्रा कुन हो?",
        "answers": [
            {"text_en": "Nepalese Rupee (NPR)", "text_np": "नेपाली रुपैयाँ", "is_correct": True},
            {"text_en": "Indian Rupee", "text_np": "भारतीय रुपैयाँ", "is_correct": False},
            {"text_en": "US Dollar", "text_np": "अमेरिकी डलर", "is_correct": False},
            {"text_en": "Taka", "text_np": "टका", "is_correct": False},
        ],
        "explanation_en": "The official currency of Nepal is the Nepalese Rupee (NPR), issued by Nepal Rastra Bank.",
        "explanation_np": "नेपालको आधिकारिक मुद्रा नेपाली रुपैयाँ (NPR) हो, जुन नेपाल राष्ट्र बैंकले जारी गर्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "The headquarter of SAARC is located in which city?",
        "question_text_np": "सार्कको मुख्यालय कुन शहरमा अवस्थित छ?",
        "answers": [
            {"text_en": "Kathmandu", "text_np": "काठमाडौं", "is_correct": True},
            {"text_en": "New Delhi", "text_np": "नयाँ दिल्ली", "is_correct": False},
            {"text_en": "Colombo", "text_np": "कोलम्बो", "is_correct": False},
            {"text_en": "Dhaka", "text_np": "ढाका", "is_correct": False},
        ],
        "explanation_en": "The SAARC Secretariat is permanently located in Kathmandu, Nepal since 1987.",
        "explanation_np": "सार्क सचिवालय सन् १९८७ देखि काठमाडौं, नेपालमा स्थायी रूपमा अवस्थित छ।",
        "difficulty": "EASY",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "Which country borders Nepal to the north?",
        "question_text_np": "नेपालको उत्तरमा कुन देश छ?",
        "answers": [
            {"text_en": "China (Tibet Autonomous Region)", "text_np": "चीन (तिब्बत स्वायत्त क्षेत्र)", "is_correct": True},
            {"text_en": "India", "text_np": "भारत", "is_correct": False},
            {"text_en": "Bhutan", "text_np": "भुटान", "is_correct": False},
            {"text_en": "Bangladesh", "text_np": "बंगलादेश", "is_correct": False},
        ],
        "explanation_en": "Nepal is bordered by China (Tibet Autonomous Region) to the north and India to the south, east, and west.",
        "explanation_np": "नेपालको उत्तरमा चीन (तिब्बत स्वायत्त क्षेत्र) र दक्षिण, पूर्व र पश्चिममा भारत छ।",
        "difficulty": "EASY",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "When was Nepal declared a Federal Democratic Republic?",
        "question_text_np": "नेपाललाई संघीय लोकतान्त्रिक गणतन्त्र घोषणा कहिले गरिएको थियो?",
        "answers": [
            {"text_en": "May 28, 2008 (Jestha 15, 2065 BS)", "text_np": "जेठ १५, २०६५ (मे २८, २००८)", "is_correct": True},
            {"text_en": "September 20, 2015", "text_np": "सेप्टेम्बर २०, २०१५", "is_correct": False},
            {"text_en": "April 24, 2006", "text_np": "अप्रिल २४, २००६", "is_correct": False},
            {"text_en": "November 21, 2006", "text_np": "नोभेम्बर २१, २००६", "is_correct": False},
        ],
        "explanation_en": "Nepal was declared a Federal Democratic Republic on May 28, 2008 (Jestha 15, 2065 BS) by the first meeting of the Constituent Assembly.",
        "explanation_np": "संविधानसभाको पहिलो बैठकले जेठ १५, २०६५ (मे २८, २००८) मा नेपाललाई संघीय लोकतान्त्रिक गणतन्त्र घोषणा गर्यो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "Which is the largest lake of Nepal?",
        "question_text_np": "नेपालको सबैभन्दा ठूलो ताल कुन हो?",
        "answers": [
            {"text_en": "Rara Lake", "text_np": "रारा ताल", "is_correct": True},
            {"text_en": "Phewa Lake", "text_np": "फेवा ताल", "is_correct": False},
            {"text_en": "Tilicho Lake", "text_np": "तिलिचो ताल", "is_correct": False},
            {"text_en": "Begnas Lake", "text_np": "बेगनास ताल", "is_correct": False},
        ],
        "explanation_en": "Rara Lake in Mugu district is the largest lake of Nepal with an area of 10.8 sq km.",
        "explanation_np": "मुगु जिल्लामा रहेको रारा ताल १०.८ वर्ग कि.मी. क्षेत्रफलमा नेपालको सबैभन्दा ठूलो ताल हो।",
        "difficulty": "EASY",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "What is the total area of Nepal?",
        "question_text_np": "नेपालको कुल क्षेत्रफल कति छ?",
        "answers": [
            {"text_en": "1,47,516 sq km", "text_np": "१,४७,५१६ वर्ग कि.मी.", "is_correct": True},
            {"text_en": "1,35,000 sq km", "text_np": "१,३५,००० वर्ग कि.मी.", "is_correct": False},
            {"text_en": "1,50,000 sq km", "text_np": "१,५०,००० वर्ग कि.मी.", "is_correct": False},
            {"text_en": "1,42,000 sq km", "text_np": "१,४२,००० वर्ग कि.मी.", "is_correct": False},
        ],
        "explanation_en": "The total area of Nepal is 1,47,516 square kilometers.",
        "explanation_np": "नेपालको कुल क्षेत्रफल १,४७,५१६ वर्ग किलोमिटर छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "Nepal Rastra Bank was established in which year (BS)?",
        "question_text_np": "नेपाल राष्ट्र बैंक कुन सालमा स्थापना भएको थियो?",
        "answers": [
            {"text_en": "2013 BS (1956 AD)", "text_np": "२०१३ साल (१९५६ ई.)", "is_correct": True},
            {"text_en": "2007 BS", "text_np": "२००७ साल", "is_correct": False},
            {"text_en": "2020 BS", "text_np": "२०२० साल", "is_correct": False},
            {"text_en": "2015 BS", "text_np": "२०१५ साल", "is_correct": False},
        ],
        "explanation_en": "Nepal Rastra Bank, the central bank of Nepal, was established on Baisakh 14, 2013 BS (April 26, 1956 AD).",
        "explanation_np": "नेपालको केन्द्रीय बैंक नेपाल राष्ट्र बैंक वैशाख १४, २०१३ सालमा स्थापना भएको थियो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "Which is the national bird of Nepal?",
        "question_text_np": "नेपालको राष्ट्रिय चरा कुन हो?",
        "answers": [
            {"text_en": "Danphe (Himalayan Monal)", "text_np": "डाँफे (हिमाली मोनाल)", "is_correct": True},
            {"text_en": "Crow", "text_np": "काग", "is_correct": False},
            {"text_en": "Eagle", "text_np": "चील", "is_correct": False},
            {"text_en": "Spiny Babbler", "text_np": "काँडे भ्याकुर", "is_correct": False},
        ],
        "explanation_en": "Danphe (Himalayan Monal / Lophophorus impejanus) is the national bird of Nepal.",
        "explanation_np": "डाँफे (हिमाली मोनाल) नेपालको राष्ट्रिय चरा हो।",
        "difficulty": "EASY",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "Lumbini, the birthplace of Lord Buddha, is located in which province of Nepal?",
        "question_text_np": "भगवान बुद्धको जन्मस्थान लुम्बिनी नेपालको कुन प्रदेशमा अवस्थित छ?",
        "answers": [
            {"text_en": "Lumbini Province", "text_np": "लुम्बिनी प्रदेश", "is_correct": True},
            {"text_en": "Bagmati Province", "text_np": "बागमती प्रदेश", "is_correct": False},
            {"text_en": "Gandaki Province", "text_np": "गण्डकी प्रदेश", "is_correct": False},
            {"text_en": "Madhesh Province", "text_np": "मधेश प्रदेश", "is_correct": False},
        ],
        "explanation_en": "Lumbini, the birthplace of Gautam Buddha, is in Rupandehi district of Lumbini Province and is a UNESCO World Heritage Site.",
        "explanation_np": "गौतम बुद्धको जन्मस्थान लुम्बिनी लुम्बिनी प्रदेशको रूपन्देही जिल्लामा छ र यो युनेस्को विश्व सम्पदा सूचीमा सूचीकृत छ।",
        "difficulty": "EASY",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "Which river system is the largest in Nepal?",
        "question_text_np": "नेपालको सबैभन्दा ठूलो नदी प्रणाली कुन हो?",
        "answers": [
            {"text_en": "Koshi River System", "text_np": "कोशी नदी प्रणाली", "is_correct": True},
            {"text_en": "Gandaki River System", "text_np": "गण्डकी नदी प्रणाली", "is_correct": False},
            {"text_en": "Karnali River System", "text_np": "कर्णाली नदी प्रणाली", "is_correct": False},
            {"text_en": "Mahakali River System", "text_np": "महाकाली नदी प्रणाली", "is_correct": False},
        ],
        "explanation_en": "The Koshi River System is the largest river system in Nepal, draining the eastern part of the country.",
        "explanation_np": "कोशी नदी प्रणाली नेपालको सबैभन्दा ठूलो नदी प्रणाली हो, जसले देशको पूर्वी भाग जलनिकास गर्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "What is the literacy rate of Nepal according to the Census 2078 BS?",
        "question_text_np": "जनगणना २०७८ अनुसार नेपालको साक्षरता दर कति छ?",
        "answers": [
            {"text_en": "76.3%", "text_np": "७६.३%", "is_correct": True},
            {"text_en": "65.9%", "text_np": "६५.९%", "is_correct": False},
            {"text_en": "82.1%", "text_np": "८२.१%", "is_correct": False},
            {"text_en": "70.5%", "text_np": "७०.५%", "is_correct": False},
        ],
        "explanation_en": "According to the National Population and Housing Census 2078 (2021), Nepal's literacy rate is 76.3%.",
        "explanation_np": "राष्ट्रिय जनगणना २०७८ अनुसार नेपालको साक्षरता दर ७६.३% छ।",
        "difficulty": "HARD",
        "source_reference": "PSC General Knowledge - Census 2078",
    },
    {
        "question_text_en": "Which of the following is NOT a UNESCO World Heritage Site in Nepal?",
        "question_text_np": "तलका मध्ये कुन नेपालको युनेस्को विश्व सम्पदा सूचीमा पर्दैन?",
        "answers": [
            {"text_en": "Rara Lake", "text_np": "रारा ताल", "is_correct": True},
            {"text_en": "Lumbini", "text_np": "लुम्बिनी", "is_correct": False},
            {"text_en": "Chitwan National Park", "text_np": "चितवन राष्ट्रिय निकुञ्ज", "is_correct": False},
            {"text_en": "Sagarmatha National Park", "text_np": "सगरमाथा राष्ट्रिय निकुञ्ज", "is_correct": False},
        ],
        "explanation_en": "Rara Lake is not a UNESCO World Heritage Site. Nepal has 4 UNESCO World Heritage Sites: Lumbini, Kathmandu Valley (7 monument zones), Chitwan National Park, and Sagarmatha National Park.",
        "explanation_np": "रारा ताल युनेस्को विश्व सम्पदा सूचीमा पर्दैन। नेपालमा ४ वटा युनेस्को विश्व सम्पदा स्थलहरू छन्।",
        "difficulty": "HARD",
        "source_reference": "PSC General Knowledge",
    },
    {
        "question_text_en": "The Sugauli Treaty was signed between Nepal and which country?",
        "question_text_np": "सुगौली सन्धि नेपाल र कुन देशबीच भएको थियो?",
        "answers": [
            {"text_en": "British East India Company", "text_np": "ब्रिटिश ईस्ट इन्डिया कम्पनी", "is_correct": True},
            {"text_en": "China", "text_np": "चीन", "is_correct": False},
            {"text_en": "Tibet", "text_np": "तिब्बत", "is_correct": False},
            {"text_en": "France", "text_np": "फ्रान्स", "is_correct": False},
        ],
        "explanation_en": "The Sugauli Treaty was signed on December 2, 1815 between Nepal and the British East India Company after the Anglo-Nepalese War.",
        "explanation_np": "सुगौली सन्धि डिसेम्बर २, १८१५ मा नेपाल र ब्रिटिश ईस्ट इन्डिया कम्पनीबीच अंग्रेज-नेपाल युद्धपछि भएको थियो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC General Knowledge",
    },
]
