"""Geography of Nepal (नेपालको भूगोल) — UNIVERSAL category questions."""

QUESTIONS = [
    {
        "question_text_en": "How many provinces does Nepal have?",
        "question_text_np": "नेपालमा कतिवटा प्रदेशहरू छन्?",
        "answers": [
            {"text_en": "7", "text_np": "७", "is_correct": True},
            {"text_en": "5", "text_np": "५", "is_correct": False},
            {"text_en": "6", "text_np": "६", "is_correct": False},
            {"text_en": "8", "text_np": "८", "is_correct": False},
        ],
        "explanation_en": "Nepal was divided into 7 provinces under the 2015 Constitution (Constitution of Nepal 2072 B.S.). The provinces were renamed in 2020.",
        "explanation_np": "नेपाललाई २०७२ को संविधान अनुसार ७ प्रदेशमा विभाजन गरिएको छ। प्रदेशहरूलाई सन् २०२० मा नाम दिइएको थियो।",
        "difficulty": "EASY",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "What is the total area of Nepal?",
        "question_text_np": "नेपालको कुल क्षेत्रफल कति हो?",
        "answers": [
            {"text_en": "147,181 sq km", "text_np": "१,४७,१८१ वर्ग किमि", "is_correct": True},
            {"text_en": "140,000 sq km", "text_np": "१,४०,००० वर्ग किमि", "is_correct": False},
            {"text_en": "152,000 sq km", "text_np": "१,५२,००० वर्ग किमि", "is_correct": False},
            {"text_en": "160,000 sq km", "text_np": "१,६०,००० वर्ग किमि", "is_correct": False},
        ],
        "explanation_en": "Nepal covers a total area of 147,181 square kilometers, making it the 93rd largest country in the world.",
        "explanation_np": "नेपालको कुल क्षेत्रफल १,४७,१८१ वर्ग किलोमिटर छ, जसले यसलाई विश्वको ९३ औं ठूलो देश बनाउँछ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "Mount Everest, the world's highest peak, is located in which district of Nepal?",
        "question_text_np": "विश्वको सबैभन्दा अग्लो शिखर माउन्ट एभरेस्ट नेपालको कुन जिल्लामा अवस्थित छ?",
        "answers": [
            {"text_en": "Solukhumbu", "text_np": "सोलुखुम्बु", "is_correct": True},
            {"text_en": "Dolakha", "text_np": "दोलखा", "is_correct": False},
            {"text_en": "Rasuwa", "text_np": "रसुवा", "is_correct": False},
            {"text_en": "Taplejung", "text_np": "ताप्लेजुङ", "is_correct": False},
        ],
        "explanation_en": "Mount Everest (8,848.86 m) is located in the Solukhumbu district of Koshi Province, Nepal. It is known as Sagarmatha (सगरमाथा) in Nepali.",
        "explanation_np": "माउन्ट एभरेस्ट (८,८४८.८६ मि.) नेपालको कोशी प्रदेशको सोलुखुम्बु जिल्लामा अवस्थित छ। नेपालीमा यसलाई सगरमाथा भनिन्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "How many districts does Nepal have?",
        "question_text_np": "नेपालमा कतिवटा जिल्लाहरू छन्?",
        "answers": [
            {"text_en": "77", "text_np": "७७", "is_correct": True},
            {"text_en": "75", "text_np": "७५", "is_correct": False},
            {"text_en": "80", "text_np": "८०", "is_correct": False},
            {"text_en": "70", "text_np": "७०", "is_correct": False},
        ],
        "explanation_en": "Nepal has 77 districts (जिल्लाहरू). Two new districts — Nawalpur and Madhesh/Sarlahi — were added from the former Nawalparasi and Mahottari districts.",
        "explanation_np": "नेपालमा ७७ जिल्लाहरू छन्। नवलपुर र मधेश/सर्लाही — यी दुई नयाँ जिल्लाहरू थपिएका थिए।",
        "difficulty": "EASY",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "Which is the largest district by area in Nepal?",
        "question_text_np": "क्षेत्रफलको हिसाबले नेपालको सबैभन्दा ठूलो जिल्ला कुन हो?",
        "answers": [
            {"text_en": "Dolpa", "text_np": "डोल्पा", "is_correct": True},
            {"text_en": "Humla", "text_np": "हुम्ला", "is_correct": False},
            {"text_en": "Taplejung", "text_np": "ताप्लेजुङ", "is_correct": False},
            {"text_en": "Kalikot", "text_np": "कालिकोट", "is_correct": False},
        ],
        "explanation_en": "Dolpa is the largest district in Nepal by area (7,889 sq km). Humla is the second largest. Kathmandu, despite being the capital, is one of the smallest districts.",
        "explanation_np": "डोल्पा क्षेत्रफलको हिसाबले नेपालको सबैभन्दा ठूलो जिल्ला हो (७,८८९ वर्ग किमि)। हुम्ला दोस्रो ठूलो हो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "Which river is known as the longest river originating from Nepal?",
        "question_text_np": "नेपालबाट उत्पत्ति भएको सबैभन्दा लामो नदी कुन हो?",
        "answers": [
            {"text_en": "Karnali", "text_np": "कर्णाली", "is_correct": True},
            {"text_en": "Koshi", "text_np": "कोशी", "is_correct": False},
            {"text_en": "Gandaki", "text_np": "गण्डकी", "is_correct": False},
            {"text_en": "Saptakoshi", "text_np": "सप्तकोशी", "is_correct": False},
        ],
        "explanation_en": "The Karnali River is the longest river originating from Nepal. It originates from Tibet and flows through Humla, eventually joining the Ganges (as the Ghaghra) in India.",
        "explanation_np": "कर्णाली नेपालबाट उत्पत्ति भएको सबैभन्दा लामो नदी हो। यो तिब्बतबाट उत्पत्ति भई हुम्लाबाट बग्छ र भारतमा गंगामा (घाघरा नाममा) मिसिन्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "The Terai region of Nepal lies at what approximate altitude range?",
        "question_text_np": "नेपालको तराई क्षेत्र कस्तो अनुमानित उचाइ दायरामा अवस्थित छ?",
        "answers": [
            {"text_en": "60 to 330 metres", "text_np": "६० देखि ३३० मिटर", "is_correct": True},
            {"text_en": "1000 to 2000 metres", "text_np": "१,००० देखि २,००० मिटर", "is_correct": False},
            {"text_en": "330 to 1000 metres", "text_np": "३३० देखि १,००० मिटर", "is_correct": False},
            {"text_en": "Below 60 metres", "text_np": "६० मिटरभन्दा तल", "is_correct": False},
        ],
        "explanation_en": "The Terai (Plains) region lies at approximately 60–330 metres above sea level. It is the most fertile region and most densely populated part of Nepal.",
        "explanation_np": "तराई (मैदान) क्षेत्र समुद्र सतहबाट लगभग ६०–३३० मिटरमा अवस्थित छ। यो नेपालको सबैभन्दा उर्वर र घनाइ बस्ती भएको क्षेत्र हो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "Which country shares the longest border with Nepal?",
        "question_text_np": "कुन देशसँग नेपालको सबैभन्दा लामो सिमाना छ?",
        "answers": [
            {"text_en": "India", "text_np": "भारत", "is_correct": True},
            {"text_en": "China", "text_np": "चीन", "is_correct": False},
            {"text_en": "Both equally", "text_np": "दुवैसँग समान", "is_correct": False},
            {"text_en": "Nepal has no border with China", "text_np": "नेपालको चीनसँग सिमाना छैन", "is_correct": False},
        ],
        "explanation_en": "Nepal shares a border of approximately 1,850 km with India (south, east, and west) and approximately 1,414 km with China (north). India has the longer border.",
        "explanation_np": "नेपालले भारतसँग लगभग १,८५० किमि (दक्षिण, पूर्व र पश्चिम) र चीनसँग लगभग १,४१४ किमि (उत्तर) सिमाना साझा गर्छ। भारतसँग लामो सिमाना छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "The Rara Lake, the largest lake in Nepal, is located in which district?",
        "question_text_np": "नेपालको सबैभन्दा ठूलो ताल रारा ताल कुन जिल्लामा अवस्थित छ?",
        "answers": [
            {"text_en": "Mugu", "text_np": "मुगु", "is_correct": True},
            {"text_en": "Humla", "text_np": "हुम्ला", "is_correct": False},
            {"text_en": "Jumla", "text_np": "जुम्ला", "is_correct": False},
            {"text_en": "Dolpa", "text_np": "डोल्पा", "is_correct": False},
        ],
        "explanation_en": "Rara Lake is located in Mugu district of Karnali Province at an altitude of 2,990 metres. It is the largest lake in Nepal with an area of 10.8 sq km.",
        "explanation_np": "रारा ताल कर्णाली प्रदेशको मुगु जिल्लामा २,९९० मिटरको उचाइमा अवस्थित छ। यो १०.८ वर्ग किमि क्षेत्रफलसहित नेपालको सबैभन्दा ठूलो ताल हो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "Which is the smallest district by area in Nepal?",
        "question_text_np": "क्षेत्रफलको हिसाबले नेपालको सबैभन्दा साना जिल्ला कुन हो?",
        "answers": [
            {"text_en": "Bhaktapur", "text_np": "भक्तपुर", "is_correct": True},
            {"text_en": "Kathmandu", "text_np": "काठमाडौं", "is_correct": False},
            {"text_en": "Lalitpur", "text_np": "ललितपुर", "is_correct": False},
            {"text_en": "Arghakhanchi", "text_np": "अर्घाखाँची", "is_correct": False},
        ],
        "explanation_en": "Bhaktapur is the smallest district in Nepal by area (119 sq km). It is located in Bagmati Province in the Kathmandu Valley.",
        "explanation_np": "भक्तपुर क्षेत्रफलको हिसाबले नेपालको सबैभन्दा साना जिल्ला हो (११९ वर्ग किमि)। यो काठमाडौं उपत्यकामा बागमती प्रदेशमा अवस्थित छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "Which mountain range separates Nepal's Terai from the Hill region?",
        "question_text_np": "कुन पर्वत श्रृंखलाले नेपालको तराई र पहाडी क्षेत्रलाई छुट्याउँछ?",
        "answers": [
            {"text_en": "Chure/Siwalik Range", "text_np": "चुरे/शिवालिक श्रृंखला", "is_correct": True},
            {"text_en": "Mahabharat Range", "text_np": "महाभारत श्रृंखला", "is_correct": False},
            {"text_en": "Himalayan Range", "text_np": "हिमालयन श्रृंखला", "is_correct": False},
            {"text_en": "Dhaulagiri Range", "text_np": "धौलागिरी श्रृंखला", "is_correct": False},
        ],
        "explanation_en": "The Chure (Siwalik) Range, the youngest and lowest Himalayan range, separates the Terai plains from the Midhills. The Mahabharat Range separates the Midhills from the High Himalayas.",
        "explanation_np": "चुरे (शिवालिक) श्रृंखला, जो सबैभन्दा कान्छो र सबैभन्दा होचो हिमालयन श्रृंखला हो, तराई मैदानलाई मध्य पहाडबाट छुट्याउँछ। महाभारत श्रृंखलाले मध्य पहाडलाई उच्च हिमालयबाट छुट्याउँछ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "The Kathmandu Valley is situated in which river basin?",
        "question_text_np": "काठमाडौं उपत्यका कुन नदी बेसिनमा अवस्थित छ?",
        "answers": [
            {"text_en": "Bagmati River Basin", "text_np": "बागमती नदी बेसिन", "is_correct": True},
            {"text_en": "Koshi River Basin", "text_np": "कोशी नदी बेसिन", "is_correct": False},
            {"text_en": "Gandaki River Basin", "text_np": "गण्डकी नदी बेसिन", "is_correct": False},
            {"text_en": "Karnali River Basin", "text_np": "कर्णाली नदी बेसिन", "is_correct": False},
        ],
        "explanation_en": "The Kathmandu Valley lies in the Bagmati River Basin. The Bagmati River originates from Shivapuri Hill and flows through the valley before joining the Koshi system.",
        "explanation_np": "काठमाडौं उपत्यका बागमती नदी बेसिनमा अवस्थित छ। बागमती शिवपुरी पहाडबाट उत्पत्ति हुन्छ र उपत्यकाबाट बगेर कोशी प्रणालीमा मिसिन्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "Which province of Nepal is landlocked and has no international border?",
        "question_text_np": "नेपालको कुन प्रदेश चारैतर्फ भूमिले घेरिएको छ र कुनै अन्तर्राष्ट्रिय सिमाना छैन?",
        "answers": [
            {"text_en": "Bagmati Province", "text_np": "बागमती प्रदेश", "is_correct": True},
            {"text_en": "Koshi Province", "text_np": "कोशी प्रदेश", "is_correct": False},
            {"text_en": "Gandaki Province", "text_np": "गण्डकी प्रदेश", "is_correct": False},
            {"text_en": "Lumbini Province", "text_np": "लुम्बिनी प्रदेश", "is_correct": False},
        ],
        "explanation_en": "Bagmati Province (Province No. 3) is the only province that does not share an international border — it is surrounded by other Nepali provinces. It contains the national capital Kathmandu.",
        "explanation_np": "बागमती प्रदेश (प्रदेश नं. ३) मात्र यस्तो प्रदेश हो जसको कुनै अन्तर्राष्ट्रिय सिमाना छैन — यो अन्य नेपाली प्रदेशहरूले घेरिएको छ। यसमा राष्ट्रिय राजधानी काठमाडौं पर्छ।",
        "difficulty": "HARD",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "How many of Nepal's peaks are above 8,000 metres?",
        "question_text_np": "नेपालमा ८,००० मिटरभन्दा अग्ला कतिवटा शिखरहरू छन्?",
        "answers": [
            {"text_en": "8", "text_np": "८", "is_correct": True},
            {"text_en": "6", "text_np": "६", "is_correct": False},
            {"text_en": "10", "text_np": "१०", "is_correct": False},
            {"text_en": "5", "text_np": "५", "is_correct": False},
        ],
        "explanation_en": "Nepal has 8 of the world's 14 peaks above 8,000 metres: Everest, Kangchenjunga, Lhotse, Makalu, Cho Oyu, Dhaulagiri, Manaslu, and Annapurna I.",
        "explanation_np": "नेपालमा विश्वका ८,०००मि.भन्दा अग्ला १४ शिखरहरूमध्ये ८ वटा छन्: एभरेस्ट, कञ्चनजंघा, ल्होत्से, मकालु, चो ओयु, धौलागिरी, मनास्लु र अन्नपूर्ण I।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "The Phewa Lake (Fewa Tal) is located in which city?",
        "question_text_np": "फेवा ताल कुन शहरमा अवस्थित छ?",
        "answers": [
            {"text_en": "Pokhara", "text_np": "पोखरा", "is_correct": True},
            {"text_en": "Kathmandu", "text_np": "काठमाडौं", "is_correct": False},
            {"text_en": "Biratnagar", "text_np": "विराटनगर", "is_correct": False},
            {"text_en": "Dharan", "text_np": "धरान", "is_correct": False},
        ],
        "explanation_en": "Phewa Lake (Fewa Tal) is a freshwater lake located in Pokhara, Gandaki Province. It is the second largest lake in Nepal and is famous for its reflection of Mt. Machhapuchhre (Fishtail).",
        "explanation_np": "फेवा ताल गण्डकी प्रदेशको पोखरामा अवस्थित एउटा मिठापानीको ताल हो। यो नेपालको दोस्रो ठूलो ताल हो र माछापुच्छ्रे पर्वतको प्रतिविम्बका लागि प्रसिद्ध छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "Which of Nepal's three physiographic zones covers the most area?",
        "question_text_np": "नेपालको तीन भौगोलिक क्षेत्रहरूमध्ये कुनले सबैभन्दा बढी क्षेत्रफल ओगटेको छ?",
        "answers": [
            {"text_en": "Mountain (Himalaya) region", "text_np": "पहाडी (हिमालय) क्षेत्र", "is_correct": True},
            {"text_en": "Hill (Pahad) region", "text_np": "पहाडी (पहाड) क्षेत्र", "is_correct": False},
            {"text_en": "Terai (plains) region", "text_np": "तराई (मैदान) क्षेत्र", "is_correct": False},
            {"text_en": "All three are equal", "text_np": "तीनवटा समान छन्", "is_correct": False},
        ],
        "explanation_en": "The Himalaya (Mountain) region covers about 35% of Nepal's area, the Hills (Pahad) cover about 42%, and the Terai covers about 23%. Hills cover the most area.",
        "explanation_np": "हिमालय क्षेत्रले नेपालको लगभग ३५%, पहाडले लगभग ४२%, र तराईले लगभग २३% ओगटेको छ। वास्तवमा पहाडले सबैभन्दा बढी क्षेत्रफल ओगटेको छ।",
        "difficulty": "HARD",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "The Koshi River flows through which province before entering India?",
        "question_text_np": "कोशी नदी भारत प्रवेश गर्नुअघि कुन प्रदेशबाट बग्छ?",
        "answers": [
            {"text_en": "Koshi Province (Province No. 1)", "text_np": "कोशी प्रदेश (प्रदेश नं. १)", "is_correct": True},
            {"text_en": "Madhesh Province", "text_np": "मधेश प्रदेश", "is_correct": False},
            {"text_en": "Bagmati Province", "text_np": "बागमती प्रदेश", "is_correct": False},
            {"text_en": "Lumbini Province", "text_np": "लुम्बिनी प्रदेश", "is_correct": False},
        ],
        "explanation_en": "The Koshi River (also called Saptakoshi) flows through Koshi Province (Province 1) in eastern Nepal before entering Bihar state in India and joining the Ganges.",
        "explanation_np": "कोशी नदी (सप्तकोशी पनि भनिन्छ) नेपालको पूर्वी भागमा रहेको कोशी प्रदेश (प्रदेश १) बाट बगेर भारतको बिहारमा प्रवेश गर्छ र गंगामा मिसिन्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "Which is the capital city of Sudurpashchim Province?",
        "question_text_np": "सुदूरपश्चिम प्रदेशको राजधानी कुन शहर हो?",
        "answers": [
            {"text_en": "Dhangadhi", "text_np": "धनगढी", "is_correct": True},
            {"text_en": "Mahendranagar", "text_np": "महेन्द्रनगर", "is_correct": False},
            {"text_en": "Dipayal", "text_np": "दिपायल", "is_correct": False},
            {"text_en": "Baitadi", "text_np": "बैतडी", "is_correct": False},
        ],
        "explanation_en": "Dhangadhi (in Kailali district) is the capital of Sudurpashchim (Far-Western) Province, the 7th province of Nepal.",
        "explanation_np": "धनगढी (कैलाली जिल्लामा) सुदूरपश्चिम प्रदेशको राजधानी हो, जुन नेपालको ७ औं प्रदेश हो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "The Gandaki Province has its capital at:",
        "question_text_np": "गण्डकी प्रदेशको राजधानी कहाँ छ?",
        "answers": [
            {"text_en": "Pokhara", "text_np": "पोखरा", "is_correct": True},
            {"text_en": "Gorkha", "text_np": "गोरखा", "is_correct": False},
            {"text_en": "Syangja", "text_np": "स्याङ्जा", "is_correct": False},
            {"text_en": "Baglung", "text_np": "बाग्लुङ", "is_correct": False},
        ],
        "explanation_en": "Pokhara is the capital of Gandaki Province. Pokhara is also Nepal's second largest city and the 'Tourism Capital of Nepal'.",
        "explanation_np": "पोखरा गण्डकी प्रदेशको राजधानी हो। पोखरा नेपालको दोस्रो ठूलो शहर र 'नेपालको पर्यटन राजधानी' पनि हो।",
        "difficulty": "EASY",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "Lumbini, the birthplace of Lord Buddha, is located in which province?",
        "question_text_np": "भगवान बुद्धको जन्मस्थल लुम्बिनी कुन प्रदेशमा अवस्थित छ?",
        "answers": [
            {"text_en": "Lumbini Province", "text_np": "लुम्बिनी प्रदेश", "is_correct": True},
            {"text_en": "Gandaki Province", "text_np": "गण्डकी प्रदेश", "is_correct": False},
            {"text_en": "Bagmati Province", "text_np": "बागमती प्रदेश", "is_correct": False},
            {"text_en": "Madhesh Province", "text_np": "मधेश प्रदेश", "is_correct": False},
        ],
        "explanation_en": "Lumbini is located in Rupandehi district of Lumbini Province. It is a UNESCO World Heritage Site and the birthplace of Siddhartha Gautama (Buddha), born around 623 BC.",
        "explanation_np": "लुम्बिनी लुम्बिनी प्रदेशको रुपन्देही जिल्लामा अवस्थित छ। यो UNESCO विश्व सम्पदा स्थल हो र सिद्धार्थ गौतम (बुद्ध) को जन्मस्थल हो, जन्म लगभग ६२३ ईसापूर्व।",
        "difficulty": "EASY",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "What percentage of Nepal's total population lives in the Kathmandu Valley?",
        "question_text_np": "नेपालको कुल जनसंख्याको कति प्रतिशत काठमाडौं उपत्यकामा बस्छ?",
        "answers": [
            {"text_en": "Approximately 12-13%", "text_np": "लगभग १२-१३%", "is_correct": True},
            {"text_en": "Approximately 5%", "text_np": "लगभग ५%", "is_correct": False},
            {"text_en": "Approximately 25%", "text_np": "लगभग २५%", "is_correct": False},
            {"text_en": "Approximately 30%", "text_np": "लगभग ३०%", "is_correct": False},
        ],
        "explanation_en": "The Kathmandu Valley (comprising Kathmandu, Lalitpur, and Bhaktapur districts) houses approximately 12-13% of Nepal's total population, making it the most densely populated area.",
        "explanation_np": "काठमाडौं उपत्यका (काठमाडौं, ललितपुर र भक्तपुर जिल्लाहरू) मा नेपालको कुल जनसंख्याको लगभग १२-१३% बस्छ, जसले यसलाई सबैभन्दा घनाइ बस्ती भएको क्षेत्र बनाउँछ।",
        "difficulty": "HARD",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "Which is the highest lake in Nepal?",
        "question_text_np": "नेपालको सबैभन्दा उचाइमा रहेको ताल कुन हो?",
        "answers": [
            {"text_en": "Tilicho Lake", "text_np": "तिलिचो ताल", "is_correct": True},
            {"text_en": "Rara Lake", "text_np": "रारा ताल", "is_correct": False},
            {"text_en": "Gosaikunda", "text_np": "गोसाइँकुण्ड", "is_correct": False},
            {"text_en": "Phewa Lake", "text_np": "फेवा ताल", "is_correct": False},
        ],
        "explanation_en": "Tilicho Lake in Manang district, at an altitude of 4,919 metres above sea level, is one of the highest lakes in the world. Gosaikunda (4,380m) is also a famous high-altitude lake.",
        "explanation_np": "मनाङ जिल्लामा रहेको तिलिचो ताल ४,९१९ मिटरको उचाइमा विश्वका सबैभन्दा उच्च ताललहरूमध्ये एक हो। गोसाइँकुण्ड (४,३८०मि.) पनि एउटा प्रसिद्ध उच्च ताल हो।",
        "difficulty": "HARD",
        "source_reference": "PSC Geography of Nepal",
    },
    {
        "question_text_en": "Which of the following is the correct order of provinces from east to west in Nepal?",
        "question_text_np": "नेपालमा पूर्वदेखि पश्चिमसम्मका प्रदेशहरूको सही क्रम कुन हो?",
        "answers": [
            {"text_en": "Koshi, Madhesh, Bagmati, Gandaki, Lumbini, Karnali, Sudurpashchim", "text_np": "कोशी, मधेश, बागमती, गण्डकी, लुम्बिनी, कर्णाली, सुदूरपश्चिम", "is_correct": True},
            {"text_en": "Madhesh, Koshi, Bagmati, Gandaki, Karnali, Lumbini, Sudurpashchim", "text_np": "मधेश, कोशी, बागमती, गण्डकी, कर्णाली, लुम्बिनी, सुदूरपश्चिम", "is_correct": False},
            {"text_en": "Koshi, Bagmati, Gandaki, Madhesh, Lumbini, Karnali, Sudurpashchim", "text_np": "कोशी, बागमती, गण्डकी, मधेश, लुम्बिनी, कर्णाली, सुदूरपश्चिम", "is_correct": False},
            {"text_en": "Sudurpashchim, Karnali, Lumbini, Gandaki, Bagmati, Koshi, Madhesh", "text_np": "सुदूरपश्चिम, कर्णाली, लुम्बिनी, गण्डकी, बागमती, कोशी, मधेश", "is_correct": False},
        ],
        "explanation_en": "From east to west: 1-Koshi, 2-Madhesh, 3-Bagmati, 4-Gandaki, 5-Lumbini, 6-Karnali, 7-Sudurpashchim. This is the official numbering and geographic east-to-west arrangement.",
        "explanation_np": "पूर्वदेखि पश्चिमसम्म: १-कोशी, २-मधेश, ३-बागमती, ४-गण्डकी, ५-लुम्बिनी, ६-कर्णाली, ७-सुदूरपश्चिम। यो आधिकारिक नम्बरिङ र भौगोलिक पूर्व-पश्चिम व्यवस्थापन हो।",
        "difficulty": "HARD",
        "source_reference": "PSC Geography of Nepal",
    },
]