"""Good Governance & Ethics (सुशासन र नैतिकता) — UNIVERSAL category questions."""

QUESTIONS = [
    {
        "question_text_en": "Which of the following is NOT a pillar of good governance?",
        "question_text_np": "निम्नमध्ये कुन सुशासनको स्तम्भ होइन?",
        "answers": [
            {"text_en": "Opacity", "text_np": "अपारदर्शिता", "is_correct": True},
            {"text_en": "Accountability", "text_np": "जवाफदेहिता", "is_correct": False},
            {"text_en": "Rule of Law", "text_np": "कानुनको शासन", "is_correct": False},
            {"text_en": "Participation", "text_np": "सहभागिता", "is_correct": False},
        ],
        "explanation_en": "The pillars of good governance include: accountability, transparency, rule of law, participation, consensus, equity, effectiveness, and responsiveness. Opacity (lack of transparency) is the opposite of good governance.",
        "explanation_np": "सुशासनका स्तम्भहरूमा जवाफदेहिता, पारदर्शिता, कानुनको शासन, सहभागिता, सहमति, समानता, प्रभावकारिता र जिम्मेवारी पर्छन्। अपारदर्शिता सुशासनको विपरीत हो।",
        "difficulty": "EASY",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "Nepal's Good Governance (Management and Operation) Act was enacted in which year (B.S.)?",
        "question_text_np": "नेपालको सुशासन (व्यवस्थापन तथा सञ्चालन) ऐन कुन वर्षमा (वि.सं.) जारी भएको हो?",
        "answers": [
            {"text_en": "2064 B.S.", "text_np": "२०६४ वि.सं.", "is_correct": True},
            {"text_en": "2060 B.S.", "text_np": "२०६० वि.सं.", "is_correct": False},
            {"text_en": "2070 B.S.", "text_np": "२०७० वि.सं.", "is_correct": False},
            {"text_en": "2055 B.S.", "text_np": "२०५५ वि.सं.", "is_correct": False},
        ],
        "explanation_en": "Nepal's Good Governance (Management and Operation) Act 2064 B.S. (2007 A.D.) was enacted to institutionalize good governance practices in Nepal's civil service.",
        "explanation_np": "नेपालको सुशासन (व्यवस्थापन तथा सञ्चालन) ऐन २०६४ वि.सं. (२००७ ई.) नेपालको निजामती सेवामा सुशासन अभ्यासलाई संस्थागत बनाउन जारी गरिएको थियो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "Which organization in Nepal is responsible for investigating corruption?",
        "question_text_np": "नेपालमा भ्रष्टाचार अनुसन्धान गर्ने जिम्मेवार निकाय कुन हो?",
        "answers": [
            {"text_en": "Commission for Investigation of Abuse of Authority (CIAA)", "text_np": "अख्तियार दुरुपयोग अनुसन्धान आयोग (अदुआ)", "is_correct": True},
            {"text_en": "National Vigilance Centre (NVC)", "text_np": "राष्ट्रिय सतर्कता केन्द्र", "is_correct": False},
            {"text_en": "Office of the Auditor General", "text_np": "महालेखापरीक्षकको कार्यालय", "is_correct": False},
            {"text_en": "Attorney General's Office", "text_np": "महान्यायाधिवक्ताको कार्यालय", "is_correct": False},
        ],
        "explanation_en": "The CIAA (Commission for Investigation of Abuse of Authority) is Nepal's constitutional body responsible for investigating corruption and abuse of authority by public officials.",
        "explanation_np": "अख्तियार दुरुपयोग अनुसन्धान आयोग (अदुआ) नेपालको संवैधानिक निकाय हो जसले सरकारी अधिकारीहरूद्वारा हुने भ्रष्टाचार र अख्तियारको दुरुपयोग अनुसन्धान गर्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "What is the principle of 'Rule of Law'?",
        "question_text_np": "'कानुनको शासन' को सिद्धान्त के हो?",
        "answers": [
            {"text_en": "Every person and institution is equally subject to and accountable under the law", "text_np": "प्रत्येक व्यक्ति र संस्था समान रूपमा कानुनको अधीनमा र जवाफदेही छ", "is_correct": True},
            {"text_en": "Only the government can create and enforce laws", "text_np": "सरकारले मात्र कानुन बनाउन र लागू गर्न सक्छ", "is_correct": False},
            {"text_en": "Rulers are above the law", "text_np": "शासकहरू कानुनभन्दा माथि छन्", "is_correct": False},
            {"text_en": "Courts can override parliament", "text_np": "अदालतहरूले संसदलाई अस्वीकार गर्न सक्छन्", "is_correct": False},
        ],
        "explanation_en": "Rule of Law means no one is above the law — not even the government. Laws apply equally to all, and disputes are resolved through a fair and transparent legal process.",
        "explanation_np": "कानुनको शासनको अर्थ हो कि कोही पनि — सरकार समेत — कानुनभन्दा माथि छैन। कानुन सबैमा समान रूपमा लागू हुन्छ र विवादहरू निष्पक्ष र पारदर्शी कानुनी प्रक्रियामार्फत समाधान गरिन्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "What does 'transparency' in governance mean?",
        "question_text_np": "शासनमा 'पारदर्शिता' को अर्थ के हो?",
        "answers": [
            {"text_en": "Making government decisions and information available and accessible to citizens", "text_np": "सरकारी निर्णयहरू र जानकारी नागरिकहरूका लागि उपलब्ध र पहुँचयोग्य बनाउनु", "is_correct": True},
            {"text_en": "Keeping all government activities secret for security", "text_np": "सुरक्षाका लागि सबै सरकारी गतिविधिहरू गोप्य राख्नु", "is_correct": False},
            {"text_en": "Allowing only officials to see budget details", "text_np": "अधिकारीहरूलाई मात्र बजेटको विवरण हेर्न दिनु", "is_correct": False},
            {"text_en": "Publishing laws but not their implementation details", "text_np": "कानुन प्रकाशित गर्ने तर कार्यान्वयन विवरण नगर्ने", "is_correct": False},
        ],
        "explanation_en": "Transparency in governance means that government decisions, rules, and processes are open, clearly understandable, and freely accessible to the public.",
        "explanation_np": "शासनमा पारदर्शिताको अर्थ हो कि सरकारी निर्णयहरू, नियमहरू र प्रक्रियाहरू खुला, स्पष्ट रूपमा बुझ्न सकिने र जनतालाई स्वतन्त्र रूपमा पहुँचयोग्य छन्।",
        "difficulty": "EASY",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "The Right to Information Act in Nepal was passed in which year (B.S.)?",
        "question_text_np": "नेपालमा सूचनाको हक सम्बन्धी ऐन कुन वर्षमा (वि.सं.) पारित भएको थियो?",
        "answers": [
            {"text_en": "2064 B.S.", "text_np": "२०६४ वि.सं.", "is_correct": True},
            {"text_en": "2072 B.S.", "text_np": "२०७२ वि.सं.", "is_correct": False},
            {"text_en": "2059 B.S.", "text_np": "२०५९ वि.सं.", "is_correct": False},
            {"text_en": "2068 B.S.", "text_np": "२०६८ वि.सं.", "is_correct": False},
        ],
        "explanation_en": "Nepal's Right to Information Act 2064 B.S. (2007 A.D.) guarantees citizens the right to seek information from public bodies within 15 days.",
        "explanation_np": "नेपालको सूचनाको हक सम्बन्धी ऐन २०६४ वि.सं. (२००७ ई.) ले नागरिकहरूलाई सार्वजनिक निकायहरूबाट १५ दिनभित्र सूचना माग्ने अधिकार ग्यारेन्टी गर्दछ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "What is 'conflict of interest' in public service ethics?",
        "question_text_np": "सार्वजनिक सेवा नैतिकतामा 'हितको द्वन्द्व' (conflict of interest) के हो?",
        "answers": [
            {"text_en": "When a public official's personal interests could improperly influence their official duties", "text_np": "जब सार्वजनिक अधिकारीको व्यक्तिगत हितले उनको आधिकारिक कर्तव्यमा अनुचित प्रभाव पार्न सक्छ", "is_correct": True},
            {"text_en": "Disagreement between two government departments", "text_np": "दुई सरकारी विभागहरूबीचको असहमति", "is_correct": False},
            {"text_en": "A public official refusing to follow orders", "text_np": "सार्वजनिक अधिकारीले आदेश पालना गर्न अस्वीकार गर्नु", "is_correct": False},
            {"text_en": "Competition between government employees for promotions", "text_np": "बढुवाका लागि सरकारी कर्मचारीहरूबीचको प्रतिस्पर्धा", "is_correct": False},
        ],
        "explanation_en": "Conflict of interest arises when a civil servant's personal, financial, or other interests conflict with their duty to act in the public interest. Declaring and managing such conflicts is key to ethical governance.",
        "explanation_np": "हितको द्वन्द्व तब उत्पन्न हुन्छ जब निजामती कर्मचारीको व्यक्तिगत, आर्थिक वा अन्य हित सार्वजनिक हितमा काम गर्ने कर्तव्यसँग बाझिन्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "Which commission was established to prevent corruption and promote good governance in Nepal?",
        "question_text_np": "नेपालमा भ्रष्टाचार रोक्न र सुशासन प्रवर्द्धन गर्न कुन आयोग स्थापना गरिएको हो?",
        "answers": [
            {"text_en": "Commission for Investigation of Abuse of Authority (CIAA)", "text_np": "अख्तियार दुरुपयोग अनुसन्धान आयोग (अदुआ)", "is_correct": True},
            {"text_en": "National Human Rights Commission (NHRC)", "text_np": "राष्ट्रिय मानव अधिकार आयोग", "is_correct": False},
            {"text_en": "Public Service Commission (PSC)", "text_np": "लोक सेवा आयोग", "is_correct": False},
            {"text_en": "Election Commission of Nepal (ECN)", "text_np": "निर्वाचन आयोग", "is_correct": False},
        ],
        "explanation_en": "The CIAA was established to investigate and take action against corruption and abuse of authority. The NHRC handles human rights. PSC conducts civil service exams. ECN manages elections.",
        "explanation_np": "अदुआ भ्रष्टाचार र अख्तियारको दुरुपयोगको अनुसन्धान र कारबाही गर्न स्थापना गरिएको हो। राष्ट्रिय मानव अधिकार आयोग मानव अधिकार, लोक सेवा आयोग निजामती परीक्षा र निर्वाचन आयोग निर्वाचन हेर्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "What is 'accountability' in the context of public administration?",
        "question_text_np": "सार्वजनिक प्रशासनको सन्दर्भमा 'जवाफदेहिता' के हो?",
        "answers": [
            {"text_en": "The obligation of public officials to answer for their actions to citizens and oversight bodies", "text_np": "सार्वजनिक अधिकारीहरूको आफ्नो कार्यका लागि नागरिक र निगरानी निकायप्रति उत्तरदायी हुने दायित्व", "is_correct": True},
            {"text_en": "The right to refuse answering questions from the public", "text_np": "जनताका प्रश्नहरूको जवाफ दिन अस्वीकार गर्ने अधिकार", "is_correct": False},
            {"text_en": "Keeping financial records for internal review only", "text_np": "आन्तरिक समीक्षाका लागि मात्र वित्तीय अभिलेख राख्ने", "is_correct": False},
            {"text_en": "The process of assigning tasks within a department", "text_np": "विभाग भित्र कार्य सुम्पने प्रक्रिया", "is_correct": False},
        ],
        "explanation_en": "Accountability means public officials must be able to justify their decisions and actions, and face consequences for misconduct. It includes financial, administrative, and political accountability.",
        "explanation_np": "जवाफदेहिताको अर्थ हो कि सार्वजनिक अधिकारीहरूले आफ्ना निर्णय र कार्यहरू उचित ठहर्याउन सक्नुपर्छ र दुर्व्यवहारका लागि परिणाम भोग्नुपर्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "Nepal's Corruption Perception Index (CPI) is published by which organization?",
        "question_text_np": "नेपालको भ्रष्टाचार धारणा सूचकांक (CPI) कुन संगठनले प्रकाशित गर्छ?",
        "answers": [
            {"text_en": "Transparency International", "text_np": "ट्रान्सपेरेन्सी इन्टरनेसनल", "is_correct": True},
            {"text_en": "United Nations", "text_np": "संयुक्त राष्ट्रसंघ", "is_correct": False},
            {"text_en": "World Bank", "text_np": "विश्व बैंक", "is_correct": False},
            {"text_en": "CIAA Nepal", "text_np": "अख्तियार दुरुपयोग अनुसन्धान आयोग", "is_correct": False},
        ],
        "explanation_en": "The Corruption Perceptions Index (CPI) is published annually by Transparency International (TI). It ranks countries by their perceived levels of public sector corruption.",
        "explanation_np": "भ्रष्टाचार धारणा सूचकांक (CPI) Transparency International (TI) द्वारा वार्षिक रूपमा प्रकाशित गरिन्छ। यसले सार्वजनिक क्षेत्रको भ्रष्टाचारको अनुमानित स्तरले देशहरूलाई वर्गीकरण गर्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "What does 'equity' mean in the context of governance?",
        "question_text_np": "शासनको सन्दर्भमा 'समानता' (equity) को अर्थ के हो?",
        "answers": [
            {"text_en": "Ensuring all people have equal opportunities to improve their well-being", "text_np": "सबै मानिसहरूलाई आफ्नो कल्याण सुधार गर्ने समान अवसर सुनिश्चित गर्नु", "is_correct": True},
            {"text_en": "Giving equal amounts of resources to all people", "text_np": "सबै मानिसहरूलाई समान मात्रामा स्रोत दिनु", "is_correct": False},
            {"text_en": "Treating everyone identically regardless of circumstances", "text_np": "परिस्थिति जे सुकै भए पनि सबैलाई समान व्यवहार गर्नु", "is_correct": False},
            {"text_en": "Distributing profits from state-owned enterprises", "text_np": "सरकारी उद्यमहरूबाट नाफा वितरण गर्नु", "is_correct": False},
        ],
        "explanation_en": "Equity in governance means fair treatment and access to resources for all, especially marginalized groups. It recognizes that different people may need different levels of support to achieve equal outcomes.",
        "explanation_np": "शासनमा समानताको अर्थ हो सबैका लागि, विशेषगरी सीमान्तकृत समूहहरूका लागि, उचित व्यवहार र स्रोतहरूमा पहुँच। यसले स्वीकार गर्छ कि विभिन्न मानिसहरूलाई समान परिणाम प्राप्त गर्न विभिन्न स्तरको समर्थन चाहिन सक्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "Which of the following is an example of ethical conduct for a public servant?",
        "question_text_np": "निम्नमध्ये कुन सार्वजनिक सेवकको नैतिक आचरणको उदाहरण हो?",
        "answers": [
            {"text_en": "Refusing to accept gifts from citizens seeking services", "text_np": "सेवा खोज्ने नागरिकहरूबाट उपहार स्वीकार गर्न अस्वीकार गर्नु", "is_correct": True},
            {"text_en": "Prioritizing requests from family members", "text_np": "परिवारका सदस्यहरूको अनुरोधलाई प्राथमिकता दिनु", "is_correct": False},
            {"text_en": "Using government vehicles for personal errands", "text_np": "व्यक्तिगत कामका लागि सरकारी सवारी साधन प्रयोग गर्नु", "is_correct": False},
            {"text_en": "Sharing confidential files with friends", "text_np": "साथीहरूसँग गोप्य फाइलहरू साझा गर्नु", "is_correct": False},
        ],
        "explanation_en": "Ethical conduct for public servants includes: refusing gifts/bribes, treating all citizens equally, using government resources only for official purposes, and maintaining confidentiality.",
        "explanation_np": "सार्वजनिक सेवकको नैतिक आचरणमा: उपहार/घूस अस्वीकार गर्नु, सबै नागरिकलाई समान व्यवहार गर्नु, सरकारी स्रोतहरू आधिकारिक उद्देश्यका लागि मात्र प्रयोग गर्नु र गोपनीयता कायम राख्नु पर्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "The concept of 'responsive governance' means:",
        "question_text_np": "'उत्तरदायी शासन' को अवधारणाको अर्थ के हो?",
        "answers": [
            {"text_en": "Government institutions serving the needs of citizens within a reasonable timeframe", "text_np": "सरकारी संस्थाहरूले उचित समयसीमाभित्र नागरिकहरूको आवश्यकता पूरा गर्नु", "is_correct": True},
            {"text_en": "Responding only to written complaints", "text_np": "लिखित उजुरीहरूमा मात्र जवाफ दिनु", "is_correct": False},
            {"text_en": "Government answering media questions", "text_np": "सरकारले मिडियाका प्रश्नहरूको जवाफ दिनु", "is_correct": False},
            {"text_en": "Police responding quickly to crimes", "text_np": "प्रहरीले अपराधहरूमा तत्काल जवाफ दिनु", "is_correct": False},
        ],
        "explanation_en": "Responsive governance means that all institutions and processes serve the needs of all stakeholders, including marginalized groups, within a reasonable timeframe.",
        "explanation_np": "उत्तरदायी शासनको अर्थ हो कि सबै संस्था र प्रक्रियाहरूले सीमान्तकृत समूहहरू सहित सबै सरोकारवालाहरूको आवश्यकता उचित समयसीमाभित्र पूरा गर्छन्।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "What is 'whistleblowing' in the context of governance?",
        "question_text_np": "शासनको सन्दर्भमा 'whistleblowing' के हो?",
        "answers": [
            {"text_en": "Reporting wrongdoing by an organization to those in authority or the public", "text_np": "संगठनको गलत कार्यको जानकारी अधिकारीहरू वा जनतालाई दिनु", "is_correct": True},
            {"text_en": "Using social media to criticize the government", "text_np": "सरकारको आलोचना गर्न सोशल मिडिया प्रयोग गर्नु", "is_correct": False},
            {"text_en": "Filing official appeals against administrative decisions", "text_np": "प्रशासनिक निर्णयहरू विरुद्ध आधिकारिक अपिल दायर गर्नु", "is_correct": False},
            {"text_en": "Striking by government employees", "text_np": "सरकारी कर्मचारीहरूद्वारा हड्ताल गर्नु", "is_correct": False},
        ],
        "explanation_en": "Whistleblowing refers to exposing information or activity within a private, public, or government organization that is deemed illegal, unethical, or harmful. Nepal has legal provisions to protect whistleblowers.",
        "explanation_np": "Whistleblowing भनेको निजी, सार्वजनिक वा सरकारी संगठनभित्र गैरकानुनी, अनैतिक वा हानिकारक मानिएको जानकारी वा गतिविधि उजागर गर्नु हो। नेपालमा यस्ता व्यक्तिहरूलाई सुरक्षा दिने कानुनी व्यवस्था छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "The UNDP identifies how many characteristics of good governance?",
        "question_text_np": "UNDP ले सुशासनका कतिवटा विशेषताहरू पहिचान गर्छ?",
        "answers": [
            {"text_en": "8", "text_np": "८", "is_correct": True},
            {"text_en": "5", "text_np": "५", "is_correct": False},
            {"text_en": "10", "text_np": "१०", "is_correct": False},
            {"text_en": "6", "text_np": "६", "is_correct": False},
        ],
        "explanation_en": "UNDP identifies 8 characteristics of good governance: participatory, consensus-oriented, accountable, transparent, responsive, effective and efficient, equitable and inclusive, and follows the rule of law.",
        "explanation_np": "UNDP ले सुशासनका ८ विशेषताहरू पहिचान गर्छ: सहभागितामूलक, सहमतिमुखी, जवाफदेही, पारदर्शी, उत्तरदायी, प्रभावकारी र दक्ष, न्यायसंगत र समावेशी, र कानुनको शासन।",
        "difficulty": "HARD",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "Which of the following violates the code of conduct for civil servants in Nepal?",
        "question_text_np": "निम्नमध्ये कुन नेपालमा निजामती कर्मचारीहरूको आचारसंहिता उल्लंघन गर्छ?",
        "answers": [
            {"text_en": "Engaging in politics while on duty", "text_np": "सेवाकालमा राजनीतिमा संलग्न हुनु", "is_correct": True},
            {"text_en": "Submitting official reports on time", "text_np": "समयमा आधिकारिक प्रतिवेदन पेश गर्नु", "is_correct": False},
            {"text_en": "Attending training programs organized by the government", "text_np": "सरकारद्वारा आयोजित तालिम कार्यक्रमहरूमा भाग लिनु", "is_correct": False},
            {"text_en": "Following the orders of superior officers", "text_np": "उच्च अधिकारीहरूको आदेश पालना गर्नु", "is_correct": False},
        ],
        "explanation_en": "Nepal's Civil Service Act prohibits civil servants from participating in political activities while in service. They must be politically neutral to maintain impartiality.",
        "explanation_np": "नेपालको निजामती सेवा ऐनले निजामती कर्मचारीहरूलाई सेवाकालमा राजनीतिक गतिविधिहरूमा भाग लिन निषेध गर्छ। निष्पक्षता कायम राख्न उनीहरू राजनीतिक रूपमा तटस्थ हुनुपर्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "Social audit is best described as:",
        "question_text_np": "सामाजिक परीक्षण (social audit) को सबैभन्दा राम्रो वर्णन के हो?",
        "answers": [
            {"text_en": "A process where communities examine and evaluate government programs and spending", "text_np": "एउटा प्रक्रिया जहाँ समुदायहरूले सरकारी कार्यक्रम र खर्चको जाँच र मूल्यांकन गर्छन्", "is_correct": True},
            {"text_en": "An audit conducted by social workers", "text_np": "सामाजिक कार्यकर्ताहरूद्वारा गरिने लेखापरीक्षण", "is_correct": False},
            {"text_en": "Financial audit of NGOs and social organizations", "text_np": "NGO र सामाजिक संगठनहरूको वित्तीय लेखापरीक्षण", "is_correct": False},
            {"text_en": "Review of a company's social media accounts", "text_np": "कम्पनीको सोशल मिडिया खाताहरूको समीक्षा", "is_correct": False},
        ],
        "explanation_en": "Social audit is a process where the community itself conducts a formal review of a government program, scrutinizing the expenditure and activities to ensure accountability and transparency.",
        "explanation_np": "सामाजिक परीक्षण एउटा प्रक्रिया हो जहाँ समुदायले नै सरकारी कार्यक्रमको औपचारिक समीक्षा गर्छ, जवाफदेहिता र पारदर्शिता सुनिश्चित गर्न खर्च र गतिविधिहरूको जाँच गर्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "Decentralization in governance primarily means:",
        "question_text_np": "शासनमा विकेन्द्रीकरण मुख्य रूपमा के हो?",
        "answers": [
            {"text_en": "Transfer of authority and responsibility from central to local governments", "text_np": "केन्द्रीय सरकारबाट स्थानीय सरकारमा अधिकार र जिम्मेवारी हस्तान्तरण गर्नु", "is_correct": True},
            {"text_en": "Moving government offices from Kathmandu to other cities", "text_np": "सरकारी कार्यालयहरू काठमाडौंबाट अन्य शहरहरूमा सार्नु", "is_correct": False},
            {"text_en": "Reducing the number of government employees", "text_np": "सरकारी कर्मचारीहरूको संख्या घटाउनु", "is_correct": False},
            {"text_en": "Privatizing government-owned enterprises", "text_np": "सरकारी उद्यमहरूको निजीकरण गर्नु", "is_correct": False},
        ],
        "explanation_en": "Decentralization transfers decision-making powers, resources, and responsibilities from the central government to regional, provincial, or local bodies. Nepal's 2015 Constitution adopted federalism, a form of decentralization.",
        "explanation_np": "विकेन्द्रीकरणले केन्द्र सरकारबाट क्षेत्रीय, प्रादेशिक वा स्थानीय निकायहरूमा निर्णय गर्ने अधिकार, स्रोत र जिम्मेवारीहरू हस्तान्तरण गर्छ। नेपालको २०७२ को संविधानले संघीयता — एक प्रकारको विकेन्द्रीकरण — अपनाएको छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "What is 'red-tapism' in public administration?",
        "question_text_np": "सार्वजनिक प्रशासनमा 'रेडट्यापिज्म' (red-tapism) के हो?",
        "answers": [
            {"text_en": "Excessive bureaucratic formalities and procedures that delay service delivery", "text_np": "सेवा वितरणमा ढिलाइ गर्ने अत्यधिक नौकरशाही औपचारिकता र प्रक्रियाहरू", "is_correct": True},
            {"text_en": "The use of red color in official documents", "text_np": "आधिकारिक कागजातहरूमा रातो रंगको प्रयोग", "is_correct": False},
            {"text_en": "Priority handling of urgent government matters", "text_np": "जरुरी सरकारी मामिलाहरूको प्राथमिकता व्यवस्थापन", "is_correct": False},
            {"text_en": "Strict security protocols in government offices", "text_np": "सरकारी कार्यालयहरूमा कडा सुरक्षा प्रोटोकल", "is_correct": False},
        ],
        "explanation_en": "Red-tapism refers to the excessive adherence to official rules and formalities — too much paperwork, multiple approvals, and rigid procedures — that slow down service delivery and hinder efficiency.",
        "explanation_np": "रेडट्यापिज्म भनेको आधिकारिक नियम र औपचारिकताहरूको अत्यधिक पालना — धेरै कागजी काम, बहु अनुमोदन र कठोर प्रक्रियाहरू — जसले सेवा वितरणमा ढिलाइ गर्छ र दक्षतामा बाधा पुर्‍याउँछ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Good Governance",
    },
    {
        "question_text_en": "The National Integrity System (NIS) of a country refers to:",
        "question_text_np": "देशको राष्ट्रिय अखण्डता प्रणाली (NIS) ले के जनाउँछ?",
        "answers": [
            {"text_en": "A set of institutions, laws, and practices that prevent corruption and promote accountability", "text_np": "भ्रष्टाचार रोक्ने र जवाफदेहिता प्रवर्द्धन गर्ने संस्था, कानुन र अभ्यासहरूको समूह", "is_correct": True},
            {"text_en": "The national cybersecurity infrastructure", "text_np": "राष्ट्रिय साइबर सुरक्षा पूर्वाधार", "is_correct": False},
            {"text_en": "A system for verifying the integrity of government software", "text_np": "सरकारी सफ्टवेयरको अखण्डता प्रमाणित गर्ने प्रणाली", "is_correct": False},
            {"text_en": "A data integrity system for public records", "text_np": "सार्वजनिक अभिलेखहरूको लागि डेटा अखण्डता प्रणाली", "is_correct": False},
        ],
        "explanation_en": "The National Integrity System (NIS) refers to the collection of institutions, laws, procedures, practices, and attitudes that together prevent corruption and promote integrity in a country.",
        "explanation_np": "राष्ट्रिय अखण्डता प्रणाली (NIS) भनेको देशमा भ्रष्टाचार रोक्न र अखण्डता प्रवर्द्धन गर्न मिलेर काम गर्ने संस्था, कानुन, प्रक्रिया, अभ्यास र मनोवृत्तिहरूको संग्रह हो।",
        "difficulty": "HARD",
        "source_reference": "PSC Good Governance",
    },
]