"""Health Service — BRANCH & SUBBRANCH category questions."""

QUESTIONS = {
    # ── BRANCH-scoped categories ──────────────────────────────────────────
    "public-health": [
        {
            "question_text_en": "What is the minimum number of Antenatal Care (ANC) visits recommended by Nepal's Safe Motherhood Program?",
            "question_text_np": "नेपालको सुरक्षित मातृत्व कार्यक्रम अनुसार न्यूनतम कति पटक प्रसवपूर्व जाँच (ANC) गर्नुपर्छ?",
            "answers": [
                {"text_en": "4 visits", "text_np": "४ पटक", "is_correct": True},
                {"text_en": "2 visits", "text_np": "२ पटक", "is_correct": False},
                {"text_en": "6 visits", "text_np": "६ पटक", "is_correct": False},
                {"text_en": "8 visits", "text_np": "८ पटक", "is_correct": False},
            ],
            "explanation_en": "Nepal's Safe Motherhood Program recommends a minimum of 4 ANC visits during pregnancy — at 4th, 6th, 8th, and 9th months.",
            "explanation_np": "नेपालको सुरक्षित मातृत्व कार्यक्रम अनुसार गर्भावस्थामा कम्तीमा ४ पटक प्रसवपूर्व जाँच गर्नुपर्छ — ४, ६, ८ र ९ औं महिनामा।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "Which organization is the apex body for health services regulation in Nepal?",
            "question_text_np": "नेपालमा स्वास्थ्य सेवा नियमनको शीर्ष निकाय कुन हो?",
            "answers": [
                {"text_en": "Ministry of Health and Population (MoHP)", "text_np": "स्वास्थ्य तथा जनसंख्या मन्त्रालय", "is_correct": True},
                {"text_en": "Nepal Medical Council", "text_np": "नेपाल मेडिकल काउन्सिल", "is_correct": False},
                {"text_en": "Department of Health Services", "text_np": "स्वास्थ्य सेवा विभाग", "is_correct": False},
                {"text_en": "World Health Organization Nepal", "text_np": "विश्व स्वास्थ्य संगठन नेपाल", "is_correct": False},
            ],
            "explanation_en": "The Ministry of Health and Population (MoHP) is the apex government body responsible for health policy, planning, and regulation in Nepal.",
            "explanation_np": "स्वास्थ्य तथा जनसंख्या मन्त्रालय नेपालमा स्वास्थ्य नीति, योजना र नियमनको लागि जिम्मेवार शीर्ष सरकारी निकाय हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the primary objective of Nepal's National Immunization Programme (NIP)?",
            "question_text_np": "नेपालको राष्ट्रिय खोप कार्यक्रम (NIP) को मुख्य उद्देश्य के हो?",
            "answers": [
                {"text_en": "To reduce morbidity and mortality from vaccine-preventable diseases", "text_np": "खोपबाट रोकथाम गर्न सकिने रोगहरूबाट रुग्णता र मृत्युदर घटाउने", "is_correct": True},
                {"text_en": "To provide free medicines to all citizens", "text_np": "सबै नागरिकलाई निःशुल्क औषधि उपलब्ध गराउने", "is_correct": False},
                {"text_en": "To build new hospitals in rural areas", "text_np": "ग्रामीण क्षेत्रमा नयाँ अस्पतालहरू निर्माण गर्ने", "is_correct": False},
                {"text_en": "To train community health workers", "text_np": "सामुदायिक स्वास्थ्य कार्यकर्ताहरूलाई तालिम दिने", "is_correct": False},
            ],
            "explanation_en": "The NIP aims to reduce morbidity and mortality caused by vaccine-preventable diseases by ensuring immunization coverage for all target populations.",
            "explanation_np": "राष्ट्रिय खोप कार्यक्रमको उद्देश्य लक्षित जनसंख्यालाई खोप सुनिश्चित गरी खोपबाट रोकथाम गर्न सकिने रोगहरूबाट हुने रुग्णता र मृत्युदर घटाउनु हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "Which disease was officially declared eliminated from Nepal in 2020?",
            "question_text_np": "सन् २०२० मा नेपालबाट कुन रोग आधिकारिक रूपमा उन्मूलन भएको घोषणा गरियो?",
            "answers": [
                {"text_en": "Trachoma", "text_np": "ट्रेकोमा", "is_correct": True},
                {"text_en": "Malaria", "text_np": "मलेरिया", "is_correct": False},
                {"text_en": "Tuberculosis", "text_np": "क्षयरोग", "is_correct": False},
                {"text_en": "Polio", "text_np": "पोलियो", "is_correct": False},
            ],
            "explanation_en": "Nepal was validated by WHO for eliminating trachoma as a public health problem in 2020, becoming the first country in Southeast Asia to achieve this milestone.",
            "explanation_np": "नेपालले सन् २०२० मा ट्रेकोमालाई सार्वजनिक स्वास्थ्य समस्याको रूपमा उन्मूलन गरेको WHO ले प्रमाणित गर्‍यो, दक्षिण-पूर्वी एसियामा यो उपलब्धि हासिल गर्ने पहिलो देश बन्दै।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the basic health service delivery structure at the community level in Nepal?",
            "question_text_np": "नेपालमा सामुदायिक स्तरमा आधारभूत स्वास्थ्य सेवा प्रदान गर्ने संरचना कुन हो?",
            "answers": [
                {"text_en": "Health Post", "text_np": "स्वास्थ्य चौकी", "is_correct": True},
                {"text_en": "District Hospital", "text_np": "जिल्ला अस्पताल", "is_correct": False},
                {"text_en": "Zonal Hospital", "text_np": "अञ्चल अस्पताल", "is_correct": False},
                {"text_en": "Teaching Hospital", "text_np": "शिक्षण अस्पताल", "is_correct": False},
            ],
            "explanation_en": "Health Posts are the primary health service delivery points at the community level in Nepal, providing basic curative, preventive, and promotive health services.",
            "explanation_np": "स्वास्थ्य चौकीहरू नेपालमा सामुदायिक स्तरमा प्राथमिक स्वास्थ्य सेवा प्रदान गर्ने केन्द्रहरू हुन्, जसले आधारभूत उपचारात्मक, रोकथाम र प्रवर्द्धनात्मक स्वास्थ्य सेवाहरू प्रदान गर्दछन्।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "Female Community Health Volunteers (FCHVs) in Nepal are primarily responsible for which level of healthcare?",
            "question_text_np": "नेपालमा महिला सामुदायिक स्वास्थ्य स्वयंसेविकाहरू (FCHVs) मुख्यतया कुन स्तरको स्वास्थ्य सेवाको लागि जिम्मेवार छन्?",
            "answers": [
                {"text_en": "Community-level preventive and promotive health", "text_np": "सामुदायिक स्तरमा रोकथाम र प्रवर्द्धनात्मक स्वास्थ्य", "is_correct": True},
                {"text_en": "Hospital-based curative care", "text_np": "अस्पतालमा आधारित उपचारात्मक सेवा", "is_correct": False},
                {"text_en": "Surgical procedures", "text_np": "शल्यक्रिया प्रक्रिया", "is_correct": False},
                {"text_en": "Specialist referral services", "text_np": "विशेषज्ञ रेफरल सेवा", "is_correct": False},
            ],
            "explanation_en": "FCHVs serve at the community level providing health education, family planning, maternal and child health services, and distribution of basic medicines like ORS and vitamin A.",
            "explanation_np": "FCHVs ले सामुदायिक स्तरमा स्वास्थ्य शिक्षा, परिवार नियोजन, मातृ तथा शिशु स्वास्थ्य सेवा र ORS तथा भिटामिन A जस्ता आधारभूत औषधि वितरण गर्दछन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the target of Nepal's National Health Policy 2019 for life expectancy at birth?",
            "question_text_np": "राष्ट्रिय स्वास्थ्य नीति २०१९ अनुसार जन्मदरमा अपेक्षित आयु कति लक्ष्य राखिएको छ?",
            "answers": [
                {"text_en": "75 years", "text_np": "७५ वर्ष", "is_correct": True},
                {"text_en": "65 years", "text_np": "६५ वर्ष", "is_correct": False},
                {"text_en": "80 years", "text_np": "८० वर्ष", "is_correct": False},
                {"text_en": "70 years", "text_np": "७० वर्ष", "is_correct": False},
            ],
            "explanation_en": "Nepal's National Health Policy 2019 sets a target of increasing life expectancy at birth to 75 years.",
            "explanation_np": "राष्ट्रिय स्वास्थ्य नीति २०१९ ले जन्मदरमा अपेक्षित आयु ७५ वर्षमा पुर्‍याउने लक्ष्य राखेको छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
    ],
    "epidemiology-biostatistics": [
        {
            "question_text_en": "What does the term 'incidence rate' refer to in epidemiology?",
            "question_text_np": "महामारीविज्ञानमा 'घटना दर' (incidence rate) भन्नाले के बुझिन्छ?",
            "answers": [
                {"text_en": "Number of new cases occurring in a population over a specific time period", "text_np": "निश्चित समयावधिमा जनसंख्यामा देखिने नयाँ रोगीहरूको संख्या", "is_correct": True},
                {"text_en": "Total number of existing cases at a point in time", "text_np": "कुनै निश्चित समयमा विद्यमान रोगीहरूको कुल संख्या", "is_correct": False},
                {"text_en": "Number of deaths in a population", "text_np": "जनसंख्यामा मृत्युको संख्या", "is_correct": False},
                {"text_en": "Ratio of diseased to healthy individuals", "text_np": "रोगी र स्वस्थ व्यक्तिहरूको अनुपात", "is_correct": False},
            ],
            "explanation_en": "Incidence rate measures the number of new cases of a disease occurring in a specified population during a defined time period, usually expressed per 1,000 or 100,000 population.",
            "explanation_np": "घटना दरले निश्चित समयावधिमा निर्दिष्ट जनसंख्यामा देखिने नयाँ रोगीहरूको संख्या मापन गर्दछ, सामान्यतया प्रति १,००० वा १,००,००० जनसंख्यामा व्यक्त गरिन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "Which measure of central tendency is most affected by extreme values (outliers)?",
            "question_text_np": "केन्द्रीय प्रवृत्तिको कुन मापमा चरम मानहरू (outliers) ले सबैभन्दा बढी प्रभाव पार्छ?",
            "answers": [
                {"text_en": "Mean", "text_np": "मध्यमान (Mean)", "is_correct": True},
                {"text_en": "Median", "text_np": "मध्यिका (Median)", "is_correct": False},
                {"text_en": "Mode", "text_np": "रीत (Mode)", "is_correct": False},
                {"text_en": "Range", "text_np": "परिसर (Range)", "is_correct": False},
            ],
            "explanation_en": "The arithmetic mean is the most sensitive to extreme values because it uses every data point in its calculation. Median and mode are more robust against outliers.",
            "explanation_np": "अंकगणितीय मध्यमान चरम मानहरूप्रति सबैभन्दा संवेदनशील हुन्छ किनभने यसले गणनामा प्रत्येक तथ्यांक प्रयोग गर्दछ। मध्यिका र रीत outliers विरुद्ध बढी मजबुत हुन्छन्।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "In a disease outbreak investigation, what is the first step?",
            "question_text_np": "रोग प्रकोप अनुसन्धानमा पहिलो कदम के हो?",
            "answers": [
                {"text_en": "Verify the diagnosis and confirm the outbreak", "text_np": "निदान प्रमाणित गर्ने र प्रकोप पुष्टि गर्ने", "is_correct": True},
                {"text_en": "Implement control measures", "text_np": "नियन्त्रण उपायहरू लागू गर्ने", "is_correct": False},
                {"text_en": "Collect laboratory samples", "text_np": "प्रयोगशाला नमूनाहरू सङ्कलन गर्ने", "is_correct": False},
                {"text_en": "Develop a hypothesis", "text_np": "परिकल्पना विकास गर्ने", "is_correct": False},
            ],
            "explanation_en": "The first step in any outbreak investigation is to verify the diagnosis and confirm that an outbreak is actually occurring by comparing observed cases with expected baseline levels.",
            "explanation_np": "कुनै पनि प्रकोप अनुसन्धानको पहिलो कदम निदान प्रमाणित गर्ने र अपेक्षित आधारभूत स्तरसँग तुलना गरी प्रकोप वास्तवमा भइरहेको छ भनी पुष्टि गर्नु हो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What type of study design is best suited for studying rare diseases?",
            "question_text_np": "दुर्लभ रोगहरूको अध्ययनका लागि कुन प्रकारको अध्ययन डिजाइन सबैभन्दा उपयुक्त हुन्छ?",
            "answers": [
                {"text_en": "Case-control study", "text_np": "केस-कन्ट्रोल अध्ययन", "is_correct": True},
                {"text_en": "Cohort study", "text_np": "कोहोर्ट अध्ययन", "is_correct": False},
                {"text_en": "Cross-sectional study", "text_np": "क्रस-सेक्शनल अध्ययन", "is_correct": False},
                {"text_en": "Randomized controlled trial", "text_np": "र‍्यान्डमाइज्ड कन्ट्रोल्ड ट्रायल", "is_correct": False},
            ],
            "explanation_en": "Case-control studies start by identifying individuals with the disease (cases) and comparing them with those without it (controls), making them ideal for rare diseases where cohort studies would require impractically large sample sizes.",
            "explanation_np": "केस-कन्ट्रोल अध्ययनले रोग भएका व्यक्तिहरू (केस) पहिचान गरी रोग नभएकाहरू (कन्ट्रोल) सँग तुलना गर्दछ, जसले गर्दा दुर्लभ रोगहरूको लागि उपयुक्त हुन्छ जहाँ कोहोर्ट अध्ययनलाई अव्यवहारिक ठूलो नमूना आवश्यक पर्नेछ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the sensitivity of a diagnostic test?",
            "question_text_np": "निदान परीक्षणको संवेदनशीलता (sensitivity) भनेको के हो?",
            "answers": [
                {"text_en": "The ability of the test to correctly identify those with the disease (true positive rate)", "text_np": "रोग भएकाहरूलाई सही रूपमा पहिचान गर्ने परीक्षणको क्षमता (वास्तविक सकारात्मक दर)", "is_correct": True},
                {"text_en": "The ability of the test to correctly identify those without the disease", "text_np": "रोग नभएकाहरूलाई सही रूपमा पहिचान गर्ने क्षमता", "is_correct": False},
                {"text_en": "The proportion of positive results that are truly positive", "text_np": "सकारात्मक नतिजाहरूमा वास्तवमा सकारात्मक हुने अनुपात", "is_correct": False},
                {"text_en": "The overall accuracy of the test", "text_np": "परीक्षणको समग्र शुद्धता", "is_correct": False},
            ],
            "explanation_en": "Sensitivity (true positive rate) measures the proportion of actual positives correctly identified by the test. A highly sensitive test has few false negatives.",
            "explanation_np": "संवेदनशीलता (वास्तविक सकारात्मक दर) ले परीक्षणद्वारा सही रूपमा पहिचान गरिएका वास्तविक सकारात्मकहरूको अनुपात मापन गर्दछ। उच्च संवेदनशीलता भएको परीक्षणमा झुटा नकारात्मक कम हुन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What does a p-value of 0.03 indicate in a statistical test?",
            "question_text_np": "तथ्यांकीय परीक्षणमा p-value ०.०३ ले के सङ्केत गर्दछ?",
            "answers": [
                {"text_en": "There is a 3% probability that the observed result occurred by chance under the null hypothesis", "text_np": "शून्य परिकल्पना अन्तर्गत अवलोकन गरिएको नतिजा संयोगवश हुने ३% सम्भावना छ", "is_correct": True},
                {"text_en": "The treatment is 97% effective", "text_np": "उपचार ९७% प्रभावकारी छ", "is_correct": False},
                {"text_en": "3% of the population is affected", "text_np": "जनसंख्याको ३% प्रभावित छ", "is_correct": False},
                {"text_en": "The study has 3% error rate", "text_np": "अध्ययनमा ३% त्रुटि दर छ", "is_correct": False},
            ],
            "explanation_en": "A p-value of 0.03 means there is a 3% probability of obtaining the observed result (or more extreme) if the null hypothesis were true. At the conventional alpha level of 0.05, this is considered statistically significant.",
            "explanation_np": "p-value ०.०३ को अर्थ शून्य परिकल्पना सत्य भएमा अवलोकन गरिएको नतिजा (वा बढी चरम) प्राप्त हुने ३% सम्भावना छ। परम्परागत alpha स्तर ०.०५ मा, यसलाई तथ्यांकीय रूपमा महत्त्वपूर्ण मानिन्छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Health Service",
        },
    ],
    "health-policy-planning": [
        {
            "question_text_en": "Which act governs the regulation of health professionals in Nepal?",
            "question_text_np": "नेपालमा स्वास्थ्य पेशाकर्मीहरूको नियमन कुन ऐनले गर्दछ?",
            "answers": [
                {"text_en": "Nepal Health Professional Council Act", "text_np": "नेपाल स्वास्थ्य व्यवसायी परिषद् ऐन", "is_correct": True},
                {"text_en": "Public Health Service Act", "text_np": "सार्वजनिक स्वास्थ्य सेवा ऐन", "is_correct": False},
                {"text_en": "Nepal Medical Education Act", "text_np": "नेपाल चिकित्सा शिक्षा ऐन", "is_correct": False},
                {"text_en": "Health Insurance Act", "text_np": "स्वास्थ्य बीमा ऐन", "is_correct": False},
            ],
            "explanation_en": "The Nepal Health Professional Council Act regulates health professionals including pharmacists, nurses, lab technicians, and other allied health workers in Nepal.",
            "explanation_np": "नेपाल स्वास्थ्य व्यवसायी परिषद् ऐनले फार्मासिस्ट, नर्स, प्रयोगशाला प्राविधिक र अन्य सम्बद्ध स्वास्थ्य कर्मीहरू सहित स्वास्थ्य पेशाकर्मीहरूको नियमन गर्दछ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the health insurance premium per person per year under Nepal's Social Health Insurance Programme?",
            "question_text_np": "नेपालको सामाजिक स्वास्थ्य बीमा कार्यक्रम अन्तर्गत प्रति व्यक्ति वार्षिक बीमा शुल्क कति हो?",
            "answers": [
                {"text_en": "Rs. 3,500 per family of up to 5 members", "text_np": "५ जनासम्मको परिवारको लागि रु. ३,५००", "is_correct": True},
                {"text_en": "Rs. 1,000 per person", "text_np": "प्रति व्यक्ति रु. १,०००", "is_correct": False},
                {"text_en": "Rs. 5,000 per family", "text_np": "प्रति परिवार रु. ५,०००", "is_correct": False},
                {"text_en": "Rs. 2,500 per person", "text_np": "प्रति व्यक्ति रु. २,५००", "is_correct": False},
            ],
            "explanation_en": "Under Nepal's Social Health Insurance Programme, the annual premium is Rs. 3,500 for a family of up to 5 members, with coverage of up to Rs. 100,000 per year.",
            "explanation_np": "नेपालको सामाजिक स्वास्थ्य बीमा कार्यक्रम अन्तर्गत ५ जनासम्मको परिवारको लागि वार्षिक बीमा शुल्क रु. ३,५०० हो, प्रतिवर्ष रु. १,००,००० सम्मको कभरेजसहित।",
            "difficulty": "HARD",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "Nepal's Health Sector Strategy (NHSS) 2015-2020 is aligned with which global framework?",
            "question_text_np": "नेपालको स्वास्थ्य क्षेत्र रणनीति (NHSS) २०१५-२०२० कुन विश्वव्यापी ढाँचासँग मिलाइएको छ?",
            "answers": [
                {"text_en": "Sustainable Development Goals (SDGs)", "text_np": "दिगो विकास लक्ष्यहरू (SDGs)", "is_correct": True},
                {"text_en": "Millennium Development Goals (MDGs)", "text_np": "सहस्राब्दी विकास लक्ष्यहरू (MDGs)", "is_correct": False},
                {"text_en": "Alma-Ata Declaration", "text_np": "अल्मा-अता घोषणा", "is_correct": False},
                {"text_en": "Paris Agreement", "text_np": "पेरिस सम्झौता", "is_correct": False},
            ],
            "explanation_en": "Nepal's Health Sector Strategy 2015-2020 was aligned with the Sustainable Development Goals, particularly SDG 3 (Good Health and Well-being) and the principle of Universal Health Coverage.",
            "explanation_np": "नेपालको स्वास्थ्य क्षेत्र रणनीति २०१५-२०२० दिगो विकास लक्ष्यहरूसँग, विशेष गरी SDG 3 (राम्रो स्वास्थ्य र कल्याण) र विश्वव्यापी स्वास्थ्य कभरेजको सिद्धान्तसँग मिलाइएको थियो।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the primary focus of Nepal's Multi-Sector Nutrition Plan (MSNP)?",
            "question_text_np": "नेपालको बहुक्षेत्रीय पोषण योजना (MSNP) को मुख्य केन्द्रबिन्दु के हो?",
            "answers": [
                {"text_en": "Addressing malnutrition through coordinated multi-sectoral approach", "text_np": "समन्वित बहुक्षेत्रीय दृष्टिकोणमार्फत कुपोषण सम्बोधन गर्ने", "is_correct": True},
                {"text_en": "Building nutrition rehabilitation centers", "text_np": "पोषण पुनर्स्थापना केन्द्रहरू निर्माण गर्ने", "is_correct": False},
                {"text_en": "Distributing food supplements to all citizens", "text_np": "सबै नागरिकलाई खाद्य पूरकहरू वितरण गर्ने", "is_correct": False},
                {"text_en": "Training doctors in nutrition science", "text_np": "पोषण विज्ञानमा चिकित्सकहरूलाई तालिम दिने", "is_correct": False},
            ],
            "explanation_en": "MSNP brings together health, agriculture, education, and WASH sectors to address malnutrition comprehensively, targeting the critical 1,000-day window from conception to age 2.",
            "explanation_np": "MSNP ले स्वास्थ्य, कृषि, शिक्षा र WASH क्षेत्रहरूलाई एकसाथ ल्याएर कुपोषणलाई व्यापक रूपमा सम्बोधन गर्दछ, गर्भधारणदेखि २ वर्ष उमेरसम्मको महत्त्वपूर्ण १,००० दिन अवधिलाई लक्षित गर्दै।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "Under Nepal's federal structure, which level of government is responsible for primary health care service delivery?",
            "question_text_np": "नेपालको सङ्घीय संरचना अन्तर्गत प्राथमिक स्वास्थ्य सेवा प्रदान गर्ने जिम्मेवारी कुन तहको सरकारको हो?",
            "answers": [
                {"text_en": "Local government (municipalities/rural municipalities)", "text_np": "स्थानीय सरकार (नगरपालिका/गाउँपालिका)", "is_correct": True},
                {"text_en": "Federal government", "text_np": "सङ्घीय सरकार", "is_correct": False},
                {"text_en": "Provincial government", "text_np": "प्रदेश सरकार", "is_correct": False},
                {"text_en": "All three levels equally", "text_np": "तीनै तह समान रूपमा", "is_correct": False},
            ],
            "explanation_en": "Under Nepal's Constitution 2015 and federal structure, primary health care delivery is the responsibility of local governments (municipalities and rural municipalities), while specialized and referral services are managed at provincial and federal levels.",
            "explanation_np": "नेपालको संविधान २०१५ र सङ्घीय संरचना अन्तर्गत प्राथमिक स्वास्थ्य सेवा प्रदान गर्ने जिम्मेवारी स्थानीय सरकार (नगरपालिका र गाउँपालिका) को हो, जबकि विशेष र रेफरल सेवाहरू प्रदेश र सङ्घीय तहमा व्यवस्थापन गरिन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What percentage of GDP does Nepal allocate to the health sector approximately?",
            "question_text_np": "नेपालले स्वास्थ्य क्षेत्रमा कुल गार्हस्थ्य उत्पादन (GDP) को लगभग कति प्रतिशत विनियोजन गर्दछ?",
            "answers": [
                {"text_en": "About 5-6%", "text_np": "लगभग ५-६%", "is_correct": True},
                {"text_en": "About 10-12%", "text_np": "लगभग १०-१२%", "is_correct": False},
                {"text_en": "About 2-3%", "text_np": "लगभग २-३%", "is_correct": False},
                {"text_en": "About 15-18%", "text_np": "लगभग १५-१८%", "is_correct": False},
            ],
            "explanation_en": "Nepal allocates approximately 5-6% of its GDP to the health sector, which includes government expenditure, external development partner funding, and out-of-pocket expenses.",
            "explanation_np": "नेपालले कुल गार्हस्थ्य उत्पादनको लगभग ५-६% स्वास्थ्य क्षेत्रमा विनियोजन गर्दछ, जसमा सरकारी खर्च, बाह्य विकास साझेदार कोष र आफ्नै खिसाबाट हुने खर्च समावेश छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Health Service",
        },
    ],
    # ── SUBBRANCH-scoped categories ────────────────────────────────────────
    "clinical-medicine": [
        {
            "question_text_en": "What is the most common cause of community-acquired pneumonia?",
            "question_text_np": "समुदायबाट प्राप्त निमोनियाको सबैभन्दा सामान्य कारण के हो?",
            "answers": [
                {"text_en": "Streptococcus pneumoniae", "text_np": "स्ट्रेप्टोकोकस निमोनिया", "is_correct": True},
                {"text_en": "Staphylococcus aureus", "text_np": "स्ट्याफिलोकोकस अरियस", "is_correct": False},
                {"text_en": "Klebsiella pneumoniae", "text_np": "क्लेब्सिएला निमोनिया", "is_correct": False},
                {"text_en": "Pseudomonas aeruginosa", "text_np": "स्यूडोमोनास एरुजिनोसा", "is_correct": False},
            ],
            "explanation_en": "Streptococcus pneumoniae (pneumococcus) is the most common cause of community-acquired pneumonia worldwide, accounting for approximately 30-40% of cases.",
            "explanation_np": "स्ट्रेप्टोकोकस निमोनिया (न्युमोकोकस) विश्वभर समुदायबाट प्राप्त निमोनियाको सबैभन्दा सामान्य कारण हो, लगभग ३०-४०% केसहरूमा पाइन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "Which investigation is the gold standard for diagnosing tuberculosis?",
            "question_text_np": "क्षयरोग निदानको लागि गोल्ड स्ट्यान्डर्ड जाँच कुन हो?",
            "answers": [
                {"text_en": "Sputum culture for Mycobacterium tuberculosis", "text_np": "माइकोब्याक्टेरियम ट्युबरकुलोसिसको लागि खकार कल्चर", "is_correct": True},
                {"text_en": "Chest X-ray", "text_np": "छातीको एक्स-रे", "is_correct": False},
                {"text_en": "Mantoux test", "text_np": "म्यान्टु परीक्षण", "is_correct": False},
                {"text_en": "Complete blood count", "text_np": "पूर्ण रक्त गणना", "is_correct": False},
            ],
            "explanation_en": "Sputum culture for Mycobacterium tuberculosis remains the gold standard for TB diagnosis, though GeneXpert MTB/RIF has become the WHO-recommended initial diagnostic test.",
            "explanation_np": "माइकोब्याक्टेरियम ट्युबरकुलोसिसको लागि खकार कल्चर TB निदानको गोल्ड स्ट्यान्डर्ड हो, यद्यपि GeneXpert MTB/RIF लाई WHO ले सिफारिस गरेको प्रारम्भिक निदान परीक्षणको रूपमा प्रयोग गरिन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the recommended first-line treatment for uncomplicated falciparum malaria in Nepal?",
            "question_text_np": "नेपालमा जटिलता नभएको फ्यालसिपेरम मलेरियाको लागि सिफारिस गरिएको प्रथम पङ्क्तिको उपचार के हो?",
            "answers": [
                {"text_en": "Artemisinin-based Combination Therapy (ACT)", "text_np": "आर्टेमिसिनिन-आधारित संयोजन चिकित्सा (ACT)", "is_correct": True},
                {"text_en": "Chloroquine alone", "text_np": "क्लोरोक्विन मात्र", "is_correct": False},
                {"text_en": "Quinine injection", "text_np": "क्विनिन इन्जेक्सन", "is_correct": False},
                {"text_en": "Mefloquine", "text_np": "मेफ्लोक्विन", "is_correct": False},
            ],
            "explanation_en": "Nepal follows WHO guidelines recommending Artemisinin-based Combination Therapy (ACT) as the first-line treatment for uncomplicated P. falciparum malaria due to widespread chloroquine resistance.",
            "explanation_np": "नेपालले WHO को दिशानिर्देश अनुसरण गर्दै व्यापक क्लोरोक्विन प्रतिरोधको कारण जटिलता नभएको P. falciparum मलेरियाको लागि ACT लाई प्रथम पङ्क्तिको उपचारको रूपमा सिफारिस गर्दछ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "Which clinical sign is pathognomonic for measles?",
            "question_text_np": "दादुराको लागि कुन नैदानिक चिन्ह विशिष्ट (pathognomonic) हो?",
            "answers": [
                {"text_en": "Koplik's spots", "text_np": "कोप्लिक्स स्पट्स", "is_correct": True},
                {"text_en": "Rose spots", "text_np": "रोज स्पट्स", "is_correct": False},
                {"text_en": "Janeway lesions", "text_np": "जेनवे लिजन्स", "is_correct": False},
                {"text_en": "Osler's nodes", "text_np": "ओस्लर्स नोड्स", "is_correct": False},
            ],
            "explanation_en": "Koplik's spots — small white spots on the buccal mucosa — appear 2-3 days before the measles rash and are pathognomonic (uniquely characteristic) for measles.",
            "explanation_np": "कोप्लिक्स स्पट्स — गालाको भित्री भागमा सानो सेतो थोप्लाहरू — दादुराको दाना आउनुभन्दा २-३ दिन अघि देखा पर्दछन् र दादुराको लागि विशिष्ट (pathognomonic) हुन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "A patient presents with sudden onset severe headache described as 'worst headache of life'. What is the most likely diagnosis?",
            "question_text_np": "एक बिरामीमा अचानक तीव्र टाउको दुखाइ देखिन्छ जसलाई 'जीवनको सबैभन्दा खराब टाउको दुखाइ' भनिएको छ। सबैभन्दा सम्भावित निदान के हो?",
            "answers": [
                {"text_en": "Subarachnoid hemorrhage", "text_np": "सबअर्याक्नोइड रक्तस्राव", "is_correct": True},
                {"text_en": "Migraine", "text_np": "माइग्रेन", "is_correct": False},
                {"text_en": "Tension headache", "text_np": "टेन्सन टाउको दुखाइ", "is_correct": False},
                {"text_en": "Sinusitis", "text_np": "साइनुसाइटिस", "is_correct": False},
            ],
            "explanation_en": "Sudden onset severe headache described as the 'worst headache of life' is the classic presentation of subarachnoid hemorrhage (SAH), usually caused by rupture of a cerebral aneurysm. This is a medical emergency requiring immediate CT scan.",
            "explanation_np": "'जीवनको सबैभन्दा खराब टाउको दुखाइ' भनिएको अचानक तीव्र टाउको दुखाइ सबअर्याक्नोइड रक्तस्राव (SAH) को शास्त्रीय प्रस्तुति हो, सामान्यतया सेरेब्रल एन्यूरिज्म फुट्दा हुन्छ। यो तुरुन्त CT स्क्यान आवश्यक पर्ने चिकित्सा आपतकालीन अवस्था हो।",
            "difficulty": "HARD",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the DOTS strategy in tuberculosis control?",
            "question_text_np": "क्षयरोग नियन्त्रणमा DOTS रणनीति भनेको के हो?",
            "answers": [
                {"text_en": "Directly Observed Treatment, Short-course", "text_np": "प्रत्यक्ष निगरानीमा उपचार, छोटो अवधि", "is_correct": True},
                {"text_en": "Daily Oral Treatment System", "text_np": "दैनिक मुखबाट उपचार प्रणाली", "is_correct": False},
                {"text_en": "Diagnostic and Observation Testing Strategy", "text_np": "निदान र अवलोकन परीक्षण रणनीति", "is_correct": False},
                {"text_en": "Drug-Oriented Therapy Standards", "text_np": "औषधि-उन्मुख चिकित्सा मापदण्ड", "is_correct": False},
            ],
            "explanation_en": "DOTS (Directly Observed Treatment, Short-course) is the WHO-recommended strategy for TB control where a health worker or trained volunteer watches the patient take each dose of medication to ensure adherence.",
            "explanation_np": "DOTS (प्रत्यक्ष निगरानीमा उपचार, छोटो अवधि) WHO द्वारा सिफारिस गरिएको TB नियन्त्रण रणनीति हो जहाँ स्वास्थ्य कर्मी वा प्रशिक्षित स्वयंसेवकले बिरामीलाई प्रत्येक मात्रा औषधि सेवन गर्दा निगरानी गर्दछन्।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
    ],
    "nursing-fundamentals-patient-care": [
        {
            "question_text_en": "What is the normal range for adult body temperature measured orally?",
            "question_text_np": "मुखबाट मापन गरिने वयस्कको शरीरको तापक्रमको सामान्य दायरा कति हो?",
            "answers": [
                {"text_en": "36.5°C to 37.5°C (97.7°F to 99.5°F)", "text_np": "३६.५°C देखि ३७.५°C (९७.७°F देखि ९९.५°F)", "is_correct": True},
                {"text_en": "35.0°C to 36.0°C (95.0°F to 96.8°F)", "text_np": "३५.०°C देखि ३६.०°C (९५.०°F देखि ९६.८°F)", "is_correct": False},
                {"text_en": "38.0°C to 39.0°C (100.4°F to 102.2°F)", "text_np": "३८.०°C देखि ३९.०°C (१००.४°F देखि १०२.२°F)", "is_correct": False},
                {"text_en": "34.0°C to 35.5°C (93.2°F to 95.9°F)", "text_np": "३४.०°C देखि ३५.५°C (९३.२°F देखि ९५.९°F)", "is_correct": False},
            ],
            "explanation_en": "Normal adult body temperature measured orally ranges from 36.5°C to 37.5°C. Temperature above 38°C (100.4°F) is generally considered fever.",
            "explanation_np": "मुखबाट मापन गरिने वयस्कको शरीरको सामान्य तापक्रम ३६.५°C देखि ३७.५°C सम्म हुन्छ। ३८°C (१००.४°F) भन्दा माथिको तापक्रमलाई सामान्यतया ज्वरो मानिन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the correct sequence of steps in the nursing process?",
            "question_text_np": "नर्सिङ प्रक्रियाका चरणहरूको सही क्रम के हो?",
            "answers": [
                {"text_en": "Assessment → Diagnosis → Planning → Implementation → Evaluation", "text_np": "मूल्याङ्कन → निदान → योजना → कार्यान्वयन → मूल्यांकन", "is_correct": True},
                {"text_en": "Diagnosis → Assessment → Planning → Implementation → Evaluation", "text_np": "निदान → मूल्याङ्कन → योजना → कार्यान्वयन → मूल्यांकन", "is_correct": False},
                {"text_en": "Planning → Diagnosis → Assessment → Implementation → Evaluation", "text_np": "योजना → निदान → मूल्याङ्कन → कार्यान्वयन → मूल्यांकन", "is_correct": False},
                {"text_en": "Assessment → Planning → Diagnosis → Evaluation → Implementation", "text_np": "मूल्याङ्कन → योजना → निदान → मूल्यांकन → कार्यान्वयन", "is_correct": False},
            ],
            "explanation_en": "The nursing process follows five sequential steps: Assessment (data collection), Diagnosis (identifying problems), Planning (setting goals), Implementation (executing care), and Evaluation (reviewing outcomes).",
            "explanation_np": "नर्सिङ प्रक्रियाले पाँच क्रमिक चरणहरू पालना गर्दछ: मूल्याङ्कन (तथ्यांक सङ्कलन), निदान (समस्या पहिचान), योजना (लक्ष्य निर्धारण), कार्यान्वयन (सेवा प्रदान), र मूल्यांकन (परिणाम समीक्षा)।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "How many drops per mL are delivered by a standard (macro) IV infusion set?",
            "question_text_np": "स्ट्यान्डर्ड (म्याक्रो) IV इन्फ्युजन सेटले प्रति mL कति थोपा दिन्छ?",
            "answers": [
                {"text_en": "15-20 drops/mL", "text_np": "१५-२० थोपा/mL", "is_correct": True},
                {"text_en": "60 drops/mL", "text_np": "६० थोपा/mL", "is_correct": False},
                {"text_en": "5 drops/mL", "text_np": "५ थोपा/mL", "is_correct": False},
                {"text_en": "100 drops/mL", "text_np": "१०० थोपा/mL", "is_correct": False},
            ],
            "explanation_en": "A standard macro IV infusion set delivers 15-20 drops per mL (commonly 20 drops/mL). A micro (pediatric) drip set delivers 60 drops per mL for more precise fluid delivery.",
            "explanation_np": "स्ट्यान्डर्ड म्याक्रो IV इन्फ्युजन सेटले प्रति mL १५-२० थोपा (सामान्यतया २० थोपा/mL) दिन्छ। माइक्रो (बालरोग) ड्रिप सेटले अधिक सटीक तरल पदार्थ प्रदानको लागि प्रति mL ६० थोपा दिन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What position should a patient be placed in for a lumbar puncture procedure?",
            "question_text_np": "लम्बर पंक्चर प्रक्रियाको लागि बिरामीलाई कुन स्थितिमा राख्नुपर्छ?",
            "answers": [
                {"text_en": "Lateral recumbent (fetal) position with knees drawn to chest", "text_np": "घुँडा छातीतिर तानेर छेउको भ्रूण स्थितिमा", "is_correct": True},
                {"text_en": "Supine position with legs elevated", "text_np": "खुट्टा उचालेर चित्त परेर सुत्ने स्थिति", "is_correct": False},
                {"text_en": "Prone position", "text_np": "भुँडीको बल सुत्ने स्थिति", "is_correct": False},
                {"text_en": "Trendelenburg position", "text_np": "ट्रेन्डेलनवर्ग स्थिति", "is_correct": False},
            ],
            "explanation_en": "For lumbar puncture, the patient is placed in the lateral recumbent (fetal) position with the back arched and knees drawn up to the chest. This opens the intervertebral spaces for easier needle insertion.",
            "explanation_np": "लम्बर पंक्चरको लागि बिरामीलाई छेउको भ्रूण स्थितिमा ढाड बाङ्गो पारी र घुँडा छातीतिर तानेर राखिन्छ। यसले सजिलो सुई प्रवेशको लागि कशेरुका बीचको खाली ठाउँ खोल्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the Glasgow Coma Scale (GCS) score of a fully conscious and oriented patient?",
            "question_text_np": "पूर्ण चेतनायुक्त र अभिमुखी बिरामीको ग्लासगो कोमा स्केल (GCS) स्कोर कति हुन्छ?",
            "answers": [
                {"text_en": "15", "text_np": "१५", "is_correct": True},
                {"text_en": "10", "text_np": "१०", "is_correct": False},
                {"text_en": "12", "text_np": "१२", "is_correct": False},
                {"text_en": "3", "text_np": "३", "is_correct": False},
            ],
            "explanation_en": "A fully conscious patient scores 15 on the GCS: Eye opening = 4 (spontaneous), Verbal response = 5 (oriented), Motor response = 6 (obeys commands). The minimum score is 3.",
            "explanation_np": "पूर्ण चेतनायुक्त बिरामीले GCS मा १५ अंक प्राप्त गर्दछ: आँखा खोल्ने = ४ (स्वतःस्फूर्त), मौखिक प्रतिक्रिया = ५ (अभिमुखी), मोटर प्रतिक्रिया = ६ (आदेश पालना)। न्यूनतम स्कोर ३ हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the correct angle for intramuscular (IM) injection?",
            "question_text_np": "इन्ट्रामस्कुलर (IM) सुई लगाउने सही कोण कति हो?",
            "answers": [
                {"text_en": "90 degrees", "text_np": "९० डिग्री", "is_correct": True},
                {"text_en": "15 degrees", "text_np": "१५ डिग्री", "is_correct": False},
                {"text_en": "45 degrees", "text_np": "४५ डिग्री", "is_correct": False},
                {"text_en": "10 degrees", "text_np": "१० डिग्री", "is_correct": False},
            ],
            "explanation_en": "Intramuscular injections are administered at a 90-degree angle to the skin to ensure the medication reaches the muscle tissue. Subcutaneous injections use 45 degrees, and intradermal uses 10-15 degrees.",
            "explanation_np": "इन्ट्रामस्कुलर सुई छालासँग ९० डिग्री कोणमा लगाइन्छ ताकि औषधि मांसपेशीको तन्तुमा पुगोस्। सबक्युटेनियस सुई ४५ डिग्री र इन्ट्राडर्मल सुई १०-१५ डिग्रीमा लगाइन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
    ],
    "midwifery-community-nursing": [
        {
            "question_text_en": "What is the recommended duration of exclusive breastfeeding according to WHO?",
            "question_text_np": "WHO अनुसार विशेष स्तनपानको सिफारिस गरिएको अवधि कति हो?",
            "answers": [
                {"text_en": "6 months", "text_np": "६ महिना", "is_correct": True},
                {"text_en": "3 months", "text_np": "३ महिना", "is_correct": False},
                {"text_en": "9 months", "text_np": "९ महिना", "is_correct": False},
                {"text_en": "12 months", "text_np": "१२ महिना", "is_correct": False},
            ],
            "explanation_en": "WHO recommends exclusive breastfeeding for the first 6 months of life, followed by continued breastfeeding with appropriate complementary foods up to 2 years or beyond.",
            "explanation_np": "WHO ले जीवनको पहिलो ६ महिनासम्म विशेष स्तनपान सिफारिस गर्दछ, त्यसपछि उपयुक्त पूरक आहारसहित २ वर्ष वा सोभन्दा बढी समयसम्म स्तनपान जारी राख्ने सिफारिस गर्दछ।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the normal duration of the first stage of labour in a primigravida?",
            "question_text_np": "पहिलो पटक गर्भवती (primigravida) मा प्रसवको पहिलो चरणको सामान्य अवधि कति हो?",
            "answers": [
                {"text_en": "12-16 hours", "text_np": "१२-१६ घण्टा", "is_correct": True},
                {"text_en": "2-4 hours", "text_np": "२-४ घण्टा", "is_correct": False},
                {"text_en": "24-30 hours", "text_np": "२४-३० घण्टा", "is_correct": False},
                {"text_en": "6-8 hours", "text_np": "६-८ घण्टा", "is_correct": False},
            ],
            "explanation_en": "The first stage of labour (from onset of regular contractions to full cervical dilation) typically lasts 12-16 hours in a primigravida and 6-8 hours in a multigravida.",
            "explanation_np": "प्रसवको पहिलो चरण (नियमित संकुचन सुरु भएदेखि पाठेघरको मुख पूर्ण खुलेसम्म) पहिलो पटक गर्भवतीमा सामान्यतया १२-१६ घण्टा र बहुगर्भवतीमा ६-८ घण्टा लाग्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the active management of the third stage of labour (AMTSL)?",
            "question_text_np": "प्रसवको तेस्रो चरणको सक्रिय व्यवस्थापन (AMTSL) भनेको के हो?",
            "answers": [
                {"text_en": "Administration of uterotonic, controlled cord traction, and uterine massage", "text_np": "गर्भाशय संकुचक औषधि, नियन्त्रित नालको तान, र गर्भाशय मालिश", "is_correct": True},
                {"text_en": "Waiting for spontaneous delivery of the placenta", "text_np": "प्लासेन्टाको स्वतःस्फूर्त प्रसवको प्रतीक्षा गर्ने", "is_correct": False},
                {"text_en": "Immediate cutting and clamping of the umbilical cord", "text_np": "नाभिनाल तुरुन्तै काट्ने र क्ल्याम्प गर्ने", "is_correct": False},
                {"text_en": "Manual removal of placenta", "text_np": "प्लासेन्टा हातले निकाल्ने", "is_correct": False},
            ],
            "explanation_en": "AMTSL includes three components: (1) administration of a uterotonic drug (oxytocin 10 IU IM) within 1 minute of birth, (2) controlled cord traction, and (3) uterine massage after placental delivery. This reduces postpartum hemorrhage risk.",
            "explanation_np": "AMTSL मा तीन घटकहरू छन्: (१) जन्मको १ मिनेटभित्र गर्भाशय संकुचक औषधि (अक्सिटोसिन १० IU IM) दिने, (२) नियन्त्रित नालको तान, र (३) प्लासेन्टा निस्किएपछि गर्भाशय मालिश। यसले प्रसवपश्चात् रक्तस्रावको जोखिम घटाउँछ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the most common cause of maternal mortality in Nepal?",
            "question_text_np": "नेपालमा मातृ मृत्युको सबैभन्दा सामान्य कारण के हो?",
            "answers": [
                {"text_en": "Postpartum hemorrhage", "text_np": "प्रसवपश्चात् रक्तस्राव", "is_correct": True},
                {"text_en": "Eclampsia", "text_np": "एक्ल्याम्पसिया", "is_correct": False},
                {"text_en": "Sepsis", "text_np": "सेप्सिस", "is_correct": False},
                {"text_en": "Obstructed labour", "text_np": "अवरुद्ध प्रसव", "is_correct": False},
            ],
            "explanation_en": "Postpartum hemorrhage (PPH) remains the leading cause of maternal mortality in Nepal, accounting for approximately 30% of all maternal deaths. This is why AMTSL and availability of uterotonics are critical interventions.",
            "explanation_np": "प्रसवपश्चात् रक्तस्राव (PPH) नेपालमा मातृ मृत्युको प्रमुख कारण हो, सबै मातृ मृत्युको लगभग ३०% भाग ओगट्दछ। यसैले AMTSL र गर्भाशय संकुचक औषधिको उपलब्धता महत्त्वपूर्ण हस्तक्षेप हुन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "At what cervical dilation is a woman considered to be in the active phase of the first stage of labour?",
            "question_text_np": "पाठेघरको मुख कति खुलेपछि महिलालाई प्रसवको पहिलो चरणको सक्रिय चरणमा मानिन्छ?",
            "answers": [
                {"text_en": "4 cm", "text_np": "४ से.मी.", "is_correct": True},
                {"text_en": "2 cm", "text_np": "२ से.मी.", "is_correct": False},
                {"text_en": "6 cm", "text_np": "६ से.मी.", "is_correct": False},
                {"text_en": "8 cm", "text_np": "८ से.मी.", "is_correct": False},
            ],
            "explanation_en": "The active phase of the first stage of labour begins at 4 cm cervical dilation with regular contractions. The latent phase is from 0-4 cm. Full dilation is 10 cm.",
            "explanation_np": "प्रसवको पहिलो चरणको सक्रिय चरण नियमित संकुचनसहित पाठेघरको मुख ४ से.मी. खुलेपछि सुरु हुन्छ। गुप्त चरण ०-४ से.मी. सम्म हुन्छ। पूर्ण विस्तार १० से.मी. हुन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the Apgar score assessed at?",
            "question_text_np": "Apgar स्कोर कुन समयमा मूल्याङ्कन गरिन्छ?",
            "answers": [
                {"text_en": "1 minute and 5 minutes after birth", "text_np": "जन्मपछि १ मिनेट र ५ मिनेटमा", "is_correct": True},
                {"text_en": "Immediately at birth only", "text_np": "जन्ममा तुरुन्तै मात्र", "is_correct": False},
                {"text_en": "10 minutes and 30 minutes after birth", "text_np": "जन्मपछि १० मिनेट र ३० मिनेटमा", "is_correct": False},
                {"text_en": "At 24 hours of life", "text_np": "जीवनको २४ घण्टामा", "is_correct": False},
            ],
            "explanation_en": "The Apgar score is routinely assessed at 1 minute and 5 minutes after birth. It evaluates Appearance, Pulse, Grimace, Activity, and Respiration on a scale of 0-10. A score of 7-10 is normal.",
            "explanation_np": "Apgar स्कोर नियमित रूपमा जन्मपछि १ मिनेट र ५ मिनेटमा मूल्याङ्कन गरिन्छ। यसले रूप, नाडी, प्रतिक्रिया, सक्रियता र श्वासप्रश्वासलाई ०-१० को स्केलमा मूल्याङ्कन गर्दछ। ७-१० को स्कोर सामान्य हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
    ],
    "medical-laboratory-science": [
        {
            "question_text_en": "What is the normal range of hemoglobin for an adult male?",
            "question_text_np": "वयस्क पुरुषको हेमोग्लोबिनको सामान्य दायरा कति हो?",
            "answers": [
                {"text_en": "13.5-17.5 g/dL", "text_np": "१३.५-१७.५ ग्राम/डेसीलिटर", "is_correct": True},
                {"text_en": "10.0-12.0 g/dL", "text_np": "१०.०-१२.० ग्राम/डेसीलिटर", "is_correct": False},
                {"text_en": "8.0-10.0 g/dL", "text_np": "८.०-१०.० ग्राम/डेसीलिटर", "is_correct": False},
                {"text_en": "18.0-22.0 g/dL", "text_np": "१८.०-२२.० ग्राम/डेसीलिटर", "is_correct": False},
            ],
            "explanation_en": "Normal hemoglobin for adult males is 13.5-17.5 g/dL and for adult females is 12.0-16.0 g/dL. Values below these ranges indicate anemia.",
            "explanation_np": "वयस्क पुरुषको सामान्य हेमोग्लोबिन १३.५-१७.५ ग्राम/डेसीलिटर र वयस्क महिलाको १२.०-१६.० ग्राम/डेसीलिटर हुन्छ। यी दायराभन्दा कम मान रक्तअल्पता (एनिमिया) सङ्केत गर्दछ।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "Which blood component is used for the treatment of hemophilia?",
            "question_text_np": "हेमोफिलियाको उपचारको लागि कुन रक्त घटक प्रयोग गरिन्छ?",
            "answers": [
                {"text_en": "Cryoprecipitate / Factor concentrates", "text_np": "क्रायोप्रेसिपिटेट / फ्याक्टर कन्सन्ट्रेट्स", "is_correct": True},
                {"text_en": "Packed red blood cells", "text_np": "प्याक्ड रातो रक्त कोशिकाहरू", "is_correct": False},
                {"text_en": "Platelet concentrate", "text_np": "प्लेटलेट कन्सन्ट्रेट", "is_correct": False},
                {"text_en": "Albumin", "text_np": "एल्बुमिन", "is_correct": False},
            ],
            "explanation_en": "Cryoprecipitate is rich in Factor VIII and fibrinogen, making it the blood component of choice for treating Hemophilia A. Factor concentrates (recombinant or plasma-derived) are now preferred when available.",
            "explanation_np": "क्रायोप्रेसिपिटेटमा फ्याक्टर VIII र फाइब्रिनोजेन प्रशस्त हुन्छ, जसले यसलाई हेमोफिलिया A को उपचारको लागि उपयुक्त रक्त घटक बनाउँछ। उपलब्ध भएमा फ्याक्टर कन्सन्ट्रेट्स (रिकम्बिनन्ट वा प्लाज्मा-व्युत्पन्न) अहिले प्राथमिकतामा छन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the anticoagulant used in EDTA tubes (purple top) for blood collection?",
            "question_text_np": "रक्त सङ्कलनको लागि EDTA ट्यूबहरू (बैजनी ढक्कन) मा प्रयोग हुने एन्टिकोएगुलेन्ट कुन हो?",
            "answers": [
                {"text_en": "Ethylenediaminetetraacetic acid (EDTA)", "text_np": "इथाइलिनडायमिनटेट्राएसेटिक एसिड (EDTA)", "is_correct": True},
                {"text_en": "Sodium citrate", "text_np": "सोडियम साइट्रेट", "is_correct": False},
                {"text_en": "Heparin", "text_np": "हेपारिन", "is_correct": False},
                {"text_en": "Potassium oxalate", "text_np": "पोटासियम अक्जालेट", "is_correct": False},
            ],
            "explanation_en": "EDTA (purple/lavender top tubes) chelates calcium ions to prevent coagulation. It is the standard anticoagulant for complete blood count (CBC) and blood film preparation.",
            "explanation_np": "EDTA (बैजनी/ल्याभेन्डर ढक्कनको ट्यूब) ले क्याल्सियम आयनहरू बाँध्छ र रक्त जम्न रोक्छ। यो पूर्ण रक्त गणना (CBC) र रक्त फिल्म तयारीको लागि मानक एन्टिकोएगुलेन्ट हो।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What does an elevated ESR (Erythrocyte Sedimentation Rate) indicate?",
            "question_text_np": "बढेको ESR (इरिथ्रोसाइट सेडिमेन्टेसन रेट) ले के सङ्केत गर्दछ?",
            "answers": [
                {"text_en": "Presence of inflammation or infection in the body", "text_np": "शरीरमा सूजन वा संक्रमणको उपस्थिति", "is_correct": True},
                {"text_en": "High blood sugar level", "text_np": "उच्च रक्त शर्करा स्तर", "is_correct": False},
                {"text_en": "Kidney failure", "text_np": "मिर्गौला विफलता", "is_correct": False},
                {"text_en": "Low platelet count", "text_np": "कम प्लेटलेट गणना", "is_correct": False},
            ],
            "explanation_en": "Elevated ESR is a non-specific marker indicating the presence of inflammation, infection, autoimmune disease, or malignancy. It measures how fast red blood cells settle in a tube over one hour.",
            "explanation_np": "बढेको ESR एक गैर-विशिष्ट सूचक हो जसले शरीरमा सूजन, संक्रमण, स्वप्रतिरक्षा रोग वा क्यान्सरको उपस्थिति सङ्केत गर्दछ। यसले एक घण्टामा ट्यूबमा रातो रक्त कोशिकाहरू कति छिटो बस्छन् मापन गर्दछ।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "Which staining technique is used for the diagnosis of acid-fast bacilli (AFB) in tuberculosis?",
            "question_text_np": "क्षयरोगमा एसिड-फास्ट ब्यासिलाई (AFB) को निदानको लागि कुन स्टेनिङ प्रविधि प्रयोग गरिन्छ?",
            "answers": [
                {"text_en": "Ziehl-Neelsen stain", "text_np": "जिल-नेल्सेन स्टेन", "is_correct": True},
                {"text_en": "Gram stain", "text_np": "ग्राम स्टेन", "is_correct": False},
                {"text_en": "Giemsa stain", "text_np": "गिम्सा स्टेन", "is_correct": False},
                {"text_en": "India ink stain", "text_np": "इन्डिया इंक स्टेन", "is_correct": False},
            ],
            "explanation_en": "Ziehl-Neelsen (ZN) staining is the standard technique for detecting acid-fast bacilli (AFB) in sputum samples for TB diagnosis. AFB appear red against a blue background.",
            "explanation_np": "जिल-नेल्सेन (ZN) स्टेनिङ TB निदानको लागि खकार नमूनाहरूमा एसिड-फास्ट ब्यासिलाई (AFB) पत्ता लगाउने मानक प्रविधि हो। AFB नीलो पृष्ठभूमिमा रातो देखिन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the principle of ELISA (Enzyme-Linked Immunosorbent Assay)?",
            "question_text_np": "ELISA (एन्जाइम-लिंक्ड इम्युनोसर्बेन्ट एसे) को सिद्धान्त के हो?",
            "answers": [
                {"text_en": "Antigen-antibody reaction detected by enzyme-substrate color change", "text_np": "एन्जाइम-सब्स्ट्रेट रंग परिवर्तनद्वारा पत्ता लगाइएको एन्टिजेन-एन्टिबडी प्रतिक्रिया", "is_correct": True},
                {"text_en": "DNA amplification using polymerase chain reaction", "text_np": "पोलिमरेज चेन रिएक्सन प्रयोग गरी DNA प्रवर्धन", "is_correct": False},
                {"text_en": "Separation of proteins by electrical charge", "text_np": "विद्युतीय चार्जद्वारा प्रोटिनहरूको विभाजन", "is_correct": False},
                {"text_en": "Direct visualization of bacteria under microscope", "text_np": "माइक्रोस्कोप मुनि ब्याक्टेरियाको प्रत्यक्ष अवलोकन", "is_correct": False},
            ],
            "explanation_en": "ELISA works on the principle of antigen-antibody binding, where an enzyme linked to an antibody produces a measurable color change when it reacts with a substrate, indicating the presence or quantity of the target analyte.",
            "explanation_np": "ELISA एन्टिजेन-एन्टिबडी बन्धनको सिद्धान्तमा काम गर्दछ, जहाँ एन्टिबडीसँग जोडिएको एन्जाइमले सब्स्ट्रेटसँग प्रतिक्रिया गर्दा मापनयोग्य रंग परिवर्तन उत्पादन गर्दछ, लक्षित विश्लेषणको उपस्थिति वा मात्रा सङ्केत गर्दै।",
            "difficulty": "HARD",
            "source_reference": "PSC Health Service",
        },
    ],
    "pharmacology-drug-management": [
        {
            "question_text_en": "Which drug is the first-line treatment for hypertension in Nepal according to national guidelines?",
            "question_text_np": "राष्ट्रिय दिशानिर्देश अनुसार नेपालमा उच्च रक्तचापको प्रथम पङ्क्तिको उपचारको लागि कुन औषधि प्रयोग गरिन्छ?",
            "answers": [
                {"text_en": "Amlodipine (Calcium channel blocker)", "text_np": "एम्लोडिपिन (क्याल्सियम च्यानल ब्लकर)", "is_correct": True},
                {"text_en": "Atenolol (Beta blocker)", "text_np": "एटेनोलोल (बीटा ब्लकर)", "is_correct": False},
                {"text_en": "Furosemide (Loop diuretic)", "text_np": "फुरोसेमाइड (लूप डाइयुरेटिक)", "is_correct": False},
                {"text_en": "Prazosin (Alpha blocker)", "text_np": "प्राजोसिन (अल्फा ब्लकर)", "is_correct": False},
            ],
            "explanation_en": "Amlodipine, a calcium channel blocker, is recommended as a first-line antihypertensive in Nepal's national guidelines. It is available as a generic drug in Nepal's essential drug list.",
            "explanation_np": "एम्लोडिपिन, एक क्याल्सियम च्यानल ब्लकर, नेपालको राष्ट्रिय दिशानिर्देशमा प्रथम पङ्क्तिको उच्च रक्तचाप विरोधी औषधिको रूपमा सिफारिस गरिएको छ। यो नेपालको अत्यावश्यक औषधि सूचीमा जेनेरिक औषधिको रूपमा उपलब्ध छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the mechanism of action of paracetamol (acetaminophen)?",
            "question_text_np": "प्यारासिटामोल (एसिटामिनोफेन) को क्रियाको तरिका के हो?",
            "answers": [
                {"text_en": "Inhibition of prostaglandin synthesis in the central nervous system", "text_np": "केन्द्रीय स्नायु प्रणालीमा प्रोस्टाग्ल्यान्डिन संश्लेषण अवरोध", "is_correct": True},
                {"text_en": "Blocking of opioid receptors", "text_np": "ओपिओइड रिसेप्टरहरूको अवरोध", "is_correct": False},
                {"text_en": "Direct anti-inflammatory action on tissues", "text_np": "तन्तुहरूमा प्रत्यक्ष सूजन विरोधी कार्य", "is_correct": False},
                {"text_en": "Blocking sodium channels in peripheral nerves", "text_np": "परिधीय स्नायुमा सोडियम च्यानलहरूको अवरोध", "is_correct": False},
            ],
            "explanation_en": "Paracetamol primarily works by inhibiting prostaglandin synthesis in the CNS, producing analgesic and antipyretic effects. Unlike NSAIDs, it has minimal peripheral anti-inflammatory activity.",
            "explanation_np": "प्यारासिटामोलले मुख्य रूपमा केन्द्रीय स्नायु प्रणालीमा प्रोस्टाग्ल्यान्डिन संश्लेषण अवरोध गरेर पीडानाशक र ज्वरोनाशक प्रभाव उत्पन्न गर्दछ। NSAIDs भन्दा फरक, यसमा न्यूनतम परिधीय सूजन विरोधी गतिविधि हुन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the maximum daily dose of paracetamol for an adult?",
            "question_text_np": "वयस्कको लागि प्यारासिटामोलको अधिकतम दैनिक मात्रा कति हो?",
            "answers": [
                {"text_en": "4 grams (4000 mg)", "text_np": "४ ग्राम (४००० मिलिग्राम)", "is_correct": True},
                {"text_en": "2 grams (2000 mg)", "text_np": "२ ग्राम (२००० मिलिग्राम)", "is_correct": False},
                {"text_en": "6 grams (6000 mg)", "text_np": "६ ग्राम (६००० मिलिग्राम)", "is_correct": False},
                {"text_en": "8 grams (8000 mg)", "text_np": "८ ग्राम (८००० मिलिग्राम)", "is_correct": False},
            ],
            "explanation_en": "The maximum recommended daily dose of paracetamol for adults is 4 grams (4000 mg). Exceeding this can cause severe hepatotoxicity (liver damage).",
            "explanation_np": "वयस्कको लागि प्यारासिटामोलको अधिकतम सिफारिस गरिएको दैनिक मात्रा ४ ग्राम (४००० मिलिग्राम) हो। यसभन्दा बढी सेवनले गम्भीर हेपाटोटोक्सिसिटी (कलेजो क्षति) हुन सक्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What does FEFO stand for in drug store management?",
            "question_text_np": "औषधि भण्डार व्यवस्थापनमा FEFO भनेको के हो?",
            "answers": [
                {"text_en": "First Expiry, First Out", "text_np": "पहिले म्याद सकिने, पहिले बाहिर", "is_correct": True},
                {"text_en": "First Entry, First Out", "text_np": "पहिले भित्रिने, पहिले बाहिर", "is_correct": False},
                {"text_en": "Fast Expiry, Fast Out", "text_np": "छिटो म्याद सकिने, छिटो बाहिर", "is_correct": False},
                {"text_en": "Final Expiry, Final Out", "text_np": "अन्तिम म्याद सकिने, अन्तिम बाहिर", "is_correct": False},
            ],
            "explanation_en": "FEFO (First Expiry, First Out) is the principle used in pharmaceutical inventory management where drugs with the earliest expiry date are dispensed first to minimize wastage from expired medicines.",
            "explanation_np": "FEFO (पहिले म्याद सकिने, पहिले बाहिर) औषधि सूची व्यवस्थापनमा प्रयोग हुने सिद्धान्त हो जहाँ म्याद सकिएका औषधिबाट हुने बर्बादी न्यूनीकरण गर्न सबैभन्दा पहिले म्याद सकिने औषधिहरू पहिले वितरण गरिन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "Which schedule of Nepal's Drug Act covers narcotic and psychotropic substances?",
            "question_text_np": "नेपालको औषधि ऐनको कुन अनुसूचीले लागूपदार्थ र मनोसक्रिय पदार्थहरू समेट्छ?",
            "answers": [
                {"text_en": "Schedule 'Ka' (A) — Narcotic drugs", "text_np": "अनुसूची 'क' — लागूपदार्थ", "is_correct": True},
                {"text_en": "Schedule 'Kha' (B) — General medicines", "text_np": "अनुसूची 'ख' — सामान्य औषधि", "is_correct": False},
                {"text_en": "Schedule 'Ga' (C) — Over-the-counter drugs", "text_np": "अनुसूची 'ग' — ओभर-द-काउन्टर औषधि", "is_correct": False},
                {"text_en": "Schedule 'Gha' (D) — Herbal medicines", "text_np": "अनुसूची 'घ' — जडीबुटी औषधि", "is_correct": False},
            ],
            "explanation_en": "Schedule 'Ka' (A) of Nepal's Drug Act lists narcotic and psychotropic substances that require strict licensing, record-keeping, and are subject to the highest level of regulatory control.",
            "explanation_np": "नेपालको औषधि ऐनको अनुसूची 'क' मा लागूपदार्थ र मनोसक्रिय पदार्थहरू सूचीकृत छन् जसलाई कडा इजाजतपत्र, अभिलेख राख्ने र उच्चतम स्तरको नियामक नियन्त्रणको अधीनमा राखिएको छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Health Service",
        },
        {
            "question_text_en": "What is the antidote for organophosphorus poisoning?",
            "question_text_np": "अर्गानोफस्फोरस विषाक्तताको विषनाशक (antidote) के हो?",
            "answers": [
                {"text_en": "Atropine and Pralidoxime (2-PAM)", "text_np": "एट्रोपिन र प्रालिडोक्सिम (2-PAM)", "is_correct": True},
                {"text_en": "N-Acetylcysteine", "text_np": "एन-एसिटाइलसिस्टिन", "is_correct": False},
                {"text_en": "Naloxone", "text_np": "न्यालोक्सोन", "is_correct": False},
                {"text_en": "Flumazenil", "text_np": "फ्लुमाजेनिल", "is_correct": False},
            ],
            "explanation_en": "Atropine (blocks muscarinic effects) and Pralidoxime/2-PAM (reactivates acetylcholinesterase) are the specific antidotes for organophosphorus poisoning, which is common in Nepal due to agricultural pesticide use.",
            "explanation_np": "एट्रोपिन (मस्करिनिक प्रभाव अवरोध गर्दछ) र प्रालिडोक्सिम/2-PAM (एसिटाइलकोलिनेस्टरेज पुनः सक्रिय गर्दछ) अर्गानोफस्फोरस विषाक्तताको विशिष्ट विषनाशक हुन्, जुन कृषि कीटनाशकको प्रयोगका कारण नेपालमा सामान्य छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Health Service",
        },
    ],
}
