"""History of Nepal (नेपालको इतिहास) — UNIVERSAL category questions."""

QUESTIONS = [
    {
        "question_text_en": "Who unified Nepal into a single nation-state?",
        "question_text_np": "नेपाललाई एक राष्ट्र-राज्यमा एकीकरण गर्ने को थिए?",
        "answers": [
            {"text_en": "Prithvi Narayan Shah", "text_np": "पृथ्वीनारायण शाह", "is_correct": True},
            {"text_en": "Amar Singh Thapa", "text_np": "अमर सिंह थापा", "is_correct": False},
            {"text_en": "Bhimsen Thapa", "text_np": "भीमसेन थापा", "is_correct": False},
            {"text_en": "Ram Shah", "text_np": "राम शाह", "is_correct": False},
        ],
        "explanation_en": "Prithvi Narayan Shah, the ruler of Gorkha, unified Nepal through a series of conquests between 1743 and 1775. He captured Kathmandu Valley in 1768 and made Kathmandu the capital.",
        "explanation_np": "गोरखाका शासक पृथ्वीनारायण शाहले १७४३ देखि १७७५ बीच एक श्रृंखला विजयहरूमार्फत नेपाललाई एकीकरण गरे। उनले १७६८ मा काठमाडौं उपत्यका जिते र काठमाडौंलाई राजधानी बनाए।",
        "difficulty": "EASY",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "In which year did Nepal become a republic?",
        "question_text_np": "नेपाल कुन वर्षमा गणतन्त्र बनेको थियो?",
        "answers": [
            {"text_en": "2008 A.D. (2065 B.S.)", "text_np": "२००८ ई. (२०६५ वि.सं.)", "is_correct": True},
            {"text_en": "2006 A.D.", "text_np": "२००६ ई.", "is_correct": False},
            {"text_en": "2015 A.D.", "text_np": "२०१५ ई.", "is_correct": False},
            {"text_en": "2001 A.D.", "text_np": "२००१ ई.", "is_correct": False},
        ],
        "explanation_en": "Nepal was declared a Federal Democratic Republic on May 28, 2008 (Jestha 15, 2065 B.S.) by the Constituent Assembly, ending 240 years of Shah dynasty rule.",
        "explanation_np": "नेपाललाई संविधान सभाद्वारा २०६५ वि.सं. जेठ १५ (मे २८, २००८ ई.) मा संघीय लोकतान्त्रिक गणतन्त्र घोषणा गरिएको थियो, जसले शाह वंशको २४० वर्षको शासनको अन्त गर्यो।",
        "difficulty": "EASY",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "The Sugauli Treaty of 1816 was signed between Nepal and which colonial power?",
        "question_text_np": "सन् १८१६ को सुगौली सन्धि नेपाल र कुन औपनिवेशिक शक्तिबीच हस्ताक्षर भएको थियो?",
        "answers": [
            {"text_en": "British East India Company", "text_np": "ब्रिटिश ईस्ट इन्डिया कम्पनी", "is_correct": True},
            {"text_en": "Chinese Qing Dynasty", "text_np": "चिनियाँ किङ राजवंश", "is_correct": False},
            {"text_en": "French Colonial Government", "text_np": "फ्रान्सेली औपनिवेशिक सरकार", "is_correct": False},
            {"text_en": "Dutch East India Company", "text_np": "डच ईस्ट इन्डिया कम्पनी", "is_correct": False},
        ],
        "explanation_en": "The Sugauli Treaty (1816) was signed between Nepal and the British East India Company after the Anglo-Nepalese War (1814-1816). Nepal ceded Sikkim, Kumaon, Garhwal, and the Terai regions.",
        "explanation_np": "सुगौली सन्धि (१८१६) नेपाल-ब्रिटेन युद्ध (१८१४-१८१६) पश्चात नेपाल र ब्रिटिश ईस्ट इन्डिया कम्पनीबीच हस्ताक्षर भएको थियो। नेपालले सिक्किम, कुमाउँ, गढवाल र तराई क्षेत्रहरू गुमायो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "The Rana oligarchy came to power in Nepal in which year?",
        "question_text_np": "राणा शासन नेपालमा कुन वर्षमा सत्तामा आएको थियो?",
        "answers": [
            {"text_en": "1846 A.D.", "text_np": "१८४६ ई.", "is_correct": True},
            {"text_en": "1816 A.D.", "text_np": "१८१६ ई.", "is_correct": False},
            {"text_en": "1900 A.D.", "text_np": "१९०० ई.", "is_correct": False},
            {"text_en": "1768 A.D.", "text_np": "१७६८ ई.", "is_correct": False},
        ],
        "explanation_en": "Jung Bahadur Rana came to power in 1846 after the Kot Massacre (Kot Parba). He established the Rana oligarchy, which ruled Nepal for 104 years until 1950.",
        "explanation_np": "जंगबहादुर राणाले कोत पर्व (कोत हत्याकाण्ड) पछि १८४६ मा सत्ता हासिल गरे। उनले राणा शासन स्थापना गरे, जसले १०४ वर्ष — सन् १९५० सम्म — नेपाललाई शासन गर्यो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "Nepal's first democratic election was held in which year?",
        "question_text_np": "नेपालको पहिलो प्रजातान्त्रिक निर्वाचन कुन वर्षमा भएको थियो?",
        "answers": [
            {"text_en": "1959 A.D.", "text_np": "१९५९ ई.", "is_correct": True},
            {"text_en": "1951 A.D.", "text_np": "१९५१ ई.", "is_correct": False},
            {"text_en": "1963 A.D.", "text_np": "१९६३ ई.", "is_correct": False},
            {"text_en": "1990 A.D.", "text_np": "१९९० ई.", "is_correct": False},
        ],
        "explanation_en": "Nepal held its first democratic parliamentary election in February 1959. The Nepali Congress party won a landslide majority. However, King Mahendra dismissed the parliament and banned political parties in 1960.",
        "explanation_np": "नेपालले फेब्रुअरी १९५९ मा पहिलो प्रजातान्त्रिक संसदीय निर्वाचन गर्यो। नेपाली कांग्रेसले भारी बहुमत प्राप्त गर्यो। तर राजा महेन्द्रले १९६० मा संसद विघटन गरी राजनीतिक दलहरूमाथि प्रतिबन्ध लगाए।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "The Panchayat system in Nepal was introduced by which king?",
        "question_text_np": "नेपालमा पञ्चायत प्रणाली कुन राजाले ल्याएका थिए?",
        "answers": [
            {"text_en": "King Mahendra", "text_np": "राजा महेन्द्र", "is_correct": True},
            {"text_en": "King Tribhuvan", "text_np": "राजा त्रिभुवन", "is_correct": False},
            {"text_en": "King Birendra", "text_np": "राजा वीरेन्द्र", "is_correct": False},
            {"text_en": "King Prithvi Narayan Shah", "text_np": "राजा पृथ्वीनारायण शाह", "is_correct": False},
        ],
        "explanation_en": "King Mahendra introduced the partyless Panchayat system in 1960 after dissolving the elected parliament. The system lasted until 1990 when people's movement (Jana Andolan I) forced its end.",
        "explanation_np": "राजा महेन्द्रले निर्वाचित संसद विघटन गरेपछि १९६० मा दलविहीन पञ्चायत प्रणाली ल्याए। यो प्रणाली १९९० सम्म चल्यो जब जन आन्दोलन (जन आन्दोलन I) ले यसको अन्त गर्न बाध्य बनायो।",
        "difficulty": "EASY",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "The first People's Movement (Jana Andolan I) in Nepal took place in which year?",
        "question_text_np": "नेपालमा पहिलो जन आन्दोलन (जन आन्दोलन I) कुन वर्षमा भएको थियो?",
        "answers": [
            {"text_en": "1990 A.D.", "text_np": "१९९० ई.", "is_correct": True},
            {"text_en": "1985 A.D.", "text_np": "१९८५ ई.", "is_correct": False},
            {"text_en": "2006 A.D.", "text_np": "२००६ ई.", "is_correct": False},
            {"text_en": "1979 A.D.", "text_np": "१९७९ ई.", "is_correct": False},
        ],
        "explanation_en": "The 1990 People's Movement (Jana Andolan I) forced King Birendra to lift the ban on political parties and introduce multi-party democracy. A new democratic constitution was promulgated in 1990.",
        "explanation_np": "१९९० को जन आन्दोलन (जन आन्दोलन I) ले राजा वीरेन्द्रलाई राजनीतिक दलहरूमाथिको प्रतिबन्ध हटाउन र बहुदलीय लोकतन्त्र ल्याउन बाध्य बनायो। १९९० मा नयाँ लोकतान्त्रिक संविधान जारी गरियो।",
        "difficulty": "EASY",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "The Maoist insurgency in Nepal officially began in which year?",
        "question_text_np": "नेपालमा माओवादी सशस्त्र द्वन्द्व आधिकारिक रूपमा कुन वर्षमा सुरु भएको थियो?",
        "answers": [
            {"text_en": "1996 A.D.", "text_np": "१९९६ ई.", "is_correct": True},
            {"text_en": "1990 A.D.", "text_np": "१९९० ई.", "is_correct": False},
            {"text_en": "2001 A.D.", "text_np": "२००१ ई.", "is_correct": False},
            {"text_en": "2000 A.D.", "text_np": "२००० ई.", "is_correct": False},
        ],
        "explanation_en": "The Communist Party of Nepal (Maoist) launched its 'People's War' on February 13, 1996. The decade-long conflict ended with the Comprehensive Peace Agreement signed on November 21, 2006.",
        "explanation_np": "नेपाल कम्युनिस्ट पार्टी (माओवादी) ले फेब्रुअरी १३, १९९६ मा 'जनयुद्ध' सुरु गर्यो। दशवर्षीय द्वन्द्व नोभेम्बर २१, २००६ मा हस्ताक्षर भएको विस्तृत शान्ति सम्झौताले अन्त भयो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "Who was the last King of Nepal?",
        "question_text_np": "नेपालका अन्तिम राजा को थिए?",
        "answers": [
            {"text_en": "Gyanendra Shah", "text_np": "ज्ञानेन्द्र शाह", "is_correct": True},
            {"text_en": "Birendra Shah", "text_np": "वीरेन्द्र शाह", "is_correct": False},
            {"text_en": "Dipendra Shah", "text_np": "दीपेन्द्र शाह", "is_correct": False},
            {"text_en": "Mahendra Shah", "text_np": "महेन्द्र शाह", "is_correct": False},
        ],
        "explanation_en": "Gyanendra Shah was the last King of Nepal. He became king after the 2001 Royal Palace Massacre. He was deposed when Nepal was declared a republic in May 2008.",
        "explanation_np": "ज्ञानेन्द्र शाह नेपालका अन्तिम राजा थिए। उनी २००१ को दरबार हत्याकाण्डपछि राजा भए। मे २००८ मा नेपाललाई गणतन्त्र घोषणा गरिँदा उनलाई पदच्युत गरियो।",
        "difficulty": "EASY",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "The Kot Massacre (Kot Parba) in 1846 took place during the reign of which king?",
        "question_text_np": "सन् १८४६ को कोत हत्याकाण्ड (कोत पर्व) कुन राजाको शासनकालमा भएको थियो?",
        "answers": [
            {"text_en": "King Rajendra Bikram Shah", "text_np": "राजा राजेन्द्र विक्रम शाह", "is_correct": True},
            {"text_en": "King Girvan Yuddha Bikram Shah", "text_np": "राजा गिर्वाण युद्ध विक्रम शाह", "is_correct": False},
            {"text_en": "King Surendra Bikram Shah", "text_np": "राजा सुरेन्द्र विक्रम शाह", "is_correct": False},
            {"text_en": "King Prithvi Narayan Shah", "text_np": "राजा पृथ्वीनारायण शाह", "is_correct": False},
        ],
        "explanation_en": "The Kot Massacre occurred in 1846 during the reign of King Rajendra Bikram Shah. Jung Bahadur Rana orchestrated the massacre to eliminate rivals and seize power as Prime Minister.",
        "explanation_np": "कोत हत्याकाण्ड १८४६ मा राजा राजेन्द्र विक्रम शाहको शासनकालमा भएको थियो। जंगबहादुर राणाले प्रतिद्वन्द्वीहरू सफाया गरी प्रधानमन्त्रीका रूपमा सत्ता कब्जा गर्न यो योजना बनाएका थिए।",
        "difficulty": "HARD",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "Which treaty ended the Anglo-Nepalese War and fixed Nepal's current borders?",
        "question_text_np": "कुन सन्धिले एंग्लो-नेपाल युद्धको अन्त गर्यो र नेपालको वर्तमान सिमाना निर्धारण गर्यो?",
        "answers": [
            {"text_en": "Treaty of Sugauli (1816)", "text_np": "सुगौली सन्धि (१८१६)", "is_correct": True},
            {"text_en": "Treaty of Thapathali (1856)", "text_np": "थापाथली सन्धि (१८५६)", "is_correct": False},
            {"text_en": "Treaty of Segauli (1814)", "text_np": "सेगाउली सन्धि (१८१४)", "is_correct": False},
            {"text_en": "Friendship Treaty of 1950", "text_np": "शान्ति तथा मैत्री सन्धि (१९५०)", "is_correct": False},
        ],
        "explanation_en": "The Treaty of Sugauli (1816) ended the Anglo-Nepalese War and established Nepal's present-day borders. Nepal lost approximately one-third of its territory including Sikkim, Garhwal, and western Terai.",
        "explanation_np": "सुगौली सन्धि (१८१६) ले एंग्लो-नेपाल युद्धको अन्त गर्यो र नेपालको हालको सिमाना स्थापना गर्यो। नेपालले सिक्किम, गढवाल र पश्चिमी तराई सहित आफ्नो करिब एक तिहाई भूभाग गुमायो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "The Licchavi period in Nepal's history is associated with which major cultural achievement?",
        "question_text_np": "नेपालको इतिहासमा लिच्छवी कालसँग कुन प्रमुख सांस्कृतिक उपलब्धि सम्बन्धित छ?",
        "answers": [
            {"text_en": "Development of the Devnagari script and flourishing of art and architecture", "text_np": "देवनागरी लिपिको विकास र कला तथा वास्तुकलाको फस्टाउनु", "is_correct": True},
            {"text_en": "Introduction of the Panchayat system", "text_np": "पञ्चायत प्रणालीको परिचय", "is_correct": False},
            {"text_en": "First unification of Nepal", "text_np": "नेपालको पहिलो एकीकरण", "is_correct": False},
            {"text_en": "Establishment of the first democracy", "text_np": "पहिलो प्रजातन्त्रको स्थापना", "is_correct": False},
        ],
        "explanation_en": "The Licchavi period (400-750 AD approx.) was a golden age for Nepal, known for the development of arts, architecture, trade with Tibet and India, and early Hindu-Buddhist cultural synthesis.",
        "explanation_np": "लिच्छवी काल (लगभग ४००-७५० ई.) नेपालको स्वर्णकाल थियो, जो कला, वास्तुकला, तिब्बत र भारतसँग व्यापार र प्रारम्भिक हिन्दू-बौद्ध सांस्कृतिक समन्वयका लागि प्रसिद्ध थियो।",
        "difficulty": "HARD",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "Who was the first Prime Minister of Nepal after the restoration of democracy in 1990?",
        "question_text_np": "सन् १९९० मा प्रजातन्त्रको पुनःस्थापनापछि नेपालको पहिलो प्रधानमन्त्री को थिए?",
        "answers": [
            {"text_en": "Krishna Prasad Bhattarai", "text_np": "कृष्णप्रसाद भट्टराई", "is_correct": True},
            {"text_en": "Girija Prasad Koirala", "text_np": "गिरिजाप्रसाद कोइराला", "is_correct": False},
            {"text_en": "Ganesh Man Singh", "text_np": "गणेशमान सिंह", "is_correct": False},
            {"text_en": "Man Mohan Adhikari", "text_np": "मनमोहन अधिकारी", "is_correct": False},
        ],
        "explanation_en": "Krishna Prasad Bhattarai (Kishunji) became Nepal's first Prime Minister after the 1990 Jana Andolan and served as the interim PM until the 1991 elections.",
        "explanation_np": "कृष्णप्रसाद भट्टराई (किशुनजी) १९९० को जन आन्दोलनपछि नेपालका पहिलो प्रधानमन्त्री बने र १९९१ को निर्वाचनसम्म अन्तरिम प्रधानमन्त्रीका रूपमा कार्य गरे।",
        "difficulty": "HARD",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "The Royal Nepal Palace Massacre occurred in which year?",
        "question_text_np": "नेपाल दरबार हत्याकाण्ड कुन वर्षमा भएको थियो?",
        "answers": [
            {"text_en": "2001 A.D.", "text_np": "२००१ ई.", "is_correct": True},
            {"text_en": "1999 A.D.", "text_np": "१९९९ ई.", "is_correct": False},
            {"text_en": "2003 A.D.", "text_np": "२००३ ई.", "is_correct": False},
            {"text_en": "2006 A.D.", "text_np": "२००६ ई.", "is_correct": False},
        ],
        "explanation_en": "The Royal Palace Massacre occurred on June 1, 2001, resulting in the deaths of King Birendra, Queen Aishwarya, and several other royal family members. Crown Prince Dipendra is held responsible.",
        "explanation_np": "दरबार हत्याकाण्ड जुन १, २००१ मा भएको थियो, जसमा राजा वीरेन्द्र, रानी ऐश्वर्य र अन्य धेरै शाही परिवारका सदस्यहरूको मृत्यु भयो। युवराज दीपेन्द्रलाई जिम्मेवार ठानिएको छ।",
        "difficulty": "EASY",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "The Second People's Movement (Jana Andolan II) in 2006 led to what major outcome?",
        "question_text_np": "२००६ को दोस्रो जन आन्दोलन (जन आन्दोलन II) ले कुन प्रमुख परिणाम दियो?",
        "answers": [
            {"text_en": "Reinstatement of Parliament and end of absolute monarchy", "text_np": "संसद पुनःस्थापना र निरंकुश राजतन्त्रको अन्त", "is_correct": True},
            {"text_en": "Nepal declared a republic immediately", "text_np": "नेपाललाई तुरुन्त गणतन्त्र घोषणा गरियो", "is_correct": False},
            {"text_en": "New constitution was promulgated", "text_np": "नयाँ संविधान जारी गरियो", "is_correct": False},
            {"text_en": "Maoist party was banned", "text_np": "माओवादी पार्टीमाथि प्रतिबन्ध लगाइयो", "is_correct": False},
        ],
        "explanation_en": "Jana Andolan II (April 2006) forced King Gyanendra to reinstate Parliament. This led to the Comprehensive Peace Agreement with Maoists (November 2006), ending the civil war. Nepal became a republic in 2008.",
        "explanation_np": "जन आन्दोलन II (अप्रिल २००६) ले राजा ज्ञानेन्द्रलाई संसद पुनःस्थापना गर्न बाध्य बनायो। यसले माओवादीसँग विस्तृत शान्ति सम्झौता (नोभेम्बर २००६) र गृहयुद्धको अन्त गर्यो। नेपाल २००८ मा गणतन्त्र बन्यो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "Nepal's current constitution was promulgated in which year?",
        "question_text_np": "नेपालको वर्तमान संविधान कुन वर्षमा जारी गरिएको थियो?",
        "answers": [
            {"text_en": "2015 A.D. (2072 B.S.)", "text_np": "२०१५ ई. (२०७२ वि.सं.)", "is_correct": True},
            {"text_en": "2008 A.D.", "text_np": "२००८ ई.", "is_correct": False},
            {"text_en": "2006 A.D.", "text_np": "२००६ ई.", "is_correct": False},
            {"text_en": "1990 A.D.", "text_np": "१९९० ई.", "is_correct": False},
        ],
        "explanation_en": "Nepal's current constitution — the Constitution of Nepal 2072 B.S. — was promulgated on September 20, 2015 (Asoj 3, 2072 B.S.). It established Nepal as a Federal Democratic Republic.",
        "explanation_np": "नेपालको वर्तमान संविधान — नेपालको संविधान २०७२ वि.सं. — २०१५ सेप्टेम्बर २० (२०७२ असोज ३) मा जारी गरिएको थियो। यसले नेपाललाई संघीय लोकतान्त्रिक गणतन्त्रका रूपमा स्थापना गर्यो।",
        "difficulty": "EASY",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "Which king abolished the slave trade in Nepal?",
        "question_text_np": "नेपालमा दास प्रथा उन्मूलन गर्ने राजा को थिए?",
        "answers": [
            {"text_en": "King Chandra Shumsher Rana (as PM)", "text_np": "प्रधानमन्त्री चन्द्र शम्शेर राणा", "is_correct": True},
            {"text_en": "King Tribhuvan", "text_np": "राजा त्रिभुवन", "is_correct": False},
            {"text_en": "Jung Bahadur Rana (as PM)", "text_np": "प्रधानमन्त्री जंगबहादुर राणा", "is_correct": False},
            {"text_en": "King Mahendra", "text_np": "राजा महेन्द्र", "is_correct": False},
        ],
        "explanation_en": "Prime Minister Chandra Shumsher Rana abolished slavery in Nepal in 1924 (1981 B.S.). He freed approximately 60,000 slaves, a landmark reform in Nepalese history.",
        "explanation_np": "प्रधानमन्त्री चन्द्र शम्शेर राणाले नेपालमा सन् १९२४ (१९८१ वि.सं.) मा दास प्रथा उन्मूलन गरे। उनले लगभग ६०,००० दासहरू मुक्त गरे, जुन नेपाली इतिहासमा एक ऐतिहासिक सुधार हो।",
        "difficulty": "HARD",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "King Tribhuvan is historically significant in Nepal because he:",
        "question_text_np": "राजा त्रिभुवन ऐतिहासिक रूपमा नेपालमा किन महत्त्वपूर्ण छन्?",
        "answers": [
            {"text_en": "Led the movement that ended Rana rule and restored democracy in 1951", "text_np": "राणा शासनको अन्त गर्न र १९५१ मा प्रजातन्त्र पुनःस्थापना गर्ने आन्दोलन नेतृत्व गरे", "is_correct": True},
            {"text_en": "First introduced the Panchayat system", "text_np": "पहिलोपटक पञ्चायत प्रणाली ल्याए", "is_correct": False},
            {"text_en": "Signed the Sugauli Treaty with the British", "text_np": "ब्रिटिशसँग सुगौली सन्धिमा हस्ताक्षर गरे", "is_correct": False},
            {"text_en": "Unified Nepal into one kingdom", "text_np": "नेपाललाई एक राज्यमा एकीकरण गरे", "is_correct": False},
        ],
        "explanation_en": "King Tribhuvan fled to the Indian Embassy in Kathmandu in 1950, which triggered the downfall of Rana rule. He returned in 1951 to restore multi-party democracy and is known as 'Father of the Nation' (Rastraka Pita).",
        "explanation_np": "राजा त्रिभुवन १९५० मा काठमाडौंस्थित भारतीय दूतावासमा शरण लिए, जसले राणा शासनको पतनलाई गति दियो। उनी १९५१ मा बहुदलीय प्रजातन्त्र पुनःस्थापना गर्न फर्किए र 'राष्ट्रका पिता' (राष्ट्रपिता) भनेर चिनिन्छन्।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "When did Nepal join the Non-Aligned Movement (NAM)?",
        "question_text_np": "नेपाल गुटनिरपेक्ष आन्दोलन (NAM) मा कहिले सामेल भयो?",
        "answers": [
            {"text_en": "1961 A.D.", "text_np": "१९६१ ई.", "is_correct": True},
            {"text_en": "1955 A.D.", "text_np": "१९५५ ई.", "is_correct": False},
            {"text_en": "1975 A.D.", "text_np": "१९७५ ई.", "is_correct": False},
            {"text_en": "1970 A.D.", "text_np": "१९७० ई.", "is_correct": False},
        ],
        "explanation_en": "Nepal became a founding member of the Non-Aligned Movement at the Belgrade Conference in 1961. Nepal's foreign policy has traditionally been based on the principles of non-alignment and Panchasheel.",
        "explanation_np": "नेपाल १९६१ मा बेलग्रेड सम्मेलनमा गुटनिरपेक्ष आन्दोलनको संस्थापक सदस्य बन्यो। नेपालको परराष्ट्र नीति परम्परागत रूपमा गुटनिरपेक्षता र पञ्चशीलका सिद्धान्तमा आधारित छ।",
        "difficulty": "HARD",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "Tenzing Norgay Sherpa and Edmund Hillary first climbed Mount Everest in which year?",
        "question_text_np": "तेन्जिङ नोर्गे शेर्पा र एडमण्ड हिलारीले माउन्ट एभरेस्ट पहिलोपटक कुन वर्षमा आरोहण गरे?",
        "answers": [
            {"text_en": "1953 A.D.", "text_np": "१९५३ ई.", "is_correct": True},
            {"text_en": "1950 A.D.", "text_np": "१९५० ई.", "is_correct": False},
            {"text_en": "1960 A.D.", "text_np": "१९६० ई.", "is_correct": False},
            {"text_en": "1948 A.D.", "text_np": "१९४८ ई.", "is_correct": False},
        ],
        "explanation_en": "Tenzing Norgay Sherpa (Nepal) and Sir Edmund Hillary (New Zealand) made the first successful ascent of Mount Everest on May 29, 1953, as part of a British expedition led by John Hunt.",
        "explanation_np": "तेन्जिङ नोर्गे शेर्पा (नेपाल) र सर एडमण्ड हिलारी (न्युजिल्यान्ड) ले मे २९, १९५३ मा जोन हन्टको नेतृत्वमा एउटा ब्रिटिश अभियानको भागको रूपमा माउन्ट एभरेस्टको पहिलो सफल आरोहण गरे।",
        "difficulty": "EASY",
        "source_reference": "PSC History of Nepal",
    },
    {
        "question_text_en": "The Muluki Ain (Civil Code) in Nepal was first enacted in which year?",
        "question_text_np": "नेपालमा मुलुकी ऐन (नागरिक संहिता) पहिलोपटक कुन वर्षमा जारी भएको थियो?",
        "answers": [
            {"text_en": "1910 B.S. (1853 A.D.)", "text_np": "१९१० वि.सं. (१८५३ ई.)", "is_correct": True},
            {"text_en": "1950 B.S.", "text_np": "१९५० वि.सं.", "is_correct": False},
            {"text_en": "2020 B.S.", "text_np": "२०२० वि.सं.", "is_correct": False},
            {"text_en": "1846 A.D.", "text_np": "१८४६ ई.", "is_correct": False},
        ],
        "explanation_en": "The first Muluki Ain (National/Civil Code) was enacted in 1910 B.S. (1853 A.D.) during the Rana period under Jung Bahadur Rana. It was Nepal's first comprehensive legal code. A new Muluki Ain was enacted in 2020 B.S. and updated again in 2074 B.S.",
        "explanation_np": "पहिलो मुलुकी ऐन (राष्ट्रिय/नागरिक संहिता) राणाकालमा जंगबहादुर राणाको पालामा १९१० वि.सं. (१८५३ ई.) मा जारी भएको थियो। यो नेपालको पहिलो व्यापक कानुनी संहिता थियो।",
        "difficulty": "HARD",
        "source_reference": "PSC History of Nepal",
    },
]