"""Judicial Service — BRANCH category questions."""

QUESTIONS = {
    # ─── BRANCH-scoped categories ────────────────────────────────────────
    "legal-system-nepal": [
        {
            "question_text_en": "What is the highest court in Nepal's judicial hierarchy?",
            "question_text_np": "नेपालको न्यायिक पदसोपानमा सर्वोच्च अदालत कुन हो?",
            "answers": [
                {"text_en": "Supreme Court", "text_np": "सर्वोच्च अदालत", "is_correct": True},
                {"text_en": "High Court", "text_np": "उच्च अदालत", "is_correct": False},
                {"text_en": "District Court", "text_np": "जिल्ला अदालत", "is_correct": False},
                {"text_en": "Appellate Court", "text_np": "पुनरावेदन अदालत", "is_correct": False},
            ],
            "explanation_en": "The Supreme Court of Nepal is the highest court and the court of last resort. It is established under Part 11 of the Constitution of Nepal, 2072.",
            "explanation_np": "नेपालको सर्वोच्च अदालत सर्वोच्च अदालत हो र अन्तिम उपायको अदालत हो। यो नेपालको संविधान, २०७२ को भाग ११ अन्तर्गत स्थापित छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Legal System",
        },
        {
            "question_text_en": "How many High Courts are there in Nepal under the federal structure?",
            "question_text_np": "संघीय संरचना अन्तर्गत नेपालमा कतिवटा उच्च अदालत छन्?",
            "answers": [
                {"text_en": "7 (one in each province)", "text_np": "७ (प्रत्येक प्रदेशमा एउटा)", "is_correct": True},
                {"text_en": "5", "text_np": "५", "is_correct": False},
                {"text_en": "14", "text_np": "१४", "is_correct": False},
                {"text_en": "3", "text_np": "३", "is_correct": False},
            ],
            "explanation_en": "Under Nepal's federal structure, there are 7 High Courts, one in each of the seven provinces, as established by the Constitution of Nepal, 2072.",
            "explanation_np": "नेपालको संघीय संरचना अन्तर्गत नेपालको संविधान, २०७२ द्वारा स्थापित गरिए अनुसार सातवटै प्रदेशमा एक-एकवटा गरी ७ वटा उच्च अदालत छन्।",
            "difficulty": "EASY",
            "source_reference": "PSC Legal System",
        },
        {
            "question_text_en": "The Chief Justice of Nepal is appointed on the recommendation of which body?",
            "question_text_np": "नेपालको प्रधानन्यायाधीश कुन निकायको सिफारिसमा नियुक्त हुन्छन्?",
            "answers": [
                {"text_en": "Constitutional Council", "text_np": "संवैधानिक परिषद्", "is_correct": True},
                {"text_en": "Judicial Council", "text_np": "न्याय परिषद्", "is_correct": False},
                {"text_en": "Parliament", "text_np": "संसद", "is_correct": False},
                {"text_en": "Cabinet of Ministers", "text_np": "मन्त्रिपरिषद्", "is_correct": False},
            ],
            "explanation_en": "The Chief Justice is appointed by the President on the recommendation of the Constitutional Council as per Article 129 of the Constitution of Nepal.",
            "explanation_np": "नेपालको संविधानको धारा १२९ अनुसार प्रधानन्यायाधीश संवैधानिक परिषद्को सिफारिसमा राष्ट्रपतिद्वारा नियुक्त हुन्छन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Legal System",
        },
        {
            "question_text_en": "The Judicial Council of Nepal is chaired by:",
            "question_text_np": "नेपालको न्याय परिषद्को अध्यक्षता कसले गर्छन्?",
            "answers": [
                {"text_en": "Chief Justice", "text_np": "प्रधानन्यायाधीश", "is_correct": True},
                {"text_en": "President", "text_np": "राष्ट्रपति", "is_correct": False},
                {"text_en": "Prime Minister", "text_np": "प्रधानमन्त्री", "is_correct": False},
                {"text_en": "Attorney General", "text_np": "महान्यायाधिवक्ता", "is_correct": False},
            ],
            "explanation_en": "The Judicial Council, established under Article 153 of the Constitution, is chaired by the Chief Justice and is responsible for recommending appointments, transfers, and disciplinary actions of judges.",
            "explanation_np": "संविधानको धारा १५३ अन्तर्गत स्थापित न्याय परिषद्को अध्यक्षता प्रधानन्यायाधीशले गर्छन् र यो न्यायाधीशहरूको नियुक्ति, सरुवा र अनुशासनात्मक कारबाहीको सिफारिस गर्ने जिम्मेवार छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Legal System",
        },
        {
            "question_text_en": "Which article of the Constitution of Nepal guarantees the right to constitutional remedy?",
            "question_text_np": "नेपालको संविधानको कुन धाराले संवैधानिक उपचारको हक प्रत्याभूत गर्छ?",
            "answers": [
                {"text_en": "Article 46", "text_np": "धारा ४६", "is_correct": True},
                {"text_en": "Article 17", "text_np": "धारा १७", "is_correct": False},
                {"text_en": "Article 55", "text_np": "धारा ५५", "is_correct": False},
                {"text_en": "Article 32", "text_np": "धारा ३२", "is_correct": False},
            ],
            "explanation_en": "Article 46 of the Constitution of Nepal, 2072 guarantees the right to constitutional remedy, allowing citizens to approach the Supreme Court for enforcement of fundamental rights.",
            "explanation_np": "नेपालको संविधान, २०७२ को धारा ४६ ले संवैधानिक उपचारको हक प्रत्याभूत गर्छ, जसले नागरिकहरूलाई मौलिक हकको कार्यान्वयनका लागि सर्वोच्च अदालतमा जान अनुमति दिन्छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Legal System",
        },
        {
            "question_text_en": "What type of jurisdiction does the Supreme Court of Nepal exercise when it interprets the Constitution?",
            "question_text_np": "सर्वोच्च अदालतले संविधानको व्याख्या गर्दा कुन प्रकारको क्षेत्राधिकार प्रयोग गर्छ?",
            "answers": [
                {"text_en": "Original jurisdiction", "text_np": "मौलिक क्षेत्राधिकार", "is_correct": True},
                {"text_en": "Appellate jurisdiction", "text_np": "पुनरावेदन क्षेत्राधिकार", "is_correct": False},
                {"text_en": "Advisory jurisdiction", "text_np": "सल्लाहकार क्षेत्राधिकार", "is_correct": False},
                {"text_en": "Revisionary jurisdiction", "text_np": "पुनरावलोकन क्षेत्राधिकार", "is_correct": False},
            ],
            "explanation_en": "The Supreme Court exercises original jurisdiction when hearing cases related to constitutional interpretation, fundamental rights enforcement, and habeas corpus petitions.",
            "explanation_np": "सर्वोच्च अदालतले संवैधानिक व्याख्या, मौलिक हक कार्यान्वयन र बन्दीप्रत्यक्षीकरण निवेदनसँग सम्बन्धित मुद्दाहरू सुन्दा मौलिक क्षेत्राधिकार प्रयोग गर्छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Legal System",
        },
    ],
    "criminal-civil-law": [
        {
            "question_text_en": "The Muluki Criminal Code (Muluki Aparadh Samhita) of Nepal came into effect in which year?",
            "question_text_np": "नेपालको मुलुकी अपराध संहिता कुन सालमा लागू भयो?",
            "answers": [
                {"text_en": "2074 BS (2017 AD)", "text_np": "२०७४ वि.सं.", "is_correct": True},
                {"text_en": "2063 BS (2006 AD)", "text_np": "२०६३ वि.सं.", "is_correct": False},
                {"text_en": "2070 BS (2013 AD)", "text_np": "२०७० वि.सं.", "is_correct": False},
                {"text_en": "2080 BS (2023 AD)", "text_np": "२०८० वि.सं.", "is_correct": False},
            ],
            "explanation_en": "The Muluki Criminal Code (Muluki Aparadh Samhita), 2074 came into effect on Bhadra 1, 2075 BS (August 17, 2018 AD), replacing the criminal provisions of the old Muluki Ain.",
            "explanation_np": "मुलुकी अपराध संहिता, २०७४ भदौ १, २०७५ मा लागू भयो, पुरानो मुलुकी ऐनको फौजदारी प्रावधानहरू प्रतिस्थापन गर्दै।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Criminal & Civil Law",
        },
        {
            "question_text_en": "Under the Muluki Criminal Code, what is the maximum sentence for murder (intentional homicide)?",
            "question_text_np": "मुलुकी अपराध संहिता अन्तर्गत हत्या (जानाजानी ज्यान मार्ने) को अधिकतम सजाय कति हो?",
            "answers": [
                {"text_en": "Life imprisonment", "text_np": "जन्मकैद", "is_correct": True},
                {"text_en": "20 years imprisonment", "text_np": "२० वर्ष कैद", "is_correct": False},
                {"text_en": "Death penalty", "text_np": "मृत्युदण्ड", "is_correct": False},
                {"text_en": "10 years imprisonment", "text_np": "१० वर्ष कैद", "is_correct": False},
            ],
            "explanation_en": "Under the Muluki Criminal Code, 2074, the maximum punishment for intentional homicide (murder) is life imprisonment. Nepal has abolished the death penalty.",
            "explanation_np": "मुलुकी अपराध संहिता, २०७४ अन्तर्गत जानाजानी ज्यान मार्ने (हत्या) को अधिकतम सजाय जन्मकैद हो। नेपालले मृत्युदण्ड खारेज गरिसकेको छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Criminal & Civil Law",
        },
        {
            "question_text_en": "The Muluki Civil Code (Muluki Dewani Samhita) addresses which of the following matters?",
            "question_text_np": "मुलुकी देवानी संहिताले निम्नमध्ये कुन विषयलाई सम्बोधन गर्छ?",
            "answers": [
                {"text_en": "Property, contracts, family law, and civil obligations", "text_np": "सम्पत्ति, करार, पारिवारिक कानुन र देवानी दायित्व", "is_correct": True},
                {"text_en": "Criminal offences and punishments", "text_np": "फौजदारी अपराध र सजाय", "is_correct": False},
                {"text_en": "Election procedures", "text_np": "निर्वाचन प्रक्रिया", "is_correct": False},
                {"text_en": "Military regulations", "text_np": "सैनिक नियमावली", "is_correct": False},
            ],
            "explanation_en": "The Muluki Civil Code (Dewani Samhita), 2074 covers civil matters including property rights, contracts, family relations, inheritance, and civil obligations.",
            "explanation_np": "मुलुकी देवानी संहिता, २०७४ ले सम्पत्ति अधिकार, करार, पारिवारिक सम्बन्ध, उत्तराधिकार र देवानी दायित्व लगायत देवानी विषयहरू समेट्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Criminal & Civil Law",
        },
        {
            "question_text_en": "What is the statute of limitations for filing a civil case related to property disputes in Nepal?",
            "question_text_np": "नेपालमा सम्पत्ति विवादसँग सम्बन्धित देवानी मुद्दा दायर गर्ने हदम्याद कति हो?",
            "answers": [
                {"text_en": "Varies by type, generally 2-5 years under Muluki Dewani Samhita", "text_np": "प्रकार अनुसार फरक हुन्छ, सामान्यतया मुलुकी देवानी संहिता अन्तर्गत २-५ वर्ष", "is_correct": True},
                {"text_en": "No time limit", "text_np": "कुनै समय सीमा छैन", "is_correct": False},
                {"text_en": "30 days", "text_np": "३० दिन", "is_correct": False},
                {"text_en": "1 year for all cases", "text_np": "सबै मुद्दाका लागि १ वर्ष", "is_correct": False},
            ],
            "explanation_en": "The statute of limitations for civil cases in Nepal varies by type of dispute. The Muluki Dewani Samhita specifies different limitation periods, generally ranging from 2 to 5 years depending on the nature of the claim.",
            "explanation_np": "नेपालमा देवानी मुद्दाको हदम्याद विवादको प्रकार अनुसार फरक हुन्छ। मुलुकी देवानी संहिताले दावीको प्रकृति अनुसार सामान्यतया २ देखि ५ वर्षसम्मको विभिन्न हदम्याद अवधि तोकेको छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Criminal & Civil Law",
        },
        {
            "question_text_en": "In Nepal's criminal justice system, the burden of proof in criminal cases lies with:",
            "question_text_np": "नेपालको फौजदारी न्याय प्रणालीमा फौजदारी मुद्दामा प्रमाणको भार कसमा हुन्छ?",
            "answers": [
                {"text_en": "The prosecution (State)", "text_np": "अभियोजन पक्ष (राज्य)", "is_correct": True},
                {"text_en": "The accused", "text_np": "अभियुक्त", "is_correct": False},
                {"text_en": "The judge", "text_np": "न्यायाधीश", "is_correct": False},
                {"text_en": "The victim", "text_np": "पीडित", "is_correct": False},
            ],
            "explanation_en": "In Nepal's criminal justice system, the burden of proof lies with the prosecution (State). The accused is presumed innocent until proven guilty beyond reasonable doubt.",
            "explanation_np": "नेपालको फौजदारी न्याय प्रणालीमा प्रमाणको भार अभियोजन पक्ष (राज्य) मा हुन्छ। अभियुक्तलाई उचित शंकाभन्दा बाहिर दोषी प्रमाणित नभएसम्म निर्दोष मानिन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Criminal & Civil Law",
        },
        {
            "question_text_en": "Which of the following is classified as a 'state case' (government case) under Nepal's criminal law?",
            "question_text_np": "निम्नमध्ये कुनलाई नेपालको फौजदारी कानुन अन्तर्गत 'सरकारी मुद्दा' को रूपमा वर्गीकरण गरिन्छ?",
            "answers": [
                {"text_en": "Murder", "text_np": "हत्या", "is_correct": True},
                {"text_en": "Defamation", "text_np": "मानहानि", "is_correct": False},
                {"text_en": "Breach of contract", "text_np": "करार उल्लंघन", "is_correct": False},
                {"text_en": "Property boundary dispute", "text_np": "सम्पत्ति सिमाना विवाद", "is_correct": False},
            ],
            "explanation_en": "Murder is classified as a state case (sarkari mudda) where the government acts as the prosecutor. Defamation and property disputes are private cases filed by the aggrieved party.",
            "explanation_np": "हत्या सरकारी मुद्दाको रूपमा वर्गीकृत छ जहाँ सरकारले अभियोजकको भूमिका निर्वाह गर्छ। मानहानि र सम्पत्ति विवाद पीडित पक्षले दायर गर्ने व्यक्तिगत मुद्दा हुन्।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Criminal & Civil Law",
        },
        {
            "question_text_en": "The concept of 'bail' in Nepal's criminal procedure allows the accused to:",
            "question_text_np": "नेपालको फौजदारी कार्यविधिमा 'धरौटी' को अवधारणाले अभियुक्तलाई के गर्न अनुमति दिन्छ?",
            "answers": [
                {"text_en": "Be released from custody pending trial upon providing security", "text_np": "जमानत प्रदान गरेपछि मुद्दा विचाराधीन रहँदा हिरासतबाट रिहा हुने", "is_correct": True},
                {"text_en": "Avoid trial completely", "text_np": "मुद्दाबाट पूर्णतया बच्ने", "is_correct": False},
                {"text_en": "Have charges dropped automatically", "text_np": "आरोप स्वतः खारेज हुने", "is_correct": False},
                {"text_en": "Transfer the case to another court", "text_np": "मुद्दा अर्को अदालतमा सार्ने", "is_correct": False},
            ],
            "explanation_en": "Bail allows an accused person to be released from custody during the trial period upon furnishing a bond or security, subject to conditions set by the court under the Criminal Procedure Code.",
            "explanation_np": "धरौटीले अभियुक्तलाई फौजदारी कार्यविधि संहिता अन्तर्गत अदालतले तोकेको शर्तहरू पालना गर्दै जमानत वा धरौटी राखेर मुद्दा विचाराधीन अवधिमा हिरासतबाट रिहा हुन अनुमति दिन्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Criminal & Civil Law",
        },
    ],
    "constitutional-law-jurisprudence": [
        {
            "question_text_en": "The Constitution of Nepal, 2072 was promulgated on which date?",
            "question_text_np": "नेपालको संविधान, २०७२ कुन मितिमा जारी गरिएको थियो?",
            "answers": [
                {"text_en": "Asoj 3, 2072 BS (September 20, 2015)", "text_np": "असोज ३, २०७२", "is_correct": True},
                {"text_en": "Jestha 15, 2072 BS", "text_np": "जेठ १५, २०७२", "is_correct": False},
                {"text_en": "Baisakh 1, 2072 BS", "text_np": "बैशाख १, २०७२", "is_correct": False},
                {"text_en": "Magh 10, 2072 BS", "text_np": "माघ १०, २०७२", "is_correct": False},
            ],
            "explanation_en": "The Constitution of Nepal, 2072 was promulgated on Asoj 3, 2072 BS (September 20, 2015 AD) by the second Constituent Assembly.",
            "explanation_np": "नेपालको संविधान, २०७२ दोस्रो संविधानसभाद्वारा असोज ३, २०७२ (सेप्टेम्बर २०, २०१५) मा जारी गरिएको थियो।",
            "difficulty": "EASY",
            "source_reference": "PSC Constitutional Law",
        },
        {
            "question_text_en": "How many fundamental rights are enshrined in the Constitution of Nepal, 2072?",
            "question_text_np": "नेपालको संविधान, २०७२ मा कतिवटा मौलिक हकहरू समावेश छन्?",
            "answers": [
                {"text_en": "31 fundamental rights", "text_np": "३१ वटा मौलिक हक", "is_correct": True},
                {"text_en": "25 fundamental rights", "text_np": "२५ वटा मौलिक हक", "is_correct": False},
                {"text_en": "15 fundamental rights", "text_np": "१५ वटा मौलिक हक", "is_correct": False},
                {"text_en": "40 fundamental rights", "text_np": "४० वटा मौलिक हक", "is_correct": False},
            ],
            "explanation_en": "The Constitution of Nepal, 2072 enshrines 31 fundamental rights in Part 3 (Articles 16-46), making it one of the most comprehensive bills of rights in South Asia.",
            "explanation_np": "नेपालको संविधान, २०७२ ले भाग ३ (धारा १६-४६) मा ३१ वटा मौलिक हकहरू समावेश गरेको छ, जसले यसलाई दक्षिण एशियाको सबैभन्दा विस्तृत अधिकार पत्रमध्ये एक बनाउँछ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Constitutional Law",
        },
        {
            "question_text_en": "The doctrine of judicial review in Nepal empowers the Supreme Court to:",
            "question_text_np": "नेपालमा न्यायिक पुनरावलोकनको सिद्धान्तले सर्वोच्च अदालतलाई कुन अधिकार दिन्छ?",
            "answers": [
                {"text_en": "Declare laws unconstitutional if they violate the Constitution", "text_np": "संविधान उल्लंघन गर्ने कानुनलाई असंवैधानिक घोषणा गर्ने", "is_correct": True},
                {"text_en": "Make new laws", "text_np": "नयाँ कानुन बनाउने", "is_correct": False},
                {"text_en": "Appoint the Prime Minister", "text_np": "प्रधानमन्त्री नियुक्त गर्ने", "is_correct": False},
                {"text_en": "Dissolve Parliament", "text_np": "संसद विघटन गर्ने", "is_correct": False},
            ],
            "explanation_en": "Judicial review empowers the Supreme Court under Article 133 to examine whether laws, orders, or actions of the state are consistent with the Constitution, and to declare them void if unconstitutional.",
            "explanation_np": "न्यायिक पुनरावलोकनले धारा १३३ अन्तर्गत सर्वोच्च अदालतलाई कानुन, आदेश वा राज्यको कार्यहरू संविधानसँग मेल खान्छन् कि भनी जाँच गर्ने र असंवैधानिक भए बदर घोषणा गर्ने अधिकार दिन्छ।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Constitutional Law",
        },
        {
            "question_text_en": "The concept of 'separation of powers' in Nepal's Constitution distributes power among:",
            "question_text_np": "नेपालको संविधानमा 'शक्ति पृथकीकरण' को अवधारणाले शक्ति कसरी बाँडफाँड गर्छ?",
            "answers": [
                {"text_en": "Legislature, Executive, and Judiciary", "text_np": "व्यवस्थापिका, कार्यपालिका र न्यायपालिका", "is_correct": True},
                {"text_en": "Federal, Provincial, and Local governments only", "text_np": "संघीय, प्रदेश र स्थानीय सरकार मात्र", "is_correct": False},
                {"text_en": "President, Prime Minister, and Chief Justice", "text_np": "राष्ट्रपति, प्रधानमन्त्री र प्रधानन्यायाधीश", "is_correct": False},
                {"text_en": "Political parties", "text_np": "राजनीतिक दलहरू", "is_correct": False},
            ],
            "explanation_en": "The separation of powers doctrine divides governmental authority among three branches: the Legislature (law-making), Executive (law-implementing), and Judiciary (law-interpreting).",
            "explanation_np": "शक्ति पृथकीकरणको सिद्धान्तले सरकारी अधिकारलाई तीन अंगमा विभाजन गर्छ: व्यवस्थापिका (कानुन बनाउने), कार्यपालिका (कानुन कार्यान्वयन गर्ने) र न्यायपालिका (कानुनको व्याख्या गर्ने)।",
            "difficulty": "EASY",
            "source_reference": "PSC Constitutional Law",
        },
        {
            "question_text_en": "Which writ can be filed to challenge the illegal detention of a person in Nepal?",
            "question_text_np": "नेपालमा कुनै व्यक्तिको गैरकानुनी हिरासतलाई चुनौती दिन कुन रिट दायर गर्न सकिन्छ?",
            "answers": [
                {"text_en": "Habeas Corpus", "text_np": "बन्दीप्रत्यक्षीकरण", "is_correct": True},
                {"text_en": "Mandamus", "text_np": "परमादेश", "is_correct": False},
                {"text_en": "Certiorari", "text_np": "उत्प्रेषण", "is_correct": False},
                {"text_en": "Quo Warranto", "text_np": "अधिकारपृच्छा", "is_correct": False},
            ],
            "explanation_en": "Habeas Corpus (bandipratyakshikaran) is the writ used to challenge unlawful detention. It requires the detaining authority to produce the detained person before the court and justify the detention.",
            "explanation_np": "बन्दीप्रत्यक्षीकरण गैरकानुनी हिरासतलाई चुनौती दिन प्रयोग हुने रिट हो। यसले हिरासतमा राख्ने अधिकारीलाई हिरासतमा रहेको व्यक्तिलाई अदालत समक्ष उपस्थित गराउन र हिरासतको औचित्य प्रमाणित गर्न आवश्यक पार्छ।",
            "difficulty": "EASY",
            "source_reference": "PSC Constitutional Law",
        },
        {
            "question_text_en": "Under the Constitution of Nepal, 2072, amendment of the Constitution requires approval of:",
            "question_text_np": "नेपालको संविधान, २०७२ अन्तर्गत संविधान संशोधनका लागि कसको स्वीकृति आवश्यक छ?",
            "answers": [
                {"text_en": "Two-thirds majority of the total members of both houses of Parliament", "text_np": "संसदका दुवै सदनका कुल सदस्यको दुई-तिहाइ बहुमत", "is_correct": True},
                {"text_en": "Simple majority of Parliament", "text_np": "संसदको साधारण बहुमत", "is_correct": False},
                {"text_en": "Approval of the President alone", "text_np": "राष्ट्रपतिको एकल स्वीकृति", "is_correct": False},
                {"text_en": "Unanimous vote of all members", "text_np": "सबै सदस्यको सर्वसम्मत मत", "is_correct": False},
            ],
            "explanation_en": "Article 274 of the Constitution requires a two-thirds majority of the total members of both houses of the Federal Parliament for constitutional amendments.",
            "explanation_np": "संविधानको धारा २७४ ले संवैधानिक संशोधनका लागि संघीय संसदका दुवै सदनका कुल सदस्यको दुई-तिहाइ बहुमत आवश्यक पार्छ।",
            "difficulty": "HARD",
            "source_reference": "PSC Constitutional Law",
        },
        {
            "question_text_en": "The principle of 'rule of law' as enshrined in Nepal's Constitution means:",
            "question_text_np": "नेपालको संविधानमा समाविष्ट 'कानुनको शासन' को सिद्धान्तले के बुझाउँछ?",
            "answers": [
                {"text_en": "Everyone, including the government, is subject to and accountable under the law", "text_np": "सरकार सहित सबैजना कानुनको अधीनमा छन् र कानुन प्रति जवाफदेही छन्", "is_correct": True},
                {"text_en": "The ruler can make laws without any limitation", "text_np": "शासकले कुनै सीमा बिना कानुन बनाउन सक्छ", "is_correct": False},
                {"text_en": "Only judges are above the law", "text_np": "न्यायाधीश मात्र कानुनभन्दा माथि छन्", "is_correct": False},
                {"text_en": "Laws apply only to citizens, not government officials", "text_np": "कानुन नागरिकमा मात्र लागू हुन्छ, सरकारी अधिकारीमा होइन", "is_correct": False},
            ],
            "explanation_en": "The rule of law means that all persons and institutions, including the government, are subject to and accountable under the law. No one is above the law.",
            "explanation_np": "कानुनको शासनले सरकार सहित सबै व्यक्ति र संस्थाहरू कानुनको अधीनमा छन् र कानुन प्रति जवाफदेही छन् भन्ने बुझाउँछ। कोही पनि कानुनभन्दा माथि छैन।",
            "difficulty": "MEDIUM",
            "source_reference": "PSC Constitutional Law",
        },
    ],
}
