"""Lok Sewa Regulations (लोक सेवा नियमावली) — UNIVERSAL category questions."""

QUESTIONS = [
    {
        "question_text_en": "The Public Service Commission (Lok Sewa Aayog) of Nepal is established under which article of the Constitution?",
        "question_text_np": "नेपालको लोक सेवा आयोग संविधानको कुन धाराअन्तर्गत स्थापित छ?",
        "answers": [
            {"text_en": "Article 242", "text_np": "धारा २४२", "is_correct": True},
            {"text_en": "Article 200", "text_np": "धारा २००", "is_correct": False},
            {"text_en": "Article 128", "text_np": "धारा १२८", "is_correct": False},
            {"text_en": "Article 300", "text_np": "धारा ३००", "is_correct": False},
        ],
        "explanation_en": "Article 242 of the Constitution of Nepal 2072 provides for the establishment of the Public Service Commission.",
        "explanation_np": "नेपालको संविधान २०७२ को धारा २४२ ले लोक सेवा आयोगको स्थापनाको व्यवस्था गर्दछ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Lok Sewa Regulations",
    },
    {
        "question_text_en": "How many members does the Public Service Commission have including the Chairperson?",
        "question_text_np": "लोक सेवा आयोगमा अध्यक्ष सहित कति सदस्य हुन्छन्?",
        "answers": [
            {"text_en": "Chairman and other members as determined by law", "text_np": "अध्यक्ष र कानूनले तोकेबमोजिमका अन्य सदस्यहरू", "is_correct": True},
            {"text_en": "5 members only", "text_np": "५ सदस्य मात्र", "is_correct": False},
            {"text_en": "10 members", "text_np": "१० सदस्य", "is_correct": False},
            {"text_en": "3 members", "text_np": "३ सदस्य", "is_correct": False},
        ],
        "explanation_en": "The Constitution provides for a Chairman and other members as determined by law for the Public Service Commission.",
        "explanation_np": "संविधानले लोक सेवा आयोगमा अध्यक्ष र कानूनले तोकेबमोजिमका अन्य सदस्यहरूको व्यवस्था गर्दछ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Lok Sewa Regulations",
    },
    {
        "question_text_en": "The Civil Service Act of Nepal was enacted in which year (BS)?",
        "question_text_np": "नेपालको निजामती सेवा ऐन कुन सालमा बनेको थियो?",
        "answers": [
            {"text_en": "2049 BS (1993 AD)", "text_np": "२०४९ साल (१९९३ ई.)", "is_correct": True},
            {"text_en": "2055 BS", "text_np": "२०५५ साल", "is_correct": False},
            {"text_en": "2046 BS", "text_np": "२०४६ साल", "is_correct": False},
            {"text_en": "2060 BS", "text_np": "२०६० साल", "is_correct": False},
        ],
        "explanation_en": "The Civil Service Act (Nijamati Sewa Ain) was enacted in 2049 BS (1993 AD) to regulate the civil service of Nepal.",
        "explanation_np": "निजामती सेवा ऐन २०४९ सालमा नेपालको निजामती सेवालाई नियमित गर्न बनाइएको थियो।",
        "difficulty": "HARD",
        "source_reference": "PSC Lok Sewa Regulations",
    },
    {
        "question_text_en": "Which is the highest non-gazetted post in Nepal's civil service?",
        "question_text_np": "नेपालको निजामती सेवामा सबैभन्दा माथिल्लो राजपत्र अनंकित पद कुन हो?",
        "answers": [
            {"text_en": "Non-Gazetted First Class (Nayab Subba)", "text_np": "राजपत्र अनंकित प्रथम श्रेणी (नायब सुब्बा)", "is_correct": True},
            {"text_en": "Non-Gazetted Second Class", "text_np": "राजपत्र अनंकित द्वितीय श्रेणी", "is_correct": False},
            {"text_en": "Gazetted Third Class", "text_np": "राजपत्रांकित तृतीय श्रेणी", "is_correct": False},
            {"text_en": "Classless", "text_np": "श्रेणी विहीन", "is_correct": False},
        ],
        "explanation_en": "Non-Gazetted First Class (Nayab Subba level) is the highest non-gazetted post in Nepal's civil service.",
        "explanation_np": "राजपत्र अनंकित प्रथम श्रेणी (नायब सुब्बा तह) नेपालको निजामती सेवामा सबैभन्दा माथिल्लो राजपत्र अनंकित पद हो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Lok Sewa Regulations",
    },
    {
        "question_text_en": "The tenure of the Chairman of the Public Service Commission is how many years?",
        "question_text_np": "लोक सेवा आयोगको अध्यक्षको कार्यकाल कति वर्ष हुन्छ?",
        "answers": [
            {"text_en": "6 years", "text_np": "६ वर्ष", "is_correct": True},
            {"text_en": "4 years", "text_np": "४ वर्ष", "is_correct": False},
            {"text_en": "5 years", "text_np": "५ वर्ष", "is_correct": False},
            {"text_en": "8 years", "text_np": "८ वर्ष", "is_correct": False},
        ],
        "explanation_en": "The Chairman and members of the Public Service Commission serve for a tenure of 6 years.",
        "explanation_np": "लोक सेवा आयोगको अध्यक्ष र सदस्यहरूको कार्यकाल ६ वर्ष हुन्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Lok Sewa Regulations",
    },
    {
        "question_text_en": "What is the retirement age for civil servants in Nepal?",
        "question_text_np": "नेपालमा निजामती कर्मचारीको अवकाश उमेर कति हो?",
        "answers": [
            {"text_en": "58 years", "text_np": "५८ वर्ष", "is_correct": True},
            {"text_en": "60 years", "text_np": "६० वर्ष", "is_correct": False},
            {"text_en": "55 years", "text_np": "५५ वर्ष", "is_correct": False},
            {"text_en": "65 years", "text_np": "६५ वर्ष", "is_correct": False},
        ],
        "explanation_en": "The retirement age for civil servants in Nepal is 58 years as per the Civil Service Act.",
        "explanation_np": "निजामती सेवा ऐन अनुसार नेपालमा निजामती कर्मचारीको अवकाश उमेर ५८ वर्ष हो।",
        "difficulty": "EASY",
        "source_reference": "PSC Lok Sewa Regulations",
    },
    {
        "question_text_en": "The civil service positions in Nepal are classified into how many classes?",
        "question_text_np": "नेपालमा निजामती सेवाको पदलाई कतिवटा श्रेणीमा वर्गीकरण गरिएको छ?",
        "answers": [
            {"text_en": "Classless, Non-Gazetted (2nd, 1st), Gazetted (3rd, 2nd, 1st), Special Class", "text_np": "श्रेणी विहीन, राजपत्र अनंकित (द्वितीय, प्रथम), राजपत्रांकित (तृतीय, द्वितीय, प्रथम), विशिष्ट श्रेणी", "is_correct": True},
            {"text_en": "Three classes only", "text_np": "तीन श्रेणी मात्र", "is_correct": False},
            {"text_en": "Level 1 to Level 11", "text_np": "तह १ देखि तह ११", "is_correct": False},
            {"text_en": "A, B, C, D grades", "text_np": "ए, बी, सी, डी ग्रेड", "is_correct": False},
        ],
        "explanation_en": "Nepal's civil service positions are classified into: Classless, Non-Gazetted (2nd and 1st class), Gazetted (3rd, 2nd, and 1st class), and Special Class.",
        "explanation_np": "नेपालको निजामती सेवाको पदलाई श्रेणी विहीन, राजपत्र अनंकित (द्वितीय र प्रथम श्रेणी), राजपत्रांकित (तृतीय, द्वितीय र प्रथम श्रेणी) र विशिष्ट श्रेणीमा वर्गीकरण गरिएको छ।",
        "difficulty": "HARD",
        "source_reference": "PSC Lok Sewa Regulations",
    },
    {
        "question_text_en": "What is the probation period for a newly appointed civil servant in Nepal?",
        "question_text_np": "नेपालमा नयाँ नियुक्त निजामती कर्मचारीको परीक्षणकाल कति हुन्छ?",
        "answers": [
            {"text_en": "1 year", "text_np": "१ वर्ष", "is_correct": True},
            {"text_en": "6 months", "text_np": "६ महिना", "is_correct": False},
            {"text_en": "2 years", "text_np": "२ वर्ष", "is_correct": False},
            {"text_en": "3 months", "text_np": "३ महिना", "is_correct": False},
        ],
        "explanation_en": "A newly appointed civil servant in Nepal has a probation period of 1 year, during which their performance is evaluated.",
        "explanation_np": "नेपालमा नयाँ नियुक्त निजामती कर्मचारीको परीक्षणकाल १ वर्ष हुन्छ, जसमा उनको कार्यसम्पादन मूल्याङ्कन गरिन्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Lok Sewa Regulations",
    },
    {
        "question_text_en": "The Good Governance (Management and Operation) Act was enacted in which year (BS)?",
        "question_text_np": "सुशासन (व्यवस्थापन तथा सञ्चालन) ऐन कुन सालमा बनेको थियो?",
        "answers": [
            {"text_en": "2064 BS (2008 AD)", "text_np": "२०६४ साल (२००८ ई.)", "is_correct": True},
            {"text_en": "2072 BS", "text_np": "२०७२ साल", "is_correct": False},
            {"text_en": "2058 BS", "text_np": "२०५८ साल", "is_correct": False},
            {"text_en": "2070 BS", "text_np": "२०७० साल", "is_correct": False},
        ],
        "explanation_en": "The Good Governance (Management and Operation) Act was enacted in 2064 BS (2008 AD) to ensure accountability and transparency in public administration.",
        "explanation_np": "सुशासन (व्यवस्थापन तथा सञ्चालन) ऐन सार्वजनिक प्रशासनमा जवाफदेहिता र पारदर्शिता सुनिश्चित गर्न २०६४ सालमा बनाइएको थियो।",
        "difficulty": "HARD",
        "source_reference": "PSC Lok Sewa Regulations",
    },
    {
        "question_text_en": "Open competition in Nepal's civil service typically fills what percentage of vacant positions?",
        "question_text_np": "नेपालको निजामती सेवामा खुल्ला प्रतिस्पर्धाले सामान्यतया कति प्रतिशत रिक्त पदहरू भर्ना गर्छ?",
        "answers": [
            {"text_en": "45%", "text_np": "४५%", "is_correct": True},
            {"text_en": "50%", "text_np": "५०%", "is_correct": False},
            {"text_en": "60%", "text_np": "६०%", "is_correct": False},
            {"text_en": "30%", "text_np": "३०%", "is_correct": False},
        ],
        "explanation_en": "Open competition fills approximately 45% of vacant positions, with the rest filled through internal competition and inclusion quotas.",
        "explanation_np": "खुल्ला प्रतिस्पर्धाले लगभग ४५% रिक्त पदहरू भर्ना गर्छ, बाँकी आन्तरिक प्रतिस्पर्धा र समावेशी कोटाबाट भरिन्छ।",
        "difficulty": "HARD",
        "source_reference": "PSC Lok Sewa Regulations",
    },
]
