"""Nepali Language & Grammar (नेपाली भाषा र व्याकरण) — UNIVERSAL category questions."""

QUESTIONS = [
    {
        "question_text_en": "What is 'Sandhi' in Nepali grammar?",
        "question_text_np": "नेपाली व्याकरणमा 'सन्धि' भनेको के हो?",
        "answers": [
            {"text_en": "The joining of two sounds or letters", "text_np": "दुई वर्ण वा ध्वनिको मेल", "is_correct": True},
            {"text_en": "The separation of compound words", "text_np": "समस्त पदको विग्रह", "is_correct": False},
            {"text_en": "A type of poetic figure of speech", "text_np": "एक प्रकारको अलङ्कार", "is_correct": False},
            {"text_en": "A punctuation mark", "text_np": "एक विराम चिन्ह", "is_correct": False},
        ],
        "explanation_en": "Sandhi (सन्धि) in Nepali grammar refers to the combination or joining of two adjacent sounds or letters to form a new sound. For example, 'हिम + आलय = हिमालय'.",
        "explanation_np": "नेपाली व्याकरणमा सन्धि भनेको दुई वर्ण वा ध्वनि नजिक आउँदा तिनीहरूको मेल हुनु हो। जस्तै: 'हिम + आलय = हिमालय'।",
        "difficulty": "EASY",
        "source_reference": "PSC Nepali Language",
    },
    {
        "question_text_en": "Which of the following is an example of 'Swar Sandhi' (vowel combination)?",
        "question_text_np": "तलका मध्ये कुन 'स्वर सन्धि' को उदाहरण हो?",
        "answers": [
            {"text_en": "विद्या + आलय = विद्यालय", "text_np": "विद्या + आलय = विद्यालय", "is_correct": True},
            {"text_en": "सत् + जन = सज्जन", "text_np": "सत् + जन = सज्जन", "is_correct": False},
            {"text_en": "दुः + गति = दुर्गति", "text_np": "दुः + गति = दुर्गति", "is_correct": False},
            {"text_en": "उत् + लास = उल्लास", "text_np": "उत् + लास = उल्लास", "is_correct": False},
        ],
        "explanation_en": "Swar Sandhi occurs when two vowels combine. In 'विद्या + आलय = विद्यालय', the vowel 'आ' at the end of विद्या combines with the vowel 'आ' at the start of आलय.",
        "explanation_np": "स्वर सन्धिमा दुई स्वर वर्णको मेल हुन्छ। 'विद्या + आलय = विद्यालय' मा विद्या को अन्तिम स्वर 'आ' र आलय को प्रारम्भिक स्वर 'आ' को मेल भएको छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Nepali Language",
    },
    {
        "question_text_en": "What is 'Samas' (compound word formation) in Nepali grammar?",
        "question_text_np": "नेपाली व्याकरणमा 'समास' भनेको के हो?",
        "answers": [
            {"text_en": "Combining two or more words into one compound word", "text_np": "दुई वा दुईभन्दा बढी शब्दलाई एउटा समस्त पदमा बनाउनु", "is_correct": True},
            {"text_en": "Breaking a word into its root forms", "text_np": "शब्दलाई धातुमा विभाजन गर्नु", "is_correct": False},
            {"text_en": "Adding a suffix to a verb", "text_np": "क्रियापदमा प्रत्यय जोड्नु", "is_correct": False},
            {"text_en": "Changing the form of a noun", "text_np": "नामपदको रूप परिवर्तन गर्नु", "is_correct": False},
        ],
        "explanation_en": "Samas is the process of combining two or more words into a single compound word (समस्त पद). For example, 'राजा + कुमार = राजकुमार'.",
        "explanation_np": "समास भनेको दुई वा दुईभन्दा बढी शब्दलाई मिलाएर एउटा समस्त पद बनाउने प्रक्रिया हो। जस्तै: 'राजा + कुमार = राजकुमार'।",
        "difficulty": "EASY",
        "source_reference": "PSC Nepali Language",
    },
    {
        "question_text_en": "Which type of Samas is 'राजकुमार' (son of a king)?",
        "question_text_np": "'राजकुमार' कुन समास हो?",
        "answers": [
            {"text_en": "Tatpurush Samas", "text_np": "तत्पुरुष समास", "is_correct": True},
            {"text_en": "Dwandwa Samas", "text_np": "द्वन्द्व समास", "is_correct": False},
            {"text_en": "Karmadharaya Samas", "text_np": "कर्मधारय समास", "is_correct": False},
            {"text_en": "Bahubrihi Samas", "text_np": "बहुव्रीहि समास", "is_correct": False},
        ],
        "explanation_en": "राजकुमार (राजाको कुमार — prince) is an example of Tatpurush Samas, where the latter word (कुमार) is the principal word and the former word (राजा) is subordinate with an implied case marker (को).",
        "explanation_np": "राजकुमार (राजाको कुमार) तत्पुरुष समासको उदाहरण हो। यसमा पछिल्लो पद (कुमार) प्रधान र अघिल्लो पद (राजा) गौण हुन्छ र विभक्ति लोप हुन्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Nepali Language",
    },
    {
        "question_text_en": "What is the synonym (पर्यायवाची) of 'सूर्य' (Sun)?",
        "question_text_np": "'सूर्य' को पर्यायवाची शब्द कुन हो?",
        "answers": [
            {"text_en": "भानु", "text_np": "भानु", "is_correct": True},
            {"text_en": "शशि", "text_np": "शशि", "is_correct": False},
            {"text_en": "तारा", "text_np": "तारा", "is_correct": False},
            {"text_en": "नभ", "text_np": "नभ", "is_correct": False},
        ],
        "explanation_en": "भानु is a synonym of सूर्य (Sun). Other synonyms include रवि, दिनकर, दिवाकर, आदित्य. Note: शशि means Moon, तारा means Star, and नभ means Sky.",
        "explanation_np": "भानु सूर्यको पर्यायवाची शब्द हो। अन्य पर्यायवाची शब्दहरू: रवि, दिनकर, दिवाकर, आदित्य। शशि चन्द्रमालाई, तारा ताराललाई र नभ आकाशलाई भनिन्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Nepali Language",
    },
    {
        "question_text_en": "What is the antonym (विपरीतार्थी) of 'धनी' (rich)?",
        "question_text_np": "'धनी' को विपरीतार्थी शब्द कुन हो?",
        "answers": [
            {"text_en": "गरिब", "text_np": "गरिब", "is_correct": True},
            {"text_en": "साहु", "text_np": "साहु", "is_correct": False},
            {"text_en": "सम्पन्न", "text_np": "सम्पन्न", "is_correct": False},
            {"text_en": "सेठ", "text_np": "सेठ", "is_correct": False},
        ],
        "explanation_en": "The antonym of धनी (rich) is गरिब (poor). साहु, सम्पन्न, and सेठ are all synonyms of धनी, not antonyms.",
        "explanation_np": "धनी को विपरीतार्थी शब्द गरिब हो। साहु, सम्पन्न र सेठ सबै धनीका पर्यायवाची शब्दहरू हुन्, विपरीतार्थी होइनन्।",
        "difficulty": "EASY",
        "source_reference": "PSC Nepali Language",
    },
    {
        "question_text_en": "What does the Nepali proverb 'खाली हात भगवानले पनि नदिने' mean?",
        "question_text_np": "'खाली हात भगवानले पनि नदिने' उखानको अर्थ के हो?",
        "answers": [
            {"text_en": "One must put in effort to get results", "text_np": "फल पाउन मेहनत गर्नुपर्छ", "is_correct": True},
            {"text_en": "God does not help anyone", "text_np": "भगवानले कसैलाई पनि सहयोग गर्दैन", "is_correct": False},
            {"text_en": "Empty hands are a sign of laziness", "text_np": "खाली हात अल्छीपनको चिन्ह हो", "is_correct": False},
            {"text_en": "One should always pray to God", "text_np": "सधैँ भगवानलाई प्रार्थना गर्नुपर्छ", "is_correct": False},
        ],
        "explanation_en": "This proverb means that even God does not give to empty hands — one must make effort and investment to receive returns. It emphasizes the importance of hard work.",
        "explanation_np": "यो उखानको अर्थ हो कि खाली हातमा भगवानले पनि केही दिँदैनन् — फल पाउन मेहनत र लगानी गर्नुपर्छ। यसले कठिन परिश्रमको महत्त्व जनाउँछ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Nepali Language",
    },
    {
        "question_text_en": "Which of the following is a correct example of 'Upama Alankar' (simile)?",
        "question_text_np": "तलका मध्ये कुन 'उपमा अलङ्कार' को सही उदाहरण हो?",
        "answers": [
            {"text_en": "उसको मुहार चन्द्रमा जस्तो छ", "text_np": "उसको मुहार चन्द्रमा जस्तो छ", "is_correct": True},
            {"text_en": "ऊ त चन्द्रमा नै हो", "text_np": "ऊ त चन्द्रमा नै हो", "is_correct": False},
            {"text_en": "फूलहरू हाँसे", "text_np": "फूलहरू हाँसे", "is_correct": False},
            {"text_en": "हिमाल बोल्छ", "text_np": "हिमाल बोल्छ", "is_correct": False},
        ],
        "explanation_en": "Upama Alankar (simile) uses comparison words like 'जस्तो' (like), 'सरह', 'समान'. 'उसको मुहार चन्द्रमा जस्तो छ' uses 'जस्तो' for comparison. 'ऊ त चन्द्रमा नै हो' is Rupak (metaphor), and 'फूलहरू हाँसे' / 'हिमाल बोल्छ' are Manavikarana (personification).",
        "explanation_np": "उपमा अलङ्कारमा 'जस्तो', 'सरह', 'समान' जस्ता तुलनावाचक शब्दहरू प्रयोग हुन्छन्। 'उसको मुहार चन्द्रमा जस्तो छ' मा 'जस्तो' तुलनावाचक शब्द छ। 'ऊ त चन्द्रमा नै हो' रूपक अलङ्कार हो र 'फूलहरू हाँसे' / 'हिमाल बोल्छ' मानवीकरण अलङ्कार हो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Nepali Language",
    },
    {
        "question_text_en": "How many 'Vibhakti' (case markers) are there in Nepali grammar?",
        "question_text_np": "नेपाली व्याकरणमा कतिवटा विभक्ति छन्?",
        "answers": [
            {"text_en": "8", "text_np": "८", "is_correct": True},
            {"text_en": "6", "text_np": "६", "is_correct": False},
            {"text_en": "10", "text_np": "१०", "is_correct": False},
            {"text_en": "12", "text_np": "१२", "is_correct": False},
        ],
        "explanation_en": "There are 8 Vibhakti (case markers) in Nepali grammar: Prathama (ले), Dwitiya (लाई), Tritiya (द्वारा/बाट), Chaturthi (को लागि), Panchami (बाट/देखि), Shashthi (को), Saptami (मा), and Sambodhan (हे/ए).",
        "explanation_np": "नेपाली व्याकरणमा ८ विभक्ति छन्: प्रथमा (ले), द्वितीया (लाई), तृतीया (द्वारा/बाट), चतुर्थी (को लागि), पञ्चमी (बाट/देखि), षष्ठी (को), सप्तमी (मा), र सम्बोधन (हे/ए)।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Nepali Language",
    },
    {
        "question_text_en": "Which sentence is grammatically correct in Nepali?",
        "question_text_np": "तलका मध्ये कुन वाक्य व्याकरणिक रूपमा शुद्ध छ?",
        "answers": [
            {"text_en": "उसले किताब पढ्यो।", "text_np": "उसले किताब पढ्यो।", "is_correct": True},
            {"text_en": "उसले किताब पढ्यौ।", "text_np": "उसले किताब पढ्यौ।", "is_correct": False},
            {"text_en": "उसले किताब पढें।", "text_np": "उसले किताब पढें।", "is_correct": False},
            {"text_en": "उसले किताब पढ्यिन्।", "text_np": "उसले किताब पढ्यिन्।", "is_correct": False},
        ],
        "explanation_en": "When the subject is third person singular masculine with 'ले' (ergative), the verb takes the '-यो' ending. 'पढ्यौ' is second person, 'पढें' is first person, and 'पढ्यिन्' is third person feminine.",
        "explanation_np": "'उसले' तेस्रो पुरुष एकवचन पुलिङ्ग कर्ता हो, त्यसैले क्रियापदमा '-यो' प्रत्यय लाग्छ। 'पढ्यौ' मध्यम पुरुष, 'पढें' उत्तम पुरुष, र 'पढ्यिन्' तेस्रो पुरुष स्त्रीलिङ्ग हो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Nepali Language",
    },
    {
        "question_text_en": "What is a 'Kriya Visheshan' (adverb) in Nepali?",
        "question_text_np": "नेपालीमा 'क्रियाविशेषण' भनेको के हो?",
        "answers": [
            {"text_en": "A word that modifies a verb, adjective, or another adverb", "text_np": "क्रिया, विशेषण वा अर्को क्रियाविशेषणलाई विशेषता दिने शब्द", "is_correct": True},
            {"text_en": "A word that replaces a noun", "text_np": "नामको सट्टामा प्रयोग हुने शब्द", "is_correct": False},
            {"text_en": "A word that describes a noun", "text_np": "नामको विशेषता बताउने शब्द", "is_correct": False},
            {"text_en": "A word that joins two sentences", "text_np": "दुई वाक्यलाई जोड्ने शब्द", "is_correct": False},
        ],
        "explanation_en": "Kriya Visheshan (adverb) is a word that modifies or qualifies a verb, adjective, or another adverb. For example, 'ढिलो' in 'ऊ ढिलो आयो' (He came late).",
        "explanation_np": "क्रियाविशेषण भनेको क्रिया, विशेषण वा अर्को क्रियाविशेषणको विशेषता बताउने शब्द हो। जस्तै: 'ऊ ढिलो आयो' मा 'ढिलो' क्रियाविशेषण हो।",
        "difficulty": "EASY",
        "source_reference": "PSC Nepali Language",
    },
    {
        "question_text_en": "What does the Nepali proverb 'जुन गोरुको सिङ छैन उसैलाई कन्छो भनी चिनाउने' mean?",
        "question_text_np": "'जुन गोरुको सिङ छैन उसैलाई कन्छो भनी चिनाउने' उखानको अर्थ के हो?",
        "answers": [
            {"text_en": "To identify someone by their weakness or deficiency", "text_np": "कसैलाई उसको कमजोरी वा कमीबाट चिनाउनु", "is_correct": True},
            {"text_en": "To compare two similar things", "text_np": "दुई समान कुरा तुलना गर्नु", "is_correct": False},
            {"text_en": "To praise someone for their qualities", "text_np": "कसैको गुणको प्रशंसा गर्नु", "is_correct": False},
            {"text_en": "To name someone after their birth order", "text_np": "जन्मक्रम अनुसार नाम राख्नु", "is_correct": False},
        ],
        "explanation_en": "This proverb means recognizing or identifying someone through their deficiency or distinguishing weakness, rather than their positive attributes.",
        "explanation_np": "यो उखानको अर्थ हो कसैलाई उसको कमी वा कमजोरीबाट चिनाउनु — सकारात्मक गुणभन्दा पनि कमजोरीबाट पहिचान गराउनु।",
        "difficulty": "HARD",
        "source_reference": "PSC Nepali Language",
    },
    {
        "question_text_en": "Which of the following is a 'Dwandwa Samas' (copulative compound)?",
        "question_text_np": "तलका मध्ये कुन 'द्वन्द्व समास' हो?",
        "answers": [
            {"text_en": "दाजुभाइ", "text_np": "दाजुभाइ", "is_correct": True},
            {"text_en": "राजकुमार", "text_np": "राजकुमार", "is_correct": False},
            {"text_en": "महादेव", "text_np": "महादेव", "is_correct": False},
            {"text_en": "चक्रपाणि", "text_np": "चक्रपाणि", "is_correct": False},
        ],
        "explanation_en": "Dwandwa Samas joins two equal/coordinate words. 'दाजुभाइ' (दाजु + भाइ) is a Dwandwa compound. 'राजकुमार' is Tatpurush, 'महादेव' is Karmadharaya, and 'चक्रपाणि' is Bahubrihi.",
        "explanation_np": "द्वन्द्व समासमा दुई समान पदको मेल हुन्छ। 'दाजुभाइ' (दाजु + भाइ) द्वन्द्व समास हो। 'राजकुमार' तत्पुरुष, 'महादेव' कर्मधारय, र 'चक्रपाणि' बहुव्रीहि समास हो।",
        "difficulty": "HARD",
        "source_reference": "PSC Nepali Language",
    },
]
