"""Quantitative Aptitude (परिमाणात्मक योग्यता) — UNIVERSAL category questions."""

QUESTIONS = [
    {
        "question_text_en": "What is 15% of 480?",
        "question_text_np": "४८० को १५% कति हो?",
        "answers": [
            {"text_en": "72", "text_np": "७२", "is_correct": True},
            {"text_en": "68", "text_np": "६८", "is_correct": False},
            {"text_en": "76", "text_np": "७६", "is_correct": False},
            {"text_en": "84", "text_np": "८४", "is_correct": False},
        ],
        "explanation_en": "15% of 480 = (15/100) × 480 = 0.15 × 480 = 72.",
        "explanation_np": "४८० को १५% = (१५/१००) × ४८० = ०.१५ × ४८० = ७२।",
        "difficulty": "EASY",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "A train travels 360 km in 4 hours. What is its speed in km/h?",
        "question_text_np": "एउटा रेल ४ घण्टामा ३६० किमि यात्रा गर्छ। यसको गति किमि/घण्टामा कति हो?",
        "answers": [
            {"text_en": "90 km/h", "text_np": "९० किमि/घण्टा", "is_correct": True},
            {"text_en": "80 km/h", "text_np": "८० किमि/घण्टा", "is_correct": False},
            {"text_en": "100 km/h", "text_np": "१०० किमि/घण्टा", "is_correct": False},
            {"text_en": "85 km/h", "text_np": "८५ किमि/घण्टा", "is_correct": False},
        ],
        "explanation_en": "Speed = Distance ÷ Time = 360 ÷ 4 = 90 km/h.",
        "explanation_np": "गति = दूरी ÷ समय = ३६० ÷ ४ = ९० किमि/घण्टा।",
        "difficulty": "EASY",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "If A:B = 3:4 and B:C = 5:6, what is A:B:C?",
        "question_text_np": "यदि A:B = ३:४ र B:C = ५:६ हो भने A:B:C कति हो?",
        "answers": [
            {"text_en": "15:20:24", "text_np": "१५:२०:२४", "is_correct": True},
            {"text_en": "3:4:6", "text_np": "३:४:६", "is_correct": False},
            {"text_en": "15:20:30", "text_np": "१५:२०:३०", "is_correct": False},
            {"text_en": "9:12:15", "text_np": "९:१२:१५", "is_correct": False},
        ],
        "explanation_en": "Make B common: A:B = 3:4 = 15:20, B:C = 5:6 = 20:24. So A:B:C = 15:20:24.",
        "explanation_np": "B समान बनाउनुहोस्: A:B = ३:४ = १५:२०, B:C = ५:६ = २०:२४। त्यसैले A:B:C = १५:२०:२४।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "The average of five consecutive odd numbers is 25. What is the largest of these numbers?",
        "question_text_np": "पाँचवटा लगातार बिजोर संख्याहरूको औसत २५ छ। यी संख्याहरूमध्ये सबैभन्दा ठूलो कति हो?",
        "answers": [
            {"text_en": "29", "text_np": "२९", "is_correct": True},
            {"text_en": "27", "text_np": "२७", "is_correct": False},
            {"text_en": "31", "text_np": "३१", "is_correct": False},
            {"text_en": "33", "text_np": "३३", "is_correct": False},
        ],
        "explanation_en": "If average of 5 consecutive odd numbers is 25, the middle number is 25. So they are 21, 23, 25, 27, 29. The largest is 29.",
        "explanation_np": "५ लगातार बिजोर संख्याहरूको औसत २५ हो भने बिचको संख्या २५ हो। त्यसैले ती २१, २३, २५, २७, २९ हुन्। सबैभन्दा ठूलो २९ हो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "A shopkeeper sells an item for Rs. 840 at a profit of 20%. What was the cost price?",
        "question_text_np": "एउटा पसलेले कुनै वस्तु रू. ८४० मा बेचेर २०% नाफा गर्छ। लागत मूल्य कति थियो?",
        "answers": [
            {"text_en": "Rs. 700", "text_np": "रू. ७००", "is_correct": True},
            {"text_en": "Rs. 720", "text_np": "रू. ७२०", "is_correct": False},
            {"text_en": "Rs. 680", "text_np": "रू. ६८०", "is_correct": False},
            {"text_en": "Rs. 750", "text_np": "रू. ७५०", "is_correct": False},
        ],
        "explanation_en": "SP = CP × (1 + profit%). 840 = CP × 1.20. CP = 840 / 1.20 = Rs. 700.",
        "explanation_np": "बिक्री मूल्य = लागत मूल्य × (१ + नाफा%). ८४० = लागत × १.२०। लागत = ८४० / १.२० = रू. ७००।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "Simple interest on Rs. 5000 at 8% per annum for 3 years is:",
        "question_text_np": "रू. ५००० मा ८% वार्षिक दरमा ३ वर्षको साधारण ब्याज कति हो?",
        "answers": [
            {"text_en": "Rs. 1200", "text_np": "रू. १२००", "is_correct": True},
            {"text_en": "Rs. 1000", "text_np": "रू. १०००", "is_correct": False},
            {"text_en": "Rs. 1400", "text_np": "रू. १४००", "is_correct": False},
            {"text_en": "Rs. 1600", "text_np": "रू. १६००", "is_correct": False},
        ],
        "explanation_en": "SI = (P × R × T) / 100 = (5000 × 8 × 3) / 100 = 120000 / 100 = Rs. 1200.",
        "explanation_np": "साधारण ब्याज = (मूलधन × दर × समय) / १०० = (५००० × ८ × ३) / १०० = १२०००० / १०० = रू. १२००।",
        "difficulty": "EASY",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "What is the LCM of 12, 15, and 20?",
        "question_text_np": "१२, १५ र २० को लघुत्तम समापवर्त्य (LCM) कति हो?",
        "answers": [
            {"text_en": "60", "text_np": "६०", "is_correct": True},
            {"text_en": "30", "text_np": "३०", "is_correct": False},
            {"text_en": "120", "text_np": "१२०", "is_correct": False},
            {"text_en": "45", "text_np": "४५", "is_correct": False},
        ],
        "explanation_en": "12 = 2²×3, 15 = 3×5, 20 = 2²×5. LCM = 2²×3×5 = 4×3×5 = 60.",
        "explanation_np": "१२ = २²×३, १५ = ३×५, २० = २²×५। LCM = २²×३×५ = ४×३×५ = ६०।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "A pipe can fill a tank in 6 hours. Another pipe can empty it in 12 hours. If both are open simultaneously, in how many hours will the tank be filled?",
        "question_text_np": "एउटा पाइपले ट्याङ्की ६ घण्टामा भर्न सक्छ। अर्को पाइपले १२ घण्टामा खाली गर्न सक्छ। दुवै एकसाथ खोलिएमा ट्याङ्की कति घण्टामा भरिन्छ?",
        "answers": [
            {"text_en": "12 hours", "text_np": "१२ घण्टा", "is_correct": True},
            {"text_en": "9 hours", "text_np": "९ घण्टा", "is_correct": False},
            {"text_en": "8 hours", "text_np": "८ घण्टा", "is_correct": False},
            {"text_en": "18 hours", "text_np": "१८ घण्टा", "is_correct": False},
        ],
        "explanation_en": "Filling rate = 1/6 per hour. Emptying rate = 1/12 per hour. Net rate = 1/6 − 1/12 = 2/12 − 1/12 = 1/12 per hour. Time = 12 hours.",
        "explanation_np": "भर्ने दर = प्रति घण्टा १/६। खाली गर्ने दर = प्रति घण्टा १/१२। शुद्ध दर = १/६ − १/१२ = १/१२ प्रति घण्टा। समय = १२ घण्टा।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "If the cost of 8 pens is Rs. 200, what is the cost of 14 pens?",
        "question_text_np": "यदि ८ वटा कलमको मूल्य रू. २०० हो भने १४ वटा कलमको मूल्य कति हो?",
        "answers": [
            {"text_en": "Rs. 350", "text_np": "रू. ३५०", "is_correct": True},
            {"text_en": "Rs. 300", "text_np": "रू. ३००", "is_correct": False},
            {"text_en": "Rs. 400", "text_np": "रू. ४००", "is_correct": False},
            {"text_en": "Rs. 325", "text_np": "रू. ३२५", "is_correct": False},
        ],
        "explanation_en": "Cost per pen = 200 ÷ 8 = Rs. 25. Cost of 14 pens = 14 × 25 = Rs. 350.",
        "explanation_np": "प्रति कलमको मूल्य = २०० ÷ ८ = रू. २५। १४ वटा कलमको मूल्य = १४ × २५ = रू. ३५०।",
        "difficulty": "EASY",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "A is twice as old as B. 10 years ago, A was three times as old as B. How old is B now?",
        "question_text_np": "A को उमेर B भन्दा दोब्बर छ। १० वर्ष अघि A को उमेर B को तीन गुणा थियो। B को हालको उमेर कति हो?",
        "answers": [
            {"text_en": "20 years", "text_np": "२० वर्ष", "is_correct": True},
            {"text_en": "15 years", "text_np": "१५ वर्ष", "is_correct": False},
            {"text_en": "25 years", "text_np": "२५ वर्ष", "is_correct": False},
            {"text_en": "18 years", "text_np": "१८ वर्ष", "is_correct": False},
        ],
        "explanation_en": "Let B = x, A = 2x. 10 years ago: 2x−10 = 3(x−10) → 2x−10 = 3x−30 → x = 20. So B is 20.",
        "explanation_np": "मान B = x, A = 2x। १० वर्ष अघि: 2x−10 = 3(x−10) → 2x−10 = 3x−30 → x = 20। त्यसैले B को उमेर २० वर्ष हो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "What is the square root of 2025?",
        "question_text_np": "२०२५ को वर्गमूल कति हो?",
        "answers": [
            {"text_en": "45", "text_np": "४५", "is_correct": True},
            {"text_en": "40", "text_np": "४०", "is_correct": False},
            {"text_en": "50", "text_np": "५०", "is_correct": False},
            {"text_en": "42", "text_np": "४२", "is_correct": False},
        ],
        "explanation_en": "45 × 45 = 2025. So √2025 = 45.",
        "explanation_np": "४५ × ४५ = २०२५। त्यसैले √२०२५ = ४५।",
        "difficulty": "EASY",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "A man spends 70% of his income. If his income increases by 20% and expenditure increases by 10%, what is the percentage change in savings?",
        "question_text_np": "एक व्यक्तिले आफ्नो आयको ७०% खर्च गर्छ। आय २०% र खर्च १०% बढेमा बचतमा कति प्रतिशत परिवर्तन हुन्छ?",
        "answers": [
            {"text_en": "43.33%", "text_np": "४३.३३%", "is_correct": True},
            {"text_en": "33.33%", "text_np": "३३.३३%", "is_correct": False},
            {"text_en": "50%", "text_np": "५०%", "is_correct": False},
            {"text_en": "40%", "text_np": "४०%", "is_correct": False},
        ],
        "explanation_en": "Let income = 100. Expenditure = 70, Savings = 30. New income = 120, New expenditure = 77. New savings = 43. Change = (43−30)/30 × 100 = 43.33%.",
        "explanation_np": "आय = १०० मानौं। खर्च = ७०, बचत = ३०। नयाँ आय = १२०, नयाँ खर्च = ७७। नयाँ बचत = ४३। परिवर्तन = (४३−३०)/३० × १०० = ४३.३३%।",
        "difficulty": "HARD",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "If 2x + y = 10 and x + 2y = 8, what is the value of x + y?",
        "question_text_np": "यदि 2x + y = 10 र x + 2y = 8 हो भने x + y को मान कति हो?",
        "answers": [
            {"text_en": "6", "text_np": "६", "is_correct": True},
            {"text_en": "5", "text_np": "५", "is_correct": False},
            {"text_en": "7", "text_np": "७", "is_correct": False},
            {"text_en": "4", "text_np": "४", "is_correct": False},
        ],
        "explanation_en": "Adding both equations: 3x + 3y = 18, so x + y = 6.",
        "explanation_np": "दुवै समीकरण जोड्दा: 3x + 3y = 18, त्यसैले x + y = 6।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "The perimeter of a rectangle is 48 cm. If its length is 14 cm, what is its area?",
        "question_text_np": "एउटा आयतकारको परिधि ४८ से.मि. छ। यसको लम्बाइ १४ से.मि. हो भने यसको क्षेत्रफल कति हो?",
        "answers": [
            {"text_en": "140 sq cm", "text_np": "१४० वर्ग से.मि.", "is_correct": True},
            {"text_en": "120 sq cm", "text_np": "१२० वर्ग से.मि.", "is_correct": False},
            {"text_en": "160 sq cm", "text_np": "१६० वर्ग से.मि.", "is_correct": False},
            {"text_en": "100 sq cm", "text_np": "१०० वर्ग से.मि.", "is_correct": False},
        ],
        "explanation_en": "Perimeter = 2(l + b). 48 = 2(14 + b) → b = 10. Area = l × b = 14 × 10 = 140 sq cm.",
        "explanation_np": "परिधि = २(ल + च)। ४८ = २(१४ + च) → च = १०। क्षेत्रफल = ल × च = १४ × १० = १४० वर्ग से.मि.।",
        "difficulty": "EASY",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "A number is increased by 25% and then decreased by 20%. What is the net change?",
        "question_text_np": "एउटा संख्यालाई २५% ले बढाइन्छ र त्यसपछि २०% ले घटाइन्छ। शुद्ध परिवर्तन कति हो?",
        "answers": [
            {"text_en": "0% (no change)", "text_np": "०% (कुनै परिवर्तन छैन)", "is_correct": True},
            {"text_en": "5% increase", "text_np": "५% वृद्धि", "is_correct": False},
            {"text_en": "5% decrease", "text_np": "५% कमी", "is_correct": False},
            {"text_en": "10% increase", "text_np": "१०% वृद्धि", "is_correct": False},
        ],
        "explanation_en": "Let number = 100. After 25% increase = 125. After 20% decrease = 125 × 0.8 = 100. Net change = 0%.",
        "explanation_np": "संख्या = १०० मानौं। २५% वृद्धिपछि = १२५। २०% कमीपछि = १२५ × ०.८ = १००। शुद्ध परिवर्तन = ०%।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "If 5 men can complete a work in 8 days, how many men are needed to complete it in 4 days?",
        "question_text_np": "यदि ५ जना मानिसले ८ दिनमा काम सम्पन्न गर्न सक्छन् भने ४ दिनमा सम्पन्न गर्न कतिजना मानिस चाहिन्छ?",
        "answers": [
            {"text_en": "10 men", "text_np": "१० जना", "is_correct": True},
            {"text_en": "8 men", "text_np": "८ जना", "is_correct": False},
            {"text_en": "12 men", "text_np": "१२ जना", "is_correct": False},
            {"text_en": "6 men", "text_np": "६ जना", "is_correct": False},
        ],
        "explanation_en": "Total work = 5 × 8 = 40 man-days. To finish in 4 days: 40 ÷ 4 = 10 men.",
        "explanation_np": "कुल काम = ५ × ८ = ४० मानिस-दिन। ४ दिनमा सम्पन्न गर्न: ४० ÷ ४ = १० जना मानिस।",
        "difficulty": "EASY",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "The difference between compound interest and simple interest on Rs. 8000 for 2 years at 5% per annum is:",
        "question_text_np": "रू. ८०००मा ५% वार्षिक दरमा २ वर्षको चक्रवृद्धि ब्याज र साधारण ब्याजको भिन्नता कति हो?",
        "answers": [
            {"text_en": "Rs. 20", "text_np": "रू. २०", "is_correct": True},
            {"text_en": "Rs. 40", "text_np": "रू. ४०", "is_correct": False},
            {"text_en": "Rs. 25", "text_np": "रू. २५", "is_correct": False},
            {"text_en": "Rs. 800", "text_np": "रू. ८००", "is_correct": False},
        ],
        "explanation_en": "SI = 8000×5×2/100 = 800. CI = 8000×(1.05²−1) = 8000×0.1025 = 820. Difference = 820−800 = Rs. 20.",
        "explanation_np": "साधारण ब्याज = ८०००×५×२/१०० = ८००। चक्रवृद्धि ब्याज = ८०००×(१.०५²−१) = ८२०। भिन्नता = ८२०−८०० = रू. २०।",
        "difficulty": "HARD",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "What is 30% of 40% of 500?",
        "question_text_np": "५०० को ४०% को ३०% कति हो?",
        "answers": [
            {"text_en": "60", "text_np": "६०", "is_correct": True},
            {"text_en": "50", "text_np": "५०", "is_correct": False},
            {"text_en": "70", "text_np": "७०", "is_correct": False},
            {"text_en": "80", "text_np": "८०", "is_correct": False},
        ],
        "explanation_en": "40% of 500 = 200. 30% of 200 = 60.",
        "explanation_np": "५०० को ४०% = २००। २०० को ३०% = ६०।",
        "difficulty": "EASY",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "Two numbers are in the ratio 5:8. If their sum is 195, what is the larger number?",
        "question_text_np": "दुईवटा संख्याहरू ५:८ अनुपातमा छन्। यदि तिनीहरूको योग १९५ हो भने ठूलो संख्या कति हो?",
        "answers": [
            {"text_en": "120", "text_np": "१२०", "is_correct": True},
            {"text_en": "75", "text_np": "७५", "is_correct": False},
            {"text_en": "104", "text_np": "१०४", "is_correct": False},
            {"text_en": "130", "text_np": "१३०", "is_correct": False},
        ],
        "explanation_en": "Total parts = 5 + 8 = 13. Larger number = (8/13) × 195 = 8 × 15 = 120.",
        "explanation_np": "कुल भाग = ५ + ८ = १३। ठूलो संख्या = (८/१३) × १९५ = ८ × १५ = १२०।",
        "difficulty": "EASY",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "A discount of 10% is given on a product whose marked price is Rs. 1500. What is the selling price?",
        "question_text_np": "रू. १५०० अंकित मूल्यको वस्तुमा १०% छूट दिइन्छ। बिक्री मूल्य कति हो?",
        "answers": [
            {"text_en": "Rs. 1350", "text_np": "रू. १३५०", "is_correct": True},
            {"text_en": "Rs. 1400", "text_np": "रू. १४००", "is_correct": False},
            {"text_en": "Rs. 1250", "text_np": "रू. १२५०", "is_correct": False},
            {"text_en": "Rs. 1300", "text_np": "रू. १३००", "is_correct": False},
        ],
        "explanation_en": "Discount = 10% of 1500 = 150. Selling price = 1500 − 150 = Rs. 1350.",
        "explanation_np": "छूट = १५०० को १०% = १५०। बिक्री मूल्य = १५०० − १५० = रू. १३५०।",
        "difficulty": "EASY",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "The sum of three consecutive even numbers is 78. What is the smallest of the three numbers?",
        "question_text_np": "तीनवटा लगातार जोर संख्याहरूको योग ७८ छ। यी तीन संख्याहरूमध्ये सबैभन्दा साना कति हो?",
        "answers": [
            {"text_en": "24", "text_np": "२४", "is_correct": True},
            {"text_en": "22", "text_np": "२२", "is_correct": False},
            {"text_en": "26", "text_np": "२६", "is_correct": False},
            {"text_en": "20", "text_np": "२०", "is_correct": False},
        ],
        "explanation_en": "Let the three numbers be n, n+2, n+4. Sum = 3n + 6 = 78 → n = 24. Smallest = 24.",
        "explanation_np": "तीन संख्याहरू n, n+2, n+4 मानौं। योग = 3n + 6 = 78 → n = 24। सबैभन्दा सानो = २४।",
        "difficulty": "EASY",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "HCF of 36 and 48 is:",
        "question_text_np": "३६ र ४८ को महत्तम समापवर्तक (HCF) कति हो?",
        "answers": [
            {"text_en": "12", "text_np": "१२", "is_correct": True},
            {"text_en": "6", "text_np": "६", "is_correct": False},
            {"text_en": "18", "text_np": "१८", "is_correct": False},
            {"text_en": "24", "text_np": "२४", "is_correct": False},
        ],
        "explanation_en": "36 = 2²×3², 48 = 2⁴×3. HCF = 2²×3 = 12.",
        "explanation_np": "३६ = २²×३², ४८ = २⁴×३। HCF = २²×३ = १२।",
        "difficulty": "EASY",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "If the radius of a circle is doubled, by what factor does its area increase?",
        "question_text_np": "वृत्तको त्रिज्या दोब्बर गरिएमा यसको क्षेत्रफल कति गुणाले बढ्छ?",
        "answers": [
            {"text_en": "4 times", "text_np": "४ गुणा", "is_correct": True},
            {"text_en": "2 times", "text_np": "२ गुणा", "is_correct": False},
            {"text_en": "3 times", "text_np": "३ गुणा", "is_correct": False},
            {"text_en": "8 times", "text_np": "८ गुणा", "is_correct": False},
        ],
        "explanation_en": "Area = πr². If r doubles to 2r, new area = π(2r)² = 4πr². The area increases 4 times.",
        "explanation_np": "क्षेत्रफल = πr²। त्रिज्या दोब्बर भई 2r हुँदा नयाँ क्षेत्रफल = π(2r)² = 4πr²। क्षेत्रफल ४ गुणा बढ्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Quantitative Aptitude",
    },
    {
        "question_text_en": "A dealer buys goods at Rs. 400 and sells them for Rs. 500. What is the profit percentage?",
        "question_text_np": "एक व्यापारीले रू. ४०० मा सामान किन्छ र रू. ५०० मा बेच्छ। नाफाको प्रतिशत कति हो?",
        "answers": [
            {"text_en": "25%", "text_np": "२५%", "is_correct": True},
            {"text_en": "20%", "text_np": "२०%", "is_correct": False},
            {"text_en": "30%", "text_np": "३०%", "is_correct": False},
            {"text_en": "15%", "text_np": "१५%", "is_correct": False},
        ],
        "explanation_en": "Profit = 500 − 400 = 100. Profit% = (100/400) × 100 = 25%.",
        "explanation_np": "नाफा = ५०० − ४०० = १००। नाफा% = (१००/४००) × १०० = २५%।",
        "difficulty": "EASY",
        "source_reference": "PSC Quantitative Aptitude",
    },
]