"""Reasoning & Mental Ability (तर्क र मानसिक क्षमता) — UNIVERSAL category questions."""

QUESTIONS = [
    {
        "question_text_en": "Complete the series: 2, 6, 18, 54, ___",
        "question_text_np": "श्रृंखला पूरा गर्नुहोस्: २, ६, १८, ५४, ___",
        "answers": [
            {"text_en": "162", "text_np": "१६२", "is_correct": True},
            {"text_en": "108", "text_np": "१०८", "is_correct": False},
            {"text_en": "144", "text_np": "१४४", "is_correct": False},
            {"text_en": "216", "text_np": "२१६", "is_correct": False},
        ],
        "explanation_en": "Each term is multiplied by 3: 2×3=6, 6×3=18, 18×3=54, 54×3=162.",
        "explanation_np": "प्रत्येक पद ३ ले गुणा गरिन्छ: २×३=६, ६×३=१८, १८×३=५४, ५४×३=१६२।",
        "difficulty": "EASY",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "If NEPAL is coded as OFQBM, how is INDIA coded?",
        "question_text_np": "यदि NEPAL लाई OFQBM लेखिन्छ भने INDIA लाई कसरी लेखिन्छ?",
        "answers": [
            {"text_en": "JOEJB", "text_np": "JOEJB", "is_correct": True},
            {"text_en": "HMCHZ", "text_np": "HMCHZ", "is_correct": False},
            {"text_en": "JODIA", "text_np": "JODIA", "is_correct": False},
            {"text_en": "JNEJB", "text_np": "JNEJB", "is_correct": False},
        ],
        "explanation_en": "Each letter is shifted forward by 1: N→O, E→F, P→Q, A→B, L→M. So I→J, N→O, D→E, I→J, A→B → JOEJB.",
        "explanation_np": "प्रत्येक अक्षर १ ले अगाडि सार्दा: N→O, E→F, P→Q, A→B, L→M। त्यसैले I→J, N→O, D→E, I→J, A→B → JOEJB।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "Find the odd one out: 3, 5, 7, 9, 11",
        "question_text_np": "भिन्न पहिचान गर्नुहोस्: ३, ५, ७, ९, ११",
        "answers": [
            {"text_en": "9", "text_np": "९", "is_correct": True},
            {"text_en": "3", "text_np": "३", "is_correct": False},
            {"text_en": "7", "text_np": "७", "is_correct": False},
            {"text_en": "11", "text_np": "११", "is_correct": False},
        ],
        "explanation_en": "3, 5, 7, 11 are prime numbers. 9 (=3×3) is not prime. So 9 is the odd one out.",
        "explanation_np": "३, ५, ७, ११ अभाज्य संख्याहरू हुन्। ९ (=३×३) अभाज्य होइन। त्यसैले ९ भिन्न हो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "A is the father of B. B is the sister of C. C is the son of D. How is D related to A?",
        "question_text_np": "A, B को बुबा हो। B, C को दिदी/बहिनी हो। C, D को छोरा हो। D को A सँग के सम्बन्ध छ?",
        "answers": [
            {"text_en": "Daughter-in-law", "text_np": "बुहारी", "is_correct": True},
            {"text_en": "Wife", "text_np": "पत्नी", "is_correct": False},
            {"text_en": "Sister", "text_np": "बहिनी", "is_correct": False},
            {"text_en": "Mother", "text_np": "आमा", "is_correct": False},
        ],
        "explanation_en": "A is father of B and C. C is D's son, so D is C's parent. Since B and C are siblings under A, D is A's daughter-in-law (C's mother).",
        "explanation_np": "A, B र C का बुबा हुन्। C, D को छोरा हो, त्यसैले D, C को आमा हो। यसरी D, A की बुहारी हो।",
        "difficulty": "HARD",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "Complete the analogy: Book : Library :: Painting : ?",
        "question_text_np": "उपमा पूरा गर्नुहोस्: पुस्तक : पुस्तकालय :: चित्र : ?",
        "answers": [
            {"text_en": "Gallery", "text_np": "ग्यालेरी", "is_correct": True},
            {"text_en": "Museum", "text_np": "सङ्ग्रहालय", "is_correct": False},
            {"text_en": "Studio", "text_np": "स्टुडियो", "is_correct": False},
            {"text_en": "Academy", "text_np": "अकादमी", "is_correct": False},
        ],
        "explanation_en": "A book is kept in a library. Similarly, a painting is kept in a gallery. A museum houses historical artifacts, not specifically paintings.",
        "explanation_np": "पुस्तक पुस्तकालयमा राखिन्छ। त्यसैगरी चित्र ग्यालेरीमा राखिन्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "If the day after tomorrow is Thursday, what day was it three days before yesterday?",
        "question_text_np": "यदि पर्सि बिहीबार हो भने हिजो भन्दा तीन दिन अघि कुन बार थियो?",
        "answers": [
            {"text_en": "Friday", "text_np": "शुक्रबार", "is_correct": True},
            {"text_en": "Saturday", "text_np": "शनिबार", "is_correct": False},
            {"text_en": "Thursday", "text_np": "बिहीबार", "is_correct": False},
            {"text_en": "Sunday", "text_np": "आइतबार", "is_correct": False},
        ],
        "explanation_en": "Day after tomorrow = Thursday → tomorrow = Wednesday → today = Tuesday → yesterday = Monday → 3 days before yesterday = Monday−3 = Friday.",
        "explanation_np": "पर्सि = बिहीबार → भोलि = बुधबार → आज = मंगलबार → हिजो = सोमबार → हिजो भन्दा ३ दिन अघि = शुक्रबार।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "Complete the series: 1, 4, 9, 16, 25, ___",
        "question_text_np": "श्रृंखला पूरा गर्नुहोस्: १, ४, ९, १६, २५, ___",
        "answers": [
            {"text_en": "36", "text_np": "३६", "is_correct": True},
            {"text_en": "30", "text_np": "३०", "is_correct": False},
            {"text_en": "32", "text_np": "३२", "is_correct": False},
            {"text_en": "49", "text_np": "४९", "is_correct": False},
        ],
        "explanation_en": "These are perfect squares: 1²=1, 2²=4, 3²=9, 4²=16, 5²=25, 6²=36.",
        "explanation_np": "यी पूर्ण वर्गहरू हुन्: १²=१, २²=४, ३²=९, ४²=१६, ५²=२५, ६²=३६।",
        "difficulty": "EASY",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "In a row of students, Sita is 8th from the left and 12th from the right. How many students are in the row?",
        "question_text_np": "विद्यार्थीहरूको एउटा कतारमा सीता बायाँबाट ८ औं र दायाँबाट १२ औं छ। कतारमा कति विद्यार्थी छन्?",
        "answers": [
            {"text_en": "19", "text_np": "१९", "is_correct": True},
            {"text_en": "20", "text_np": "२०", "is_correct": False},
            {"text_en": "18", "text_np": "१८", "is_correct": False},
            {"text_en": "21", "text_np": "२१", "is_correct": False},
        ],
        "explanation_en": "Total students = (8 + 12) − 1 = 19. (We subtract 1 because Sita is counted in both positions.)",
        "explanation_np": "कुल विद्यार्थी = (८ + १२) − १ = १९। (सीता दुवैतर्फ गनिएकोले १ घटाइन्छ।)",
        "difficulty": "EASY",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "Find the missing number: 3, 8, 15, 24, 35, ___",
        "question_text_np": "हराएको संख्या फेला पार्नुहोस्: ३, ८, १५, २४, ३५, ___",
        "answers": [
            {"text_en": "48", "text_np": "४८", "is_correct": True},
            {"text_en": "42", "text_np": "४२", "is_correct": False},
            {"text_en": "46", "text_np": "४६", "is_correct": False},
            {"text_en": "50", "text_np": "५०", "is_correct": False},
        ],
        "explanation_en": "Pattern: n²−1 where n = 2,3,4,5,6,7. So: 4−1=3, 9−1=8, 16−1=15, 25−1=24, 36−1=35, 49−1=48.",
        "explanation_np": "ढाँचा: n²−१ जहाँ n = २,३,४,५,६,७। त्यसैले: ४−१=३, ९−१=८, ..., ४९−१=४८।",
        "difficulty": "HARD",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "All cats are animals. All animals are living beings. Which conclusion follows?",
        "question_text_np": "सबै बिरालाहरू जनावर हुन्। सबै जनावरहरू जीवित प्राणी हुन्। कुन निष्कर्ष निकाल्न सकिन्छ?",
        "answers": [
            {"text_en": "All cats are living beings.", "text_np": "सबै बिरालाहरू जीवित प्राणी हुन्।", "is_correct": True},
            {"text_en": "All living beings are cats.", "text_np": "सबै जीवित प्राणी बिरालाहरू हुन्।", "is_correct": False},
            {"text_en": "Some animals are not living beings.", "text_np": "केही जनावरहरू जीवित प्राणी होइनन्।", "is_correct": False},
            {"text_en": "No living being is an animal.", "text_np": "कुनै जीवित प्राणी जनावर होइन।", "is_correct": False},
        ],
        "explanation_en": "By syllogism: If all A are B and all B are C, then all A are C. So all cats (A) are living beings (C).",
        "explanation_np": "syllogism द्वारा: यदि सबै A, B हुन् र सबै B, C हुन् भने सबै A, C हुन्। त्यसैले सबै बिरालाहरू जीवित प्राणी हुन्।",
        "difficulty": "EASY",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "Mirror image: If you look at the number '31' in a mirror, what will you see?",
        "question_text_np": "ऐनाको प्रतिविम्ब: '31' संख्यालाई ऐनामा हेर्दा के देखिन्छ?",
        "answers": [
            {"text_en": "IE (mirror '3' becomes 'E', '1' becomes 'I')", "text_np": "ऐनामा '31' को प्रतिविम्ब", "is_correct": False},
            {"text_en": "13 (horizontally flipped)", "text_np": "१३ (तेर्सो पल्टिएको)", "is_correct": True},
            {"text_en": "31", "text_np": "३१", "is_correct": False},
            {"text_en": "LE", "text_np": "LE", "is_correct": False},
        ],
        "explanation_en": "In a mirror, left and right are reversed. '31' viewed in a mirror appears as '13' with each digit also horizontally flipped.",
        "explanation_np": "ऐनामा बायाँ र दायाँ उल्टो देखिन्छ। '31' ऐनामा '13' को रूपमा देखिन्छ।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "Choose the word that does not belong: Kathmandu, Pokhara, Mumbai, Lalitpur",
        "question_text_np": "नपर्ने शब्द छान्नुहोस्: काठमाडौं, पोखरा, मुम्बई, ललितपुर",
        "answers": [
            {"text_en": "Mumbai", "text_np": "मुम्बई", "is_correct": True},
            {"text_en": "Kathmandu", "text_np": "काठमाडौं", "is_correct": False},
            {"text_en": "Pokhara", "text_np": "पोखरा", "is_correct": False},
            {"text_en": "Lalitpur", "text_np": "ललितपुर", "is_correct": False},
        ],
        "explanation_en": "Kathmandu, Pokhara, and Lalitpur are cities in Nepal. Mumbai is a city in India — it doesn't belong.",
        "explanation_np": "काठमाडौं, पोखरा र ललितपुर नेपालका शहरहरू हुन्। मुम्बई भारतको शहर हो — यो यहाँ पर्दैन।",
        "difficulty": "EASY",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "If 'x' means '+', '÷' means '−', '+' means '×', and '−' means '÷', find the value of: 8 + 4 x 3 ÷ 2 − 1",
        "question_text_np": "यदि 'x' को अर्थ '+', '÷' को अर्थ '−', '+' को अर्थ '×', र '−' को अर्थ '÷' हो भने: 8 + 4 x 3 ÷ 2 − 1 को मान कति हो?",
        "answers": [
            {"text_en": "33", "text_np": "३३", "is_correct": True},
            {"text_en": "22", "text_np": "२२", "is_correct": False},
            {"text_en": "15", "text_np": "१५", "is_correct": False},
            {"text_en": "40", "text_np": "४०", "is_correct": False},
        ],
        "explanation_en": "Replacing symbols: 8×4 + 3 − 2÷1 = 32 + 3 − 2 = 33.",
        "explanation_np": "प्रतीकहरू बदल्दा: 8×4 + 3 − 2÷1 = 32 + 3 − 2 = 33।",
        "difficulty": "HARD",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "Which direction will you face if you start facing North, turn right twice (90° each), then turn left once (90°)?",
        "question_text_np": "यदि उत्तर फर्किएर दुई पटक दायाँ (प्रत्येक ९०°) र एक पटक बायाँ (९०°) फर्किनु भयो भने कुन दिशामा हुनुहुन्छ?",
        "answers": [
            {"text_en": "East", "text_np": "पूर्व", "is_correct": True},
            {"text_en": "West", "text_np": "पश्चिम", "is_correct": False},
            {"text_en": "South", "text_np": "दक्षिण", "is_correct": False},
            {"text_en": "North", "text_np": "उत्तर", "is_correct": False},
        ],
        "explanation_en": "Start: North. Turn right 90° → East. Turn right 90° → South. Turn left 90° → East.",
        "explanation_np": "सुरु: उत्तर। दायाँ ९०° → पूर्व। दायाँ ९०° → दक्षिण। बायाँ ९०° → पूर्व।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "Complete the analogy: Doctor : Hospital :: Teacher : ?",
        "question_text_np": "उपमा पूरा गर्नुहोस्: डाक्टर : अस्पताल :: शिक्षक : ?",
        "answers": [
            {"text_en": "School", "text_np": "विद्यालय", "is_correct": True},
            {"text_en": "Library", "text_np": "पुस्तकालय", "is_correct": False},
            {"text_en": "Office", "text_np": "कार्यालय", "is_correct": False},
            {"text_en": "College", "text_np": "कलेज", "is_correct": False},
        ],
        "explanation_en": "A doctor works in a hospital. Similarly, a teacher works in a school. Though teachers can also work in colleges, 'school' is the most direct analogy.",
        "explanation_np": "डाक्टर अस्पतालमा काम गर्छ। त्यसैगरी शिक्षक विद्यालयमा काम गर्छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "Find the next number: 1, 1, 2, 3, 5, 8, 13, ___",
        "question_text_np": "अर्को संख्या फेला पार्नुहोस्: १, १, २, ३, ५, ८, १३, ___",
        "answers": [
            {"text_en": "21", "text_np": "२१", "is_correct": True},
            {"text_en": "18", "text_np": "१८", "is_correct": False},
            {"text_en": "20", "text_np": "२०", "is_correct": False},
            {"text_en": "24", "text_np": "२४", "is_correct": False},
        ],
        "explanation_en": "This is the Fibonacci sequence where each number is the sum of the two preceding ones. 8 + 13 = 21.",
        "explanation_np": "यो Fibonacci श्रृंखला हो जहाँ प्रत्येक संख्या अघिका दुई संख्याहरूको योग हो। ८ + १३ = २१।",
        "difficulty": "EASY",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "Ram walks 5 km north, then 3 km east, then 5 km south. How far is he from the starting point and in which direction?",
        "question_text_np": "राम ५ किमि उत्तर, ३ किमि पूर्व, र ५ किमि दक्षिण हिँड्छ। सुरुको स्थानबाट कति र कुन दिशामा छ?",
        "answers": [
            {"text_en": "3 km East", "text_np": "३ किमि पूर्व", "is_correct": True},
            {"text_en": "3 km West", "text_np": "३ किमि पश्चिम", "is_correct": False},
            {"text_en": "5 km North", "text_np": "५ किमि उत्तर", "is_correct": False},
            {"text_en": "8 km East", "text_np": "८ किमि पूर्व", "is_correct": False},
        ],
        "explanation_en": "5 km North and 5 km South cancel out. He is left 3 km East of the starting point.",
        "explanation_np": "५ किमि उत्तर र ५ किमि दक्षिण रद्द हुन्छन्। ऊ सुरुको स्थानबाट ३ किमि पूर्वमा छ।",
        "difficulty": "EASY",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "Choose the odd one out: Pen, Pencil, Chalk, Eraser",
        "question_text_np": "भिन्न पहिचान गर्नुहोस्: कलम, पेन्सिल, चक, रबर",
        "answers": [
            {"text_en": "Eraser", "text_np": "रबर", "is_correct": True},
            {"text_en": "Pen", "text_np": "कलम", "is_correct": False},
            {"text_en": "Pencil", "text_np": "पेन्सिल", "is_correct": False},
            {"text_en": "Chalk", "text_np": "चक", "is_correct": False},
        ],
        "explanation_en": "Pen, Pencil, and Chalk are all writing instruments. Eraser is used to remove writing, not to write — it's the odd one out.",
        "explanation_np": "कलम, पेन्सिल र चक सबै लेख्ने उपकरण हुन्। रबर लेखाइ मेटाउन प्रयोग गरिन्छ — यो भिन्न हो।",
        "difficulty": "EASY",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "Complete the pattern: AZ, BY, CX, DW, ___",
        "question_text_np": "ढाँचा पूरा गर्नुहोस्: AZ, BY, CX, DW, ___",
        "answers": [
            {"text_en": "EV", "text_np": "EV", "is_correct": True},
            {"text_en": "EU", "text_np": "EU", "is_correct": False},
            {"text_en": "FV", "text_np": "FV", "is_correct": False},
            {"text_en": "EW", "text_np": "EW", "is_correct": False},
        ],
        "explanation_en": "First letters go forward (A, B, C, D, E) and second letters go backward (Z, Y, X, W, V). Next pair: EV.",
        "explanation_np": "पहिलो अक्षरहरू अगाडि जान्छन् (A, B, C, D, E) र दोस्रो अक्षरहरू पछाडि जान्छन् (Z, Y, X, W, V)। अर्को जोडी: EV।",
        "difficulty": "EASY",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "In a certain code, 'LAND' is written as 'MBOF'. How is 'ROAD' written in that code?",
        "question_text_np": "एउटा निश्चित कूटभाषामा 'LAND' लाई 'MBOF' लेखिन्छ। त्यस कूटभाषामा 'ROAD' कसरी लेखिन्छ?",
        "answers": [
            {"text_en": "SPBE", "text_np": "SPBE", "is_correct": True},
            {"text_en": "RNBC", "text_np": "RNBC", "is_correct": False},
            {"text_en": "TQBF", "text_np": "TQBF", "is_correct": False},
            {"text_en": "SPBD", "text_np": "SPBD", "is_correct": False},
        ],
        "explanation_en": "Each letter is shifted +1: L→M, A→B, N→O, D→E. So R→S, O→P, A→B, D→E → SPBE.",
        "explanation_np": "प्रत्येक अक्षर +१ ले सार्दा: L→M, A→B, N→O, D→E। त्यसैले R→S, O→P, A→B, D→E → SPBE।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "Statement: 'All officers are honest. Some honest people are brave.' Conclusion: Some officers are brave.",
        "question_text_np": "कथन: 'सबै अधिकारीहरू इमानदार छन्। केही इमानदार मानिसहरू साहसी छन्।' निष्कर्ष: केही अधिकारीहरू साहसी छन्।",
        "answers": [
            {"text_en": "The conclusion does not definitely follow.", "text_np": "निष्कर्ष निश्चित रूपमा निकाल्न सकिँदैन।", "is_correct": True},
            {"text_en": "The conclusion definitely follows.", "text_np": "निष्कर्ष निश्चित रूपमा निकाल्न सकिन्छ।", "is_correct": False},
            {"text_en": "All officers are brave.", "text_np": "सबै अधिकारीहरू साहसी छन्।", "is_correct": False},
            {"text_en": "No officer is brave.", "text_np": "कोही अधिकारी साहसी छैन।", "is_correct": False},
        ],
        "explanation_en": "All officers are honest, but only 'some' honest people are brave. Those 'some' may or may not include officers. So the conclusion is not definite.",
        "explanation_np": "सबै अधिकारीहरू इमानदार छन्, तर 'केही' मात्र इमानदार मानिसहरू साहसी छन्। ती 'केही' मा अधिकारीहरू पर्ने वा नपर्ने निश्चित छैन।",
        "difficulty": "HARD",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "Find the missing term: 4, 9, 25, 49, ___",
        "question_text_np": "हराएको पद फेला पार्नुहोस्: ४, ९, २५, ४९, ___",
        "answers": [
            {"text_en": "121", "text_np": "१२१", "is_correct": True},
            {"text_en": "81", "text_np": "८१", "is_correct": False},
            {"text_en": "100", "text_np": "१००", "is_correct": False},
            {"text_en": "64", "text_np": "६४", "is_correct": False},
        ],
        "explanation_en": "These are squares of prime numbers: 2²=4, 3²=9, 5²=25, 7²=49, 11²=121.",
        "explanation_np": "यी अभाज्य संख्याहरूका वर्गहरू हुन्: २²=४, ३²=९, ५²=२५, ७²=४९, ११²=१२१।",
        "difficulty": "HARD",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "If 'red' means 'white', 'white' means 'blue', 'blue' means 'green', and 'green' means 'yellow', what is the color of the sky?",
        "question_text_np": "यदि 'रातो' को अर्थ 'सेतो', 'सेतो' को अर्थ 'नीलो', 'नीलो' को अर्थ 'हरियो', र 'हरियो' को अर्थ 'पहेंलो' हो भने आकाशको रंग के हो?",
        "answers": [
            {"text_en": "Green", "text_np": "हरियो", "is_correct": True},
            {"text_en": "Blue", "text_np": "नीलो", "is_correct": False},
            {"text_en": "White", "text_np": "सेतो", "is_correct": False},
            {"text_en": "Yellow", "text_np": "पहेंलो", "is_correct": False},
        ],
        "explanation_en": "Sky is 'blue' in reality. In this code, 'blue' means 'green'. So the sky's color is 'green' in this code.",
        "explanation_np": "आकाश वास्तवमा 'नीलो' हो। यस कूटभाषामा 'नीलो' को अर्थ 'हरियो' हो। त्यसैले आकाशको रंग 'हरियो' हो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Reasoning",
    },
    {
        "question_text_en": "Find the odd one out: 144, 169, 196, 225, 250",
        "question_text_np": "भिन्न पहिचान गर्नुहोस्: १४४, १६९, १९६, २२५, २५०",
        "answers": [
            {"text_en": "250", "text_np": "२५०", "is_correct": True},
            {"text_en": "144", "text_np": "१४४", "is_correct": False},
            {"text_en": "196", "text_np": "१९६", "is_correct": False},
            {"text_en": "225", "text_np": "२२५", "is_correct": False},
        ],
        "explanation_en": "144=12², 169=13², 196=14², 225=15², but 250 is not a perfect square. So 250 is the odd one out.",
        "explanation_np": "१४४=१२², १६९=१३², १९६=१४², २२५=१५², तर २५० पूर्ण वर्ग होइन। त्यसैले २५० भिन्न हो।",
        "difficulty": "MEDIUM",
        "source_reference": "PSC Reasoning",
    },
]